### ISSUE TITLE
Assertion failed: (!mCompleteLedgers.hasValue (prevMissing)), function resumeAcquiring

### ISSUE THREAD

**Issue by alexdupre** [ripple/rippled#107]
Another failed assertion during rippled execution:

Assertion failed: (!mCompleteLedgers.hasValue (prevMissing)), function resumeAcquiring, file ./src/cpp/ripple/LedgerMaster.cpp, line 452.

Last log lines before dumping:

2013-Jun-30 17:59:00 ripple_LedgerConsensus:NFO initial position 0000000000000000000000000000000000000000000000000000000000000000
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Checking for TX consensus: agree=0, disagree=0
2013-Jun-30 17:59:02 LedgerTiming:NFO normal consensus
2013-Jun-30 17:59:02 ripple_LedgerConsensus:NFO Converge cutoff (0 participants)
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Report: Prop=no val=no corLCL=yes fail=no
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Report: Prev = 1F98F6470B858554854571E5721AD464D45B0EC72E0371FDC7AB722A15AA2801:7
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Report: TxSt = 0000000000000000000000000000000000000000000000000000000000000000, close 425930340
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Applying consensus set transactions to the last closed ledger
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Pass: 0 Txns: 0 retriable
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Pass: 0 finished 0 changes
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Pass: 1 Txns: 0 final
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Pass: 1 finished 0 changes
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Report: NewL  = 83A67AC0E74B3B74EA28F75873F6F16EFB24F12B7DF5C885A8B61EC740E45E8C:8
2013-Jun-30 17:59:02 ripple_LedgerConsensus:NFO CNF newLCL 83A67AC0E74B3B74EA28F75873F6F16EFB24F12B7DF5C885A8B61EC740E45E8C
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Applying transactions from current open ledger
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Pass: 0 Txns: 0 retriable
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Pass: 0 finished 0 changes
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Pass: 1 Txns: 0 final
2013-Jun-30 17:59:02 ripple_LedgerConsensus:DBG Pass: 1 finished 0 changes
2013-Jun-30 17:59:02 LedgerMaster:NFO StashAccepted: 83A67AC0E74B3B74EA28F75873F6F16EFB24F12B7DF5C885A8B61EC740E45E8C

Backtrace of failed thread:

Thread 11 (Thread 80500ac80 (LWP 100539)):
#0  0x000000080331704c in thr_kill () from /lib/libc.so.7
#1  0x00000008033b402b in abort () from /lib/libc.so.7
#2  0x000000080339d355 in __assert () from /lib/libc.so.7
#3  0x000000000128b288 in ripple::LedgerMaster::resumeAcquiring (this=0x80507f0b0) at ./src/cpp/ripple/LedgerMaster.cpp:452
#4  0x00000000012898a1 in ripple::LedgerMaster::asyncAccept (this=0x80507f0b0, ledger=...) at ./src/cpp/ripple/LedgerMaster.cpp:264
#5  0x00000000012efe82 in std::tr1::_Mem_fn<void (ripple::LedgerMaster::*)(boost::shared_ptr<ripple::Ledger>)>::operator() (this=0x8050861f0, __object=0x80507f0b0, __args#0=...)
    at /usr/local/lib/gcc46/include/c++/tr1/functional:572
#6  0x00000000012e4f9f in std::tr1::_Bind<std::tr1::_Mem_fn<void (ripple::LedgerMaster::*)(boost::shared_ptr<ripple::Ledger>)> (ripple::LedgerMaster*, boost::shared_ptr<ripple::Ledger>)>::__call<ripple::Job&, 0, 1>(std::tr1::tuple<ripple::Job&> const&, std::tr1::_Index_tuple<0, 1>) (this=0x8050861f0, __args=...) at /usr/local/lib/gcc46/include/c++/tr1/functional:1153
#7  0x00000000012d448c in std::tr1::_Bind<std::tr1::_Mem_fn<void (ripple::LedgerMaster::*)(boost::shared_ptr<ripple::Ledger>)> (ripple::LedgerMaster*, boost::shared_ptr<ripple::Ledger>)>::operator()<ripple::Job>(ripple::Job&) (this=0x8050861f0) at /usr/local/lib/gcc46/include/c++/tr1/functional:1207
#8  0x00000000012c3e98 in std::tr1::_Function_handler<void (ripple::Job&), std::tr1::_Bind<std::tr1::_Mem_fn<void (ripple::LedgerMaster::*)(boost::shared_ptr<ripple::Ledger>)> (ripple::LedgerMaster*, boost::shared_ptr<ripple::Ledger>)> >::_M_invoke(std::tr1::_Any_data const&, ripple::Job&) (__functor=..., __args#0=...) at /usr/local/lib/gcc46/include/c++/tr1/functional:1684
#9  0x0000000000ec7372 in std::tr1::function<void (ripple::Job&)>::operator()(ripple::Job&) const (this=0x7fffff5fbce0, __args#0=...)
    at /usr/local/lib/gcc46/include/c++/tr1/functional:2040
#10 0x0000000000ebf87a in ripple::Job::doJob (this=0x7fffff5fbcd0) at modules/ripple_core/functional/ripple_Job.cpp:41
#11 0x0000000000ec140e in ripple::JobQueue::threadEntry (this=0x80507fa20) at modules/ripple_core/functional/ripple_JobQueue.cpp:268
#12 0x0000000000ed0998 in std::tr1::_Mem_fn<void (ripple::JobQueue::*)()>::operator() (this=0x8050a77d0, __object=0x80507fa20) at /usr/local/lib/gcc46/include/c++/tr1/functional:572
#13 0x0000000000ed088c in std::tr1::_Bind<std::tr1::_Mem_fn<void (ripple::JobQueue::*)()> (ripple::JobQueue*)>::__call<, 0>(std::tr1::tuple<> const&, std::tr1::_Index_tuple<0>) (
    this=0x8050a77d0, __args=...) at /usr/local/lib/gcc46/include/c++/tr1/functional:1153
#14 0x0000000000ed05dc in std::tr1::_Bind<std::tr1::_Mem_fn<void (ripple::JobQueue::*)()> (ripple::JobQueue*)>::operator()<>() (this=0x8050a77d0)
    at /usr/local/lib/gcc46/include/c++/tr1/functional:1207
#15 0x0000000000ed01ca in boost::detail::thread_data<std::tr1::_Bind<std::tr1::_Mem_fn<void (ripple::JobQueue::*)()> (ripple::JobQueue*)> >::run() (this=0x8050a7700)
    at /usr/local/include/boost/thread/detail/thread.hpp:78
#16 0x000000080285aac3 in thread_proxy () from /usr/local/lib/libboost_thread.so.5
#17 0x0000000801f7b5e1 in ?? () from /lib/libthr.so.3
#18 0x0000000000000000 in ?? ()

**Comment by rec** [comment]
Can't reproduce, feel free to re-open with a new test case or report!
