### ISSUE TITLE
Web-socket Initialization Error

### ISSUE THREAD

**Issue by whotooktwarden** [ripple/rippled#1233]
rippled will not start if I set the secure web socket protocol using:

> > # [port_wss]
> > # port = 443
> > # ip = 185.82.201.85
> > # admin = 127.0.0.1
> > # protocol = wss
> > # ssl_key = /etc/apache2/sites-available/xagate.com.key
> > # ssl_cert = /etc/apache2/sites-available/xagate.com.crt
> > # ssl_chain = /etc/apache2/sites-available/xagate.com.bundle.crt

I have to comment out all mentions of it in the configuration or else the server will continuously attempt to start itself, I receive:

> > 2015-Jul-08 00:24:59 WebSocket:WRN Websocket version 0.2
> > 2015-Jul-08 00:24:59 WebSocket:WRN Websocket: creating endpoint 'port_wss' (ip=185.82.201.85:443, admin IPs:127.0.0.1, wss)
> > Startup RPC: 
> > {
> >     >>    "command" : "log_level",
> >      >>   "severity" : "warning"
> > }
> > 
> > 2015-Jul-08 00:24:59 WebSocket:WRN Websocket: listening on 'port_wss' (ip=185.82.201.85:443, admin IPs:127.0.0.1, wss)
> > Result: {}
> > 
> > terminate called after throwing an instance of 'std::exception'
> > what():  std::exception

And this initialization of wss on port 443 will continue without ending its attempt to start the rippled server. This does not occur when I am using the ws protocol on port 51233.

[More information](https://forum.ripple.com/viewtopic.php?f=2&t=10627).

**Comment by nbougalis** [comment]
Are you running [b]rippled[/b] as root? Unless you are, you won't be able to bind to any port less than 1024.

**Comment by whotooktwarden** [comment]
I run sudo service rippled command under the manager account which has sudo access.  I will test this tomorrow running as root when I apply the 0.29 rippled update.  Apache crapped out on me earlier and I got too busy to do that today, perhaps the new version has solved this issue.  I'll update this issue tomorrow afternoon.

**Comment by nbougalis** [comment]
This could also happen if you have something else listening on port 443... Apache perhaps? There is an issue with `rippled`: the error message displayed when exiting is wrong, as is the automatic restart.

**Comment by whotooktwarden** [comment]
I will attempt to bind wss to 443 first when I apply the 0.29 update tomorrow.  If this fails, can you suggest an open port above the 1024 threshold that should be open by default?  My networking skills are inept.

**Comment by nbougalis** [comment]
I can't speak as to what port you should use.

**Comment by whotooktwarden** [comment]
I was able to get wss to bind on port 48212.  I was not able to interface with ripple-REST.  I suspect that this could be an issue with port 443 being used on my web server in conjunction with Apache to host https://xagate.com.  I want to secure my rippled server by using secure web sockets or https, can you please point me to some resources where I can use secure RPC calls in lieu of secure web sockets for the time being?

**Comment by nbougalis** [comment]
You can't "share" a port between two different processes, unless you "bind" one process (or both) to specific IPs.

I'll see if we can have someone more familiar with ripple-REST answer your question.
