### ISSUE TITLE
List Issuers on the Ripple Network

### ISSUE THREAD

**Issue by whotooktwarden** [ripple/rippled#1234]
How can rippled support an API call that will provide a list of:

-Issuers
-Currency Code
-Amount

[More information](https://forum.ripple.com/viewtopic.php?f=2&t=10674)

**Comment by nbougalis** [comment]
_Every_ account can issue currency, so the list of potential issuers is the list of all potential accounts, and every account can choose to issue any [currency](https://wiki.ripple.com/Currency_format). You may be interested in the [gateway_balances](https://ripple.com/build/rippled-apis/#gateway-balances) RPC command.
