### ISSUE TITLE
rippled init script

### ISSUE THREAD

**Issue by whotooktwarden** [ripple/rippled#1235]
This is the rippled init script:

> > # !/bin/bash
> > ### BEGIN INIT INFO
> > # Provides:          ripple
> > # Required-Start:    $local_fs $remote_fs $network $syslog
> > # Required-Stop:     $local_fs $remote_fs $network $syslog
> > # Default-Start:     2 3 4 5
> > # Default-Stop:      0 1 6
> > # Short-Description: starts the ripple network node
> > # Description:       starts rippled using start-stop-daemon
> > ### END INIT INFO
> > 
> > NAME=rippled
> > USER="rippled"
> > GROUP="rippled"
> > PIDFILE=/var/run/$NAME.pid
> > DAEMON=/home/manager/rippled-0.28.2/build/rippled
> > DAEMON_OPTS="--conf /etc/rippled/rippled.cfg"
> > NET_OPTS="--net $DAEMON_OPTS"
> > LOGDIR="/var/log/rippled"
> > STOP_LOOPS=30

DAEMON=/usr/bin/rippled was set on this line instead of the path to the new version of rippled. On each system boot, this should cause the rippled user to run /home/manager/rippled-0.28.2/build/rippled --conf /etc/rippled/rippled.cfg --net as that is what this script specifies, correct? From what I have tested, ripple-rest will not acknowledge that rippled is running unless I run sudo service rippled command as a user with sudo access. root is the user that owns /etc/init.d/rippled so I think that is why this occurs, should I change the ownership of this to rippled and see if that fixes this issue?

I'm still using the exact same configuration as I mention in the [rippled websocket initialization error thread](https://forum.ripple.com/viewtopic.php?f=2&t=10627#p65118) and even though this new version was supposed to fix SSL, I still cannot get wss to bind with rippled. Normal, unsecure web socket works fine on port 51233 still but I want wss bound to port 443.  This issue could somehow be tied to another, [separate issue](https://forum.ripple.com/viewtopic.php?f=2&t=10426), that I noticed with two instances of rippled running on my server.

**Comment by nbougalis** [comment]
It could be an ownership issue (likely and it could be related to trying to open port 443 - which as I explained can (typically) only be done by a root user.

**Comment by whotooktwarden** [comment]
I'm just about to reboot my web server to see if I can get these issues resolved.  I modified the name and group fields to root and the path to /home/rippled-0.29.0/build/rippled with --conf /etc/ripppled/rippled.cfg --start set as the options.

**Comment by whotooktwarden** [comment]
I would like to confirm that these modifications worked positively.  rippled will not require me to run the command sudo service rippled command to begin the rippled server, it just starts at boot time with the changes I mention above to the options.  I am still trouble shooting the secure web socket issue.  This issue can be closed.

**Comment by vinniefalco** [comment]
Great!
