### ISSUE TITLE
bad bucket error after running rippled.

### ISSUE THREAD

**Issue by TOMOAKI12345** [ripple/rippled#1268]
$ sudo ./build/rippled
2015-Sep-04 03:03:24 LedgerConsensus:WRN 
{
	"accepted" : true,
	"account_hash" : "A21ED30C04C88046FC61DB9DC19375EEDBD365FD8C17286F27127DF804E9CAA6",
	"close_time" : 494651010,
	"close_time_human" : "2015-Sep-04 03:03:30",
	"close_time_resolution" : 30,
	"closed" : true,
	"hash" : "997AE030AA5366E5FCA28143AD23947C9DA00454E64419B7ACF192E03303FC66",
	"ledger_hash" : "997AE030AA5366E5FCA28143AD23947C9DA00454E64419B7ACF192E03303FC66",
	"ledger_index" : "2",
	"parent_hash" : "AB868A6CFEEC779C2FF845C0AF00A642259986AF40C01976A7F842B6918936C7",
	"seqNum" : "2",
	"totalCoins" : "100000000000000000",
	"total_coins" : "100000000000000000",
	"transaction_hash" : "0000000000000000000000000000000000000000000000000000000000000000"
}

2015-Sep-04 03:03:24 LedgerConsensus:WRN Need consensus ledger 598E372381234D16C2002898484BFBCDE02C26E332B501B0C72E7648F55E698F
2015-Sep-04 03:03:26 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:26 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:26 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:26 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:26 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:26 LedgerConsensus:WRN Need consensus ledger 598E372381234D16C2002898484BFBCDE02C26E332B501B0C72E7648F55E698F
2015-Sep-04 03:03:31 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:31 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:31 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:31 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:31 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:31 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:31 LedgerConsensus:WRN Need consensus ledger 0BB4835B2E4896563E4600D4065D535DA3CB8A338930FD3D02F9700120698E10
2015-Sep-04 03:03:34 LedgerTiming:WRN We see no consensus, but 80% of nodes have moved on
2015-Sep-04 03:03:34 ConnectionImpl:WRN WebSocket: rcvMessage
2015-Sep-04 03:03:36 NetworkOPs:WRN We are not running on the consensus ledger
2015-Sep-04 03:03:36 LedgerConsensus:WRN Need consensus ledger EFBE9907A8A49E5C78FFA1AB017478EC958F14065B832E93CB36284B76AB7947
2015-Sep-04 03:03:37 LedgerConsensus:WRN By the time we got the map F8B3A62B397EEFA6602B6C71DA69F4EC949C57B41D7DB74B610ECA2ED8B78CDA no peers were proposing it
2015-Sep-04 03:03:37 LedgerConsensus:WRN By the time we got the map 24811E49937C739DCEFE94901F2D612C0F9B16A9EC3CA83B6D362EDAC1E8AE32 no peers were proposing it
libc++abi.dylib: terminating with uncaught exception of type beast::nudb::store_corrupt_error: bad bucket size

**Comment by vinniefalco** [comment]
Hmm...looks like a corrupted database

**Comment by JoelKatz** [comment]
This definitely looks like a corrupted NuDB index file.

**Comment by TOMOAKI12345** [comment]
thanks, delete and resync, then has fixed.

**Comment by vinniefalco** [comment]
@TOMOAKI12345 If there's a problem with your media then you'll get corruption again. You might check the disk or something.

**Comment by TOMOAKI12345** [comment]
@vinniefalco thank you for telling me about  the corruption.
