### ISSUE TITLE
Expose settings from src/ripple/app/ledger/impl/InboundLedger.cpp in config

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#1275]
Changing these parameters helped me to get in sync more often and more consistently on my limited home connection. Please expose them in the config file too, recompiling just to change a setting is a bit inconvenient + it might help others.

**Comment by nbougalis** [comment]
What did you change and to what?

**Comment by MarkusTeufelberger** [comment]
I would need to check with the ticket on JIRA (which is now hidden from me), generally I increased the timeout, decreased the total retries, increased the number of peers to be added at retries, got aggressive much earlier and decreased the number to consider a fetch "small". Now my server doesn't just get a handful of ledgers every 100 ledgers but manages to consistently stay at least in "syncing" mode and acquire more history.

My internet connection has "only" 10 MBit downstream and 1 MBit upstream and rippled constantly uses up all of it (I'm transferring over 1 TB/month, luckily bandwidth is unmetered here at least)

**Comment by nbougalis** [comment]
Thanks - I'll see about allow some degree of auto-tuning.

**Comment by yxxyun** [comment]
@MarkusTeufelberger Hi, can you provide your settings, I have similar internet connection problem.

**Comment by MarkusTeufelberger** [comment]
I'm not 100% sure if they don't hurt the network (maybe by querying too aggressively)...

If @nbougalis or some other RL experts tell me it is OK to modify these values as one sees fit, I can publish my settings. Some auto tuning might still be helpful, since I have set some more according to intuition rather than based on any facts so a bad setting in one variable might be cancelled out by a good one elsewhere for example. Also I really care about finally reaching full (or at least down to 32570) history, something that others might not tune for.

**Comment by nbougalis** [comment]
@MarkusTeufelberger please send me the settings you've tweaked by e-mail (nikb@ripple.com) and I'll go over them. If they look good, we can use them as a basis for auto-tuning, and consider exposing some of them via tweakable config options.

**Comment by MarkusTeufelberger** [comment]
Closing this report since rippled needs even more bandwidth these days and I managed to get a better internet connection, so no longer an issue.
