### ISSUE TITLE
separate linkable library for rippled

### ISSUE THREAD

**Issue by hthayko** [ripple/rippled#1284]
having a lib with functionality of 
1. signing transactions
2. getting public key from private key
3. extending trustlines
4. putting orders
will be very helpful for independent C/C++/Objective-C developers to create services for Ripple

**Comment by vinniefalco** [comment]
Sounds great, get to work!

**Comment by MarkusTeufelberger** [comment]
https://github.com/ripple/ripple-libpp seems to be the result of this.

**Comment by vinniefalco** [comment]
This is happening.
