### ISSUE TITLE
Add Minw-W64 crosscompile target

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#1299]
Apparently eventually you want to split the SConstruct file (https://github.com/ripple/rippled/pull/1252). Is this going to become the "new" way to build rippled moving forward? I'd like to add mingw-w64 targets to get a Windows binary without having to deal with VisualStudio... if I start editing the existing SConstruct file though and in a few days it gets completely overhauled anyways, it would be smarter to start with the new version in mind.

**Comment by vinniefalco** [comment]
Building under mingw is really ambitious...

**Comment by MarkusTeufelberger** [comment]
So I should just start with the current one? At least the issue that kept me from compiling before seems to have been fixed by now, I'll report here from time to time about progress made.

**Comment by vinniefalco** [comment]
Yes. I think its worthwhile

**Comment by MarkusTeufelberger** [comment]
Hm, I got it to do... something. At least it starts mingw, passes on some reasonably looking options and uses CPU.
Already ran into the first issue: htobe64() and others are not available for Windows under that name. There seems to be already some fixes for this in beast/ByteOrder.h. Some code that seems to come from bitcoin (ripple/basics/base_uint.h) still uses htobeXX() though. An alternative to rewriting would be to use something like https://gist.github.com/panzi/6856583. What would you prefer?

**Comment by vinniefalco** [comment]
@nbougalis What do you think?

**Comment by MarkusTeufelberger** [comment]
I went ahead and used the beast functions, if you still want to implement the standard ones, I guess you would expose them via beast/ByteOrder.h anyways.

**Comment by nbougalis** [comment]
I think that using the Beast functions is the beast for right now. If we decide to change things, we can do so in the future, but I'd rather not have _another_ way of handling endianess.

**Comment by MarkusTeufelberger** [comment]
Another one: ripple/app/misc/UniqueNodeList.cpp line848 uses std::ifstream, not the boost::filesystem version. This means an error (http://stackoverflow.com/questions/21456443/opening-a-input-filestream-with-a-unicode-name-but-ascii-data) gets thrown, apparently Windows and Linux/UNIX disagree on the default size of a character in path names.

**Comment by MarkusTeufelberger** [comment]
Actually, you can just search for std::ifstream and std::ofstream (there is already a TODO somewhere to make logs work with unicode path names...) and add boost::filesystem there instead.

**Comment by nbougalis** [comment]
A lot of that code will likely be changing, but if you want to fix it to get mingw compiles going, I'm not going to complain :smile:

**Comment by MarkusTeufelberger** [comment]
Well, it needs to be fixed sooner or later anyways and if I manage to get a mingw target added to the SConstruct you'll hopefully be more careful to not break builds! :grinning: 

I'll still need to fix up the SConstruct file for the moment though to enable the mingw target properly... I'll start with a few other commits (like the endianness conversions or boost::filesystem) to see if I broke something along the way yet.

**Comment by vinniefalco** [comment]
I think its still worth looking into mingw but what's so hard about installing the Community version of VS2015? Its free...

**Comment by MarkusTeufelberger** [comment]
Free as in beer, not as in speech/Stallman. Also I want to move away from Windows anyways and this seemed like a good place to start to learn about cross platform development. Additionally I want to be able to build and package rippled using Docker later on and producing a Windows build would be awesome - but "Docker on Windows" currently means running a Linux VM...

**Comment by MarkusTeufelberger** [comment]
If I understand the vcxproj files correctly, my fixes should have orphaned the ByteOrder header in ripple/basics. Nice! :-) 

Other than that, often _MSC_VER is used to check if something is being compiled for Windows instead of _WIN32... I don't want to do the hackish way of setting _MSC_VER from outside, so I changed it whenever I got an error. There is likely more to be fixed though in this regard.

Another issue is UPPERCASE/lowercase, especially for including "windows.h" (lowercase W) - Windows itself won't care, compiling on Linux however throws some errors.

**Comment by MarkusTeufelberger** [comment]
Oh, and I just found a small error in your current build: https://github.com/ripple/rippled/blob/develop/SConstruct#L550 should be 0x0600 (Vista), not 0x6000 (probably still a while this this gets released... but yay, bluescreens for the holodeck!).

**Comment by MarkusTeufelberger** [comment]
Ok, after some issues with snappy (that I temporarily "solved" by just not compiling it and moving on) the next bigger hurdle seems to be boost.

Apparently boost-context can only be built using Microsoft tools (MASM) - https://svn.boost.org/trac/boost/ticket/7262 - and according to http://mingw-users.1079350.n2.nabble.com/Boost-Context-MinGW-EXPORT-keyword-td7582532.html they are not going to change that for a similar reason that Vinnie gave: MASM is "free", so there's no reason to support open source implementations additionally. Might still be worth trying to hand in a patch (there seem to be several available over time) to boost upstream... but this stuff is starting to get annoying.

boost-coroutine has similar issues apparently.

**Comment by vinniefalco** [comment]
I fear that even if you get past these issues, you will have unsolveable problems at link-time. Specifically you will need a standard runtime library and its going to have problems like being DLL-only and having shaky support for threads. This might have improved since I last tried to build projects with MinGW but maybe not.

**Comment by MarkusTeufelberger** [comment]
Yeah, getting linking to work seems like a very special nightmare... it might be easier to get VS running in WINE than solving this crosscompiling mess. >:-(

**Comment by MarkusTeufelberger** [comment]
Closing this, running on Windows is not a very good idea anyways imho.
