### ISSUE TITLE
RPC account_lines does not honor peer parameter

### ISSUE THREAD

**Issue by compositor** [ripple/rippled#135]
The `peer` parameter for  `account_lines` call does not work in the command line (even with the latest build from master)

```
rippled account_lines "rLc4CW7gDJJXzg8FCytcz4xTSjCzyxnx8h" "rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q"
```

 returns 4 lines

Websocket call works correctly and returns only one line though

**Comment by vinniefalco** [comment]
Obsolete
