### ISSUE TITLE
0.30.1-b4 doesn't build on Manjaro(Arch) Linux

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#1376]
Error in the linker step:
/usr/bin/ld: cannot find -lprotobuf
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto

This happens most likely because Arch Linux doesn't provide static libraries for many packages, including protobuf and openssl. Checking with ldd on the previous binary confirms that it is just linked dynamically, probably the --static option in pkg-config didn't do much.

Do you really *have* to compile everything statically in the binary (even libstdc++)? I'm sure there are reasons for and against this behaviour, it would be just nice to be able to continue to build rippled for sources without having to jump through several hoops (building a package to install using Docker or recompiling openssl...) or maintaining a fork (changing the SConstruct file to link these 3 libraries dynamically).

**Comment by nbougalis** [comment]
We will take a look at this and see if we can sort it out. The changes in linking behavior are necessary and were prompted by the move to `gcc` 5.x.

**Comment by MarkusTeufelberger** [comment]
It works just fine when linking dynamically by the way (changing 2 lines in the SConstruct file), so that might be a workaround. The problem is that Arch Linux does NOT offer static libraries for many packages, including OpenSSL and protobuf. Pkg-config probably took the "--static" switch more like a suggestion so far and just linked dynamically, while now you've hardcoded the static inclusion of these libraries at the linker step.

**Comment by MarkusTeufelberger** [comment]
0.30.1-b5 builds and links again, thanks for the fix(es)! :-)
