### ISSUE TITLE
ledger_request acting weirdly (0.30.1-b9)

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#1428]
The answer to the first call to ledger_request (e.g. "rippled ledger_request 40000") is a few ledgers off, the second and all subsequent calls return the correct ledger header. If a different ledger (e.g. "rippled ledger_request 50000") is requested, the same thing happens again.

    [...]$ rippled --conf /etc/rippled/rippled.cfg ledger_request 40000
Loading: "/etc/rippled/rippled.cfg"
Connecting to 127.0.0.1:5005
{
   "result" : {
      "accepted" : true,
      "account_hash" : "B79B7172E64375D1825B34E135EF2B13038103DC3DFA7737D921C89A105290EB",
      "close_flags" : 0,
      "close_time" : 410462820,
      "close_time_human" : "2013-Jan-02 17:27:00",
      "close_time_resolution" : 10,
      "closed" : true,
      "hash" : "F80997EFF9A703906FC7BD1064107D360DADEE39D15DD48E3ED3604610F8B3EB",
      "ledger_hash" : "F80997EFF9A703906FC7BD1064107D360DADEE39D15DD48E3ED3604610F8B3EB",
      "ledger_index" : "40192",
      "parent_close_time" : 410462800,
      "parent_hash" : "0FBA04DD03B4713C605B772582DCE09F81D3A363ED182AEA13173361D88E4C86",
      "seqNum" : "40192",
      "status" : "success",
      "totalCoins" : "99999999999996230",
      "total_coins" : "99999999999996230",
      "transaction_hash" : "0000000000000000000000000000000000000000000000000000000000000000"
   }
}

    [...]$ rippled --conf /etc/rippled/rippled.cfg ledger_request 40000
Loading: "/etc/rippled/rippled.cfg"
Connecting to 127.0.0.1:5005
{
   "result" : {
      "accepted" : true,
      "account_hash" : "1B536BFBDFC92B9550F2F63D32F7269D451885FFB2CAB374332EBC2D663320E0",
      "close_flags" : 0,
      "close_time" : 410459130,
      "close_time_human" : "2013-Jan-02 16:25:30",
      "close_time_resolution" : 10,
      "closed" : true,
      "hash" : "16BB8E41DD96D643BC72E1981865C5D76B990464E2EA151FEAC16CDF1AE29388",
      "ledger_hash" : "16BB8E41DD96D643BC72E1981865C5D76B990464E2EA151FEAC16CDF1AE29388",
      "ledger_index" : "40000",
      "parent_close_time" : 410459110,
      "parent_hash" : "CDFD329A6E418591770695D0FB859113641AC20CB3A1F39AB3D721CEA2685EFE",
      "seqNum" : "40000",
      "status" : "success",
      "totalCoins" : "99999999999996310",
      "total_coins" : "99999999999996310",
      "transaction_hash" : "0000000000000000000000000000000000000000000000000000000000000000"
   }
}

**Comment by nbougalis** [comment]
@MarkusTeufelberger please close this issue if you are still having weird behavior from `ledger_request` when running https://github.com/ripple/rippled/commits/develop.

**Comment by MarkusTeufelberger** [comment]
[...]$ rippled --conf /etc/rippled/rippled.cfg ledger_request 40000
Loading: "/etc/rippled/rippled.cfg"
Connecting to 127.0.0.1:5005
{
   "result" : {
      "acquiring" : {
         "accepted" : true,
         "account_hash" : "B79B7172E64375D1825B34E135EF2B13038103DC3DFA7737D921C89A105290EB",
         "close_flags" : 0,
         "close_time" : 410462820,
         "close_time_human" : "2013-Jan-02 17:27:00",
         "close_time_resolution" : 10,
         "closed" : true,
         "hash" : "F80997EFF9A703906FC7BD1064107D360DADEE39D15DD48E3ED3604610F8B3EB",
         "ledger_hash" : "F80997EFF9A703906FC7BD1064107D360DADEE39D15DD48E3ED3604610F8B3EB",
         "ledger_index" : "40192",
         "parent_close_time" : 410462800,
         "parent_hash" : "0FBA04DD03B4713C605B772582DCE09F81D3A363ED182AEA13173361D88E4C86",
         "seqNum" : "40192",
         "totalCoins" : "99999999999996230",
         "total_coins" : "99999999999996230",
         "transaction_hash" : "0000000000000000000000000000000000000000000000000000000000000000"
      },
      "error" : "lgrNotFound",
      "error_code" : 20,
      "error_message" : "acquiring ledger containing requested index",
      "request" : {
         "command" : "ledger_request",
         "ledger_index" : 40000
      },
      "status" : "error"
   }
}

This is with 0.31.0-b4

Still 40192, not 40000, even though it is even correct in the error message!

**Comment by nbougalis** [comment]
The 40192 may appear weird and even unintuitive but it is correct: it is not the index of the ledger you asked for, but the index of the ledger that the server is currently attempting to acquire to service your particular request.

In this case, you asked for ledger 40000. The server doesn't know its hash, so it tries to look for the closest ledger whose skip list will contain the hash of the request ledger. This happens to be ledger 40192. Hence it tries to acquire it.

**Comment by MarkusTeufelberger** [comment]
Ah, that makes sense of course!
