### ISSUE TITLE
Alter Hello message format in ripple.proto to send explicit unpacked version numbers

### ISSUE THREAD

**Issue by kravets** [ripple/rippled#143]
protoVersion and protoVersionMin fields currently pack both major and minor versions into each unint32 field.  This is undocumented and non-obvious, there should simply be 4 (possibly smaller uint16) bit fields instead.

See 

https://github.com/ripple/rippled/blob/develop/modules/ripple_data/protocol/ripple.proto?source=c#L65

**Comment by MarkusTeufelberger** [comment]
Has this been fixed in the meantime?
