### ISSUE TITLE
Question about Multi-Core CPU optimize

### ISSUE THREAD

**Issue by dreamlich** [ripple/rippled#1433]
According to https://wiki.ripple.com/Validator, the validator of ripple lab is setup at least in AWS m1.large.
Most of the AWS machine is based on multi-core cpu such as Intel Xeon E5-2430.
When there are huge real transactions in short time, the CPU load of validator  will be too high. 
In Ubuntu-64, I find that there are only two or three task for rippled.
My question is that is there any special code for optimizing the performance on multi-core cpu?
Does the rippled task support the parallel tool such as GNU Parallel?

**Comment by MarkusTeufelberger** [comment]
"When there are huge real transactions in short time, the CPU load of validator will be too high."

Do you have any indication for this or are you guessing? I don't really see any CPU spikes on my validator, but it is bandwith choked, so it might have more work with keeping up than calculating new state.

According to the "server_info" call, my server currently runs 6 threads (on 4 cores + 4 HT-cores) and I'm not sure how running several rippled validators in parallel should help here...

**Comment by dreamlich** [comment]
Hi Markus,

According to the "server_info" call, my server currently runs only 3 threads. 
         "load" : {
            "job_types" : [
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand",
                  "peak_time" : 3,
                  "per_second" : 3
               },
               {
                  "job_type" : "writeObjects",
                  "peak_time" : 1
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 5
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 1
               }
            ],
            "threads" : 3
         },

And with linux ps command, there are two task for rippled. Actually, the linux command only run in single CPU core. When validator need to verify sign of transactions, I think it's better to use mutli-core to improve the performance. 

I don't know how much transactions per second rippled server can support now. If the load increase tenfold, the CPU performance maybe become bottleneck?

**Comment by nbougalis** [comment]
@dreamlich there are two tasks because `rippled` forks a copy of itself to function as a watchdog, so that the process that is running the server code can be restarted if it terminates. The `ps` command does not display threads by default (try: `ps -auxH | grep rippled` to see threads)

If the server is reporting three threads in `server_info`, then your server is, actually, running with three threads. The server uses as many threads as are appropriate and automatically tunes this value based on the resources available on your computer.

The server is smart about when and how it performs signature validation and naively adding more threads won't help performance. And rest assured that we are keeping an eye at the performance of the server and will not hesitate to make changes to clear out any bottlenecks.

**Comment by dreamlich** [comment]
@nbougalis  Thanks for your quick reply. 
Could you please kindly show me the  files or function about smart adding threads for performance?

**Comment by nbougalis** [comment]
@dreamlich the most important piece is the `Workers` object, which is behind the RippleD "job queue": by default it creates as many threads as there processors on the system. See https://github.com/ripple/rippled/blob/develop/src/beast/beast/module/core/thread/Workers.h#L51-L61.

Additionally, other operations or objects create their own threads in which lengthy or parrelelizable tasks will execute. Examples of such objects are the [ledger cleaner](https://github.com/ripple/rippled/blob/develop/src/ripple/app/ledger/impl/LedgerCleaner.cpp#L105-L108), the [SHAMap store](https://github.com/ripple/rippled/blob/develop/src/ripple/app/misc/SHAMapStoreImp.h#L227-L232), the [websocket server](https://github.com/ripple/rippled/blob/develop/src/ripple/websocket/Server.h#L89-L92) and the [resoruce manager](https://github.com/ripple/rippled/blob/develop/src/ripple/resource/impl/ResourceManager.cpp#L44-L50).
