### ISSUE TITLE
Limit of requests

### ISSUE THREAD

**Issue by AlexSanzharevskyy** [ripple/rippled#1439]
Hi there! Is there any limit of requests per second? Cause we have an issue, that our IP is blocked and server returns 503 error. We tried 5-10 requests per second. Each request is like this - https://id.ripple.com/v1/user/{ripple-address}. Thank you!

**Comment by vinniefalco** [comment]
Are you sure this is a rippled problem?

**Comment by AlexSanzharevskyy** [comment]
seems like yes, cause if we're trying to use the same request at the same time, but with proxy - it works.

**Comment by vinniefalco** [comment]
rippled doesn't serve responses to URLs with that form though

**Comment by AlexSanzharevskyy** [comment]
thank you.

**Comment by vinniefalco** [comment]
The URL provided belongs to the Identity API, which is not part of rippled
