### ISSUE TITLE
Error trying to build from code

### ISSUE THREAD

**Issue by alexandrev** [ripple/rippled#1448]
I'm trying to build ripple from the develop branch and I'm getting this error time after time:
```
:coroutine_context::coroutine_context(void (*)(long), boost::coroutines::detail::preallocated const&)'
collect2: error: ld returned 1 exit status
scons: *** [build/gcc.release/rippled] Error 1
scons: building terminated because of errors.
```

I'm using Ubuntu 15.10 and I've followed the tutorial you have published here: https://wiki.ripple.com/Ubuntu_build_instructions 

Any help?

**Comment by vinniefalco** [comment]
Which version of boost?

**Comment by alexandrev** [comment]
I've been used the latest one I could find. The 1.60 version. I've also tried it with the 1.55 but no luck.

--
Alexandre Vazquez

Enviado desde dispositivo móvil.

**Comment by HowardHinnant** [comment]
We have not yet ported rippled to boost 1.60 (which was just released two days ago).  I can confirm that the port is more than a simple re-compile.  rippled is known to work well with boost 1.59.  Can you try that?

**Comment by alexandrev** [comment]
As you said, with the 1.59 the software builds as expected. So I'm going to close this issue. :) Thanks a million for your help
