### ISSUE TITLE
Error trying to build from code (master branch)

### ISSUE THREAD

**Issue by alexandrev** [ripple/rippled#1449]
I'm trying to build ripple from the master branch and I'm getting this error time after time:

```
developer@ubuntu:~/rippled$ scons
scons: Reading SConscript files ...
ValueError: time data 'reproducible build, date unspecified' does not match format '%a %b %d %H:%M:%S %Z %Y':
  File "/home/developer/rippled/SConstruct", line 619:
    config_base(base)
  File "/home/developer/rippled/SConstruct", line 282:
    check_openssl()
  File "/home/developer/rippled/SConstruct", line 133:
    if parse_time(line) < parse_time(BUILD_TIME):
  File "/home/developer/rippled/SConstruct", line 117:
    return time.strptime(t, '%a %b %d %H:%M:%S %Z %Y')
  File "/usr/lib/python2.7/_strptime.py", line 467:
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 325:
    (data_string, format))
```

Any help?

**Comment by alexandrev** [comment]
This problem seems related to the change in the openssl version date as you can see here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794218. It seems it is fixed in the develop branch but it has not been promoted to the master branch. Anyone could confirm?

**Comment by nbougalis** [comment]
That seems plausible @alexandrev - I will verify that *develop* fixes the issue, and if so, this will be resolved automatically when we merge *develop* into *master*.

**Comment by nbougalis** [comment]
@alexandrev: this issue will be solved shortly, when we update the master branch. I expect it will happen in the next day or two.
