### ISSUE TITLE
Question about database performance test in Benchmarks.md

### ISSUE THREAD

**Issue by dreamlich** [ripple/rippled#1459]
I used to run below command: 
$rippled --unittest=NodeStoreTiming --unittest-arg="type=rocksdb,num_objects=2000000,open_files=2000,filter_bits=12,cache_mb=256,file_size_mb=8,file_size_mult=2;type=rocksdbquick,num_objects=2000000"
But it seems that result  is 
"0ms, 0 suites, 0 cases, 0 tests total, 0 failures".
My ripple version is 0.30. 
Is this feature removed? If it still exists, please correct my tedt command. 
Thanks.

**Comment by vinniefalco** [comment]
The test is still present:
https://github.com/ripple/rippled/blob/develop/src/ripple/nodestore/tests/Timing.test.cpp#L747

**Comment by dreamlich** [comment]
@vinniefalco  I've watched the code. This test should run manually, but when I run it locally, it seems that the result include none test case.

**Comment by vinniefalco** [comment]
Oops... I see the problem. The command line should read ...`--unittest=NodeStore.Timing` (note the period)

**Comment by dreamlich** [comment]
I just copy it from Benchmarks.md.
I used --unittest=NodeStore.Timing
It still can not work.

**Comment by dreamlich** [comment]
From wiki, https://wiki.ripple.com/Rippled#--unittest.2C_-u. I think the command should be ripple.NodeStoreTiming but not ripple.NodeStore.Timing

**Comment by nbougalis** [comment]
@dreamlich: I'll check to make sure that the matching works; in the meantime, try: `rippled --unittest Timing`. Do note, you may get spurious failures with this test.

**Comment by dreamlich** [comment]
@nbougalis Thanks. The "--unittest Timing" test works fine.

**Comment by vinniefalco** [comment]
@dreamlich The doc you linked includes the period
