### ISSUE TITLE
validator_keys and validation_manifest sections not documented/present in example.cfg

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#1481]
0.31.0-b1 seems to rely on these sections and my node just constantly fails and restarts every few seconds...

**Comment by nbougalis** [comment]
I'll double-check and make sure that these sections aren't required.

**Comment by MarkusTeufelberger** [comment]
As of 0.31.0-b4 the constant restarts are gone, it still spits out some warnings about missing these sections on startup though.

**Comment by nbougalis** [comment]
@MarkusTeufelberger yeah, the messages were, for some reason, set to "warning" level. PR #1510  brings the verbosity down to "debug" where it should have been to begin with; the change should get merged into *0.31.0-b5*.

I'm going to close this for now; feel free to reopen if the issue persists.
