### ISSUE TITLE
Memory utilization question

### ISSUE THREAD

**Issue by dreamlich** [ripple/rippled#1509]
I set up two public server with different RAM. One is 8Gb and the other is 32Gb. The cfg is the same with node_size=large and history=full. Then I create about 1 million accounts for testing. 
I find that in the 8Gb machine, the memory utilization is up to 95% and won't increase. But in the 32Gb machine, the memory cost is about 13Gb and it increased all the time. The increase speed is about 1Mb every 8 minute(I won't do any transaction). 

I have two question about this.
1. Does the increased memory used by sqlite?
2. Does ripple set the max memory utilization in code? Or there is a unknown memory leak?

Thanks.

**Comment by JoelKatz** [comment]
How are you measuring the memory used? Are you measuring virtual memory usage or physical memory usage?

**Comment by vinniefalco** [comment]
Is this still an issue?
