### ISSUE TITLE
Make path_find status response and unsolicited updates similar

### ISSUE THREAD

**Issue by dchapes** [ripple/rippled#155]
Is there any chance to tweak the path_find unsolicited updates or is it too late to change this API? Also, the [wiki API docs](https://ripple.com/wiki/RPC_API#path_find) don't seem to match the actual response from the path_find status command.

I have test code in a loop reading responses from the server after issuing a `path_find create` and I occasionally issue a `path_find status` (e.g. in response to `SIGINFO`). Even though the same code reads both, the unsolicited updates and the status update need to be parsed completely separately. This is because although they contain basically the same information they are structured differently.

An unsolicited response is:

``` json
{
  "alternatives": [],
  "destination_account": "xxx",
  "destination_amount": {},
  "destination_currencies": [],
  "destination_tag": false,
  "ledger_hash": "xxx",
  "ledger_index": 1234,
  "source_account": "xxx",
  "type": "path_find"
}
```

but the path_find status response is:

``` json

{
  "result": {
    "alternatives": [],
    "destination_account": "xxx",
    "destination_amount": {},
    "destination_currencies": [],
    "destination_tag": false,
    "ledger_hash": "xxx",
    "ledger_index": 1234,
    "source_account": "xxx"
  },
  "status": "success",
  "type": "response"
}
```

The former lacks a "status" field (like almost every other response the server sends) and the later wraps the same fields into a "result" struct. Personally I'd prefer if the former were changed to match the later (with some appropriate "status" field added).

**Comment by nbougalis** [comment]
I'll close this issue, as it is basically prehistoric, but I wanted to say that we are aware that this is an issue (I've been bitten by the inconsistency in the way data is formatted) and we are going to be restructuring the API to fix this issue, @dchapes. 

Expect a proposal to be published so that we can have feedback and comments from the broader community.
