### ISSUE TITLE
Please add comments to all .cpp files decoding the programmer's original intent

### ISSUE THREAD

**Issue by kravets** [ripple/rippled#156]
I suggest David spends a day or two simply going through all .cpp files and adding comments to if/else clauses, function declarations, etc to **decrypt** his original intent now obscured by tricky and verbose C++.

This is a perfectly safe source file change which is very very helpful to other C++ programmers or implementors of alternative implementations in other languages.

Such as:

//This clause handles the case of the ledger being bla bla bla
//
else 
{
...
}

**Comment by vinniefalco** [comment]
Obsolete
