### ISSUE TITLE
[old bug happen again] deletes funded offers thinking they are unfunded

### ISSUE THREAD

**Issue by yxxyun** [ripple/rippled#1567]
I think this had been fixed by https://github.com/ripple/rippled/commit/2b91e62d5d9256c1d851807190cefd645276916e ,but it happened again.
transaction 
"hash": "3A4C63FFFDAEA1D725F9901D325DE8DED8721A8D3018E183F20B391633D278A4", 

as I checked, it caused to delete rCut663MvYAGVrYeRR1jdHtYjHLy5zwuy 's offer hash:1BF8FDD85FF3DB2F1E70F4D22952DD8BA0AE9FFB74AB993B473D44AE26187098

rKY5KrMxePseZnNjRFCNKPCB3tALaUrsM4's offer hash:C7623EF43B61B7A290B888ACDF98CFE975C7BB4FC798DAD4ACC3BC13E6FBD42F and 0A8D46406C38D2F52FA477C8D9B1F3CFC07363B25EC9C96068A8CC0D0746FA76 and 0C103C3A46C340291BF212F9283446F5F6BAE977EE1C2E62F8259E89F6241AEA.

I'm not check all the offers this tx had affected.  

rKY5KrMxePseZnNjRFCNKPCB3tALaUrsM4 report this in RippleFox QQ group.

please check&fix.  @seelabs @nbougalis @vinniefalco

**Comment by nbougalis** [comment]
Thank you for the report. 

This issue has been addressed in *release* as of 0.30.1-hf2 with commit 675cbb72a6704eaec9ccc7c3c3917bcb1ec4b110. The fix is also in *develop* as of 0.31.0-b11 with commit d8ee487c196bf5972ad2b0f153df56008e0b02ac.
