### ISSUE TITLE
Duplicate LedgerSeq's in rippled database on ct

### ISSUE THREAD

**Issue by emschwartz** [ripple/rippled#163]
The following LedgerSeq's seem to have more than one entry. They are the result of running `select LedgerSeq from Ledgers group by LedgerSeq having count(LedgerSeq) > 1;` in ubuntu@ct.ripple.com:/ripple/server/db/ledgers.db):

1252259
1264133
1321947
1325107
1325112
1327641
1328711
1330412
1334758
1335224
1347521
1355923
1356945
1357669
1370342
1370518
1371990
1378441
1379089
1379719
1396650
1396654
1414427
1416741
1418417
1418424
1419095
1419961
1421079
1421865
1422577
1427561
1430177
1438873
1446499
1461166
1461567
1461586
1464155
1469978
1470342
1483356
1490177
1495790
1495795
1498990
1499458
1504302
1507330
1508701
1512053
1516414
1517475
1521927
1521928
1525642
1535849
1536337
1541556
1554043
1562106
1565467
1567786
1580557
1586275
1586401
1587403
1587795
1587934
1616673
1624413
1629143
1629264
1649174
1652464
1655253
1656482
1657277
1659089
1665202
1669057
1669092
1669912
1670645
1671303
1672409
1674099
1674360
1675849
1676378
1677130
1682582
1682946
1683980
1686028
1689786
1694217
1696362
1704264
1704544
1707281
1711288
1717837
1720264
1721981
1722025

**Comment by vinniefalco** [comment]
Obsolete
