### ISSUE TITLE
Minimize disk usage for non-public validating nodes

### ISSUE THREAD

**Issue by mjethani** [ripple/rippled#169]
If validating nodes do not need to store the history, then it should be so that they take up very little disk space. Right now, no matter what configuration settings you use, the database just keeps growing, and has to be manually deleted every few hours.

This is important for adoption. It should be possible for every geek out there to download and run their own Ripple validator on their home computer. Public keys can be shared via Facebook or Twitter. We can achieve true decentralization only if we lower the barrier to entry to the point where any average middle-class person is able to participate in the global trust network.

**Comment by vinniefalco** [comment]
Obsolete with the rotate/delete feature
