### ISSUE TITLE
Error build rippled from souce code

### ISSUE THREAD

**Issue by fulviusguelfi** [ripple/rippled#1710]
This is the erro that I have tring to build (release branch)

Can anyone help me?

root@vps [~/rippled]# scons
scons: Reading SConscript files ...
Exception: pkg-config failed for openssl; Exception: 'module' object has no attribute 'check_output':
  File "/root/rippled/SConstruct", line 1051:
    config_env(toolchain, variant, env)
  File "/root/rippled/SConstruct", line 494:
    static, dynamic = get_libs(l, link_static)
  File "/root/rippled/SConstruct", line 425:
    raise Exception('pkg-config failed for ' + lib + '; Exception: ' + str(e))

**Comment by fulviusguelfi** [comment]
Here another test

root@vps [~/rippled]# which python
/usr/local/bin/python
root@vps [~/rippled]# /usr/local/bin/python --version
Python 2.7.6
root@vps [~/rippled]# /usr/local/bin/python SConstruct --static
Traceback (most recent call last):
  File "SConstruct", line 120, in <module>
    import SCons.Action
ImportError: No module named SCons.Action

**Comment by fulviusguelfi** [comment]
other test

root@vps [~/rippled]# scons
scons: Reading SConscript files ...
cmd=
['pkg-config', '--static', '--libs', 'openssl']
subprocess.STDOUT=
-2
Exception: pkg-config failed for openssl; Exception: 'module' object has no attribute 'check_output':
  File "/root/rippled/SConstruct", line 1055:
    config_env(toolchain, variant, env)
  File "/root/rippled/SConstruct", line 498:
    static, dynamic = get_libs(l, link_static)
  File "/root/rippled/SConstruct", line 429:
    raise Exception('pkg-config failed for ' + lib + '; Exception: ' + str(e))
root@vps [~/rippled]# pkg-config --static --libs openssl
-Wl,-z,relro -lssl -lcrypto -ldl -lz -lgssapi_krb5 -lkrb5 -lcom_err -lk5crypto

**Comment by nbougalis** [comment]
What Linux distribution are you compiling on?

**Comment by fulviusguelfi** [comment]
CentOS

**Comment by fulviusguelfi** [comment]
CentOS release 6.7 (Final)

**Comment by fulviusguelfi** [comment]
I do not want to build but yum to install rippled do not work too

**Comment by nbougalis** [comment]
What happens when you try to install the yum package?

**Comment by fulviusguelfi** [comment]
This

root@vps [~]# rpm -Uvh https://mirrors.ripple.com/ripple-repo-el7.rpm
Retrieving https://mirrors.ripple.com/ripple-repo-el7.rpm
Preparing...                ########################################### [100%]
	package ripple-repo-1-2.el7.centos.noarch is already installed
root@vps [~]# yum install rippled
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
epel/metalink                                            |  13 kB     00:00     
 * base: denver.gaminghost.co
 * epel: fedora-epel.mirror.lstn.net
 * extras: mirror.cogentco.com
 * updates: pubmirrors.dal.corespace.com
base                                                     | 3.7 kB     00:00     
extras                                                   | 3.4 kB     00:00     
hgdedi                                                   | 2.9 kB     00:00     
scl                                                      | 2.9 kB     00:00     
updates                                                  | 3.4 kB     00:00     
No package rippled available.
Error: Nothing to do

**Comment by fulviusguelfi** [comment]
sory now correct

root@vps [~]# yum install --enablerepo=ripple-stable rippled
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
epel/metalink                                            |  13 kB     00:00     
 * base: denver.gaminghost.co
 * epel: fedora-epel.mirror.lstn.net
 * extras: mirror.cogentco.com
 * updates: pubmirrors.dal.corespace.com
base                                                     | 3.7 kB     00:00     
extras                                                   | 3.4 kB     00:00     
hgdedi                                                   | 2.9 kB     00:00     
https://mirrors.ripple.com/rpm/6/stable/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "NSS: client certificate not found (nickname not specified)"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: ripple-stable. Please verify its path and try again

**Comment by fulviusguelfi** [comment]
Hi nbougalis,

Any sugetions?

**Comment by nbougalis** [comment]
I do not  - I'll bring this to the attention of someone who may be able to assist you more effectively.

**Comment by fulviusguelfi** [comment]
Ok dear friend, I ll be waiting here at forum.
Very Much Tank you and I hope see Ya soon

**Comment by fulviusguelfi** [comment]
Hey, anyone can help me at my problem? ... I did several searches about this build problem and till now the yum package do not work well

**Comment by fulviusguelfi** [comment]
this is error

root@vps [~]# rpm -Uvh https://mirrors.ripple.com/ripple-repo-el7.rpm
Retrieving https://mirrors.ripple.com/ripple-repo-el7.rpm
Preparing...                ########################################### [100%]
	package ripple-repo-1-2.el7.centos.noarch is already installed
root@vps [~]# yum install --enablerepo=ripple-stable rippled
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
epel/metalink                                            |  12 kB     00:00     
 * base: mirror.raystedman.net
 * epel: fedora-epel.mirror.lstn.net
 * extras: pubmirrors.dal.corespace.com
 * updates: centos.mirror.lstn.net
base                                                     | 3.7 kB     00:00     
extras                                                   | 3.4 kB     00:00     
hgdedi                                                   | 2.9 kB     00:00     
https://mirrors.ripple.com/rpm/6/stable/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "NSS: client certificate not found (nickname not specified)"
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

Error: Cannot retrieve repository metadata (repomd.xml) for repository: ripple-stable. Please verify its path and try again

**Comment by fulviusguelfi** [comment]
Hey, I found this problem
My yum is trying to find https://mirrors.ripple.com/rpm/6/stable/x86_64/repodata/repomd.xml and there is no file in this link
The correct link must be https://mirrors.ripple.com/rpm/7/stable/x86_64/repodata/repomd.xml
Ok but my server is CentOS 6.7 (final) like I sad before. and the command was build whit this information. I am trying to update my server to 7 but it is not recommended by all sites that I read and till now I couldn't find a way to upgrade safely 

So can anyone help me whit this problem? Pls I want to run a new Gateway in Brasil and this wil improve our network and services in Ripple Ecosystem... Pls I need so much your help.

**Comment by wilsonianb** [comment]
Hi @fulviusguelfi, the rippled rpm package is currently only available for CentOS 7.
https://ripple.com/build/rippled-setup/#system-requirements

**Comment by fulviusguelfi** [comment]
ok tks
