### ISSUE TITLE
Scons build terminating due to errors

### ISSUE THREAD

**Issue by shambhavi1993** [ripple/rippled#1711]
I have followed all the instructions for building rippled given on https://wiki.ripple.com/Ubuntu_build_instructions.

But when i build using the scons command i get the following error:

scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
protoc -Isrc/ripple/proto --cpp_out=build/proto src/ripple/proto/ripple.proto
sh: 1: protoc: not found
scons: *** [build/proto/ripple.pb.cc] Error 127
scons: building terminated because of errors.

I have updated boost library to 1.57
gcc version is 4.9.3
Ubuntu version is 14.04

**Comment by MarkusTeufelberger** [comment]
You seem to be missing protobuf

**Comment by nbougalis** [comment]
You will not be able to build `rippled` with your current setup. `rippled` requires gcc 5.x or later, and a newer version of Boost. The instructions on https://wiki.ripple.com/Ubuntu_build_instructions include a script that will download and install the correct libraries. Even if you run the script and install the dependencies, ABI changes will complicate the situation and may still leave you unable to properly build.

I recommend that you upgrade to a newer version of Ubuntu: 16.04 LTS is available for download now: http://www.ubuntu.com/download/desktop
