### ISSUE TITLE
Scons build terminating due to errors

### ISSUE THREAD

**Issue by shambhavi1993** [ripple/rippled#1712]
I have followed all the instructions for building rippled given on https://wiki.ripple.com/Ubuntu_build_instructions.

But when i build using the scons command i get the following error:

In file included from src/ripple/unity/app_ledger.cpp:27:0:
src/ripple/app/ledger/Ledger.cpp:1271:45: error: ‘class boost::optional<long unsigned int>’ has no member named ‘value_or’
         time_point{duration{prevClosingTime.value_or(0)}},
                                             ^
src/ripple/app/ledger/Ledger.cpp:1271:56: error: no matching function for call to ‘std::chrono::duration<unsigned int, std::ratio<1l> >::duration(<brace-enclosed initializer list>)’
         time_point{duration{prevClosingTime.value_or(0)}},
                                                        ^
src/ripple/app/ledger/Ledger.cpp:1271:56: note: candidates are:
In file included from src/beast/beast/hash/hash_append.h:28:0,
                 from src/ripple/basics/hardened_hash.h:23,
                 from src/ripple/basics/base_uint.h:31,
                 from src/ripple/protocol/Keylet.h:24,
                 from src/ripple/protocol/Indexes.h:23,
                 from src/ripple/protocol/STLedgerEntry.h:23,
                 from src/ripple/ledger/TxMeta.h:23,
                 from src/ripple/app/ledger/Ledger.h:23,
                 from src/ripple/app/ledger/AcceptedLedgerTx.h:23,
                 from src/ripple/app/ledger/AcceptedLedger.h:23,
                 from src/ripple/app/ledger/AcceptedLedger.cpp:21,
                 from src/ripple/unity/app_ledger.cpp:22:
/usr/include/c++/4.9/chrono:270:14: note: template<class _Rep2, class _Period2, class> constexpr std::chrono::duration<_Rep, _Period>::duration(const std::chrono::duration<_Rep, _Period>&)
    constexpr duration(const duration<_Rep2, _Period2>& __d)
              ^
/usr/include/c++/4.9/chrono:270:14: note:   template argument deduction/substitution failed:
/usr/include/c++/4.9/chrono:263:23: note: template<class _Rep2, class> constexpr std::chrono::duration<_Rep, _Period>::duration(const _Rep2&)
    constexpr explicit duration(const _Rep2& __rep)
                       ^
/usr/include/c++/4.9/chrono:263:23: note:   template argument deduction/substitution failed:
/usr/include/c++/4.9/chrono:257:2: note: std::chrono::duration<_Rep, _Period>::duration(const std::chrono::duration<_Rep, _Period>&) [with _Rep = unsigned int; _Period = std::ratio<1l>]
  duration(const duration&) = default;
  ^
/usr/include/c++/4.9/chrono:257:2: note:   no known conversion for argument 1 from ‘<type error>’ to ‘const std::chrono::duration<unsigned int, std::ratio<1l> >&’
/usr/include/c++/4.9/chrono:252:12: note: constexpr std::chrono::duration<_Rep, _Period>::duration() [with _Rep = unsigned int; _Period = std::ratio<1l>]
  constexpr duration() = default;
            ^
/usr/include/c++/4.9/chrono:252:12: note:   candidate expects 0 arguments, 1 provided
In file included from src/ripple/unity/app_ledger.cpp:27:0:
src/ripple/app/ledger/Ledger.cpp:1271:57: error: no matching function for call to ‘std::chrono::time_point<ripple::NetClock>::time_point(<brace-enclosed initializer list>)’
         time_point{duration{prevClosingTime.value_or(0)}},
                                                         ^
src/ripple/app/ledger/Ledger.cpp:1271:57: note: candidates are:
In file included from src/beast/beast/hash/hash_append.h:28:0,
                 from src/ripple/basics/hardened_hash.h:23,
                 from src/ripple/basics/base_uint.h:31,
                 from src/ripple/protocol/Keylet.h:24,
                 from src/ripple/protocol/Indexes.h:23,
                 from src/ripple/protocol/STLedgerEntry.h:23,
                 from src/ripple/ledger/TxMeta.h:23,
                 from src/ripple/app/ledger/Ledger.h:23,
                 from src/ripple/app/ledger/AcceptedLedgerTx.h:23,
                 from src/ripple/app/ledger/AcceptedLedger.h:23,
                 from src/ripple/app/ledger/AcceptedLedger.cpp:21,
                 from src/ripple/unity/app_ledger.cpp:22:
/usr/include/c++/4.9/chrono:562:14: note: template<class _Dur2> constexpr std::chrono::time_point<_Clock, _Dur>::time_point(const std::chrono::time_point<_Clock, _Dur2>&)
    constexpr time_point(const time_point<clock, _Dur2>& __t)
              ^
/usr/include/c++/4.9/chrono:562:14: note:   template argument deduction/substitution failed:
/usr/include/c++/4.9/chrono:556:21: note: constexpr std::chrono::time_point<_Clock, _Dur>::time_point(const duration&) [with _Clock = ripple::NetClock; _Dur = std::chrono::duration<unsigned int, std::ratio<1l> >; std::chrono::time_point<_Clock, _Dur>::duration = std::chrono::duration<unsigned int, std::ratio<1l> >]
  constexpr explicit time_point(const duration& __dur)
                     ^
/usr/include/c++/4.9/chrono:556:21: note:   no known conversion for argument 1 from ‘<type error>’ to ‘const duration& {aka const std::chrono::duration<unsigned int, std::ratio<1l> >&}’
/usr/include/c++/4.9/chrono:553:12: note: constexpr std::chrono::time_point<_Clock, _Dur>::time_point() [with _Clock = ripple::NetClock; _Dur = std::chrono::duration<unsigned int, std::ratio<1l> >]
  constexpr time_point() : __d(duration::zero())
            ^
/usr/include/c++/4.9/chrono:553:12: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/4.9/chrono:546:14: note: constexpr std::chrono::time_point<ripple::NetClock>::time_point(const std::chrono::time_point<ripple::NetClock>&)
       struct time_point
              ^
/usr/include/c++/4.9/chrono:546:14: note:   no known conversion for argument 1 from ‘<type error>’ to ‘const std::chrono::time_point<ripple::NetClock>&’
/usr/include/c++/4.9/chrono:546:14: note: constexpr std::chrono::time_point<ripple::NetClock>::time_point(std::chrono::time_point<ripple::NetClock>&&)
/usr/include/c++/4.9/chrono:546:14: note:   no known conversion for argument 1 from ‘<type error>’ to ‘std::chrono::time_point<ripple::NetClock>&&’
In file included from src/ripple/unity/app_ledger.cpp:27:0:
src/ripple/app/ledger/Ledger.cpp:1272:20: error: ‘class boost::optional<long unsigned int>’ has no member named ‘value_or’
         closeFlags.value_or(0),
                    ^
src/ripple/app/ledger/Ledger.cpp:1273:34: error: ‘class boost::optional<long unsigned int>’ has no member named ‘value_or’
         duration{closeResolution.value_or(0)},
                                  ^
src/ripple/app/ledger/Ledger.cpp:1273:45: error: no matching function for call to ‘std::chrono::duration<unsigned int, std::ratio<1l> >::duration(<brace-enclosed initializer list>)’
         duration{closeResolution.value_or(0)},
                                             ^
src/ripple/app/ledger/Ledger.cpp:1273:45: note: candidates are:
In file included from src/beast/beast/hash/hash_append.h:28:0,
                 from src/ripple/basics/hardened_hash.h:23,
                 from src/ripple/basics/base_uint.h:31,
                 from src/ripple/protocol/Keylet.h:24,
                 from src/ripple/protocol/Indexes.h:23,
                 from src/ripple/protocol/STLedgerEntry.h:23,
                 from src/ripple/ledger/TxMeta.h:23,
                 from src/ripple/app/ledger/Ledger.h:23,
                 from src/ripple/app/ledger/AcceptedLedgerTx.h:23,
                 from src/ripple/app/ledger/AcceptedLedger.h:23,
                 from src/ripple/app/ledger/AcceptedLedger.cpp:21,
                 from src/ripple/unity/app_ledger.cpp:22:
/usr/include/c++/4.9/chrono:270:14: note: template<class _Rep2, class _Period2, class> constexpr std::chrono::duration<_Rep, _Period>::duration(const std::chrono::duration<_Rep, _Period>&)
    constexpr duration(const duration<_Rep2, _Period2>& __d)
              ^
/usr/include/c++/4.9/chrono:270:14: note:   template argument deduction/substitution failed:
/usr/include/c++/4.9/chrono:263:23: note: template<class _Rep2, class> constexpr std::chrono::duration<_Rep, _Period>::duration(const _Rep2&)
    constexpr explicit duration(const _Rep2& __rep)
                       ^
/usr/include/c++/4.9/chrono:263:23: note:   template argument deduction/substitution failed:
/usr/include/c++/4.9/chrono:257:2: note: std::chrono::duration<_Rep, _Period>::duration(const std::chrono::duration<_Rep, _Period>&) [with _Rep = unsigned int; _Period = std::ratio<1l>]
  duration(const duration&) = default;
  ^
/usr/include/c++/4.9/chrono:257:2: note:   no known conversion for argument 1 from ‘<type error>’ to ‘const std::chrono::duration<unsigned int, std::ratio<1l> >&’
/usr/include/c++/4.9/chrono:252:12: note: constexpr std::chrono::duration<_Rep, _Period>::duration() [with _Rep = unsigned int; _Period = std::ratio<1l>]
  constexpr duration() = default;
            ^
/usr/include/c++/4.9/chrono:252:12: note:   candidate expects 0 arguments, 1 provided
In file included from src/ripple/unity/app_ledger.cpp:28:0:
src/ripple/app/ledger/LedgerHistory.cpp: In member function ‘void ripple::LedgerHistory::builtLedger(const std::shared_ptr<const ripple::Ledger>&, Json::Value)’:
src/ripple/app/ledger/LedgerHistory.cpp:440:18: error: ‘class boost::optional<ripple::base_uint<256ul> >’ has no member named ‘emplace’
     entry->built.emplace (hash);
                  ^
src/ripple/app/ledger/LedgerHistory.cpp:441:22: error: ‘class boost::optional<Json::Value>’ has no member named ‘emplace’
     entry->consensus.emplace (std::move (consensus));
                      ^
src/ripple/app/ledger/LedgerHistory.cpp: In member function ‘void ripple::LedgerHistory::validatedLedger(const std::shared_ptr<const ripple::Ledger>&)’:
src/ripple/app/ledger/LedgerHistory.cpp:473:22: error: ‘class boost::optional<ripple::base_uint<256ul> >’ has no member named ‘emplace’
     entry->validated.emplace (hash);
                      ^
In file included from src/ripple/app/ledger/impl/LedgerConsensusImp.cpp:35:0,
                 from src/ripple/unity/app_ledger.cpp:39:
src/ripple/app/misc/TxQ.h: At global scope:
src/ripple/app/misc/TxQ.h:362:18: error: ‘iterator_type’ in ‘using FeeMultiSet = class boost::intrusive::multiset<ripple::TxQ::CandidateTxn, boost::intrusive::member_hook<ripple::TxQ::CandidateTxn, boost::intrusive::set_member_hook<>, &ripple::TxQ::CandidateTxn::byFeeListHook>, boost::intrusive::compare<ripple::TxQ::GreaterFee> > {aka class boost::intrusive::multiset<ripple::TxQ::CandidateTxn, boost::intrusive::member_hook<ripple::TxQ::CandidateTxn, boost::intrusive::set_member_hook<>, &ripple::TxQ::CandidateTxn::byFeeListHook>, boost::intrusive::compare<ripple::TxQ::GreaterFee> >}’ does not name a type
     FeeMultiSet::iterator_type erase(FeeMultiSet::const_iterator_type);
                  ^
In file included from src/ripple/unity/app_ledger.cpp:39:0:
src/ripple/app/ledger/impl/LedgerConsensusImp.cpp: In member function ‘virtual void ripple::LedgerConsensusImp::simulate(boost::optional<std::chrono::duration<long int, std::ratio<1l, 1000l> > >)’:
src/ripple/app/ledger/impl/LedgerConsensusImp.cpp:928:39: error: ‘class boost::optional<std::chrono::duration<long int, std::ratio<1l, 1000l> > >’ has no member named ‘value_or’
     mCurrentMSeconds = consensusDelay.value_or(100ms);
                                       ^
src/ripple/app/ledger/impl/LedgerConsensusImp.cpp: In member function ‘void ripple::LedgerConsensusImp::accept(std::shared_ptr<ripple::SHAMap>)’:
src/ripple/app/ledger/impl/LedgerConsensusImp.cpp:1152:19: error: ‘class boost::optional<ripple::Rules>’ has no member named ‘emplace’
             rules.emplace(*lastVal);
                   ^
src/ripple/app/ledger/impl/LedgerConsensusImp.cpp:1154:19: error: ‘class boost::optional<ripple::Rules>’ has no member named ‘emplace’
             rules.emplace();
                   ^
In file included from src/ripple/unity/app_ledger.cpp:27:0:
src/ripple/app/ledger/Ledger.cpp: In function ‘std::tuple<std::shared_ptr<ripple::Ledger>, unsigned int, ripple::base_uint<256ul, void> > ripple::loadLedgerHelper(const string&, ripple::Application&)’:
src/ripple/app/ledger/Ledger.cpp:1284:1: warning: control reaches end of non-void function [-Wreturn-type]  }  ^
scons: *** [build/gcc.release/src/ripple/unity/app_ledger.o] Error 1
scons: building terminated because of errors.

I have updated boost library to 1.57
gcc version is 4.9.3
Ubuntu version is 14.04

**Comment by seelabs** [comment]
@shambhavi1993 Thanks for the report. The build instructions were out of date. The latest release of rippled uses C++-14 and requires gcc 5 or better. Once gcc 5 is installed rippled should build. I updated the wiki to reflect this.

**Comment by shambhavi1993** [comment]
Hey,

I have updated gcc and g++ version to 5.3 but still i get the same errors.

In file included from src/ripple/unity/app_ledger.cpp:27:0:

src/ripple/app/ledger/Ledger.cpp:1271:45: error: ‘class
boost::optional<long unsigned int>’ has no member named ‘value_or’

         time_point{duration{prevClosingTime.value_or(0)}},

                                             ^

src/ripple/app/ledger/Ledger.cpp:1271:56: error: no matching function for
call to ‘std::chrono::duration<unsigned int, std::ratio<1l>
>::duration(<brace-enclosed initializer list>)’

         time_point{duration{prevClosingTime.value_or(0)}},

                                                        ^

src/ripple/app/ledger/Ledger.cpp:1271:56: note: candidates are:

In file included from src/beast/beast/hash/hash_append.h:28:0,

                 from src/ripple/basics/hardened_hash.h:23,

                 from src/ripple/basics/base_uint.h:31,

                 from src/ripple/protocol/Keylet.h:24,

                 from src/ripple/protocol/Indexes.h:23,

                 from src/ripple/protocol/STLedgerEntry.h:23,

                 from src/ripple/ledger/TxMeta.h:23,

                 from src/ripple/app/ledger/Ledger.h:23,

                 from src/ripple/app/ledger/AcceptedLedgerTx.h:23,

                 from src/ripple/app/ledger/AcceptedLedger.h:23,

                 from src/ripple/app/ledger/AcceptedLedger.cpp:21,

                 from src/ripple/unity/app_ledger.cpp:22:

/usr/include/c++/4.9/chrono:270:14: note: template<class _Rep2, class
_Period2, class> constexpr std::chrono::duration<_Rep,
_Period>::duration(const std::chrono::duration<_Rep, _Period>&)

    constexpr duration(const duration<_Rep2, _Period2>& __d)

              ^

/usr/include/c++/4.9/chrono:270:14: note:   template argument
deduction/substitution failed:

/usr/include/c++/4.9/chrono:263:23: note: template<class _Rep2, class>
constexpr std::chrono::duration<_Rep, _Period>::duration(const _Rep2&)

    constexpr explicit duration(const _Rep2& __rep)

                       ^

/usr/include/c++/4.9/chrono:263:23: note:   template argument
deduction/substitution failed:

/usr/include/c++/4.9/chrono:257:2: note: std::chrono::duration<_Rep,
_Period>::duration(const std::chrono::duration<_Rep, _Period>&) [with _Rep
= unsigned int; _Period = std::ratio<1l>]

  duration(const duration&) = default;

  ^

/usr/include/c++/4.9/chrono:257:2: note:   no known conversion for argument
1 from ‘<type error>’ to ‘const std::chrono::duration<unsigned int,
std::ratio<1l> >&’

/usr/include/c++/4.9/chrono:252:12: note: constexpr
std::chrono::duration<_Rep, _Period>::duration() [with _Rep = unsigned int;
_Period = std::ratio<1l>]

  constexpr duration() = default;

            ^

/usr/include/c++/4.9/chrono:252:12: note:   candidate expects 0 arguments,
1 provided

In file included from src/ripple/unity/app_ledger.cpp:27:0:

src/ripple/app/ledger/Ledger.cpp:1271:57: error: no matching function for
call to
‘std::chrono::time_point<ripple::NetClock>::time_point(<brace-enclosed
initializer list>)’

         time_point{duration{prevClosingTime.value_or(0)}},

                                                         ^

src/ripple/app/ledger/Ledger.cpp:1271:57: note: candidates are:

In file included from src/beast/beast/hash/hash_append.h:28:0,

                 from src/ripple/basics/hardened_hash.h:23,

                 from src/ripple/basics/base_uint.h:31,

                 from src/ripple/protocol/Keylet.h:24,

                 from src/ripple/protocol/Indexes.h:23,

                 from src/ripple/protocol/STLedgerEntry.h:23,

                 from src/ripple/ledger/TxMeta.h:23,

                 from src/ripple/app/ledger/Ledger.h:23,

                 from src/ripple/app/ledger/AcceptedLedgerTx.h:23,

                 from src/ripple/app/ledger/AcceptedLedger.h:23,

                 from src/ripple/app/ledger/AcceptedLedger.cpp:21,

                 from src/ripple/unity/app_ledger.cpp:22:

/usr/include/c++/4.9/chrono:562:14: note: template<class _Dur2> constexpr
std::chrono::time_point<_Clock, _Dur>::time_point(const
std::chrono::time_point<_Clock, _Dur2>&)

    constexpr time_point(const time_point<clock, _Dur2>& __t)

              ^

/usr/include/c++/4.9/chrono:562:14: note:   template argument
deduction/substitution failed:

/usr/include/c++/4.9/chrono:556:21: note: constexpr
std::chrono::time_point<_Clock, _Dur>::time_point(const duration&) [with
_Clock = ripple::NetClock; _Dur = std::chrono::duration<unsigned int,
std::ratio<1l> >; std::chrono::time_point<_Clock, _Dur>::duration =
std::chrono::duration<unsigned int, std::ratio<1l> >]

  constexpr explicit time_point(const duration& __dur)

                     ^

/usr/include/c++/4.9/chrono:556:21: note:   no known conversion for
argument 1 from ‘<type error>’ to ‘const duration& {aka const
std::chrono::duration<unsigned int, std::ratio<1l> >&}’

/usr/include/c++/4.9/chrono:553:12: note: constexpr
std::chrono::time_point<_Clock, _Dur>::time_point() [with _Clock =
ripple::NetClock; _Dur = std::chrono::duration<unsigned int, std::ratio<1l>
>]

  constexpr time_point() : __d(duration::zero())

            ^

/usr/include/c++/4.9/chrono:553:12: note:   candidate expects 0 arguments,
1 provided

/usr/include/c++/4.9/chrono:546:14: note: constexpr
std::chrono::time_point<ripple::NetClock>::time_point(const
std::chrono::time_point<ripple::NetClock>&)

       struct time_point

              ^

/usr/include/c++/4.9/chrono:546:14: note:   no known conversion for
argument 1 from ‘<type error>’ to ‘const
std::chrono::time_point<ripple::NetClock>&’

/usr/include/c++/4.9/chrono:546:14: note: constexpr
std::chrono::time_point<ripple::NetClock>::time_point(std::chrono::time_point<ripple::NetClock>&&)

/usr/include/c++/4.9/chrono:546:14: note:   no known conversion for
argument 1 from ‘<type error>’ to
‘std::chrono::time_point<ripple::NetClock>&&’

In file included from src/ripple/unity/app_ledger.cpp:27:0:

src/ripple/app/ledger/Ledger.cpp:1272:20: error: ‘class
boost::optional<long unsigned int>’ has no member named ‘value_or’

         closeFlags.value_or(0),

                    ^

src/ripple/app/ledger/Ledger.cpp:1273:34: error: ‘class
boost::optional<long unsigned int>’ has no member named ‘value_or’

         duration{closeResolution.value_or(0)},

                                  ^

src/ripple/app/ledger/Ledger.cpp:1273:45: error: no matching function for
call to ‘std::chrono::duration<unsigned int, std::ratio<1l>
>::duration(<brace-enclosed initializer list>)’

         duration{closeResolution.value_or(0)},

                                             ^

src/ripple/app/ledger/Ledger.cpp:1273:45: note: candidates are:

In file included from src/beast/beast/hash/hash_append.h:28:0,

                 from src/ripple/basics/hardened_hash.h:23,

                 from src/ripple/basics/base_uint.h:31,

                 from src/ripple/protocol/Keylet.h:24,

                 from src/ripple/protocol/Indexes.h:23,

                 from src/ripple/protocol/STLedgerEntry.h:23,

                 from src/ripple/ledger/TxMeta.h:23,

                 from src/ripple/app/ledger/Ledger.h:23,

                 from src/ripple/app/ledger/AcceptedLedgerTx.h:23,

                 from src/ripple/app/ledger/AcceptedLedger.h:23,

                 from src/ripple/app/ledger/AcceptedLedger.cpp:21,

                 from src/ripple/unity/app_ledger.cpp:22:

/usr/include/c++/4.9/chrono:270:14: note: template<class _Rep2, class
_Period2, class> constexpr std::chrono::duration<_Rep,
_Period>::duration(const std::chrono::duration<_Rep, _Period>&)

    constexpr duration(const duration<_Rep2, _Period2>& __d)

              ^

/usr/include/c++/4.9/chrono:270:14: note:   template argument
deduction/substitution failed:

/usr/include/c++/4.9/chrono:263:23: note: template<class _Rep2, class>
constexpr std::chrono::duration<_Rep, _Period>::duration(const _Rep2&)

    constexpr explicit duration(const _Rep2& __rep)

                       ^

/usr/include/c++/4.9/chrono:263:23: note:   template argument
deduction/substitution failed:

/usr/include/c++/4.9/chrono:257:2: note: std::chrono::duration<_Rep,
_Period>::duration(const std::chrono::duration<_Rep, _Period>&) [with _Rep
= unsigned int; _Period = std::ratio<1l>]

  duration(const duration&) = default;

  ^

/usr/include/c++/4.9/chrono:257:2: note:   no known conversion for argument
1 from ‘<type error>’ to ‘const std::chrono::duration<unsigned int,
std::ratio<1l> >&’

/usr/include/c++/4.9/chrono:252:12: note: constexpr
std::chrono::duration<_Rep, _Period>::duration() [with _Rep = unsigned int;
_Period = std::ratio<1l>]

  constexpr duration() = default;

            ^

/usr/include/c++/4.9/chrono:252:12: note:   candidate expects 0 arguments,
1 provided

In file included from src/ripple/unity/app_ledger.cpp:28:0:

src/ripple/app/ledger/LedgerHistory.cpp: In member function ‘void
ripple::LedgerHistory::builtLedger(const std::shared_ptr<const
ripple::Ledger>&, Json::Value)’:

src/ripple/app/ledger/LedgerHistory.cpp:440:18: error: ‘class
boost::optional<ripple::base_uint<256ul> >’ has no member named ‘emplace’

     entry->built.emplace (hash);

                  ^

src/ripple/app/ledger/LedgerHistory.cpp:441:22: error: ‘class
boost::optional<Json::Value>’ has no member named ‘emplace’

     entry->consensus.emplace (std::move (consensus));

                      ^

src/ripple/app/ledger/LedgerHistory.cpp: In member function ‘void
ripple::LedgerHistory::validatedLedger(const std::shared_ptr<const
ripple::Ledger>&)’:

src/ripple/app/ledger/LedgerHistory.cpp:473:22: error: ‘class
boost::optional<ripple::base_uint<256ul> >’ has no member named ‘emplace’

     entry->validated.emplace (hash);

                      ^

In file included from
src/ripple/app/ledger/impl/LedgerConsensusImp.cpp:35:0,

                 from src/ripple/unity/app_ledger.cpp:39:

src/ripple/app/misc/TxQ.h: At global scope:

src/ripple/app/misc/TxQ.h:362:18: error: ‘iterator_type’ in ‘using
FeeMultiSet = class boost::intrusive::multiset<ripple::TxQ::CandidateTxn,
boost::intrusive::member_hook<ripple::TxQ::CandidateTxn,
boost::intrusive::set_member_hook<>,
&ripple::TxQ::CandidateTxn::byFeeListHook>,
boost::intrusive::compare<ripple::TxQ::GreaterFee> > {aka class
boost::intrusive::multiset<ripple::TxQ::CandidateTxn,
boost::intrusive::member_hook<ripple::TxQ::CandidateTxn,
boost::intrusive::set_member_hook<>,
&ripple::TxQ::CandidateTxn::byFeeListHook>,
boost::intrusive::compare<ripple::TxQ::GreaterFee> >}’ does not name a type

     FeeMultiSet::iterator_type erase(FeeMultiSet::const_iterator_type);

                  ^

In file included from src/ripple/unity/app_ledger.cpp:39:0:

src/ripple/app/ledger/impl/LedgerConsensusImp.cpp: In member function
‘virtual void
ripple::LedgerConsensusImp::simulate(boost::optional<std::chrono::duration<long
int, std::ratio<1l, 1000l> > >)’:

src/ripple/app/ledger/impl/LedgerConsensusImp.cpp:928:39: error: ‘class
boost::optional<std::chrono::duration<long int, std::ratio<1l, 1000l> > >’
has no member named ‘value_or’

     mCurrentMSeconds = consensusDelay.value_or(100ms);

                                       ^

src/ripple/app/ledger/impl/LedgerConsensusImp.cpp: In member function ‘void
ripple::LedgerConsensusImp::accept(std::shared_ptr<ripple::SHAMap>)’:

src/ripple/app/ledger/impl/LedgerConsensusImp.cpp:1152:19: error: ‘class
boost::optional<ripple::Rules>’ has no member named ‘emplace’

             rules.emplace(*lastVal);

                   ^

src/ripple/app/ledger/impl/LedgerConsensusImp.cpp:1154:19: error: ‘class
boost::optional<ripple::Rules>’ has no member named ‘emplace’

             rules.emplace();

                   ^

In file included from src/ripple/unity/app_ledger.cpp:27:0:

src/ripple/app/ledger/Ledger.cpp: In function
‘std::tuple<std::shared_ptr<ripple::Ledger>, unsigned int,
ripple::base_uint<256ul, void> > ripple::loadLedgerHelper(const string&,
ripple::Application&)’:

src/ripple/app/ledger/Ledger.cpp:1284:1: warning: control reaches end of
non-void function [-Wreturn-type]  }  ^

scons: *** [build/gcc.release/src/ripple/unity/app_ledger.o] Error 1

scons: building terminated because of errors.


I have ubuntu version 14.04.


Please let me know what is the possible solution.

Thanks.

**Comment by shambhavi1993** [comment]
I have also set BOOST_ROOT and PROTOBUF_DIR paths.

**Comment by yxxyun** [comment]
https://github.com/ripple/rippled/blob/develop/Builds/Ubuntu/install_rippled_depends_ubuntu.sh

**Comment by shambhavi1993** [comment]
after running this command
sudo Builds/Ubuntu/install_rippled_depends_ubuntu.sh

I get the following warning and error:
WARNING: The following packages cannot be authenticated!
  boost-all boost-all-dev
E: There are problems and -y was used without --force-yes

And when i again build it using scons command I again get the same above error.

**Comment by yxxyun** [comment]
Well,I install a fresh ubuntu 14.04 and test again, got same warning.
so I modify the https://github.com/ripple/rippled/blob/release/Builds/Ubuntu/install_rippled_depends_ubuntu.sh#L41 
and add --force-yes
after install the depends, begin compile, not complete yet, but so far seems good.

**Comment by yxxyun** [comment]
well, got a error, seems like because of the boost version? maybe should try boost 1.59

**Comment by shambhavi1993** [comment]
Yes I did the same....and my build was successful

**Comment by yxxyun** [comment]
Congratulation.  I got a error because my VPS is overload and killed the build process.

**Comment by shambhavi1993** [comment]
hey,
my build was successful.

But now when I do steps under Development Ripple-lib

after running the grunt command I get the following error:

A valid Gruntfile could not be found. Please see the getting started guide
for
more information on how to configure grunt:
http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.

Please tell me what will be the possible solution.

Thanks
