### ISSUE TITLE
Fatal error: Unable to find Gruntfile.

### ISSUE THREAD

**Issue by shambhavi1993** [ripple/rippled#1715]
my build was successful.

But now when I do steps under "Development Ripple-lib" on this link https://wiki.ripple.com/Ubuntu_build_instructions

after running the **grunt** command I get the following error:

A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.

Please tell me what will be the possible solution.

**Comment by sublimator** [comment]
Oh, the wiki needs updating! Don't try and use `development ripple-lib`, only the one specified in the package.json

**Comment by shambhavi1993** [comment]
I want to setup development env for Ripple.
So please suggest me what should i follow.

**Comment by shambhavi1993** [comment]
After successful building using scons command , what we should do in order to show payment processing on local setup.

**Comment by nbougalis** [comment]
For future reference, this is not the correct project for your issue: `rippled` is the reference C++ server implementation of the Ripple protocol.
