### ISSUE TITLE
Query about KYC implementation on Ripple

### ISSUE THREAD

**Issue by shambhavi1993** [ripple/rippled#1716]
Hey, 
I wanted to know whether we can implement KYC using Ripple.
And if we can, do Ripple has any base for it.

Because I've been searching for some links related to KYC on Ripple and in one of the links it was mentioned that Ripple will be starting with KYC implementation.

Let me know if I'm right.

**Comment by MarkusTeufelberger** [comment]
If you issue something on Ripple, you can (optionally) decide who is allowed to hold your issued tokens. A way to decide on that list would be to have some sort of KYC process on your end.

Ripple itself does not deal with KYC directly, it deals with offering a trading platform or market or settlement layer or whatever you want to call it.

Ripple (the company) offered a wallet for the Ripple network through a sub-company and they started to require KYC through them to use it before they discontinued the product. Maybe that was what you read?
