### ISSUE TITLE
Maintain API documentation alongside with code in GIT-repo

### ISSUE THREAD

**Issue by dokterbob** [ripple/rippled#172]
Becasue there are several branches and progress is fast it seems that the documentation on the wiki is lagging behind on the state of the code.

For third parties to be able to reliably install and build rippled it might make sense to include documentation in the GIT-repo. This way, keeping documentation in sync with the features could be simplified by requiring pull requests to be accompanied with documentation. As a bonus, it is a cheap way to increase the documentation whenever new features are implemented.

Perhaps it would be even wise to have API documentation in the source tree as well for the same reasons as above.

**Comment by vinniefalco** [comment]
wontfix, API documentation is in the official site
