### ISSUE TITLE
Permission error while running admin commands

### ISSUE THREAD

**Issue by shambhavi1993** [ripple/rippled#1724]
I have done the validator setup under the link : https://ripple.com/build/rippled-setup/#installing-rippled
When i run the admin command **wallet_propose** i get the below error:
{
   "result" : {
      "error" : "noPermission",
      "error_code" : 6,
      "error_message" : "You don't have permission for this command.",
      "request" : {
         "command" : "wallet_propose",
         "passphrase" : "masterpassphrase"
      },
      "status" : "error"
   }
}

In  the rippled.cfg file I have added my system IP for admin under [port_rpc_admin_local]

Please let me know what's the fix for this.

**Comment by vinniefalco** [comment]
Is this still an issue?
