### ISSUE TITLE
txnNotFound error

### ISSUE THREAD

**Issue by shambhavi1993** [ripple/rippled#1725]
I have followed the instructions given on the below link: https://ripple.com/build/reliable-transaction-submission/ for constructing, signing and submitting the transaction.

All of the above step had a success error message but when I verify the transaction, I get a txnNotFound error code.

I have looked out for several things but couldn't come down to a solution.

Help me with this...!

**Comment by JoelKatz** [comment]
Can you show us what your last command is before you get the error, what reply you get, what command gets the error, and the exact error message?

**Comment by vinniefalco** [comment]
Is this still an issue?
