### ISSUE TITLE
rpc_allow instead of rpc_allow_remote

### ISSUE THREAD

**Issue by dokterbob** [ripple/rippled#175]
Currently, it is only possible to enable/disable RPC access for `127.0.0.1` rather than being able to specify exactly which address or addresses have access - while for admin-specific commands this is already possible. I would like to propose instead having `rpc_allow` with a similar syntax as `rpc_admin_allow`.

This is related to #170 and #174 but is more of a suggested improvement rather than a bugfix; in a lot of cases we want to open up the RPC interface just to a particular network (ie. DMZ, VPN) for just a particular address or a particular group of addresses. Moreover, this would allow for the OS to handle whether or not a socket can be established (rather than rippled itself as with rpc_allow_remote), potentially increasing security.

**Comment by vinniefalco** [comment]
Obsolete
