### ISSUE TITLE
Add new transaction or account flag for the purpose of account shutdown/compromise.

### ISSUE THREAD

**Issue by dchapes** [ripple/rippled#180]
In the case where someone no longer wants to use a Ripple account, or worse has discovered that their secret has been compromised, it would be great if there was a transaction they could issue that would zero the limit (limit, not balance) of any _incoming_ trust lines and possibly also set the [`tfRequireAuth`](https://ripple.com/wiki/Transaction_Format#AccountSet_.283.29) flag so that new incoming trust lines cannot be created. Perhaps this could simply be a new account flag: `tfCompromised` or `tfDoNotUse`.

Otherwise the account holder needs to contact the owners of all the incoming trust lines to ask them to remove the trust. In the case of a compromise this may be urgent if the attacker has not yet used the compromised secret or hasn't yet figured out they can leverage the trust lines. Even if the attacker has already maxed out any personal trust lines, payments by others may change the balance allowing the attacker to extract further funds later unless the trust lines are limited.

This would currently only be of concern to people who use personal trust lines rather than the simplified use case of only trusting gateways.

**Comment by JoelKatz** [comment]
This really isn't necessary. If you don't have control over the account, you can't set this flag anyway. And if you do have control over the account, you can set a new regular key, remove signer lists, disable the master key, set trust lines to zero, and so on. People wouldn't set this flag manually, they'd use some program that offers this feature. That program can just as easily execute the necessary steps to secure the account.

**Comment by ximinez** [comment]
> If the authority to issue money is compromised then there has to be a mechanism in which transactions are frozen while the previous balances are reconciled and the ability given for users to be able to redeem their electronic money to fiat or to be issued with new money.

This sounds like [Global Freeze](https://ripple.com/build/freeze/#global-freeze).
