### ISSUE TITLE
PROTOBUF_GENERATE_CPP command line on CMakeLists.txt cannot processes.

### ISSUE THREAD

**Issue by rchatsiri** [ripple/rippled#1836]
I built rippled project with Cmake tools. ```CMakeLists.txt``` requires boost, protobuf , openssl library which system install library completed.  I'm didn't  know PROTOBUF_GENERATE_CPP line on CMakeList.txt cannot processes and show error as  

```Unknow CMake command "PROTOBUF_GENERATE_CPP". ```

**Comment by seelabs** [comment]
@rchatsiri Thanks for the report. I will look into the issue. CMake support is still experimental; our scons build support should be used if cmake is failing for you.

The `PROTOBUF_GENERATE_CPP` comes from the cmake module FindProtobuf.cmake, except on windows where we define it ourselves. It found the cmake module (or we would have seen a different error). 

To help me track down this problem, can you tell me:
1) What OS you're using.
2) What version of CMake you're using.
4) Is the `protoc` command installed and on your path. If not install it and try again.
5) If you can easily find the file `FindProtobuf.cmake` (on my system it's in `/usr/share/cmake-3.5/Modules/FindProtobuf.cmake`). Is that function defined in that file?

**Comment by rchatsiri** [comment]
@seelabs  Reply for questioning.
1)  14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
2) cmake version 3.2.2
4) I can use Protoc command line in terminal mode.
5) I found FindProtobuf.cmake at path /usr/share/cmake-3.2/Modules
6) I attach error at cmake run unsuccess steps.
```
rchatsiri@rchatsiri-ThinkPad-T420s:~/sdc1/workspacecpp/blockchain/rippled/build$ cmake ..
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   coroutine
--   context
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   thread
-- Could NOT find PROTOBUF (missing:  PROTOBUF_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rchatsiri/sdc1/workspacecpp/blockchain/rippled/build
```

After run with make && make install

```
In file included from /home/rchatsiri/sdc1/workspacecpp/blockchain/rippled/src/ripple/app/ledger/LedgerMaster.h:40:0,
                 from /home/rchatsiri/sdc1/workspacecpp/blockchain/rippled/src/ripple/app/ledger/AccountStateSF.cpp:22,
                 from /home/rchatsiri/sdc1/workspacecpp/blockchain/rippled/src/ripple/unity/app_ledger.cpp:24:
/home/rchatsiri/sdc1/workspacecpp/blockchain/rippled/build/ripple.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
compilation terminated.
```

**Comment by rchatsiri** [comment]
It's source code build success because use command as ```cmake -DPROTOBUF_INCLUDE_DIR="/protobuf-2.5.0/build/include" ..```. I think that issues should close.
