### ISSUE TITLE
Please keep command parameter names consistent with JSON parameters

### ISSUE THREAD

**Issue by ThePiachu** [ripple/rippled#188]
While reading the RPC API page on various commands, I can see entries like:

Command line:
wallet_propose [pass_phrase]
JSON:
{
  passphrase: string
}

With two different ways of writing the same command parameter. This has caused me a few times to use the wrong spelling for my program. If it is possible, it would be great to keep those parameter names the same (preferably without the underscores).

**Comment by rec** [comment]
I agree with the sentiment entire! - and sorry for the frustration - but we aren't unfortunately going to change any names until a future RPC 2.0, where everything will be consistent.
