### ISSUE TITLE
Rippled seems to have issues with public IP changes while running

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#1924]
My ISP unfortunately has a 24h reconnect to hand out a new public IP from its pool to all connected customers. 0.40.0-rc1 does often not manage to communicate at all with the worls after that happens, usually after complaining about a time shift.

I'll post logs tomorrow (didn't think to copy them after restarting today) in case they help you, maybe you anyways already have some idea what could be going on, since this is realatively new (earlier 0.40.0 betas did not fail this as far as I remember).

**Comment by vinniefalco** [comment]
How do you suggest we address this in rippled?

**Comment by MarkusTeufelberger** [comment]
Previously it just complained for a few seconds, (re)connected to some peers and went on its merry way. Now it just sits there passively. A potential fix might be to drop peer connections/sessions and reconnect after a certain threshold of not receiving any data or validations from the network.

**Comment by vinniefalco** [comment]
Another solution, which I realize is less than satisfying, is simply to state as a requirement of running rippled to have a stable IP.

**Comment by MarkusTeufelberger** [comment]
I agree (though having a stable host name is much easier to accomplish in practice) and I can also think of a few workarounds including just restarting rippled every 24 hours. Still this used to work without issues and now it doesn't, so I thought it might be some unintended side effect of some recent changes.

**Comment by nbougalis** [comment]
This shouldn't happen. I'll try and look into why this is happening, but it's going to be low on my priority list. Probably something to look at over the holidays.

**Comment by MarkusTeufelberger** [comment]
...and of course this issue does not happen the past 2 days after presenting itself for 3 days straight. -.-'

**Comment by MarkusTeufelberger** [comment]
Did very rarely happen lately, probably an edge case anyways...
Closing this issue.
