### ISSUE TITLE
Command "rippled ledger full" returns internal error

### ISSUE THREAD

**Issue by matejr** [ripple/rippled#1933]
Command
```
/opt/ripple/bin/rippled ledger 26200000 full
```

returns:
```
Loading: "/etc/opt/ripple/rippled.cfg"
Connecting to 127.0.0.1:5005
{
   "error" : "internal",
   "error_code" : 69,
   "error_message" : "Internal error.",
   "error_what" : "couldn't parse reply from server"
}
```

Rippled version 0.33.0-hf1 running on CentOS 7. 

If I use another ledger index (e.g. 26200002), I get the same error.

**Comment by JoelKatz** [comment]
I can replicate this. And it used to (just barely) work.

**Comment by JoelKatz** [comment]
You can fix this by changing RPC_REPLY_MAX_BYTES in RPCCall.cpp from 256*1024*1024 to 1024*1024*1024 -- but you really shouldn't be asking rippled to get you an entire ledger and convert it from binary to text all in one shot as one JSON object. It's just not efficient.

**Comment by vinniefalco** [comment]
Is this still an issue?

**Comment by matejr** [comment]
Not for me (anymore). I used curl for sending queries to rippled and it worked.
