### ISSUE TITLE
tfSetNoRipple ineffective when creating a new trust line

### ISSUE THREAD

**Issue by dchapes** [ripple/rippled#195]
It appears that `tfSetNoRipple` is ineffective when used in a transaction that creates a new trust line. If used in a following transaction to modify the same trust line it works as expected.

Tx `BBC1B69083937F3F2A0A9FCEC24E37E540CF00140F6B9B9A4BB0A4FBCCD8F45F` creates a trust line but `lsfHighNoRipple` is _not_ set in the created node (nor does it appear to be set when querying the trust lines with `account_lines`).
Tx `8CD0E7FADFC397976F30D6EEDD06EFA9E27F87AF0B12C353DA95BE06CB9742CB` adjusts the same trust line again using `tfSetNoRipple`. Now `lsfHighNoRipple` is in the flags for the modified node and `no_ripple: true` appears with `account_lines`.

**Comment by vinniefalco** [comment]
Obsolete
