### ISSUE TITLE
Websocket API subscribe to multiple books only returns last book

### ISSUE THREAD

**Issue by donovanhide** [ripple/rippled#196]
Sending this command to a ripple server:

{"id":1,"command":"subscribe","books":[{"taker_gets":{"currency":"XRP"},"taker_pays":{"currency":"CNY","issuer":"rnuF96W4SZoCJmbHYBFoJZpR8eCaxNvekK"},"snapshot":true,"both":true},{"taker_gets":{"currency":"XRP"},"taker_pays":{"currency":"BTC","issuer":"rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B"},"snapshot":true,"both":true}]}

only results in the snapshot of the second book being returned.

**Comment by HowardHinnant** [comment]
Fixed by https://github.com/ripple/rippled/commit/b2ba6a0c8571c3080d467c59f9c065b8fb95a578
