### ISSUE TITLE
Allow ripple_path_find to be used with dummy source + destination accounts

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#1965]
https://ripple.com/build/rippled-apis/#ripple-path-find requires a source_account and destination_account that already exists on the ledger.

I'd like to propose that this could be extended by a special value "dummy" or "limitless" (or some other fitting name) that is used instead of an actual account in one of these 2 fields. This would assume an account with an infinite amount of each entry in source_currencies (issuer has to be specified in that case and source_currencies would be mandatory, even for XRP) for the sending account and an account with an infinite trust line for the currency in destination_amount (again: issuer mandatory).

The goal of this extension is to be able to measure the total available liquidity at a certain ledger or at the moment for any currency pair, maybe a bit similar to the "autobridging" which also showed more available liquidity.

Possible limitations might be to make this admin-only (since it could be relatively expensive to compute) or maybe instead of adding a few special cases to ripple_path_find to add a ripple_path_liquidity RPC call that is modelled after r_p_f. I'd still like to see some aspects of path_find in there though, for example to see how much slippage occurs depending on the amount sent/received.

If only one of these two fields is set to the dummy value, this would answer the questions of "how many X can my account send at most?" (with a receiving dummy, though this could also be modelled by specifying the gateway account as a receiver) and "how many X could someone send me?" (also not the most exciting use case, since this is the limit of the existing trust line for X).

**Comment by carlhua** [comment]
Closing this - this should be implemented outside of rippled. Perhaps we can consider a service that provides paid pathfinding services.
