### ISSUE TITLE
[Documentation] Latest releases not documented on GitHub

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#1977]
https://github.com/ripple/rippled/releases seems to be the only(?) public source left for release notes as the wiki only links there, please also post the current ones.

**Comment by MarkusTeufelberger** [comment]
@mDuo13 - I guess this is in your area. :-)

**Comment by nbougalis** [comment]
Thanks @MarkusTeufelberger. We will try to improve our release process so that information about releases is also available on GitHub and in https://github.com/ripple/rippled/blob/develop/RELEASENOTES.md.

**Comment by mDuo13** [comment]
I've edited the tags in GitHub to contain the release notes. We're working on a process improvement to make sure this doesn't get missed again. Also, we're also posting the release notes to the [Ripple Dev Blog](https://ripple.com/dev-blog/) now.

**Comment by MarkusTeufelberger** [comment]
Thanks. :-)
