### ISSUE TITLE
server streaming not working.

### ISSUE THREAD

**Issue by ripplerm** [ripple/rippled#1991]
was trying to subscribe to server status stream via websocket command as follow:
[https://ripple.com/build/websocket-tool/#subscribe](https://ripple.com/build/websocket-tool/#subscribe)

but the subscription never received any stream of server status.

**Comment by bachase** [comment]
Currently, a server status update is published when

1.  The operating mode changes (e.g. syncing -> tracking)
2.  There is a change to the local fee, but not the open ledger fees (https://ripple.com/build/transaction-cost/#load-cost-and-open-ledger-cost).

Both of those are very rare, so its not surprising you don't see any updates.

I'm guessing you are interested in receiving updates as open ledger fees change too?  We will work to add that support, but I don't have an ETA for you now.

**Comment by ripplerm** [comment]
> I'm guessing you are interested in receiving updates as open ledger fees change too?
yes, that's what we need for dynamically setting fee for submitting transaction.

currently we are requesting those info by periodically sending 'server_info' or 'fee' command.
IMO it would be better if could get this info updates from server subscription.

**Comment by ripplerm** [comment]
of maybe could create another subscription stream named 'fee' that published the change of open ledger fees.
