### ISSUE TITLE
[Question] How to run rippled in testnet mode?

### ISSUE THREAD

**Issue by gituser** [ripple/rippled#2078]
Hello.

I understand ripple labs offers external rpc server to connect to the testnet, but how do I put my own rippled daemon into testnet mode?

By default it use production network, but I'd like to test everything properly before putting it into the production environment.

Thanks.

**Comment by wilsonianb** [comment]
Hello, you can connect to the testnet by reconfiguring the peers you connect to and the validators you trust.

Change the following field in rippled.cfg:
```
[ips]
52.11.28.194 51235
54.94.245.104 51235
54.201.240.60 51235
54.238.143.216 51235
```

Also change the following field in validators.txt:
```
[validators]
nHUhG1PgAG8H8myUENypM35JgfqXAKNQvRVVAFDRzJrny5eZN8d5
nHBu9PTL9dn2GuZtdW4U2WzBwffyX9qsQCd9CNU4Z5YG3PQfViM8
nHUPDdcdb2Y5DZAJne4c2iabFuAP3F34xZUgYQT2NH7qfkdapgnz
nHB1X37qrniVugfQcuBTAjswphC1drx7QjFFojJPZwKHHnt8kU7v
nHUkAWDR4cB8AgPg7VXMX6et8xRTQb2KJfgv1aBEXozwrawRKgMB
```

**Comment by gituser** [comment]
thanks for this!
how do I know if rippled is in sync? 
ripple db's directory seems growing and growing..

**Comment by wilsonianb** [comment]
You can run `server_info` and check for `"server_state" : "full"` and a `"validated_ledger"` with a `"seq"` close to what's shown here: https://api.altnet.rippletest.net:5990/v1/server

https://ripple.com/build/rippled-apis/#server-info

**Comment by gituser** [comment]
thanks!

**Comment by icemilo** [comment]
Are these ips and validators still valid? I'm getting `LedgerMaster:DBG No validated ledger` from the logs. Could you enlighten me? @wilsonianb

**Comment by wilsonianb** [comment]
Hi @icemilo 
I was just able to sync to the testnet with that configuration.
You could try replacing `54.201.240.60 51235` with `54.213.214.68 51235` in the `[ips]` section.
If that still doesn't work, would you mind running `rippled unl_list` and posting the response?
Thanks

**Comment by icemilo** [comment]
@wilsonianb Thanks for the reply, after I changed the ips to what you have stated above, `No validated ledger` warning seems to be gone. However, I'm getting `NetworkOPs:WRN We are not running on the consensus ledger` instead. The below is the response when running `rippled unl_list`.

```{
   "id" : 1,
   "result" : {
      "status" : "success",
      "unl" : [
         {
            "pubkey_validator" : "n9LdgEtkmGB9E2h3K4Vp7iGUaKuq23Zr32ehxiU8FWY7xoxbWTSA",
            "trusted" : true
         },
         {
            "pubkey_validator" : "n949f75evCHwgyP4fPVgaHqNHxUVN15PsJEZ3B3HnXPcPjcZAoy7",
            "trusted" : true
         },
         {
            "pubkey_validator" : "n9MD5h24qrQqiyBC8aeqqCWvpiBiYQ3jxSr91uiDvmrkyHRdYLUj",
            "trusted" : true
         },
         {
            "pubkey_validator" : "n9KiYM9CgngLvtRCQHZwgC2gjpdaZcCcbt3VboxiNFcKuwFVujzS",
            "trusted" : true
         },
         {
            "pubkey_validator" : "n9L81uNCaPgtUJfaHh89gmdvXKAmSt5Gdsw2g1iPWaPkAHW5Nm4C",
            "trusted" : true
         }
      ]
   }
}```

**Comment by nbougalis** [comment]
You seem to be trusting the mainnet validators, not the testnet ones.

**Comment by icemilo** [comment]
@nbougalis Thanks for pointing out. I forgot to put `[validators]` above the validators specified in the config file. Below is the new `unl_list` after changing to testnet validators

```{
   "id" : 1,
   "result" : {
      "status" : "success",
      "unl" : [
         {
            "pubkey_validator" : "n9LdgEtkmGB9E2h3K4Vp7iGUaKuq23Zr32ehxiU8FWY7xoxbWTSA",
            "trusted" : false
         },
         {
            "pubkey_validator" : "n9L81uNCaPgtUJfaHh89gmdvXKAmSt5Gdsw2g1iPWaPkAHW5Nm4C",
            "trusted" : false
         },
         {
            "pubkey_validator" : "n9MD5h24qrQqiyBC8aeqqCWvpiBiYQ3jxSr91uiDvmrkyHRdYLUj",
            "trusted" : false
         },
         {
            "pubkey_validator" : "n949f75evCHwgyP4fPVgaHqNHxUVN15PsJEZ3B3HnXPcPjcZAoy7",
            "trusted" : false
         },
         {
            "pubkey_validator" : "n9KiYM9CgngLvtRCQHZwgC2gjpdaZcCcbt3VboxiNFcKuwFVujzS",
            "trusted" : false
         },
         {
            "pubkey_validator" : "nHUkAWDR4cB8AgPg7VXMX6et8xRTQb2KJfgv1aBEXozwrawRKgMB",
            "trusted" : true
         },
         {
            "pubkey_validator" : "nHUhG1PgAG8H8myUENypM35JgfqXAKNQvRVVAFDRzJrny5eZN8d5",
            "trusted" : true
         },
         {
            "pubkey_validator" : "nHUPDdcdb2Y5DZAJne4c2iabFuAP3F34xZUgYQT2NH7qfkdapgnz",
            "trusted" : true
         },
         {
            "pubkey_validator" : "nHBu9PTL9dn2GuZtdW4U2WzBwffyX9qsQCd9CNU4Z5YG3PQfViM8",
            "trusted" : true
         },
         {
            "pubkey_validator" : "nHB1X37qrniVugfQcuBTAjswphC1drx7QjFFojJPZwKHHnt8kU7v",
            "trusted" : true
         }
      ]
   }```

**Comment by wilsonianb** [comment]
@icemilo That `unl_list` response indicates that you are currently using both testnet and main network validators.

Check if the [main network validators](https://github.com/ripple/rippled/blob/develop/doc/validators-example.txt#L50-L54) are still listed in rippled.cfg or validators.txt, and remove them. Both files are located in `/opt/ripple/etc/` if you installed using the rpm.

**Comment by gituser** [comment]
Guys, can you tell me please if testnet is being reset daily?

Because it seems after some time `account_tx` is no longer returning transaction history for the account.. While the balance is still there on the account.

**Comment by wilsonianb** [comment]
Hi @gituser 

The testnet ledger is reset at most once per month. The reason you aren't getting the full transaction history is that the public testnet servers only keep limited ledger history (<1 day's worth).

If you require more history, you can run rippled with the `[ledger_history]` of your choice.
https://github.com/ripple/rippled/blob/develop/doc/rippled-example.cfg#L568

**Comment by gituser** [comment]
@wilsonianb no, i do not use public rpc service. I'm using my own rippled running in the testnet.

So, I need to add there:

```
[ledger_history]
full
```
right?

**Comment by wilsonianb** [comment]
Correct. Note that this will only help you keep all testnet ledgers going forward.
You will still be unable to get previous transactions, unless there is another full history testnet server to fetch ledgers from.

**Comment by gituser** [comment]
After adding this parameter rippled starts, but one of the processes is in the Zombie state for some reason..

```
ripple    4559  0.0  0.1 105228  8244 ?        Ss   19:59   0:00 /home/ripple/rippled --net --conf=/home/ripple/.ripple/rippled_testnet.cfg
ripple    4560  0.0  0.0      0     0 ?        Z    19:59   0:00 [rippled: main] <defunct>
```
and after some time it closes rippled completely..

**Comment by gituser** [comment]
@wilsonianb what about mainnet? is it relevant there?

**Comment by wilsonianb** [comment]
There are mainnet nodes with full ledger history. You could still keep full history on your own rippled in order to not be dependent on them, however that currently requires several terabytes of disk space.

>why not to store transaction history locally
I'm not sure exactly what you mean. Are you wanting to store transaction history only for particular accounts?

**Comment by gituser** [comment]
>I'm not sure exactly what you mean. Are you wanting to store transaction history only for particular accounts?

Yes, that's correct. For locally created accounts.

**Comment by wilsonianb** [comment]
I don't think that's currently possible with rippled. One option is to use an `account` websocket subscription and store the account transactions yourself.
https://ripple.com/build/rippled-apis/#subscribe

**Comment by wilsonianb** [comment]
There is also the historical database API
https://data.ripple.com/

**Comment by gituser** [comment]
>I don't think that's currently possible with rippled. One option is to use an accounts websocket subscription and store the account transactions yourself.
https://ripple.com/build/rippled-apis/#subscribe

so if i use 
```
[ledger_history]
full
```
how much space it will take approximately to store transaction history form the whole ripple?

though I'm interested only in particular account transactions.. would be nice if you guys could add this as a feature request somehow.

**Comment by gituser** [comment]
On the mainnet:

After setting ledger_history to full and removing `online_delete` rippled rapes I/O on the host.. Constantly reading HDD... I've also set cache to 512mb of the RocksDB and set node_size to large but seems it's not helping at all. 

Here is a snip of my config:

```
[node_size]
large


[ledger_history]
full

# This is primary persistent datastore for rippled.  This includes transaction
# metadata, account states, and ledger headers.  Helpful information can be
# found here: https://ripple.com/wiki/NodeBackEnd
# delete old ledgers while maintaining at least 2000. Do not require an
# external administrative command to initiate deletion.
[node_db]
type=RocksDB
path=/home/ripple/.ripple/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=512
file_size_mb=8
file_size_mult=2
#online_delete=65535
advisory_delete=0
```

I've set for now `ledger_history` back to defaults `256` and set `online_delete` to `65535`, seems better.. But that means history of the monitored account will disappear after some time.

Maybe there is a devel patch to track only your own account history or what do I change in ripple code to achieve that?

Thank you.

**Comment by gituser** [comment]
>There is also the historical database API (for the mainnet)
https://data.ripple.com/

@wilsonianb is there the same functionality for the testnet network?

Thank you.

**Comment by wilsonianb** [comment]
There is not currently a https://github.com/ripple/rippled-historical-database instance for the testnet.

**Comment by gituser** [comment]
hey guys, i'm getting when trying to send testnet transaction on my `v0.80.2` rippled node:
```
{
   "id" : 1,
   "result" : {
      "error" : "amendmentBlocked",
      "error_code" : 14,
      "error_message" : "Amendment blocked, need upgrade.",
      "request" : {
         "command" : "submit",
         "secret" : "XXXXX",
         "tx_json" : {
            "Account" : "xxx",
            "Amount" : "40000000",
            "Destination" : "xxx",
            "DestinationTag" : "yyy",
            "Fee" : "10000",
            "TransactionType" : "Payment"
         }
      },
      "status" : "error"
   }
}
```

How to fix this? Is there a new set of validators for the testnet or something else I'm missing? Thank you.

**Comment by nbougalis** [comment]
Yep, your version of `rippled` didn't know how to handle an amendment that is enabled on the altnet. Upgrading to the latest *develop* version is the solution.

:+1:

**Comment by gituser** [comment]
check this comment if you're having trouble running in testnet with mentioned earlier config: https://github.com/ripple/rippled/issues/2332#issuecomment-357727585

**Comment by rhaps107** [comment]
@wilsonianb could you help?

i tried config above, but still getting 

```2018-Jan-29 20:47:32 NetworkOPs:WRN We are not running on the consensus ledger
2018-Jan-29 20:47:32 ValidatorList:WRN New quorum of 18446744073709551615 exceeds the number of trusted validators (5)
2018-Jan-29 20:47:32 LedgerConsensus:WRN Need consensus ledger 51A75AB48EEF95306A946C4B7009E42BDF0BD4D36AAA4A7011754D6FBF1A644B
```

unl_list is:

```{
   "id" : 1,
   "result" : {
      "status" : "success",
      "unl" : [
         {
            "pubkey_validator" : "nHUkAWDR4cB8AgPg7VXMX6et8xRTQb2KJfgv1aBEXozwrawRKgMB",
            "trusted" : true
         },
         {
            "pubkey_validator" : "nHUhG1PgAG8H8myUENypM35JgfqXAKNQvRVVAFDRzJrny5eZN8d5",
            "trusted" : true
         },
         {
            "pubkey_validator" : "nHUPDdcdb2Y5DZAJne4c2iabFuAP3F34xZUgYQT2NH7qfkdapgnz",
            "trusted" : true
         },
         {
            "pubkey_validator" : "nHBu9PTL9dn2GuZtdW4U2WzBwffyX9qsQCd9CNU4Z5YG3PQfViM8",
            "trusted" : true
         },
         {
            "pubkey_validator" : "nHB1X37qrniVugfQcuBTAjswphC1drx7QjFFojJPZwKHHnt8kU7v",
            "trusted" : true
         }
      ]
   }
}```

**Comment by wilsonianb** [comment]
Hi @rhaps107 
The Ripple-operated testnet validator keys have changed. You'll want to replace the `[validators]` section with the following:
```
[validator_list_sites]
https://vl.altnet.rippletest.net

[validator_list_keys]
ED264807102805220DA0F312E71FC2C69E1552C9C5790F6C25E3729DEB573D5860
```

**Comment by gituser** [comment]
@rhaps107 also you need to run latest rippled which is `0.90-b4`, compile it from `develop` branch.

**Comment by rhaps107** [comment]
@wilsonianb 
thanks, tried this, doesnt work, now getting
```
2018-Jan-29 21:03:38 Amendments:ERR Unsupported amendment 157D2D480E006395B76F948E3E07A45A05FE10230D88A7993C71F97AE4B1F2D1 activated.
2018-Jan-29 21:03:38 Amendments:ERR Unsupported amendment 67A34F2CF55BFC0F93AACD5B281413176FEE195269FA6D95219A2DF738671172 activated.
2018-Jan-29 21:03:38 Amendments:ERR Unsupported amendment F64E1EABBE79D55B3BB82020516CEC2C582A98A6BFE20FBE9BB6A0D233418064 activated.
2018-Jan-29 21:03:38 LedgerMaster:ERR One or more unsupported amendments activated: server blocked.
```

ill try compile from develop branch, as @gituser says

**Comment by wilsonianb** [comment]
Or if you are using the rpm, you can update to the latest nightly. Just use `--enablerepo=ripple-nightly`
https://ripple.com/build/rippled-setup/#installing-rippled

**Comment by rhaps107** [comment]
@wilsonianb @gituser 
ripple-nightly works! thank you so much

**Comment by rhaps107** [comment]
@wilsonianb 

now i can successfully query my node's api in test network, but in log im getting warning:

```
2018-Jan-30 15:21:32 NetworkOPs:WRN We are not running on the consensus ledger
2018-Jan-30 15:21:32 LedgerConsensus:WRN Need consensus ledger C59058B86A0D7DC68E2597A395295AE8557A4EC1EE8A505C5502EA9B7D3C1253
```

is that ok?

**Comment by wilsonianb** [comment]
Make sure that the `[ips]` section in your rippled.cfg includes
```
r.altnet.rippletest.net 51235
```

**Comment by rhaps107** [comment]
@wilsonianb yes, it is so

**Comment by via1982** [comment]
Hi All,
I'm tring to start rippled on testnet under windows machine in docker container.
I loaded image from https://hub.docker.com/r/gatehub/rippled/ but where can I get  actual rippled.conf for testnet?  Could you please share it with me?

Thanks a lot!

**Comment by wilsonianb** [comment]
Hi @via1982 
You can use the existing rippled.cfg and replace `r.ripple.com 51235` with `r.altnet.rippletest.net 51235` under the `[ips]` section.
Then replace the contents of validators.txt with the following
```
[validator_list_sites]
https://vl.altnet.rippletest.net

[validator_list_keys]
ED264807102805220DA0F312E71FC2C69E1552C9C5790F6C25E3729DEB573D5860
```

**Comment by via1982** [comment]
Think you so much @wilsonianb for the quick answer.

I run it, but got the following

2018-Feb-18 11:56:04 NetworkOPs:WRN We are not running on the consensus ledger
2018-Feb-18 11:56:04 LedgerConsensus:WRN Need consensus ledger 73B490D438C0A54CF5BA45EAA5056F5CFCBBEC08833423C678F32CB8979A0651
2018-Feb-18 11:56:07 NetworkOPs:WRN We are not running on the consensus ledger
2018-Feb-18 11:56:07 LedgerConsensus:WRN Need consensus ledger 95BFF92A9A3AAD7C8960EEDA58B24913B0C8BE857E10ED80E79D362AB744D28F
2018-Feb-18 11:56:09 NetworkOPs:WRN We are not running on the consensus ledger
2018-Feb-18 11:56:09 LedgerConsensus:WRN Need consensus ledger 26B863CBC9489F06EC067358BEF615E12EC3E6A9499BFF5610031D7C236DF437
2018-Feb-18 11:56:12 NetworkOPs:WRN We are not running on the consensus ledger
2018-Feb-18 11:56:12 LedgerConsensus:WRN Need consensus ledger D10143DFC22219281DB18F6A507BA7533C84F795525AC915385160A6E11E35CF
2018-Feb-18 11:56:13 Amendments:ERR Unsupported amendment 157D2D480E006395B76F948E3E07A45A05FE10230D88A7993C71F97AE4B1F2D1 activated.
2018-Feb-18 11:56:13 Amendments:ERR Unsupported amendment 67A34F2CF55BFC0F93AACD5B281413176FEE195269FA6D95219A2DF738671172 activated.
2018-Feb-18 11:56:13 Amendments:ERR Unsupported amendment F64E1EABBE79D55B3BB82020516CEC2C582A98A6BFE20FBE9BB6A0D233418064 activated.
2018-Feb-18 11:56:13 LedgerMaster:ERR One or more unsupported amendments activated: server blocked.

Is it because I'm using rippled version 0.81.0?
I couldn't find image for 0.90-b4.

Thanks,
Ilya

**Comment by kiahmed** [comment]
trying to run a testnode. my server_info says   "server_state": "tracking", but the seq is same with latest from the link above. How long would it take for state to be full ? 
Also i had to manually update the conf file online_delete=1000000001 what effect would it have?

**Comment by rhaps107** [comment]
@via1982 
try 
--enablerepo=ripple-nightly 
while installing rippled

**Comment by via1982** [comment]
Hi All,

I started on the ripple-nightly in testnet with param **@wilsonianb** mentioned and got the following and nothing happens

2018-Feb-19 18:16:02 NetworkOPs:WRN We are not running on the consensus ledger
2018-Feb-19 18:16:02 LedgerConsensus:WRN Need consensus ledger 49C033C11A2A4BF76BBA57AB6E47F0D9F740811CB9FAA45D8A341873BFB08466
2018-Feb-19 18:16:03 LedgerConsensus:WRN View of consensus changed during open status=open,  mode=wrongLedger
2018-Feb-19 18:16:03 LedgerConsensus:WRN 49C033C11A2A4BF76BBA57AB6E47F0D9F740811CB9FAA45D8A341873BFB08466 to C2DA8593635724EAE2955A76FF984302215E2D9B84C84A80511B8EFF42489584
2018-Feb-19 18:16:03 LedgerConsensus:WRN {"accepted":true,"account_hash":"483DA36A5CE4EBC544D291D660BC660988A492BDC5BE8D4676B30B3438C3A659","close_flags":0,"close_time":572379360,"close_time_human":"2018-Feb-19 18:16:00","close_time_resolution":30,"closed":true,"hash":"0DABFE1BA07294138AFCA1FC9E9E87F19C05869FC4CEF40F21B5EB29513B1B59","ledger_hash":"0DABFE1BA07294138AFCA1FC9E9E87F19C05869FC4CEF40F21B5EB29513B1B59","ledger_index":"3","parent_close_time":572379300,"parent_hash":"97218122C5F2705FA221797BD6F2EC51ACF19EEC84B1E6B7F931DAB8B2C6FE3C","seqNum":"3","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2018-Feb-19 18:16:03 LedgerConsensus:WRN Need consensus ledger C2DA8593635724EAE2955A76FF984302215E2D9B84C84A80511B8EFF42489584
2018-Feb-19 18:16:06 NetworkOPs:WRN We are not running on the consensus ledger
2018-Feb-19 18:16:07 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2018-Feb-19 18:16:07 LedgerConsensus:WRN C2DA8593635724EAE2955A76FF984302215E2D9B84C84A80511B8EFF42489584 to 755136A2AD0E854CCBD8564D289295DD0E731BF3C5CE155B9A206692C379894A
2018-Feb-19 18:16:07 LedgerConsensus:WRN {"accepted":true,"account_hash":"6402C6B0B074F36263C34179350FFEA6859C07E16D010FB8D2260C7B97BFD9A2","close_flags":0,"close_time":572379361,"close_time_human":"2018-Feb-19 18:16:01","close_time_resolution":30,"closed":true,"hash":"D087FCB3B415286F567A6B82B3FF04A7313B0A1B0FADA97B2082622CC0AEEA77","ledger_hash":"D087FCB3B415286F567A6B82B3FF04A7313B0A1B0FADA97B2082622CC0AEEA77","ledger_index":"4","parent_close_time":572379360,"parent_hash":"0DABFE1BA07294138AFCA1FC9E9E87F19C05869FC4CEF40F21B5EB29513B1B59","seqNum":"4","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2018-Feb-19 18:16:07 LedgerConsensus:WRN Need consensus ledger 755136A2AD0E854CCBD8564D289295DD0E731BF3C5CE155B9A206692C379894A
2018-Feb-19 18:16:08 NetworkOPs:WRN We are not running on the consensus ledger
2018-Feb-19 18:16:10 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2018-Feb-19 18:16:10 LedgerConsensus:WRN 755136A2AD0E854CCBD8564D289295DD0E731BF3C5CE155B9A206692C379894A to EFD1397EDB7CD1672550B6CA8D40FE97765BBF163038E18AED7715B2B5A8969B
2018-Feb-19 18:16:10 LedgerConsensus:WRN {"accepted":true,"account_hash":"33B5B80D7B9D38E342F7D8C89496F7702C858C1EA051E1242BC91DD951E55348","close_flags":0,"close_time":572379362,"close_time_human":"2018-Feb-19 18:16:02","close_time_resolution":30,"closed":true,"hash":"D89E116813B0F6FD4D7B8B3534F833AF9EAA668E555EF5FE87930E6041C3F9FB","ledger_hash":"D89E116813B0F6FD4D7B8B3534F833AF9EAA668E555EF5FE87930E6041C3F9FB","ledger_index":"5","parent_close_time":572379361,"parent_hash":"D087FCB3B415286F567A6B82B3FF04A7313B0A1B0FADA97B2082622CC0AEEA77","seqNum":"5","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2018-Feb-19 18:16:10 LedgerConsensus:WRN Need consensus ledger EFD1397EDB7CD1672550B6CA8D40FE97765BBF163038E18AED7715B2B5A8969B
2018-Feb-19 18:16:12 NetworkOPs:WRN We are not running on the consensus ledger
2018-Feb-19 18:16:13 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2018-Feb-19 18:16:13 LedgerConsensus:WRN EFD1397EDB7CD1672550B6CA8D40FE97765BBF163038E18AED7715B2B5A8969B to E07DA4109317A6BAB7BD23881FC452041BA100509A1CA5199348C9ED705A1945
2018-Feb-19 18:16:13 LedgerConsensus:WRN {"accepted":true,"account_hash":"24AE643BA76F3D190DB63FC16A1C3375F31511F4A95CCF1A6E772D0219174540","close_flags":0,"close_time":572379363,"close_time_human":"2018-Feb-19 18:16:03","close_time_resolution":30,"closed":true,"hash":"3593FD38AD26D6DF37781911A71F32FA192DE1D74229001054FC1CED61878035","ledger_hash":"3593FD38AD26D6DF37781911A71F32FA192DE1D74229001054FC1CED61878035","ledger_index":"6","parent_close_time":572379362,"parent_hash":"D89E116813B0F6FD4D7B8B3534F833AF9EAA668E555EF5FE87930E6041C3F9FB","seqNum":"6","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}

**Comment by rhaps107** [comment]
@via1982 
i got same messages, but nodes api works.

**Comment by via1982** [comment]
But I thought that the testnet ledger will be loaded.

**Comment by Vivek-Patil** [comment]
@wilsonianb I have made the changes described for the testnet in rippled.cfg and started the server. I even get the serrver_state as full. But when I run a rpc command for account_info I get error InsufficientNetworkMode. Can you help me out as of what this error means ?

**Comment by naetkss** [comment]
@Vivek-Patil did you win? Did you get a working test net for ripple?

**Comment by songjim** [comment]
@rhaps107  hi，
my node always display `Rippled not initialized`  can you help me？

**Comment by PawanTiwariOodles** [comment]
Hello, 
When I try to run rippled some commands. it says:
sudo rippled server_state
sudo: rippled: command not found
Can anyone help.?

**Comment by gituser** [comment]
@PawanTiwariOodles most likely you dont have in your `$PATH` environment rippled, try going to the directory where rippled resides and run `./rippled server_state`

**Comment by PawanTiwariOodles** [comment]
@gituser , Thanks, it works. How can I set Path variable so that I can start using sudo. Not by going to the directory.
Thanks.

**Comment by zuraizm** [comment]
hi
I want to connect my account with ripple testnet server, can u tell me how to connect to it because the link given on official documentation are not working

**Comment by kiahmed** [comment]
i did, it running and transacting. what specific problem you have?

**Comment by biniama** [comment]
Hello,
I created [this issue](https://github.com/ripple/rippled/issues/2683) which contains the `curl` command I used

Please see and help.
@zuraizm @kiahmed

**Comment by 520weishun** [comment]
在官网安装完xrp之后，应该怎么创建xrp钱包

**Comment by nbougalis** [comment]
@520weishun: this is not the right forum for your question.

**Comment by 520weishun** [comment]
![0f163b91-064d-4e7a-8cbc-5126e5d806a8](https://user-images.githubusercontent.com/44760946/48184210-46499280-e36c-11e8-9efe-e0f8da1ac92f.png)
When I created the ledger in independent mode, there was a problem with the master method thread lock

**Comment by DaShak** [comment]
For anyone who hasn't found/read the official documentation on connecting rippled to the XRP Test Net, here is the link:  https://developers.ripple.com/connect-your-rippled-to-the-xrp-test-net.html

Considering this thread's prominence in Google search results, I felt it would be beneficial to make this comment here.

**Comment by burnside** [comment]
I was pulling my hair out on this. Spent many hours trying various testnet config tweaks:

- small/medium/large,
- http/https on the validator_list_sites
- list of validators vs no list of validators
- etc

For each change I let it run 10-15 mins and watched the logs.  My node was getting lots of peers, lots of data flowing in the logs, etc., but my node was never getting a server_state beyond "connected".  Eventually I remembered that another currency I'd worked with before kept a list of peers in the local db.  So I wiped my db directory, started it up, and within 5 minutes I am "syncing" just fine.  My guess is I started it up with the wrong validators.txt config in the past and it peered with mainnet.  Probably all I needed to wipe was the "peerfinder.sqlite" file.

Hope that helps someone - if you've ever accidentally peered with mainnet chances are your testnet node will not come up without some cleanuip.

**Comment by DaShak** [comment]
> I was pulling my hair out on this. Spent many hours trying various testnet config tweaks: 
…
I found the stock/default/documented configuration works well, @burnside.
However, I have had to delete the db directory after `rippled` would break down - particularly with _Main Net_ and `RocksDB` - I have yet to experiment with `NuDB`, to see if it is more reliable & resilient…

**Comment by livingrock7** [comment]
Hi everyone,

I am running a rippled server connected to testnet. Here is my server_info

`{
   "result" : {
      "info" : {
         "amendment_blocked" : true,
         "build_version" : "1.1.2",
         "complete_ledgers" : "3258768-3262698",
         "hostid" : "moonx-latitude-chirag",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 2.001,
            "proposers" : 6
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "untrustedProposal",
                  "per_second" : 1
               },
               {
                  "job_type" : "ledgerData",
                  "peak_time" : 8,
                  "per_second" : 2
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand",
                  "per_second" : 1
               },
               {
                  "job_type" : "transaction",
                  "per_second" : 1
               },
               {
                  "job_type" : "batch",
                  "per_second" : 1
               },
               {
                  "job_type" : "advanceLedger",
                  "peak_time" : 4,
                  "per_second" : 2
               },
               {
                  "job_type" : "fetchTxnData",
                  "per_second" : 1
               },
               {
                  "job_type" : "trustedValidation",
                  "peak_time" : 1,
                  "per_second" : 1
               },
               {
                  "job_type" : "writeObjects",
                  "per_second" : 4
               },
               {
                  "job_type" : "trustedProposal",
                  "per_second" : 1
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 17
               },
               {
                  "job_type" : "diskAccess",
                  "per_second" : 1
               },
               {
                  "job_type" : "processTransaction",
                  "per_second" : 1
               },
               {
                  "job_type" : "SyncReadNode",
                  "per_second" : 2
               },
               {
                  "job_type" : "AsyncReadNode",
                  "per_second" : 2
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 12
               }
            ],
            "threads" : 6
         },
         "load_factor" : 1,
         "peer_disconnects" : "2",
         "peer_disconnects_resources" : "0",
         "peers" : 2,
         "pubkey_node" : "n9KGAHJbQjyustZXZUfTqJA8wyeQYQ21kggNLrdvUHKepuK3dAf7",
         "pubkey_validator" : "none",
         "server_state" : "tracking",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "80592372",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "1275906",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "syncing" : {
               "duration_us" : "8011859",
               "transitions" : 2
            },
            "tracking" : {
               "duration_us" : "8827845209",
               "transitions" : 3
            }
         },
         "time" : "2019-Dec-28 06:23:30.181911",
         "uptime" : 8917,
         "validated_ledger" : {
            "age" : 0,
            "base_fee_xrp" : 1e-05,
            "hash" : "0F2ED5624E067A0C985596F1700B05E94B7897EEC59DB569A421CB728D700337",
            "reserve_base_xrp" : 20,
            "reserve_inc_xrp" : 5,
            "seq" : 3262698
         },
         "validation_quorum" : 5,
         "validator_list" : {
            "count" : 1,
            "expiration" : "2020-Dec-01 00:00:00.000000000",
            "status" : "active"
         }
      },
      "status" : "success"
   }
}
`

I want to test following operations.

- create wallets on this node
- do transactions among these addresses
- latest ledger-check and look for incoming transactions in these wallets by RPC methods (existing java lib would be helpful)
- dispatch transactions to other testnet addresses

I am looking to open RPC connection and use this node to perform these operations.
Any leads would be helpful.

Thank you!

**Comment by MarkusTeufelberger** [comment]
Run a more recent version of `rippled`.

Also this is not a support forum.

**Comment by Dinshaw7** [comment]
hey, I am unable to get ledger history.. I am giving earliest_sequence= 4425000, and fetch_depth=full. I want all ledgers from this no. When i started my rippled service, it was on ledger no. 4437696. I am getting all latest one. means ir is moving fine in forward direction. but in backward direction it is only giving me till 4437637. Can anybody please help me.
