### ISSUE TITLE
WSS in 0.50.0-b2 

### ISSUE THREAD

**Issue by njmurarka** [ripple/rippled#2102]
Hi.

I have noticed on a bunch of nodes that are running 0.50.0-b2 that WSS does not "work". Yes, the WSS port is open and I can telnet to it to just verify in a very rudimentary way that the port is answering requests, but I can't make requests, etc on that port.

Ideas? What is going on here? I have WSS configured the same way on other versions of rippled and it is all fine, so I am pretty sure it is not my SSL certificates or anything related to that. I simply have noticed that exactly ALL the 0.50.0-b2 nodes don't work with WSS.

**Comment by vinniefalco** [comment]
Is this still an issue?

**Comment by njmurarka** [comment]
Yes. With nodes running that specific version of rippled.

**Comment by vinniefalco** [comment]
So it is resolved by upgrading to a newer rippled? I would not say it was still an issue then :)

**Comment by bachase** [comment]
Please re-open a new issue if this is still a problem with newer rippled.
