### ISSUE TITLE
What's this, a new key/value database? !!

### ISSUE THREAD

**Issue by vinniefalco** [ripple/rippled#2116]
https://github.com/LiveAsynchronousVisualizedArchitecture/simdb

**Comment by nbougalis** [comment]
Interesting!

**Comment by seelabs** [comment]
Reading the reddit thread on this, simdb is memory only; it is not a persistent database. See this comment from the author (point 3 in particular): https://www.reddit.com/r/cpp/comments/6b44jx/simdbhpp_2k_lines_and_70kb_a_high_performance/dhjo9gr/ (Vinnie clearly already saw that comment, but for useful for others).

**Comment by vinniefalco** [comment]
Yeah, I saw that :(
