### ISSUE TITLE
Make rippled JSON responses compliant with JSON RPC 2.0 specification

### ISSUE THREAD

**Issue by ThePiachu** [ripple/rippled#214]
Relevant discussion - https://ripple.com/forum/viewtopic.php?f=2&t=4240&p=23490&sid=ddb111f102ec26ef30c4f35c86614864 .

Looking at the specification - http://json-rpc.org/wiki/specification#a1.2Response - and comparing it to the result I got after sending a random() request to the public rippled server at https://s1.ripple.com:51234 - {'result': {'status': 'success', 'random': '675B6CFA117B2B27A35D9B89600DA1E265539B5C022CD5955547FD8BCA92E17A'}} - I think the response is missing the fields for id and error that should be present (even if null).

Please ensure the JSON responses are compliant with JSON RPC 2.0 specification - this way anyone using standard libraries for JSON RPC would not encounter errors in case the library is pedantic about the data returned.

**Comment by vinniefalco** [comment]
@HowardHinnant has taken lead on this, and its getting done. This issue is obsolete.
