### ISSUE TITLE
Sync issue between 60.3 and 70

### ISSUE THREAD

**Issue by professorhantzen** [ripple/rippled#2147]
I'm operating a rippled instance and don't tend to experience any significant loss of sync with the network (occasionally one ledger).  However, commencing around the time of the announced upgrade of Ripple-operated rippled instances to 0.70 (15th June 2pm PST), my 0.60.3 rippled began to lose sync very frequently and in extreme amounts.  (Up to 20 mins out of sync.)

Since I upgraded to 0.70 the issue appears to be resolved. Was this expected behaviour?  It would appear that the 0.70 recommendation that server operators upgrade by the 29th of June may be unwise.  Were I to have experienced no loss of sync, I would have had to have upgraded prior to 15th June.

**Comment by professorhantzen** [comment]
This may be an issue on my end.  The problem since returned on my updated 0.70.  When I noticed it, I shut down my rippled and switched to the public servers.  The problem immediately disappeared.  It would now appear that something going wrong with my rippled that coincided with the changeover of Ripple's servers to 0.70, and persisted through an upgrade from 0.60.3 to 0.70.  I may try cycling my instance hardware and erasing my rippled's database.

**Comment by professorhantzen** [comment]
Alright, after redeploying my rippled at 0.70 on new hardware and watching it for a while it's become apparent this was totally an issue on my end - apologies for any confusion.

**Comment by nbougalis** [comment]
Thank you for the report and for verifying that this isn't an issue. We appreciate it! :+1:
