### ISSUE TITLE
Sending transaction with large amount results in NULL

### ISSUE THREAD

**Issue by gituser** [ripple/rippled#2149]
I'm trying to send about 17K XRP and getting NULL for the transaction.

I've already upgraded to the latest `0.70.0` but that didn't help.

Before it was working just fine, what could be wrong and how do I fix this?

I'm posting this json array to rippled via `submit` mode:
```
array (
  'post' => 
  array (
    'offline' => false,
    'secret' => '_omitted_',
    'tx_json' => 
    array (
      'Account' => 'XXX',
      'Amount' => 17009037910,
      'Destination' => 'YYY',
      'TransactionType' => 'Payment',
    ),
    'fee_mult_max' => 1000,
  ),
  'result' => NULL,
)
```

**Comment by nbougalis** [comment]
You're submitting against your 0.70.0 server?

**Comment by JoelKatz** [comment]
I think you're submitting the XRP amount as an integer, which is not a good idea because JSON's integer semantics are, shall we say, imperfect.

**Comment by gituser** [comment]
@nbougalis yes

@JoelKatz 
>I think you're submitting the XRP amount as an integer, which is not a good idea because JSON's integer semantics are, shall we say, imperfect.
>I can't quite find the perfect link, but this should help:
>https://ripple.com/build/rippled-apis/#specifying-currency-amounts

Yes, you're correct! After fixing our code it works again. Thanks a lot for the tip!
