### ISSUE TITLE
Eliminate the dependence on certain boost modules that require linking.

### ISSUE THREAD

**Issue by vinniefalco** [ripple/rippled#216]
rippled relies on a small number of boost modules that are not header-only, and require linking against a library. They are:

```
boost_date_time
boost_filesystem
boost_program_options
boost_regex
boost_system
boost_thread
boost_random
```

We need to change the rippled code to eliminate the use of these modules one by one. There are simple alternatives for all of them, someone just needs to do the work (one module at a time).

A benefit of not requiring linking is that it will no longer be necessary to build boost (running bjam) but the bigger benefit is that we can insert the entire boost distribution directly in the rippled repository, so that everyone will be using the same version and there will be no hassle of install or configuration issues for boost.

**Comment by rec** [comment]
We can't fix this - we're hooked on `boost::coroutine` now, there's no replacement, and it looks as if none of the other boost libraries are easily removable.

Sorry!
