### ISSUE TITLE
release notes on github missing again

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2174]
pinging @mDuo13 

See https://github.com/ripple/rippled/releases and #1977

**Comment by xasos** [comment]
We also need to mark 0.70.1 as the "latest release"

Maybe we should set up some sort of hook to update the docs online as well as on github? Or some sort of checklist before we push a release to master.

**Comment by bachase** [comment]
We are still working to improve this, but closing this for now.
