### ISSUE TITLE
Bitcoin bridge direct send succeeds but is never debited to the sending ripple account

### ISSUE THREAD

**Issue by kravets** [ripple/rippled#218]
2.225 BTC was received at 1MUJropxdq9txyRJDJ5XJBsjQg7TU9BCFD via

https://blockchain.info/tx/5c4f98b335db018ee53e92f1cd8189277ce3bc7a5b789d45dcccd415a91f5f5f

from rw3Ms86G9Dmm23Z5TM6yAsxiA5v24UZKf7 using a send through a Bitcoin bridge

However the sending account was never debited 2.225 BTC

https://ripple.com/tools/info/#rw3Ms86G9Dmm23Z5TM6yAsxiA5v24UZKf7

**Comment by vinniefalco** [comment]
Obsolete and not specific to rippled
