### ISSUE TITLE
Websocket API versioning

### ISSUE THREAD

**Issue by donovanhide** [ripple/rippled#219]
With reference to bugs, such as #196, it might be convenient to allow for versioning of an API to be specified by the client so that clients can know what to expect. There are a number of possible choices:
- Specify a different URL for connecting, such as https://s1.ripple.com/v2/:443
- Specify a subprotocol such as "v2.ripple.com" as per: http://tools.ietf.org/html/rfc6455#page-12
- Specify a "version" field in every API call.

The first two options have the advantage of allowing for a per-session version choice, and perhaps would yield cleaner code.

A similar and consistent scheme would have to be followed for the JSON-RPC API.

**Comment by vinniefalco** [comment]
This is part of the JSON-RPC 2.0 feature

**Comment by intelliot** [comment]
Despite Vinnie closing this issue, it was not actually done, as far as I can tell. 

Personally, I favor the third option (Specify a "version" field in every API call) because it allows clients to migrate to new APIs gradually (for example, if they want an old response in one area of their code and a new response in another). However, the other options are also acceptable.

**Comment by carlhua** [comment]
Closing the issue. We have API versioning implemented. For further enhancement ideas - we can open new issues.

**Comment by MarkusTeufelberger** [comment]
Can you please give an example on how API versions can actually be reliably used/queried? I don't see any version fields in my responses and did not find any documentation on version differences or even the existence of different API versions.

**Comment by pwang200** [comment]
Currently only version 1 is supported. For JSON-RPC, it can be specified in the request. 
```
{
    "method": "...",
    "params": [
        {
            "api_version": 1,
            ...
        }
    ]
}
```
For WebSockets RPC:
```
{
    "api_version": 1,
    "id": 4,
    "command": "...",
    ...
}
```
If missing from the request, the `api_version` is default to 1.
