### ISSUE TITLE
Error building on freeBSD

### ISSUE THREAD

**Issue by realcodywburns** [ripple/rippled#2236]
Exception: Unknown system platform "FreeBSD":                                   
  File "/rippled/SConstruct", line 133:                                         
    import Beast                                                                
  File "src/ripple/beast/site_scons/Beast.py", line 92:                         
    system = __System()                                                         
  File "src/ripple/beast/site_scons/Beast.py", line 71:                         
    raise Exception('Unknown system platform "' + self.name + '"')

**Comment by nbougalis** [comment]
Thank you for the report. Unfortunately, FreeBSD is not a supported platform.

There (unfortunately) seems to be very little demand for BSD builds and so haven’t made offering BSD compatibility a priority. At this time, we just don’t have the infrastructure needed to make it one in place.

**Comment by nbougalis** [comment]
Thank you for the report. Unfortunately, FreeBSD is not a supported platform.

There (unfortunately) seems to be very little demand for BSD builds and so haven’t made offering BSD compatibility a priority. At this time, we just don’t have the infrastructure (e.g. CI systems, production servers, packaging systems, etc) needed to make it one in place.

We will keep this in mind for the future; hopefully we we will get `rippled` added to the ports collection.

For now, I will close this issue.

**Comment by MarkusTeufelberger** [comment]
Seems to fail quite early already in scons... is cmake available in FreeBSD? You might have some luck there, but that depends on what OS specific code Vinnie wrote in his beast library a few years back (these days he re-used the name for a completely unrelated project).
