### ISSUE TITLE
account_tx failing with error: lgrNotValidated "Ledger not validated."

### ISSUE THREAD

**Issue by got3nks** [ripple/rippled#2241]
Why is account_tx failing?

```
root@xx:~# /opt/ripple/bin/rippled account_tx rBe...C6G
{
   "id" : 1,
   "result" : {
      "error" : "lgrNotValidated",
      "error_code" : 21,
      "error_message" : "Ledger not validated.",
      "request" : {
         "account" : "rBe...C6G",
         "command" : "account_tx"
      },
      "status" : "error"
   }
}
```

Node is sync'd.

```
root@xx:~# /opt/ripple/bin/rippled ledger_current
2017-Oct-09 15:38:46 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "id" : 1,
   "result" : {
      "ledger_current_index" : 33371652,
      "status" : "success"
   }
}
```

**Comment by bachase** [comment]
It is a bug with how the `account_tx` RPC is handling the default ledger range. Until we land a fix, you will need to specify a minimum or maximum range for the ledgers. A value of `-1` means to use the minimum/maximum available validated ledger, but the command line parser thinks `-1` is a flag rather than a number. 

Can you try the following for now and see if it works?

```
curl -X POST -d '{ "method" : "account_tx", "params" : [ { "account" : "r*****","ledger_index_min" : -1, "ledger_index_max" : -1 } ] } ' http://127.0.0.1:5005
```

**Comment by got3nks** [comment]
Yes that works.

**Comment by got3nks** [comment]
https://ripple.com/build/ripple-info-tool/ is showing 8 transactions when I lookup my address, while my call:

`root@xx:~# curl -X POST -d '{ "method" : "account_tx", "params" : [ { "account" : "rBe...C6G","ledger_index_min" : 32570, "ledger_index_max" : 33374525 } ] } ' http://127.0.0.1:5005`

is showing only 4 transactions!

**Comment by bachase** [comment]
I believe the info tool uses s2.ripple.com, which is a full history server.  How much history are you storing locally (that is the `complete_ledgers` field in `server_info` RPC)?

**Comment by got3nks** [comment]
I understand, and yes you are right.

`         "complete_ledgers" : "33371066-33374924",`

Is there any way to download older ledgers?

**Comment by bachase** [comment]
If there are specific ledgers you want, you can request them via the [ledger_request](https://ripple.com/build/rippled-apis/#ledger-request) command.

If you want to increase the amount of ledgers you store on your local `rippled`, you can edit the [`ledger_history`](https://github.com/ripple/rippled/blob/develop/doc/rippled-example.cfg#L581) value in your server's `rippled.cfg`. As noted in #2129, this is rather large to store the full history. At this time, we still do not have support for storing just the history of specific accounts.

**Comment by got3nks** [comment]
Thank you very much for your help!

**Comment by got3nks** [comment]
I have updated my `rippled.cfg`:

```
[ledger_history]
full

#online_delete=2000
```

Will it now download all the previous ledgers or will it keep only new ledgers? How much HDD storage does the full ledger since 0 requires at the moment?

**Comment by got3nks** [comment]
We received a payment that is showing up on https://ripple.com/build/ripple-info-tool/ but not on our node:

**Comment by MarkusTeufelberger** [comment]
> Will it now download all the previous ledgers

Yes

> How much HDD storage does the full ledger since 0 requires at the moment?

The smallest publicly available ledger is not 0 but 32570. That set aside, about 5 TB. You likely won't be able to use HDDs as a back end to rippled though, querying a historic ledger creates hundreds of thousands of random reads all over the database. SSDs typically can respond to a few thousand or tens of thousands of  these per second, HDDs are more in the tens to hundreds range.

**Comment by JoelKatz** [comment]
@got3nks The response to account_tx will always tell you which ledgers it queried over. Unless a server is seriously misconfigured, this should be 100% reliable. If the account_tx says is queried from ledger X to ledger Y and is a complete response (no marker for continuation), it should always include every relevant transaction in those ledgers.

I would suggest you only try to keep a month or two of history on your node. In the rare cases where you need more history, you can query s2.ripple.com. That's a best effort service with no promoses, so I wouldn't point any live systems at it. But it's available if you need more history than your own servers, or the s1 cluster, hold.

**Comment by got3nks** [comment]
Thank you for the help.

Our Ripple node is currently using 14.6GB of RAM, is this normal usage? 😮

**Comment by MarkusTeufelberger** [comment]
That's a bit high, but sounds about right if you were querying historic data and not just validating. 14.6 GB is not the highest by far I've seen on my node, so I'd call that medium usage.
