### ISSUE TITLE
Payment subscriptions with callback not working

### ISSUE THREAD

**Issue by hahahatrick** [ripple/rippled#2255]
Hi,

I'm trying to subscribe to payments for an account on the test net, but not able to get any response.

```subscribe({:id => 3, :command => "subscribe", :accounts => ["rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh"], :url => "https://requestb.in/1ieywq91"})```

```{:status=>"success"}```

Then I made a transaction to the account.

```submit({:secret => "xxxxxxx", :tx_json => {:TransactionType => "Payment", :Account =>"rHFawyv2HGj621fDqdeiDbdBqwEjAd8tbL", :Destination => "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh", :Amount => 1000000}})```

```{:engine_result=>"tesSUCCESS", :engine_result_code=>0, :engine_result_message=>"The transaction was applied. Only final in a validated ledger.", :status=>"success", :tx_blob=>"120000228000000024000000086140000000000F424068400000000000000A7321020D014146257AD5901DF0560FF1EA90FF0F8080E15F2612738F6591BE5927847A744730450221008E40E57537E27B9FD99F361950D57286A8CC65243C2DC1DC2F9E746EC2469501022016DDBE5EF6E7236CE93D958E7D500F590086044137C926CFA5C5EE03F5EA435B8114B869E1543367810BB4828A7CCFEF7C6C98287EC18314B5F762798A53D543A014CAF8B297CFF8F2F937E8", :tx_json=>{"Account"=>"rHFawyv2HGj621fDqdeiDbdBqwEjAd8tbL", "Amount"=>"1000000", "Destination"=>"rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh", "Fee"=>"10", "Flags"=>2147483648, "Sequence"=>8, "SigningPubKey"=>"020D014146257AD5901DF0560FF1EA90FF0F8080E15F2612738F6591BE5927847A", "TransactionType"=>"Payment", "TxnSignature"=>"30450221008E40E57537E27B9FD99F361950D57286A8CC65243C2DC1DC2F9E746EC2469501022016DDBE5EF6E7236CE93D958E7D500F590086044137C926CFA5C5EE03F5EA435B", "hash"=>"7A73E02A2D75077BAB09BCCB883B98478F5935526DD822A868B8C632342F11BC"}}{:engine_result=>"tesSUCCESS", :engine_result_code=>0, :engine_result_message=>"The transaction was applied. Only final in a validated ledger.", :status=>"success", :tx_blob=>"120000228000000024000000086140000000000F424068400000000000000A7321020D014146257AD5901DF0560FF1EA90FF0F8080E15F2612738F6591BE5927847A744730450221008E40E57537E27B9FD99F361950D57286A8CC65243C2DC1DC2F9E746EC2469501022016DDBE5EF6E7236CE93D958E7D500F590086044137C926CFA5C5EE03F5EA435B8114B869E1543367810BB4828A7CCFEF7C6C98287EC18314B5F762798A53D543A014CAF8B297CFF8F2F937E8", :tx_json=>{"Account"=>"rHFawyv2HGj621fDqdeiDbdBqwEjAd8tbL", "Amount"=>"1000000", "Destination"=>"rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh", "Fee"=>"10", "Flags"=>2147483648, "Sequence"=>8, "SigningPubKey"=>"020D014146257AD5901DF0560FF1EA90FF0F8080E15F2612738F6591BE5927847A", "TransactionType"=>"Payment", "TxnSignature"=>"30450221008E40E57537E27B9FD99F361950D57286A8CC65243C2DC1DC2F9E746EC2469501022016DDBE5EF6E7236CE93D958E7D500F590086044137C926CFA5C5EE03F5EA435B", "hash"=>"7A73E02A2D75077BAB09BCCB883B98478F5935526DD822A868B8C632342F11BC"}}```

Found in debug.log:
2017-Nov-02 11:26:16 RPCSub:NFO RPCCall::fromNetwork start
2017-Nov-02 11:26:16 RPCSub:NFO RPCCall::fromNetwork: requestb.in

I'm still not able to see anything on the webhook.

Thank you.

**Comment by MarkusTeufelberger** [comment]
You did run this on your server's admin port, right?

**Comment by hahahatrick** [comment]
Yes. This was run on admin port, also got a success response.

**Comment by hahahatrick** [comment]
When I use an IP address instead of a domain name it works.

**Comment by bachase** [comment]
@hahahatrick is this still an issue for you with the recently released 0.80.1?

**Comment by bachase** [comment]
Closing this for now, please re-open if you are still having trouble.
