### ISSUE TITLE
Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES) (found version "1.0.2m")

### ISSUE THREAD

**Issue by passionofvc** [ripple/rippled#2260]
######cmake command########
cmake .. -DCMAKE_BUILD_TYPE=Debug -DOPENSSL_ROOT_DIR=/home/Administrator/lib/OpenSSL-Win64 -DOPENSSL_LIBRARIES=/home/Administrator/lib/OpenSSL-Win64/lib -DOPENSSL_INCLUDE_DIR=/home/Administrator/lib/OpenSSL-Win64/include

######cmake log#####
I use cmake build in window server2008, but show openssl not found
(cmake run in Cygwin64)

-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   chrono
--   coroutine
--   context
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   thread
**-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES) (found version "1.0.2m")**
CMake Error at Builds/CMake/CMakeFuncs.cmake:405 (message):
  OpenSSL not found
Call Stack (most recent call first):
  CMakeLists.txt:158 (use_openssl)

opsnssl has innstalled in local drive

############openssl#########
WIN-ITM34OUEE4U@Administrator$ ls -l ~/lib/OpenSSL-Win64/
合計 4029
drwxr-xr-x+ 1 Administrators None       0 11月  6 22:58 bin
-rwxr-xr-x  1 Administrators None  499693 11月  2 07:33 changes.txt
drwxr-xr-x+ 1 Administrators None       0 11月  6 22:58 exp
-rwxr-xr-x  1 Administrators None      84 5月   3  2016 faq.txt
drwxr-xr-x+ 1 Administrators None       0 11月  6 22:58 include
drwxr-xr-x+ 1 Administrators None       0 11月  6 22:58 lib
-rwxr-xr-x  1 Administrators None 2093568 11月  3 21:26 libeay32.dll
-rwxr-xr-x  1 Administrators None  353280 11月  3 21:26 libssl32.dll
-rwxr-xr-x  1 Administrators None    6281 11月  2 07:32 license.txt
-rwxr-xr-x  1 Administrators None   34862 11月  2 07:33 news.txt
-rwxr-xr-x  1 Administrators None    3281 11月  2 07:33 readme.txt
-rwxr-xr-x  1 Administrators None  353280 11月  3 21:26 ssleay32.dll
-rwxr-xr-x  1 Administrators None   22148 11月  6 22:58 unins000.dat
-rwxr-xr-x  1 Administrators None  719521 11月  6 22:57 unins000.exe
WIN-ITM34OUEE4U@Administrator$

Can anyone help me  to build in window?
I also set OPENSSL_LIBRARIES in cmake command, but also give me error.

**Comment by nbougalis** [comment]
Please take a look at https://github.com/ripple/rippled/blob/develop/Builds/VisualStudio2015/README.md

**Comment by passionofvc** [comment]
Thanks, change to [Microsoft Visual Studio Community 2017 Version 15.4.2]
Step by Step setting according to [https://github.com/ripple/rippled/blob/develop/Builds/VisualStudio2015/README.md]
but also show me another error below.
I have build boost ok.

LINK : fatal error LNK1104: ファイル 'libboost_thread-vc141-mt-sgd-1_65_1.lib' を開くことができません。

**Comment by passionofvc** [comment]
I hava fixed with [bjam --toolset=msvc-14.1]
because  vs version is [Microsoft Visual Studio Community 2017 Version 15.4.2]

**Comment by nbougalis** [comment]
Thanks @passionofvc; I will update the build instructions to reference VS2015 and VS2017.
