### ISSUE TITLE
where would the my sending  balance go?

### ISSUE THREAD

**Issue by passionofvc** [ripple/rippled#2262]
I am sttruggling with many time with below problem.

1.generate Credentials https://ripple.com/build/xrp-test-net/ and get 10,000 XRP
2.send rfuSnkGavGYcAy3sv6ENkFgsepRdRW5ENe to rBHz4W74nq3A4V4CkLFh5ngomxFxisSdyS
  and sending is fininshed and then balance decreased including tx fee
3.step 1 and step 2 is OK, but rBHz4W74nq3A4V4CkLFh5ngomxFxisSdyS not received any XRP, even show no Account found.
  by the way ,  rBHz4W74nq3A4V4CkLFh5ngomxFxisSdyS is create by local RippleD.exe daemon and RippleD run in test-net
so where would the balance go?
Would the balance not work(increased) in testnet?

[ripple@localhost build]$ curl -s -X POST "https://api.altnet.rippletest.net:51234" -d @- <<-END
> {
>   "method" : "sign",
>   "params" : [
>     {
>         "secret" : "sawA4kNNCqSSieMASJyTqciTmtbzt",
>         "tx_json" : {
>             "TransactionType":"Payment",
>             "Account":"rfuSnkGavGYcAy3sv6ENkFgsepRdRW5ENe",
>             "Amount":"1000000",
>             "Destination":"rBHz4W74nq3A4V4CkLFh5ngomxFxisSdyS"
>         }
>     }
>   ]
> }
> END
{"result":{"status":"success","tx_blob":"120000228000000024000000016140000000000F424068400000000000000A7321029820CC114806EA975210E59096DDC29C9398E5289E86E417D2926793C24C004B744630440220197889B8463E9453E77C8A1B084F154585DC4E096C1B77153758E7394A89E96C0220431438B503712940EE7086B7DDC32571D60E20AE280C2D7DD3C82FD9676AAB0181144BBB526C9104F8B50A3E51D2DFE84B55C3DA8201831470E7CDD1DBE503279C974694EEFE93581BEE947A","tx_json":{"Account":"rfuSnkGavGYcAy3sv6ENkFgsepRdRW5ENe","Amount":"1000000","Destination":"rBHz4W74nq3A4V4CkLFh5ngomxFxisSdyS","Fee":"10","Flags":2147483648,"Sequence":1,"SigningPubKey":"029820CC114806EA975210E59096DDC29C9398E5289E86E417D2926793C24C004B","TransactionType":"Payment","TxnSignature":"30440220197889B8463E9453E77C8A1B084F154585DC4E096C1B77153758E7394A89E96C0220431438B503712940EE7086B7DDC32571D60E20AE280C2D7DD3C82FD9676AAB01","hash":"9B95CAC5EED0A41BE982C0DA3B85EBBC4C2C3A25595DC49B4A360E4A66A9E4A0"}}}

[ripple@localhost build]$ curl -s -X POST "https://api.altnet.rippletest.net:51234" -d @- <<-END
> {
>     "method": "submit",
>     "params": [
>         {
>              "tx_blob":"120000228000000024000000016140000000000F424068400000000000000A7321029820CC114806EA975210E59096DDC29C9398E5289E86E417D2926793C24C004B744630440220197889B8463E9453E77C8A1B084F154585DC4E096C1B77153758E7394A89E96C0220431438B503712940EE7086B7DDC32571D60E20AE280C2D7DD3C82FD9676AAB0181144BBB526C9104F8B50A3E51D2DFE84B55C3DA8201831470E7CDD1DBE503279C974694EEFE93581BEE947A"
>         }
>     ]
> }
> END
{"result":{"engine_result":"tesSUCCESS","engine_result_code":0,"engine_result_message":"The transaction was applied. Only final in a validated ledger.","status":"success","tx_blob":"120000228000000024000000016140000000000F424068400000000000000A7321029820CC114806EA975210E59096DDC29C9398E5289E86E417D2926793C24C004B744630440220197889B8463E9453E77C8A1B084F154585DC4E096C1B77153758E7394A89E96C0220431438B503712940EE7086B7DDC32571D60E20AE280C2D7DD3C82FD9676AAB0181144BBB526C9104F8B50A3E51D2DFE84B55C3DA8201831470E7CDD1DBE503279C974694EEFE93581BEE947A","tx_json":{"Account":"rfuSnkGavGYcAy3sv6ENkFgsepRdRW5ENe","Amount":"1000000","Destination":"rBHz4W74nq3A4V4CkLFh5ngomxFxisSdyS","Fee":"10","Flags":2147483648,"Sequence":1,"SigningPubKey":"029820CC114806EA975210E59096DDC29C9398E5289E86E417D2926793C24C004B","TransactionType":"Payment","TxnSignature":"30440220197889B8463E9453E77C8A1B084F154585DC4E096C1B77153758E7394A89E96C0220431438B503712940EE7086B7DDC32571D60E20AE280C2D7DD3C82FD9676AAB01","hash":"9B95CAC5EED0A41BE982C0DA3B85EBBC4C2C3A25595DC49B4A360E4A66A9E4A0"}}}

[ripple@localhost build]$ curl -s -X POST "https://s.altnet.rippletest.net:51234" -d @- <<-END
{
    "method": "account_info",
    "params": [{ "account": "rfuSnkGavGYcAy3sv6ENkFgsepRdRW5ENe" }]
}
END

{"result":{"account_data":{"Account":"rfuSnkGavGYcAy3sv6ENkFgsepRdRW5ENe","Balance":"9998999990","Flags":0,"LedgerEntryType":"AccountRoot","OwnerCount":0,"PreviousTxnID":"9B95CAC5EED0A41BE982C0DA3B85EBBC4C2C3A25595DC49B4A360E4A66A9E4A0","PreviousTxnLgrSeq":3958748,"Sequence":2,"index":"01B7DB2D721C7351A78151F04DA8F3918F33223D0CF7621104B3B4692CFC7750"},"ledger_current_index":3961878,"status":"success","validated":false}}

the RippleD.exe Daemon ins running in Winndow with testnet mode
acrding to https://github.com/ripple/rippled/issues/2078

C:\Users\\rippled\build\msvc.debug>RippleD.exe account_info rB8R7Jz2Ueh4p83RovUdkD9Naa5X6GNAJy
Loading: "C:\Users\\rippled\build\msvc.debug\rippled.cfg"
2017-Nov-09 06:24:50 HTTPClient:NFO Connecting to 127.0.0.1:5005
{
   "id" : 1,
   "result" : {
      "account" : "rB8R7Jz2Ueh4p83RovUdkD9Naa5X6GNAJy",
      "error" : "actNotFound",
      "error_code" : 19,
      "error_message" : "Account not found.",
      "ledger_current_index" : 3961815,
      "request" : {
         "account" : "rB8R7Jz2Ueh4p83RovUdkD9Naa5X6GNAJy",
         "command" : "account_info"
      },
      "status" : "error",
      "validated" : false
   }
}

**Comment by MarkusTeufelberger** [comment]
The amount is in drops. You tried to send 1 XRP to an account that wasn't activated yet. I guess the testnet will have the same fees as the mainnet, so you need to send at least 20 XRP.

Check the transaction 9B95CAC5EED0A41BE982C0DA3B85EBBC4C2C3A25595DC49B4A360E4A66A9E4A0 on testnet to confirm that it didn't actually succeed.

**Comment by passionofvc** [comment]
Thanks I will resend more large amount, and check balance again.

**Comment by passionofvc** [comment]
I test below but not work.

**1、get 10000XRP from testnet**
https://ripple.com/build/xrp-test-net/
	Address
	rNUMHsbuov9BtHUw1e2NpoheYiRrGVfmc5
	Secret
	snmxFGV7xcujGApVXhC6ksNZuKJT3
	Balance
	10,000 XRP




**2.send 9000000000**
curl -s -X POST "https://api.altnet.rippletest.net:51234" -d @- <<-END
 {
    "method" : "sign",
    "params" : [
      {
          "secret" : "snmxFGV7xcujGApVXhC6ksNZuKJT3",
          "offline": true,
          "tx_json" : {
              "TransactionType":"Payment",
              "Account":"rNUMHsbuov9BtHUw1e2NpoheYiRrGVfmc5",
              "Amount":"9000000000",
              "Fee":"10000",
              "Sequence":"1",
              "Destination":"rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2"
          }
      }
    ]
 }
 END

{

"result":{
"status":"success",
"tx_blob":"12000022800000002400000001614000000218711A00684000000000002710732102EEDA57A1407275E6F6B6B1BB98AC3F0BBE4A279D2CCAA1A1BF3F727E1796E1CF74473045022100846B36D9015BF44AA29DBAE65E63DAD1F68D68C5EF9B8F15181937F786EB26F40220253A26076763357C67D9C0DEAD2710F200FD838FF46F055EC3AB8B4EBAED0612811490BF2308B7204D9AA29B74B5F51D1F80C1C502F08314BFBDC8222ED80E0CC3E8AE5C2F7BEA6AFF33F782",
"tx_json":{
    "Account":"rNUMHsbuov9BtHUw1e2NpoheYiRrGVfmc5",
    "Amount":"9000000000",
    "Destination":"rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2",
    "Fee":"10000",
    "Flags":2147483648,
    "Sequence":1,
    "SigningPubKey":"02EEDA57A1407275E6F6B6B1BB98AC3F0BBE4A279D2CCAA1A1BF3F727E1796E1CF",
    "TransactionType":"Payment",
    "TxnSignature":"3045022100846B36D9015BF44AA29DBAE65E63DAD1F68D68C5EF9B8F15181937F786EB26F40220253A26076763357C67D9C0DEAD2710F200FD838FF46F055EC3AB8B4EBAED0612",
    "hash":"A530780241DC7317A421A4EE49ACFC7906B3CC77A7BD94C5774A3783B3BBE828"
    }
 }
}

curl -s -X POST "https://api.altnet.rippletest.net:51234"  -d @- <<-END
 {
     "method": "submit",
     "params": [
         {
             "tx_blob": "12000022800000002400000001614000000218711A00684000000000002710732102EEDA57A1407275E6F6B6B1BB98AC3F0BBE4A279D2CCAA1A1BF3F727E1796E1CF74473045022100846B36D9015BF44AA29DBAE65E63DAD1F68D68C5EF9B8F15181937F786EB26F40220253A26076763357C67D9C0DEAD2710F200FD838FF46F055EC3AB8B4EBAED0612811490BF2308B7204D9AA29B74B5F51D1F80C1C502F08314BFBDC8222ED80E0CC3E8AE5C2F7BEA6AFF33F782"
         }
     ]
 }
 END

{

"result":{
"engine_result":"tesSUCCESS",
"engine_result_code":0,
"engine_result_message":"The transaction was applied. Only final in a validated ledger.",
"status":"success",
"tx_blob":"12000022800000002400000001614000000218711A00684000000000002710732102EEDA57A1407275E6F6B6B1BB98AC3F0BBE4A279D2CCAA1A1BF3F727E1796E1CF74473045022100846B36D9015BF44AA29DBAE65E63DAD1F68D68C5EF9B8F15181937F786EB26F40220253A26076763357C67D9C0DEAD2710F200FD838FF46F055EC3AB8B4EBAED0612811490BF2308B7204D9AA29B74B5F51D1F80C1C502F08314BFBDC8222ED80E0CC3E8AE5C2F7BEA6AFF33F782",
"tx_json":{
"Account":"rNUMHsbuov9BtHUw1e2NpoheYiRrGVfmc5",
"Amount":"9000000000",
"Destination":"rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2",
"Fee":"10000",
"Flags":2147483648,
"Sequence":1,
"SigningPubKey":"02EEDA57A1407275E6F6B6B1BB98AC3F0BBE4A279D2CCAA1A1BF3F727E1796E1CF",
"TransactionType":"Payment",
"TxnSignature":"3045022100846B36D9015BF44AA29DBAE65E63DAD1F68D68C5EF9B8F15181937F786EB26F40220253A26076763357C67D9C0DEAD2710F200FD838FF46F055EC3AB8B4EBAED0612",
"hash":"A530780241DC7317A421A4EE49ACFC7906B3CC77A7BD94C5774A3783B3BBE828"
}
}

}


**3、confirm the balance,[sender：rNUMHsbuov9BtHUw1e2NpoheYiRrGVfmc5]**
 curl -s -X POST "https://api.altnet.rippletest.net:51234"  -d @- <<-END
 {
     "method": "account_info",
     "params": [
         {
             "account": "rNUMHsbuov9BtHUw1e2NpoheYiRrGVfmc5",
             "strict": true,
             "ledger_index": "current",
             "queue": true
         }
     ]
 }
 END

{

"result":{
"account_data":{
"Account":"rNUMHsbuov9BtHUw1e2NpoheYiRrGVfmc5",
"Balance":"999990000",
"Flags":0,
"LedgerEntryType":"AccountRoot",
"OwnerCount":0,
"PreviousTxnID":"A530780241DC7317A421A4EE49ACFC7906B3CC77A7BD94C5774A3783B3BBE828",
"PreviousTxnLgrSeq":4106007,
"Sequence":2,
"index":"93B772380C130E82D6A079BE502DBC7CCAF7BECC18DBF7E2705A6745FCA6F91F"
},
"ledger_current_index":4106013,
"queue_data":{
"txn_count":0
},
"status":"success",
"validated":false
}

}

**４、Confirm the tx state**
curl -s -X POST "https://api.altnet.rippletest.net:51234" -d @- <<-END
 {
     "method": "tx",
     "params": [
         {
             "transaction": "A530780241DC7317A421A4EE49ACFC7906B3CC77A7BD94C5774A3783B3BBE828",
             "binary": false
         }
     ]
 }
 END

{

"result":{
"Account":"rNUMHsbuov9BtHUw1e2NpoheYiRrGVfmc5",
"Amount":"9000000000",
"Destination":"rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2",
"Fee":"10000",
"Flags":2147483648,
"Sequence":1,
"SigningPubKey":"02EEDA57A1407275E6F6B6B1BB98AC3F0BBE4A279D2CCAA1A1BF3F727E1796E1CF",
"TransactionType":"Payment",
"TxnSignature":"3045022100846B36D9015BF44AA29DBAE65E63DAD1F68D68C5EF9B8F15181937F786EB26F40220253A26076763357C67D9C0DEAD2710F200FD838FF46F055EC3AB8B4EBAED0612",
"date":563964312,
"hash":"A530780241DC7317A421A4EE49ACFC7906B3CC77A7BD94C5774A3783B3BBE828",
"inLedger":4106007,
"ledger_index":4106007,
"meta":{
"AffectedNodes":[
1. {
"ModifiedNode":{
"FinalFields":{
"Account":"rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2",
"Balance":"17999999980",
"Flags":0,
"OwnerCount":0,
"Sequence":1
},
"LedgerEntryType":"AccountRoot",
"LedgerIndex":"226775A439718619B86E009A4A9AA87748D7C9F42ABCF8EE792AA53835E7B7E0",
"PreviousFields":{
"Balance":"8999999980"
},
"PreviousTxnID":"697C12B191AC6E9495D3C9F61F4EFC46B8200C54CD5967FAC87D8C1E27D6B61E",
"PreviousTxnLgrSeq":4104364
}
},
2. {
"ModifiedNode":{
"FinalFields":{
"Account":"rNUMHsbuov9BtHUw1e2NpoheYiRrGVfmc5",
"Balance":"999990000",
"Flags":0,
"OwnerCount":0,
"Sequence":2
},
"LedgerEntryType":"AccountRoot",
"LedgerIndex":"93B772380C130E82D6A079BE502DBC7CCAF7BECC18DBF7E2705A6745FCA6F91F",
"PreviousFields":{
"Balance":"10000000000",
"Sequence":1
},
"PreviousTxnID":"4AB18A2B4AEBD530742672E15F49D4B0416B8B7123FAB833480FADEDD404201E",
"PreviousTxnLgrSeq":4105954
}
}
],
"TransactionIndex":2,
"TransactionResult":"tesSUCCESS",
"delivered_amount":"9000000000"
},
"status":"success",
"validated":true
}

}

**5、confirm the balance,[receipient：rHj6xyoucaB3JgVznuBFPNnijHQryoNRCZ]**

 curl -s -X POST "https://api.altnet.rippletest.net:51234"  -d @- <<-END
 {
     "method": "account_info",
     "params": [
         {
             "account": "rHj6xyoucaB3JgVznuBFPNnijHQryoNRCZ",
             "ledger": "validated"
         }
     ]
 }
END

{

"result":{
"account_data":{
    "Account":"rHj6xyoucaB3JgVznuBFPNnijHQryoNRCZ",
    "Balance":"999999990",
    "Flags":0,
    "LedgerEntryType":"AccountRoot",
    "OwnerCount":0,
    "PreviousTxnID":"697C12B191AC6E9495D3C9F61F4EFC46B8200C54CD5967FAC87D8C1E27D6B61E",
    "PreviousTxnLgrSeq":4104364,
    "Sequence":4,
    "index":"EFDBAF1A3C3EBFAAEF05D50E4C5D3F122330CC1677C73C2F3FC3063305D93001"
},
"ledger_hash":"A6534945BEC84630EC39185DCA8E49326C9150AE650C513E832E2C56F5AA1C50",
"ledger_index":4106401,
"status":"success",
"validated":true
}

}

the [receipient：rHj6xyoucaB3JgVznuBFPNnijHQryoNRCZ] balabce is incorrect,
not receive any balance even if sender already finished and balance decremented.

**Comment by passionofvc** [comment]
by the way 
sender balance decremented by FEE   (10000)+acoumt(9000000000), and remainer 999990000
this is ok.
TotalAmount | 10000000000
Fee | 10000
SendAmount | 9000000000
Remainer | 999990000

the [receipient：rHj6xyoucaB3JgVznuBFPNnijHQryoNRCZ] balance no changed.

**Comment by wilsonianb** [comment]
```
"Destination":"rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2"
```
The recipient in your transaction was not `rHj6xyoucaB3JgVznuBFPNnijHQryoNRCZ`

**Comment by passionofvc** [comment]
Sorry, I query [rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2] even is wrong.

curl -s -X POST "https://api.altnet.rippletest.net:51234" -d @- <<-END
{
"method": "account_info",
"params": [
    {
    "account": "rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2",
    "ledger": "validated"
    }
    ]
}
END

{
    "result":{
        "account_data":{
            "Account":"rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2",
            **"Balance":"17999999980",**
            "Flags":0,
            "LedgerEntryType":"AccountRoot",
            "OwnerCount":0,
            "PreviousTxnID":"A530780241DC7317A421A4EE49ACFC7906B3CC77A7BD94C5774A3783B3BBE828",
            "PreviousTxnLgrSeq":4106007,
            "Sequence":1,
            "index":"226775A439718619B86E009A4A9AA87748D7C9F42ABCF8EE792AA53835E7B7E0"
        },
        "ledger_hash":"5D22274123441520E2CA683F1C772AE6840C9053122CBE18729D9418197CB171",
        "ledger_index":4108475,
        "status":"success",
        "validated":true
    }

}

    "result":{
        "account_data":{
            "Account":"rHj6xyoucaB3JgVznuBFPNnijHQryoNRCZ",
            "Balance":"999999990",
            "Flags":0,
            "LedgerEntryType":"AccountRoot",
            "OwnerCount":0,
            "PreviousTxnID":"697C12B191AC6E9495D3C9F61F4EFC46B8200C54CD5967FAC87D8C1E27D6B61E",
            "PreviousTxnLgrSeq":4104364,
            "Sequence":4,
            "index":"EFDBAF1A3C3EBFAAEF05D50E4C5D3F122330CC1677C73C2F3FC3063305D93001"
        },
        "ledger_hash":"03E32983BDE7D8364F9B2CEF3324D0F648262E66AC038839B79B87BA62E306EF",
        "ledger_index":4108433,
        "status":"success",
        "validated":true
    }

}

**Comment by passionofvc** [comment]
sorry I figureed out that the balance is 17999999980,
and  999990000 + 9000000000=17999999980,
I am very sorry、this is OK

ripple@localhost build]$ rippled  account_info rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2
Loading: "/home/ripple/rippled/build/rippled.cfg"
2017-Nov-14 10:57:50 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "id" : 1,
   "result" : {
      "account_data" : {
         "Account" : "rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2",
         "Balance" : "17999999980",
         "Flags" : 0,
         "LedgerEntryType" : "AccountRoot",
         "OwnerCount" : 0,
         "PreviousTxnID" : "A530780241DC7317A421A4EE49ACFC7906B3CC77A7BD94C5774A3783B3BBE828",
         "PreviousTxnLgrSeq" : 4106007,
         "Sequence" : 1,
         "index" : "226775A439718619B86E009A4A9AA87748D7C9F42ABCF8EE792AA53835E7B7E0"
      },
      "ledger_current_index" : 4108615,
      "status" : "success",
      "validated" : false
   }
}
[ripple@localhost build]$ curl -s -X POST "https://api.altnet.rippletest.net:51234" -d @- <<-END
> {
>     "method": "tx",
>     "params": [
>         {
>             "transaction": "A530780241DC7317A421A4EE49ACFC7906B3CC77A7BD94C5774A3783B3BBE828",
>             "binary": false
>         }
>     ]
> }
> END
{

    "result":{
        "Account":"rNUMHsbuov9BtHUw1e2NpoheYiRrGVfmc5",
        "Amount":"9000000000",
        "Destination":"rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2",
        "Fee":"10000",
        "Flags":2147483648,
        "Sequence":1,
        "SigningPubKey":"02EEDA57A1407275E6F6B6B1BB98AC3F0BBE4A279D2CCAA1A1BF3F727E1796E1CF",
        "TransactionType":"Payment",
        "TxnSignature":"3045022100846B36D9015BF44AA29DBAE65E63DAD1F68D68C5EF9B8F15181937F786EB26F40220253A26076763357C67D9C0DEAD2710F200FD838FF46F055EC3AB8B4EBAED0612",
        "date":563964312,
        "hash":"A530780241DC7317A421A4EE49ACFC7906B3CC77A7BD94C5774A3783B3BBE828",
        "inLedger":4106007,
        "ledger_index":4106007,
        "meta":{
            "AffectedNodes":[
                {
                    "ModifiedNode":{
                        "FinalFields":{
                            "Account":"rJ7qQugRbMCwDeGo25pvERXtudcuB4guT2",
                            "Balance":"17999999980",
                            "Flags":0,
                            "OwnerCount":0,
                            "Sequence":1
                        },
                        "LedgerEntryType":"AccountRoot",
                        "LedgerIndex":"226775A439718619B86E009A4A9AA87748D7C9F42ABCF8EE792AA53835E7B7E0",
                        "PreviousFields":{
                            "Balance":"8999999980"
                        },
                        "PreviousTxnID":"697C12B191AC6E9495D3C9F61F4EFC46B8200C54CD5967FAC87D8C1E27D6B61E",
                        "PreviousTxnLgrSeq":4104364
                    }
                },
                {
                    "ModifiedNode":{
                        "FinalFields":{
                            "Account":"rNUMHsbuov9BtHUw1e2NpoheYiRrGVfmc5",
                            "Balance":"999990000",
                            "Flags":0,
                            "OwnerCount":0,
                            "Sequence":2
                        },
                        "LedgerEntryType":"AccountRoot",
                        "LedgerIndex":"93B772380C130E82D6A079BE502DBC7CCAF7BECC18DBF7E2705A6745FCA6F91F",
                        "PreviousFields":{
                            "Balance":"10000000000",
                            "Sequence":1
                        },
                        "PreviousTxnID":"4AB18A2B4AEBD530742672E15F49D4B0416B8B7123FAB833480FADEDD404201E",
                        "PreviousTxnLgrSeq":4105954
                    }
                }
            ],
            "TransactionIndex":2,
            "TransactionResult":"tesSUCCESS",
            "delivered_amount":"9000000000"
        },
        "status":"success",
        "validated":true
    }

}
[ripple@localhost build]$
