### ISSUE TITLE
how to recovery  my master_seed?

### ISSUE THREAD

**Issue by passionofvc** [ripple/rippled#2265]
I wallet_propose to get new address for sending XRP,
but if I forgot { "master_seed" : "sniboTahMe6YKBkuaR9P5uP52fYMd"}
how to recovery  my master_seed,because I know
when sign transaction the master_seed is needed.
 
[ripple@localhost build]$ rippled wallet_propose
Loading: "/home/ripple/rippled/build/rippled.cfg"
2017-Nov-14 06:10:30 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "id" : 1,
   "result" : {
      "account_id" : "rEkCmshzUPVapRYWDhBMmraUEUamEJowMe",
      "key_type" : "secp256k1",
      "master_key" : "NAT REEL LENT RAFT EASY BEND VOLT HOLM BAY CHUM GOAD DEBT",
      **"master_seed" : "sniboTahMe6YKBkuaR9P5uP52fYMd",**
      "master_seed_hex" : "E2D85833193473F5AC9AC765B4C6F92A",
      "public_key" : "aB4DXnKLcrptnf6f5y2TpdMgHDXotp2vSCeemCNVSXWFh1BLqmAt",
      "public_key_hex" : "022219F1CF3C7B3E48A1D306BDF6FA503B6D93E0658B3FD940AFEC0751EE8B4C90",
      "status" : "success"
   }
}

**Comment by peterjkrey** [comment]
If you have your master_seed why do you need to recover it?

**Comment by passionofvc** [comment]
No ,I don't have my master_seed
Above just is testnet output.
Someone may forgot master seed,
does this means when lost master seed, lost  all money with than address.
Does master seed same to  private key in bitcoin?

**Comment by peterjkrey** [comment]
Yes.

**Comment by sublimator** [comment]
:(

**Comment by passionofvc** [comment]
In bitcoind, I can dump my private key from my wallet file, 
but in rippled can not dump my master seed from
my wallet file, so regrettable!

**Comment by nbougalis** [comment]
@passionofvc: but in `rippled`, there is no wallet file. I understand that this is a different model from Bitcoin. I would welcome any ideas on how we can improve the process.

One option may be to improve the information displayed by the `wallet_propose` command, so that it is nicely formatted and includes both a warning to save your key and a convenient option to back your key up on a USB stick or other medium.

It is my hope that well-designed third-party wallet apps will have thoughtful "setup" guides that will include, among other things, instructions on how to perform secure backups.

**Comment by passionofvc** [comment]
I just list my db fold create by rippled, also show me wallt.db,
does this is not a wallet file?
In bitcoin, hard fork often corrurred, we want to need transfering balance between wallets,
so we do dump wallet private key and import to another wallet for balance transfering.
 
[ripple@localhost build]$ ls -ltr /home/ripple/rippled/build/db/
合計 37644
**-rw-r--r--. 1 ripple ripple    16384 11月 14 12:44 wallet.db**
-rw-r--r--. 1 ripple ripple    12288 11月 14 16:07 state.db
drwxrwxr-x. 4 ripple ripple       48 11月 14 16:07 rocksdb
-rw-------. 1 ripple ripple     1024 11月 14 16:48 random.seed
-rw-r--r--. 1 ripple ripple 20557824 11月 14 17:08 transaction.db
-rw-r--r--. 1 ripple ripple 10510336 11月 14 17:09 ledger.db
-rw-r--r--. 1 ripple ripple    40960 11月 14 17:09 peerfinder.sqlite
-rw-r--r--. 1 ripple ripple    32768 11月 14 17:10 transaction.db-shm
-rw-r--r--. 1 ripple ripple    32768 11月 14 17:10 ledger.db-shm
-rw-r--r--. 1 ripple ripple  2995272 11月 14 17:10 transaction.db-wal
-rw-r--r--. 1 ripple ripple  3407272 11月 14 17:10 ledger.db-wal
[ripple@localhost build]$

**Comment by nbougalis** [comment]
@passionofvc, no, the *poorly named* `wallet.db` is not a wallet file. It contains things like validator and publishers manifests, and the identity of your `rippled` node. It does not contain any wallet information.

**Comment by passionofvc** [comment]
I confirmed it  very thanks.

sqlite> .database
seq  name             file
---  ---------------  ----------------------------------------------------------
0    main             /home/ripple/rippled/build/db/wallet.db
sqlite> .tables
NodeIdentity        PublisherManifests  ValidatorManifests

**Comment by derysendiri** [comment]
/.

**Comment by Apollo-IT** [comment]
@passionofvc @nbougalis I wanna backup private keys and addresses from rippled.
Any suggestion for it?

**Comment by passionofvc** [comment]
@Apollo-IT 
rippled do not have any key management, you can not backup private key from rippled.

**Comment by livingrock7** [comment]
I want to move wallet addresses from one rippled server to another as part of migration. Can you please advise?

**Comment by MarkusTeufelberger** [comment]
There is no user facing key material stored by `rippled`, so I'm not sure what you mean by this question. Also this issue is closed, please open a new one.
