### ISSUE TITLE
Is there a RPC command to list all account_info created by wallet_propose?

### ISSUE THREAD

**Issue by passionofvc** [ripple/rippled#2267]
I want to know all account_info created by  wallet_propose ,
Is there anything same to getaddressesbyaccount in bitcoind.

**Comment by ximinez** [comment]
No.  rippled does not keep any record of the results of `wallet_propose`.

**Comment by MarkusTeufelberger** [comment]
Imagine rippled more like a back-end server that has no wallet attached. Actual wallet software communicates with rippled to know the current state of the network, but rippled does not hold any keys that hold actual funds.

In Bitcoinland this would be similar to Electrum wallets + Electrum-server.

**Comment by passionofvc** [comment]
@MarkusTeufelberger 
thanks you!
I get understand below.

If client use rippled(wallet_propose) to get new address every time,
it means that client also must persist save it's output in some local drives, may be USB so on.
If hard drive broken, anything is lost.
