### ISSUE TITLE
[Question] How to make account require Destination Tag and reject transactions without it?

### ISSUE THREAD

**Issue by gituser** [ripple/rippled#2284]
Hi.

Is there any way to make existing account to require Destination Tag in transaction otherwise reject them with `TransactionResult : "tecDST_TAG_NEEDED"` ?

Thanks.

**Comment by MarkusTeufelberger** [comment]
Set the lsfRequireDestTag flag: https://ripple.com/build/ledger-format/#accountroot-flags

**Comment by gituser** [comment]
thank you, @MarkusTeufelberger 

couldn't quickly find in google :/
