### ISSUE TITLE
Always get RippledError(noNetwork)

### ISSUE THREAD

**Issue by khowarizmi** [ripple/rippled#2296]
It seems that the transactions are too much this time, and rippled are too busy to answer request.
Is it possible to solve this problem by setting up a rippled by myself.
Is there any way to handle RippledError(noNetwork)?

**Comment by bachase** [comment]
We highly encourage users to run their own rippled servers. Please consult https://ripple.com/build/rippled-setup/#installing-rippled.  Feel free to open another issue with any specific technical issues you run in to.
