### ISSUE TITLE
Where can I get the historical account amounts of XRP?

### ISSUE THREAD

**Issue by franklili** [ripple/rippled#2301]
I want to analysis the trend of account amounts of XRP. Where can I get the historical account amounts of XRP?

**Comment by JoelKatz** [comment]
It's a bit tedious, but I always do it by figuring out the ledger number I need to query by bisection and then querying the account in that ledger.

So if you want the balance as of a particular date, you find a ledger before that date and a ledger after that date and then keep trying sequence numbers halfway between them until you find the ledger to query. Then check that ledger. I don't know of any tool to automate this.

You can get ledger headers with the "ledger" command. For example:

```
$ curl -s -X POST -d \
'{ "method" : "ledger", "params" : [ { "ledger_index" : 10000000}] }' \
http://s2.ripple.com:51234 | json_pp 

{
   "result" : {
      "ledger" : {
         "hash" : "80DC3D4E82611DA5516010EB04FA64E8907F913FF47739F7A67A667FCFF0894B",
         "parent_hash" : "F5F748541BAF7AD7DE5DB1A2A5339D6EA1A95DAEC9EA067AA61E62EE4CFECA37",
         "accepted" : true,
         "totalCoins" : "99999860385491369",
         "total_coins" : "99999860385491369",
         "closed" : true,
         "ledger_hash" : "80DC3D4E82611DA5516010EB04FA64E8907F913FF47739F7A67A667FCFF0894B",
         "transaction_hash" : "7F8363BD9A1FEA7ABFB2A751E8F1DDB2FA82E1E44FED5528859AFDF686FA42E9",
         "close_flags" : 0,
         "close_time" : 469584890,
         "close_time_resolution" : 10,
         "ledger_index" : "10000000",
         "parent_close_time" : 469584880,
         "account_hash" : "A157E2EB34EDB550B0B6573DE5B0F1CDA1F1F21DA3FD35D505EB11607F6734D5",
         "close_time_human" : "2014-Nov-18 00:14:50",
         "seqNum" : "10000000"
      },
      "status" : "success",
      "ledger_index" : 10000000,
      "validated" : true,
      "warning" : "load",
      "ledger_hash" : "80DC3D4E82611DA5516010EB04FA64E8907F913FF47739F7A67A667FCFF0894B"
   }
}
```

This shows that ledger 10,000,000 closed on November 14, 2018 at 14:50 UTC. This command can be adjusted and used to find the ledger to query.

To query a historical ledger for a balance, use a command like this:

```
$ curl -s -X POST -d '{ "method" : "account_info", "params" : [ { "ledger_index" : 30000000, "account" : "rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv" }] }' http://s2.ripple.com:51234 | json_pp 

{
   "result" : {
      "ledger_hash" : "CAC728A1AB9E743B9184802AB2A60DA061449441E80C0F00E72EFCC7971A2E20",
      "validated" : true,
      "account_data" : {
         "PreviousTxnLgrSeq" : 29999989,
         "PreviousTxnID" : "FE12D67C6EAC84A527D83E840456B88D989646CC580223F18825FA7C388A5F51",
         "Sequence" : 10413,
         "LedgerEntryType" : "AccountRoot",
         "OwnerCount" : 0,
         "index" : "C3B625B296E95A21D7BBBB7E3D343AF423B463B87B5D56EE7F79C8E16A47A6F5",
         "Flags" : 131072,
         "Balance" : "2626616779576",
         "Account" : "rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv"
      },
      "status" : "success",
      "ledger_index" : 30000000,
      "warning" : "load"
   }
}
```

This shows the balance (in drops, or millionths of an XRP) of the specified account in the specified ledger.

Note that the s2.ripple.com cluster is a best effort service and should be queried gently or it will refuse you service.

**Comment by sublimator** [comment]
Succumed to OS  too? Or installed json_pp on linux?

**Comment by sublimator** [comment]
^ OSX :)

**Comment by sublimator** [comment]
https://ripple.com/build/data-api-v2/

Never used it myself. I believe it powers the charts on the ripple.com site
though.

**Comment by gituser** [comment]
Yes, the best method to get history of particular account is do use data api or run your own data node.

**Comment by aiffone** [comment]
where do I run this code?
