### ISSUE TITLE
Rippled performance

### ISSUE THREAD

**Issue by jnr101** [ripple/rippled#2302]
Hi,

I am running a personal rippled for some time now. Up till recently it ran rather well, not much disturbance. The last few weeks I see more frequently service outages and it takes more time to 'catch up' with the latest ledger. When I do a 'dmesg -T' it seems I am sometimes running out of memory, so it could be that my vm is becoming too small, considering the current (and future) load. But before upgrading I want to make sure that memory is the issue.

My current VM: Centos 7, 40GB SSD, vCPU: 2, vRAM: 2GB

Because of the outages (service stops responding and I'll have to wait till it's back on track again) I have configured my bots again to s1.ripple.com. So I am running a rippled node now doing nothing special, it is only being a node in the network (I do not allow others to connect my rippled).
To put just a little load on it, I open a rippex wallet (the old ripple desktop wallet) and use 'send' to get an offer / path to send an amount to an other wallet.  Please see the attached debug.log (log level WRN) at 11:20 and forward for the effects this had (rippled kept on responding in this case, no outage yet)

[debug.log](https://github.com/ripple/rippled/files/1565594/debug.log)

Could someone take a brief look at the rippled log file and check if this is normal behavior? Would increasing the vRAM to 4GB help, or is it latency in the network and would I be better off using another cloud hosting provider? 

Thanks in advance,
jn_r

**Comment by JoelKatz** [comment]
What version are you running? We had an issue that could cause dropped transactions and severed server-sever links. It was fixed in 0.80.2 and older versions may have issues.

**Comment by jnr101** [comment]
I am running with version 0.80.2. 
(the rippled is automatically upgraded to the latest version)
