### ISSUE TITLE
Json-RPC issue

### ISSUE THREAD

**Issue by SneakyFish5** [ripple/rippled#2303]
Hi!

I've been running the following command: 
`curl -X POST -d '{ "method" : "ledger", "params": [{"ledger_index": "validated", "accounts": true, "expand": true}] }' http://s2.ripple.com:51234>dec10ledger.dat`

Whenever I download the ledger info though, it's a few Kb when it should be like 600 mb. Anyone know what I'm doing wrong?

**Comment by bachase** [comment]
Hi @SneakyFish5!
The `"accounts":true` option of the `ledger` call requires admin privileges on the server (see
https://ripple.com/build/rippled-apis/#ledger).  You would likely need to run your own `rippled` server to have admin access; see https://ripple.com/build/rippled-setup/ for details on setting one up.
