### ISSUE TITLE
LoadManager:WRN Server stalled when i run rippled --net

### ISSUE THREAD

**Issue by 555leo** [ripple/rippled#2308]
2017-Dec-20 10:11:15 Application:FTL Startup RPC: 
{
	"command" : "log_level",
	"severity" : "warning"
}
2017-Dec-20 10:11:15 Application:FTL Result: {}

2017-Dec-20 10:11:24 LoadManager:WRN Server stalled for 10 seconds.
2017-Dec-20 10:11:34 LoadManager:WRN Server stalled for 20 seconds.

How should I solve this problem?

**Comment by bachase** [comment]
That is generally an indication that your server is overloaded or starved for RAM, CPU or IO resources.  Is this a new server you are setting up, or an existing one that is now having trouble performing?

What are the hardware specs of the machine?

**Comment by waibb** [comment]
thank you for your reply
I run new server on ubuntu14.04.

**Comment by bachase** [comment]
Does the machine have an SSD or spinning disk? How much RAM does it have? How many CPU cores?

**Comment by waibb** [comment]
RAM:8G;
CPU :1;
