### ISSUE TITLE
ShaMap v2

### ISSUE THREAD

**Issue by sublimator** [ripple/rippled#2310]
I was playing with rippled the other day, and then went out for a few days around Christmas, leaving it running. I came back and the nodestore/sqlite was 150 GB. 

Of course, it was probably back filling, but it got me to wondering and my investigations found that the ShaMap v2 amendment wasn't enabled. 

I'm curious why not. 

Problems found?

**Comment by MarkusTeufelberger** [comment]
Probably still scaling in the same order as SHAmap v1 (O(n*log(n))) - might be a short term solution, but not a game changer imho.

Still would be nice to have an option to store full history NOT on SSDs by the way, but that's not related to SHAmapv2...

**Comment by sublimator** [comment]
>>> Probably still scaling in the same order as SHAmap v1

Hrmmm. I can't recall the exact details as it has been quite some moons and beers betwixt, but I thought it was still considerable/"worth it" even if not a game changer. Those orderbooks have 192 bit common prefixes creating a whole bunch of useless inner nodes, empty bar one.  If you analyze a node store (compression aside) it's mostly 0s.

I always liked the idea of history packs that store a ledger header and initial full trees in canonical binary form, with just the leaves, as inner nodes are implied. For each subsequent ledger you store the ledger header, full txn tree but only deltas for the account state tree. You could add the validator sigs too I guess.

**Comment by MarkusTeufelberger** [comment]
Well, here's my feature request from 2(!) years ago with close to 0 response: https://github.com/ripple/rippled/issues/1343

And then Ripple is wondering why they don't attract a developer community around their blockchain. :-(

**Comment by sublimator** [comment]
I feel ya :)

**Comment by sublimator** [comment]
Writing the command wouldn't actually be that hard. I've done something similar before. Getting it merged would be another story: meeting the teams standards, persisting through long code review processes and even just getting them interested would be tricky.

It might be possible to implement in such a way that you can just rebase it each update though.

**Comment by MarkusTeufelberger** [comment]
I looked into just interfacing my code with NuDB instead, but that header only modern C++ stuff is also not the most accessible, especially across language boundaries. Looking at the more infrastructure PRs I did so far though it is really a pain to even get someone to take a look (or to state they took a look). I would understand it if the project had dozens of PRs a day like Ansible or Kubernetes - but here there's maaaaybe one PR per day or less and a bug report a week.

**Comment by sublimator** [comment]
> it is really a pain to even get someone to take a look

I worked at ripple for ~3 years, and even being on the "inside" it was the same :)  Just getting back into playing with ripple lately. 

What language do you code in usually ?

**Comment by MarkusTeufelberger** [comment]
> What language do you code in usually ?

Bad Python 3. I probably just need to get around to read through the docs of https://github.com/pybind/pybind11.

Back on topic:  
The more I look at SHAmaps and the DB backend I wonder how/if this problem could be solved in a better way - yes, the signal/noise ratio would be better with v2, but in general the scaling would be still in the same ballpark. Storing it completely expanded would by now cause a few hundred MB every few seconds of mostly duplicated data.  
Probably checkpoints + diffs are the way to go, for more performance differential diffs, for less disk usage incremental ones.

**Comment by sublimator** [comment]
You mean like binary diffs? re: "differential" ?

**Comment by MarkusTeufelberger** [comment]
More like backup strategies:

Incremental: Full state + all diffs since full state = current state

Differential: Full state + single diff = current state

The first strategy has the downside of requiring you to load and apply all diffs since the full state but these are as small as possible since they only diff against their predecessor.
The second one has the downside of accumulating duplicated content (e.g. a node gets added 2 ledgers after the full state, now every diff until the next full state will contain this node).

**Comment by sublimator** [comment]
It already only stores tree diffs in the nodestore. I am fairly sure there
is not 100s of megs of duplicated data per second. There's really none
since the nodestore is a kinda CAS (keyval backend key is hash of the
content, a very interesting property) but there's a lot of wasted inner
nodes. Also, *all* inner nodes are implied.

History packs would be very amenable to map reduce etc and good at being
source data for evolving schemas (think bugs while importing into a
different form)

**Comment by sublimator** [comment]
Thanks for the clarification :)

**Comment by sublimator** [comment]
I'd like to see the RPC and core txn node split up. Imagine the sqlite db
size for full history these days!!!

**Comment by MarkusTeufelberger** [comment]
> I'd like to see the RPC and core txn node split up.

Pull request ?

:-P

**Comment by sublimator** [comment]
hahaha

**Comment by sublimator** [comment]
See:
https://github.com/stellar/stellar-core
https://github.com/stellar/go/tree/master/services/horizon
https://github.com/stellar/go/tree/master/tools/stellar-archivist

This sort of structuring makes a lot of sense to me :)

**Comment by sublimator** [comment]
I believe they actually are able to replay the transactions for regression testing. Other things stellar improved are adding a field symmetrical to rippled's LastLedgerSequence for really easily determining a valid ledger range for a transaction. It affords a dead simple mental model and confidence.
