### ISSUE TITLE
Format String Vulnerability on line 58 of rippled/src/rocksdb2/util/filename.cc

### ISSUE THREAD

**Issue by petermalone** [ripple/rippled#2311]
Line 58 of rippled/src/rocksdb2/util/filename.cc suffers from a format string vulnerability: https://github.com/ripple/rippled/blob/dc9e9f498ad9124e3db16eba11af1f6ae5752055/src/rocksdb2/util/filename.cc#L59

```
snprintf(dest + write_idx, len - write_idx, suffix);
```

dest is passed in via Line 35:
```
static size_t GetInfoLogPrefix(const std::string& path, char* dest, int len) {
```

The call is on Line 167:
```
size_t len = GetInfoLogPrefix(db_absolute_path, buf, sizeof(buf));
```

This comes from Line 159:
```
InfoLogPrefix::InfoLogPrefix(bool has_log_dir,
                             const std::string& db_absolute_path) {
```

Here's an example vulnerable piece of code:
```
sj@slinafirinne:~$ cat fff.c
#include <stdio.h>

int main() {
        char *str;
        char *str2 = "%x";
        snprintf(str2, 2, str);
}
sj@slinafirinne:~$ ./fff
Segmentation fault
```

More info: https://www.owasp.org/index.php/Format_string_attack

**Comment by nbougalis** [comment]
Thank you for the report; this code does not suffer from a vulnerability, since the format string contains no formatting characters, but the hard-coded string `_LOG`.

See https://github.com/ripple/rippled/blob/dc9e9f498ad9124e3db16eba11af1f6ae5752055/src/rocksdb2/util/filename.cc#L36
