### ISSUE TITLE
Not able to download repository throught RPM

### ISSUE THREAD

**Issue by khelle** [ripple/rippled#2313]
I am not able to downlaod the repository needed to install the node with command specified in documentation. I am using Ubuntu 16.04

```
> sudo rpm -Uvh https://mirrors.ripple.com/ripple-repo-el7.rpm
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
Retrieving https://mirrors.ripple.com/ripple-repo-el7.rpm
error: skipping https://mirrors.ripple.com/ripple-repo-el7.rpm - transfer failed
```

It does not seem to be firewall issue. How this issue can be fixed?

**Comment by khelle** [comment]
Ok, I was able to fix it by downloading it first via wget:

`wget https://mirrors.ripple.com/ripple-repo-el7.rpm`

And then running rpm locally:

`sudo rpm -Uvh ripple-repo-el7.rpm`

The same problem and solution occured for GPG key.

**Comment by MarkusTeufelberger** [comment]
It already tells you what to do:

`RPM should not be used directly install RPM packages, use Alien instead!`

**Comment by khelle** [comment]
@MarkusTeufelberger this example is taken from documentation, and at this point we are supposed to use RPM to download the package, then Alien. The info is irrelevant. The problem is that RPM is not able for some reason to download the remote package. The workaround for this is to download it manually then use RPM locally. Nothing more nothing less

**Comment by tuloski** [comment]
Yeah I had the same problem and I solved in the same way.
