### ISSUE TITLE
Remove boost::hash_value() overloads

### ISSUE THREAD

**Issue by vinniefalco** [ripple/rippled#232]
Currently, some Ripple classes (like base_uint, et. al.) rely on boost::hash_value overloads for associative container support. This should be removed, since it requires global variables for the seed used by the hardened hash function. There's already a suitable replacement, which is the specialization of boost::hash. I've also added the specialization for std::hash. So we should remove hash_value overloads and the global initialization that accompanies it.

**Comment by rec** [comment]
I think @HowardHinnant already did this?

**Comment by HowardHinnant** [comment]
I'll do a survey to make sure.

**Comment by HowardHinnant** [comment]
The string "hash_value" does not appear within src/ripple or src/beast.  Closing.
