### ISSUE TITLE
Where is gettimeofday defined?

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2339]
See https://github.com/ripple/rippled/blob/87742a5e6c5093bfd4ddad88b858d722a91738cd/src/ripple/beast/core/Time.cpp#L41 - where does this function come from?

**Comment by sublimator** [comment]
Seems like a stdlib time.h ?

![image](https://user-images.githubusercontent.com/525211/35179217-67a88c22-fdc8-11e7-96c9-7f2be7363e13.png)

**Comment by MarkusTeufelberger** [comment]
The missing import is in core.unity.cpp, but the code is dead anyways, see #2345.

Closing this.
