### ISSUE TITLE
Ledger command requires ledger_index key to be an int

### ISSUE THREAD

**Issue by miracle2k** [ripple/rippled#234]
It took a while until I figured out why the following doesn't work right (it simply returns some default current ledger response):

```
{"command": "ledger", "transactions" : true,"ledger_index": "4044952", "expand": true} 
```

It's because ledger_index is a string. I'm only reporting this because in _responses_, ledger_index is also given as a string, which is if nothing else inconsistent.

**Comment by HowardHinnant** [comment]
The `ledger_index`, if specified as a numerical sequence number, is now well specified to be a 32-bit unsigned integer:  https://ripple.com/build/rippled-apis/#ledger-index

The response now has a top-level `ledger_index` field containing the ledger index as an unsigned integral type.

However it remains true that the response also contains a `ledger` object which itself has a duplicate `ledger_index` containing the numeric value as a string type.  This can not be changed for the current rippled API for backwards compatibility reasons.  However a future ("versioned") API may change this aspect.
