### ISSUE TITLE
Where is clock_type defined?

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2340]
https://github.com/ripple/rippled/blob/develop/src/ripple/resource/impl/Import.h#L44 refers to a "clock_type" and there are several different variables in the code base with that name. The file is missing an import for this type and I'm not sure which one should be used.

**Comment by scottschurr** [comment]
Hi @MarkusTeufelberger.  I'm pretty sure the `clock_type` that you want is this one: https://github.com/ripple/rippled/blob/develop/src/ripple/resource/impl/Entry.h#L33.  That is defined in the `Resource` namespace which also encloses the definition of `struct Import`.

**Comment by MarkusTeufelberger** [comment]
Great, thanks! That's another missing import case solved then. :-)

**Comment by MarkusTeufelberger** [comment]
Closing this, thanks for the answer.
