### ISSUE TITLE
Help me please - noNetwork, error_code" : 17, error_message" : InsufficientNetworkMode

### ISSUE THREAD

**Issue by lambda2003** [ripple/rippled#2349]
I tried to get my account_info but I got below error.
rippled account_info rww9KRNZ7mEHNAXEeLdVreiuk4bimtmbiS
{
   "id" : 1,
   "result" : {
      "error" : "noNetwork",
      "error_code" : 17,
      "error_message" : "InsufficientNetworkMode",
      "request" : {
         "account" : "rww9KRNZ7mEHNAXEeLdVreiuk4bimtmbiS",
         "command" : "account_info"
      },
      "status" : "error"
   }
}

Here is my server_info
"id" : 1,
   "result" : {
      "info" : {
         "build_version" : "0.80.1",
         "closed_ledger" : {
            "age" : 14,
            "base_fee_xrp" : 1e-05,
            "hash" : "CA187376DA6D43CE2F6F160E3EFB533729A5DF7E351D30C87DEBC875B1154FAC",
            "reserve_base_xrp" : 20,
            "reserve_inc_xrp" : 5,
            "seq" : 36032354
         },
         "complete_ledgers" : "empty",
         "hostid" : "ip-10-0-10-56",
         "io_latency_ms" : 1,
         "last_close" : {
            "converge_time_s" : 1.999,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "untrustedValidation",
                  "per_second" : 1
               },
               {
                  "job_type" : "untrustedProposal",
                  "per_second" : 30
               },
               {
                  "avg_time" : 19,
                  "job_type" : "ledgerData",
                  "peak_time" : 117
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "job_type" : "writeObjects",
                  "per_second" : 141
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 390
               },
               {
                  "job_type" : "SyncReadNode",
                  "per_second" : 167
               },
               {
                  "job_type" : "AsyncReadNode",
                  "per_second" : 1655
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 160
               }
            ],
            "threads" : 6
         },
         "load_factor" : 1,
         "network_ledger" : "waiting",
         "peers" : 10,
         "pubkey_node" : "n9LFhRMkzemDMULAANicF7Bp9g2earNGAnrciEjJt6BB7b8ajHsn",
         "pubkey_validator" : "nHBX3ipdipAsp1HwSFjQr7AXVVx1Z6vByD7ckWKqvwbdCWb6V1JH",
         "published_ledger" : "none",
         "server_state" : "connected",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "694891241",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "1196517",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : 0
            }
         },
         "uptime" : 696,
         "validation_quorum" : 4,
         "validator_list_expires" : "never"
      },
      "status" : "success"
   }
}

Any help please??

**Comment by wilsonianb** [comment]
Hi @lambda2003 
The keys for Ripple-operated validators were recently changed.
You can find instructions for updating your rippled configuration here:
https://ripple.com/dev-blog/reminder-rippled-version-0-81-0-validator-key-replacement/

**Comment by lambda2003** [comment]
Thank you. Let me check. :)
