### ISSUE TITLE
account_objects can't filter by checks

### ISSUE THREAD

**Issue by mDuo13** [ripple/rippled#2350]
The `account_objects` API method's `type` field lets you get only objects of a specific type, but it looks like the Checks amendment (PR #2245) doesn't add checks to the list of types you can filter by:

https://github.com/ripple/rippled/blob/develop/src/ripple/rpc/impl/RPCHelpers.cpp#L668-L687

As a result, doing `account_objects` with `"type": "check"` has no effect; non-check objects get returned alongside checks.

**Comment by scottschurr** [comment]
Great catch, @mDuo13.  Thanks.
