### ISSUE TITLE
[enhancement] tfBuy flag on offers

### ISSUE THREAD

**Issue by tuloski** [ripple/rippled#2361]
Why is there a tfSell flag for OfferCreate but not a tfBuy flag, where it tries to get the complete TakerPays, and gets whatever TakerGets the market can offer?

**Comment by nbougalis** [comment]
How exactly is that different than the way offers currently operate? If there's a distinction, I'm missing it.

**Comment by tuloski** [comment]
Maybe it is just my trip, but this is how I understood tfSell:

Example: 
- My offer is TakerGets: 1BTC, TakerPays: 10000USD. On the market there is only an offer that gives 9000USD per BTC.
- The tfSell basically is for someone that want to sell (sort of market trade), so even if my quality was 1:10000 it will accept the 1:9000 offer in the market, making me get only 9000 USD (sell at all cost 1BTC! with whatever quality it finds).

Now imagine I want to obtain exactly 10000 USD at all costs (at market price). I could make an offer again TakerGets 1BTC, TakerPays: 10000 USD, but I can spend more than 1BTC, so with tfBuy flag my transaction is allowed to use more than 1BTC (if I have them of course) to obtain the 10000 USD.

But this is only my interpretation and I think the documentation has a flaw since it says "even if it means obtaining more than the TakerPays amount in exchange." when it should be "obtaining less".

**Comment by tuloski** [comment]
Edited example because also for tfBuy the quality has to be lower than the quality of my offer.

**Comment by nbougalis** [comment]
If I understand this right, I’m _personally_ opposes to this.

I am wary of a flag that basically allows you to place an offer that’s the equivalent of King Richard proclaiming “MY KINGDOM FOR A HORSE!”

**Comment by intelliot** [comment]
@tuloski I think @ximinez 's answer is correct but just to elaborate on the original question:

> Why is there a tfSell flag for OfferCreate but not a tfBuy flag, where it tries to get the complete TakerPays, and gets whatever TakerGets the market can offer?

This is not what tfSell does. Rather, the tfSell flag indicates that the offer should behave like a "sell" order: the TakerGets amount is the amount that you want to sell. The opposite ("tfBuy"?) would be the default behavior, where the TakerPays amount is the amount you want to buy.

In any case, none of this is related to market trades (or market orders). As described above, you can just place a generous offer in order to effectively get a market order.

**Comment by intelliot** [comment]
Just for reference, here's the [documentation for OfferCreate](https://ripple.com/build/transactions/#offer-preference).

**Comment by tuloski** [comment]
@all: thanks for the explanation. I was living with a wrong assumption on how offer as taker work (I did mainly maker).

About this:
> If tfSell is NOT set, then your offer is saying, "I want to get 10000USD. I am willing to give up up to 1BTC for it." If an existing offer has TakerGets: 20000USD and TakerPays: 1BTC, you will get your 10000USD and be left with 0.5BTC

I was thinking that in that case I would pay the whole 1BTC and get the 20000 USD, while it requires the tfSell flag for that oO.

**Comment by tuloski** [comment]
@nbougalis that is what most exchanges call market order, and yeah I'm also against it because you don't have control on the quality and how much you'll pay, but for a liquid market sometimes it's easier and useful.
