### ISSUE TITLE
RippleCalc:WRN advanceNode: PAST INTERNAL ERROR REVERSE: OFFER NON-POSITIVE: node.saTakerPays=0/XRP node.saTakerGets=0/JPY/rB3gZey7VWHYRqJHLoHDEJXJ2pEPNieKiS

### ISSUE THREAD

**Issue by Amitdangwal007** [ripple/rippled#2365]
I am getting this issue while running the ripple node. I have to use node for crypto currency exchange so i have to install full node on my server. This is my conf file
[server]
port_rpc_admin_local
port_peer
port_ws_admin_local
#port_ws_public
#ssl_key = /etc/ssl/private/server.key
#ssl_cert = /etc/ssl/certs/server.crt

[port_rpc_admin_local]
port = 5005
ip = 127.0.0.1
admin = 127.0.0.1
protocol = http

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws

#[port_ws_public]
#port = 5005
#ip = 127.0.0.1
#protocol = wss

#-------------------------------------------------------------------------------

[node_size]
medium

[node_db]
type=RocksDB
path=/externaldevice/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=2000
advisory_delete=0

[database_path]
/externaldevice/db/

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
r.ripple.com 51235

[validators]
n949f75evCHwgyP4fPVgaHqNHxUVN15PsJEZ3B3HnXPcPjcZAoy7    RL1
n9MD5h24qrQqiyBC8aeqqCWvpiBiYQ3jxSr91uiDvmrkyHRdYLUj    RL2
n9L81uNCaPgtUJfaHh89gmdvXKAmSt5Gdsw2g1iPWaPkAHW5Nm4C    RL3
n9KiYM9CgngLvtRCQHZwgC2gjpdaZcCcbt3VboxiNFcKuwFVujzS    RL4
n9LdgEtkmGB9E2h3K4Vp7iGUaKuq23Zr32ehxiU8FWY7xoxbWTSA    RL5

[validation_quorum]
3

[validation_seed]
ssdecohJMDPFuUPDkmG1w4objZyp4

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
1

[fetch_depth]
full

This is output of server_info

{
   "id" : 1,
   "result" : {
      "info" : {
         "build_version" : "0.81.0",
         "closed_ledger" : {
            "age" : 6,
            "base_fee_xrp" : 1e-05,
            "hash" : "2B180A3916F499D19795666BA1D1A4B6A2E297021C05274D17C03AEAD7573B14",
            "reserve_base_xrp" : 20,
            "reserve_inc_xrp" : 5,
            "seq" : 36263639
         },
         "complete_ledgers" : "empty",
         "hostid" : "ip-172-31-46-9",
         "io_latency_ms" : 1,
         "last_close" : {
            "converge_time_s" : 1.999,
            "proposers" : 7
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "ledgerRequest",
                  "per_second" : 5
               },
               {
                  "job_type" : "untrustedProposal",
                  "peak_time" : 1,
                  "per_second" : 35
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "job_type" : "transaction",
                  "peak_time" : 3,
                  "per_second" : 17
               },
               {
                  "job_type" : "batch",
                  "peak_time" : 8
               },
               {
                  "job_type" : "fetchTxnData",
                  "peak_time" : 2,
                  "per_second" : 4
               },
               {
                  "job_type" : "writeObjects",
                  "peak_time" : 2,
                  "per_second" : 1
               },
               {
                  "job_type" : "trustedProposal",
                  "per_second" : 2
               },
               {
                  "job_type" : "peerCommand",
                  "peak_time" : 1,
                  "per_second" : 838
               },
               {
                  "job_type" : "processTransaction",
                  "per_second" : 8
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 280
               }
            ],
            "threads" : 4
         },
         "load_factor" : 1,
         "peers" : 17,
         "pubkey_node" : "n9K9YqgJdfJbZGyv52puDQ2ULKUyD2mp5CCtGKvoLMjnGvY3zDbD",
         "pubkey_validator" : "n9KHn8NfbBsZV5q8bLfS72XyGqwFt5mgoPbcTV4c6qKiuPTAtXYk",
         "published_ledger" : "none",
         "server_state" : "proposing",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "113093667",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "1200718",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "97041180",
               "transitions" : 1
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "tracking" : {
               "duration_us" : "1",
               "transitions" : 1
            }
         },
         "uptime" : 212,
         "validation_quorum" : 10,
         "validator_list_expires" : "2018-Feb-07 00:00:00"
      },
      "status" : "success"
   }
}

**Comment by seelabs** [comment]
@Amitdangwal007 Thank you for the report. The warning is complaining about an offer on that books that should have already been removed (it has zero input and zero output). The offer will not interfere with other transactions and will be removed by the next successful transaction that encounters the offer. You can safely ignore this warning.

I've made a note that this warning came up. Thanks again for the report.

**Comment by Amitdangwal007** [comment]
Thank you alot
I want to know that the node is properly synchronizing with the full node. It is showing server status proposing. How to detect how much synchronizing is done or progress, anything??
