### ISSUE TITLE
Sharding on forked ledgers is broken before ledger 32570

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2379]
https://github.com/ripple/rippled/blob/eaff9a0e6aec0ad077f118501791c7684debcfd5/src/ripple/nodestore/Types.h#L53

This variable prevents rippled from storing pre-32570 ledgers in a shard database. This is likely due to the unavailable ledgers from late 2012 on XRPL, but not a specific limitation to rippled in general. Please make this setting configurable instead of hard-coding it.

**Comment by nbougalis** [comment]
We will sort this out. Thanks for pointing it out.

**Comment by miguelportilla** [comment]
@MarkusTeufelberger thanks for reporting this. I've addressed the issue here: https://github.com/ripple/rippled/pull/2410

**Comment by MarkusTeufelberger** [comment]
Thanks.

I'm not so sure if it is a good strategy to compile the default of 32570 into the software and require a setting to change it instead of the other way around... but that's up to you.
