### ISSUE TITLE
account_tx doesnt return data on my node in testnet

### ISSUE THREAD

**Issue by rhaps107** [ripple/rippled#2391]
requesting account_tx with: 
address rU28T5aeXcDCup9eZH2aBWkb1wyqEqYgKV
forward true

https://s.altnet.rippletest.net:51234 returns 6 txs

my node response:
```{"result":{"account":"rU28T5aeXcDCup9eZH2aBWkb1wyqEqYgKV","ledger_index_max":6759348,"ledger_index_min":6756959,"limit":0,"status":"success","transactions":[]}}```

**Comment by ximinez** [comment]
Check which ledgers those transactions are in (you can look for the `ledger_index` field in the results). Your node only has ledgers 6756959-6759348. If all of those transactions are outside that range (specifically before 6759348), you're node is not going to have them. Some of the nodes on the altnet have older ledgers, so you can wait for yours to backfill, BUT note that the altnet nodes intentionally do not keep a lot of history, so I can't make any promises. (This is not the case on the production network, where there are several "full history" nodes that serve old ledgers.)

**Comment by rhaps107** [comment]
@ximinez i started my node about 3 weeks ago. Why there is no history transaction on it? How to download it?

**Comment by ximinez** [comment]
It comes down to how you've got the node configured. By default, you're going to have a decent amount of history, but not everything. You might want to look at your settings for `online_delete`, `advisory_delete`, and `ledger_history`. If you make changes, you'll need to restart.

Another possibility is that your settings are fine, but your node does not have the extra bandwidth and/or processing power to get ahead enough to request historical ledgers so it can backfill.

**Comment by rhaps107** [comment]
@ximinez 
i set 
```[ledger_history]
full

...
advisory_delete=0
online_delete=0```

also tried online_delete=100000000
but looks like now delete everything but last ledger.
how to disable data deleting?
i need full history node.

**Comment by ximinez** [comment]
If you want full history, your best bet is to remove or comment out `online_delete` entirely
