### ISSUE TITLE
who determine the Base reserve and ower reserve?Does it change in the future?

### ISSUE THREAD

**Issue by passionofvc** [ripple/rippled#2395]
I test account for multisig sign tx,  the account has 8 signer list
and I need below XRP(80.5 USD )  to maintain the account if I do the same in the main net.
So I think it is very so high,  this may stop many XRP users  from using multiple signatures function
and finally there is a risk of lowering security of XRP.
who determine the Base reserve and ower reserve?Does it change in the future?
Does the ripple protocol would lower the high cost in the XRP multi-sign?

```
total reserve = 70 XRP = 80.5 USD (suppose 1XRP/1.15USD)
base reserve  = 20 XRP
owner reserve = (10 * 5) = 50 XRP 

leger objects     = 10
siger_list object = 2
signer count      = 8

```

**Comment by nbougalis** [comment]
Reserves are voted on by validators. Admins can configure their validators to vote for higher or lower reserves, and the network attempts to reach a consensus on what the reserves ought to be.

**Comment by passionofvc** [comment]
hi @nbougalis 
I know the cost is determined by the network  consensus, the majority validator run by 
ripple lab, so I think the the ripple lab control the network cost.
