### ISSUE TITLE
Filipino [Tagalog Localization][REQUEST]

### ISSUE THREAD

**Issue by cordeta** [ripple/rippled#2398]
Hi 

I would like to offer free localization of your README and LICENSE FILE. One thing that i would like to request is a repository of Translation/tl_PH so that i could work efficiently.

I am a ripple holder also . This proposed contribution would help you reach Filipino Investors

**Comment by nbougalis** [comment]
Thanks for offering to localize the content. While I do appreciate it, and would be supportive of this, I do not know if it is practical, especially considering that the README file can and does change, and translations might become out of date.

Still, if you are interested in doing this, feel free to fork the repo, and create whatever directories you think you need for this work. We will review the PR as a whole when you submit it.
