### ISSUE TITLE
Is outputDebugString() actually used?

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2399]
Function in question: `outputDebugString()`, which seems to be only being used here: https://github.com/ripple/rippled/blob/87742a5e6c5093bfd4ddad88b858d722a91738cd/src/ripple/beast/insight/impl/StatsDCollector.cpp#L343-L353

I assume it can be safely removed alltogether and the string might be printable to stderr with a different mechanism. Maybe it is not even actually used anyways? https://github.com/ripple/rippled/blob/87742a5e6c5093bfd4ddad88b858d722a91738cd/src/ripple/beast/insight/impl/StatsDCollector.cpp#L39-L41 looks like it... (this is the only place I could find this variable being used).

That would only leave `getComputerName()` in SystemStats which is also only used one single time in `server_info` calls by admins. Maybe removing the `hostid` field (after all, there's `pubkey_node` as unique ID) from `server_info` might be a way forward? It is not very useful for end users and I don't think for admins either.

**Comment by mellery451** [comment]
Good suggestions - `getComputerName()` has been proposed for removal/replacement by @scottschurr, so that's on my list for sure. I'll investigate `outputDebugString` as well.

**Comment by mellery451** [comment]
https://github.com/ripple/rippled/pull/2414

**Comment by JoeLoser** [comment]
@mellery451 Mind closing this issue then since your PR got merged?
