### ISSUE TITLE
#2388 broke Test.py

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2401]
Specifically https://github.com/ripple/rippled/blob/6230204e425f6aef6ec1c0def0bdd1257e1c4c7f/Builds/Test.py#L307-L309
does not initialize `testjobs` unless it appears in `ARGS`.

Pinging @ximinez

**Comment by ximinez** [comment]
Sorry about that oversight. Thank you for submitting a fix.

**Comment by MarkusTeufelberger** [comment]
obsolete
