### ISSUE TITLE
src/ripple/beast/core/core.unity.cpp is used in nounity builds

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2405]
Maybe it is just misnamed a bit, but all in all it's a cpp file that's including a bunch of other cpp files and so I'd say it probably shouldn't be used in nounity builds.

**Comment by mellery451** [comment]
I agree. I did try to unroll this one as part of https://github.com/ripple/rippled/pull/2376, but it got to be a bit more than I wanted for that PR. I'll add this issue to my list. Thanks.

**Comment by MarkusTeufelberger** [comment]
Another weird case is `src/ripple/beast/unity/beast_hash_unity.cpp` which also seems to include one of the few .c files in the ripple subfolder into a .cpp file - but then again apparently it has a C++ header file with namespace and everything. This really messes with trying to compile this separately...

**Comment by MarkusTeufelberger** [comment]
As a side note, there are several xxhash implementations in this code base...
