### ISSUE TITLE
Rippled in prod network validation doesnt work, history is not loaded

### ISSUE THREAD

**Issue by rhaps107** [ripple/rippled#2411]
Set up node according to
https://ripple.com/build/rippled-setup/#installation-on-ubuntu-with-alien

in rippled.cfg set
[history]
full
...
online_delete=1000000
also set up validation https://ripple.com/build/rippled-setup/#validator-setup:
generated validator keys.

Then i check `/opt/ripple/bin/rippled server_info`

question 1.
i get `"complete_ledgers" : "empty",` in response. Node doesnt load blocks? Why?

question 2.
i got `pubkey_validator` different to /opt/ripple/bin/validator-keys create_token output. Why?

**Comment by MarkusTeufelberger** [comment]
If you actually want full history, you need to remove the online_delete setting completely, otherwise you'll waste bandwidth and time without ever getting full history.

Question 1: Impossible to answer with the information given.

Question 2: See answer to question 1.

**Comment by syeduali93** [comment]
I believe this is the sharding feature?

**Comment by nbougalis** [comment]
@rhaps107: as @MarkusTeufelberger said, it's impossible to answer your questions with the information provided. I am going to close this issue, but if you are still having problems, please feel free to reopen and provide additional information.
