### ISSUE TITLE
RocksDB in example config

### ISSUE THREAD

**Issue by sublimator** [ripple/rippled#2416]
https://github.com/ripple/rippled/blob/develop/doc/rippled-example.cfg#L1068

Why not nudb ?

**Comment by sublimator** [comment]
![image](https://user-images.githubusercontent.com/525211/36826476-2e64ddd4-1d40-11e8-8eab-8b78f86892be.png)

Hrmmmm

**Comment by rgrz** [comment]
My guess is nudb only works in SSD drives. While RockDB can work on spinning disk and SSDs.

**Comment by sublimator** [comment]
Thanks, I think you're right :)

Who uses rot* disks these days?

**Comment by yxxyun** [comment]
https://github.com/ripple/ripple-dev-portal/pull/307/files

> RocksDB vs NuDB
RocksDB requires approximately one-third less disk storage than NuDB and provides a corresponding improvement in I/O latency. However, this comes at a cost of increased memory utilization as storage size grows. NuDB, on the other hand, has nearly constant performance and memory footprint regardless of [storage](#storage).

`rippled` servers that operate as validators keep only a few days' worth of data or less. Ripple recommends using RocksDB for validators. For all other uses, Ripple recommends using NuDB for the Ledger Store.
