### ISSUE TITLE
Use a TLS cipher suite

### ISSUE THREAD

**Issue by donovanhide** [ripple/rippled#242]
The current cipher suite yields a slightly unfortunate ADH cipher and ties Go users to C openssl bindings:

https://github.com/ripple/rippled/blob/develop/src/ripple_core/functional/Config.h#L43

There was mention of moving to 'C4-SHA:HIGH:!ADH' which might help. Go has TLS 1.2 in its standard library and I could dump the openssl bindings if one of these suites was chosen:

http://golang.org/src/pkg/crypto/tls/cipher_suites.go#L256

It seems like this might mean distributing certificates however? My SSL/TLS knowledge isn't the best, although I have hacked together the session cookie verification and can fully operate on the peer network currently, but would really like to drop the openssl dependency...

**Comment by vinniefalco** [comment]
This is obsolete, given the numerous changes we've made to the TLS cipher suite to account for CVEs.
