### ISSUE TITLE
rippled report me telINSUF_FEE_P even the transaction validate in ledger.

### ISSUE THREAD

**Issue by passionofvc** [ripple/rippled#2427]
rippled report me telINSUF_FEE_P in mainnet even the transaction validate in ledger,

```
[
    engine_result='telINSUF_FEE_P', engine_result_code=-394, engine_result_message='Fee insufficient'
]
```

according to 

[](https://ripple.com/build/transactions/
https://ripple.com/build/reliable-transaction-submission/
)

the [tel=transaction engine local error] mean client must to resubmit the tx,
but in fact in mainnet I get [engine_result_code=-394] and somewhile the tx go into validated ledger.
I do not resubmit anything, the tx is finally successed,
this gave me confusion,
how would I to do when engine_result_code is not 0?
Do I to resubmit the  engine_result is  ter/tec/tel?

```
Category       Prefix     Description
Local error    tel        The rippled server had an error due to local conditions, such as high load. You may get a different response if you resubmit to a different server or at a different time.
```

**Comment by ximinez** [comment]
The rippled node itself acts like a client in this case, and will retry most failed transactions a few times before dropping them entirely. 

From https://ripple.com/build/reliable-transaction-submission/

> APIs may return provisional results based on the result of applying candidate transactions to the current, in-progress ledger. Applications must not confuse these with the final, immutable, results of a transaction. Immutable results are found only in validated ledgers. Applications may need to query the status of a transaction repeatedly, until the ledger containing the transaction results is validated.

The most important word here is "provisional". Any provisional result, both failures and successes, can change after the transaction is submitted to the network (even a `tem` malformed transaction can later succeed if a later amendment learns how to process a previously illegal field in that transaction before the transaction expires or is replaced).

**Comment by passionofvc** [comment]
hi @ximinez 
I don not know how to process when rippled return result code 
to client when engine_result_code is not 0,
if rippled know the tx is "provisional", why rippled would not return client success engine_result_code=0?
Does this mean client must not rely on engine_result_code but also to polling the all the tx status
until tx is final in validate ledger.

I do not understand why the rippled engine_result_code is inconsistent for the "provisional" tx state.

**Comment by ximinez** [comment]
> Does this mean client must not rely on engine_result_code but also to polling the all the tx status
until tx is final in validate ledger.

**Comment by gituser** [comment]
Just stumbled upon this and due this error we've made double payments, because there is no clarification that rippled will automatically re-send this failed transaction, even though on submission we've used:

`'fail_hard':true`

Why rippled is acting like this?

**Comment by yxxyun** [comment]
Did you set LastLedgerSequence?

**Comment by gituser** [comment]
> Did you set LastLedgerSequence?

No, I did not. I was relying on rippled automatic `LastLedgerSequence`, it still has nothing to do with the issue.

`hard_fail` implies that the transaction shouldn't be re-submitted if it fails with some code like `telINSUF_FEE_P`.

**Comment by MarkusTeufelberger** [comment]
The transaction could have reached a different server already that doesn't know or care about the fact that you submitted to your server with `hard_fail`.

Please read and follow the steps in https://developers.ripple.com/reliable-transaction-submission.html to reliably submit transactions.

**Comment by gituser** [comment]
@MarkusTeufelberger it's super complicated scheme.

We only send transaction once and check for return codes from rippled and then retry it manually.

Automated re-sending might be full of bugs.

And, also regarding `fail_hard` I've found this issue: https://github.com/ripple/rippled/issues/2847

So it's clearly a documentation issue and it should be fixed ASAP as it's not working as described at all.

**Comment by passionofvc** [comment]
I have another problem
sometime submit tx to s1.ripple.com server use below bash
the ['engine_result='tefALREADY', engine_result_code=-198, engine_result_message='The exact transaction was already in this ledger.']
happened, I only post one time, why it show me the transaction also post twice?
```
host_url=https://s1.ripple.com:51234
curl -s -X POST "$host_url" -d @- <<-END
{
    "method": "submit",
    "params": [
        {
            "tx_blob": "120000xxxxx..."
        }
    ]
}
END
```
