### ISSUE TITLE
NuDB with SHAMAPV2 enabled

### ISSUE THREAD

**Issue by luleigreat** [ripple/rippled#2445]
I deployed a chain on linux with SHAMAPV2 enabled and the node_db type is NuDB. Ripple version is 0.80.1.
But there is always a storage problem: when I open a new node to synchronize data，the ledger cannot be fetched if there are transactions on it. It reports:"nodeobject codec v2: short inner node size: " .
I don't know why ,is SHAMAPV2 not compatible with NuDB ？

**Comment by sublimator** [comment]
Are you deploying your own alternate net?

**Comment by luleigreat** [comment]
You can think that I was deploying an alternate net, but that's not the key. The problem is I don't know the compatibility of SHAMAPV2, is this feature conflicts with NuDB ? Is there problem if I use RocksDB and SHAMAPV2？

**Comment by sublimator** [comment]
Well, I don't know, but SHAMAPV2 isn't deployed on the main net :)

**Comment by luleigreat** [comment]
I see, thanks @sublimator 
I launched a node to connect the main net, and use "feature" command to look up the status of new feature, I found that none of the new features are enabled, I wonder why.

**Comment by sublimator** [comment]
No idea, many on the rippled team are quite conservative, with decades of
experience. Probably not rushing into anything with all that money at stake.

Move fast and ... break things? :)

**Comment by luleigreat** [comment]
`    case 5: // compressed v2 inner node
    {
        auto const hs =
            field<std::uint16_t>::size; // Mask size
        if (in_size < hs + 65)
            Throw<std::runtime_error> (
                "nodeobject codec v2: short inner node size: "
                + std::string("size = ") + std::to_string(in_size)
                + " hs = " + std::to_string(hs));
`
It seems the condition is not right, it assumes there are at least two txs, if there is only one tx in this ledger,it will throw an exception, and process dumped because there is no try-catch. If I change 65 to 33,the code runs well ,and I can get the ledger successfully.

**Comment by luleigreat** [comment]
That's ok, thanks @sublimator .
