### ISSUE TITLE
Configuration for OVH VPS SSD 3

### ISSUE THREAD

**Issue by codedot** [ripple/rippled#2448]
After switching to version 0.90.0, `rippled` with its default configuration takes too long to sync, consumes all available RAM, increases load average up to 4, then restarts.

What `rippled` configuration is recommended for [OVH VPS SSD 3][1]?

I want to limit `rippled` to use strictly <4 GB RAM and <1 load average.

[1]: https://www.ovh.com/world/vps/vps-ssd.xml

**Comment by miguelportilla** [comment]
Try setting `node_size` to `tiny`, `ledger_history` to `256` and `online_delete` to `256`

**Comment by codedot** [comment]
I already did. Behavior is the same.

**Comment by nbougalis** [comment]
I am going to close this issue at this time. There is work underway to improve/reduce the resource utilization of `rippled` which may be relevant to your request.

**Comment by nbougalis** [comment]
This issue asked for a configuration for a recommend configuration for [OVH VPS SSD 3](https://www.ovh.com/world/vps/vps-ssd.xml). You were provided with some settings, and you replied that the behavior is the same. For more on capacity planning and recommended hardware, check out https://developers.ripple.com/capacity-planning.html.

Your constraint is that you "want to limit `rippled` to use strictly <4 GB RAM and <1 load average" and I simply don't believe that running `rippled` against the main network under such a tightly constrained system is practical today and I doubt it will be in the future.

I casually mentioned that there is worth underway to improve resource utilization, but let's be clear, _nothing_ we do will make it possible to run `rippled` on a system that has about as much RAM as a present-day cellphone. 

I'm happy to reopen this issue if you feel that are follow-up questions that are relevant and can be answered. But, as it stands, I'm not sure how else this issue can be resolved.

**Comment by mDuo13** [comment]
I think it is not possible to run `rippled` on the production network with ≤4GB of RAM, and the stated system requirements are 8+ GB of RAM. Closing.
