### ISSUE TITLE
src/ripple/overlay/README.md incorrect

### ISSUE THREAD

**Issue by codedot** [ripple/rippled#2449]
The peer handshake protocol [documentation][3] provided in the `src/ripple/overlay/README.md` file is currently inconsistent with implementation. In particular, the example HTTP request
```
GET / HTTP/1.1
User-Agent: rippled-0.27.0
Local-Address: 192.168.0.101:8421
Upgrade: RTXP/1.2, RTXP/1.3
Connection: Upgrade
Connect-As: Leaf, Peer
Accept-Encoding: identity, zlib, snappy
Public-Key: aBRoQibi2jpDofohooFuzZi9nEzKw9Zdfc4ExVNmuXHaJpSPh8uJ
Session-Signature: 71ED064155FFADFA38782C5E0158CB26
```
provided in documentation is very different from what `rippled` actually sends:
```
GET / HTTP/1.1
User-Agent: rippled-0.81.0
Upgrade: RTXP/1.2
Connection: Upgrade
Connect-As: Peer
Crawl: public
Public-Key: n9JkLKbdx7nK5DAVEVt12tfuPTjRyKSzgHcL5sZt1MEZCys5anyA
Session-Signature: MEUCIQCB0sFjTi7EJOSHYNBm0r2wNy2CZ5GP1kG95fQWYSrgMwIgcPqEZsSXpIvX/DTA2fLeiBEHNpNODL1yIKGusx/cjLU=
Network-Time: 574447212
Closed-Ledger: dnh7rcZ4/OIOi0HrAWltMjtsK7+2ozvXJpDwO5shTzA=
Previous-Ledger: q4aKbP7sd5wv+EXArwCmQiWZhq9AwBl2p/hCtpGJNsc=
```
after exchanging the following `Finished` messages during TLS handshake (see #2413 for details):
```
<Buffer d9 84 67 bb 33 a4 92 e0 f8 b2 3c 3a>
<Buffer 1c 85 dd d7 0d e7 b3 61 9b cf 8c ae>
```
Since `Session-Signature` can be verified with the `Public-Key` and the above `Finished` messages using [this function][1], `Public-Key` is therefore a base-58-encoded value formed according to the [*Encodings*][2] article (type 28), which contradicts documentation:
```
* `Public-Key`

    This field value must be present, and contain a base 64 encoded value used
    as a server public key identifier.
```
Also, documentation is missing description of how exactly the `Session-Signature` field is formed, only vaguely referring to source code. Finally, the `Network-Time`, `Closed-Ledger`, and `Previous-Ledger` fields are not mentioned in documentation at all.

[1]: https://github.com/codedot/xmm/blob/a68f7fb10ca7768ffadb8d6258635f9335bf45a8/key.js#L59-L78
[2]: https://wiki.ripple.com/Encodings
[3]: https://github.com/ripple/rippled/blob/afd4b45036e90a46b4a104aff3f874454d3972c7/src/ripple/overlay/README.md

**Comment by nbougalis** [comment]
Thank you. We are working on improving the documentation of this particular section of the code.

**Comment by codedot** [comment]
Why is this issue closed? The documentation has not yet been corrected at all, the latest commit being still afd4b45 on Nov 9, 2016.

**Comment by nbougalis** [comment]
Touché. This issue should remain open until such time as the documentation is fixed. You may feel free to submit a pull request, if you're so inclined.

**Comment by MarkusTeufelberger** [comment]
See #3049

**Comment by nbougalis** [comment]
The documentation has been updated with #3049. I believe that this issue no longer applies. If you still feel it does, please create a new issue. Thanks. :vulcan_salute:
