### ISSUE TITLE
Validated ledger dropped

### ISSUE THREAD

**Issue by simaqiaoxi** [ripple/rippled#2452]
Hi there, we are running our own rippled node (synced to the mainnet) and run a separate process to monitor all incoming transactions. We only read validated ledgers but on occasion are seeing either 'missing' or 'unvalidated' ledgers.

We poll the ledger over RPC with params: { ledger_index: 'validated', transactions: false } and get ledger.ledger_index which we compare with our last ledger height.

If it's higher than our last processed height we fetch the ledger with params { ledger_index: ${ledger_idx_from_above}, transactions: true, expand: true }.

On occasion (few times a day), we receive either a lgrNotFound error (strange, but acceptable), or sometimes even ledgers which are a) not validated, and b) not closed. Not really understanding what's happening here as the same process just retrieved that ledger with ledger_index: 'validated'.

I assume these 'unvalidated' ledgers eventually became validated in their current state, but if not, thankfully we had an assert in there to double-check validated is true, as we were treating these results as validated & final.

Am I misunderstanding something fundamental or? 

**Config details**
online_delete=48000
advisory_delete=0

node_size=tiny
ledger_history=16
fetch_depth=128

**Node details:**
VPS hosted
ram=8gb, the rippled process generally sits on around 60% mem. 
monitoring shows no spikes in mem/cpu/network

**Comment by nbougalis** [comment]
Can you provide an example of a response with a ledger that's neither validated nor closed? Thanks

**Comment by simaqiaoxi** [comment]
Hi @nbougalis thanks for the quick response.

Here's a sample response from our error report I'm not sure whether the reporting tool we use has excluded fields other than 'ledger' or whether 'ledger' is the only field which was returned.

`{'ledger': {'closed': False, 'ledger_index': '37394755', 'parent_hash': '6A7B0A5824D085AB8E8EFAD5E1592A66B57DF7EEB8E4EECD65E782126A241E7F', 'seqNum': '37394755', 'transactions': [{'Account': 'rnt9HnGsrEwqpneD4XTbCXuvZxrM2c3EqA', 'Fee': '12', 'Flags': 2147483648, 'hash': '2E2F38173B30F0B4662A725F2348904ACEE37EDA1D48D856E693BD9E587423AF', 'LastLedgerSequence': 37394765, 'OfferSequence': 1654177, 'Sequence': 1654182, 'SigningPubKey': '0291D2EBF202C1F09DA301078ADD497797CD66CD5AA5AB667D0EB3B61FA600F54D', 'TransactionType': 'OfferCancel', 'TxnSignature': '3045022100FB96DC53BED99C5F9C7916EC60B6A7C162D88407CC7A2FEB63B1EF63BE5EE18C02206FC40C5D6100DB4B34C7300E9048BAB495DB919FD1DD88EB37CAFDEF40A34EBF'}]}}`

Please note this is after requesting via ledger_index: 37394755. ledger_index: 'validated' appears to always returns validated/closed ledgers. After retrieving the ledger_index from 'validated' and comparing to our existing count (in-memory) we send the second request immediately.

Cheers.
