### ISSUE TITLE
testnet node doesn't work

### ISSUE THREAD

**Issue by rhaps107** [ripple/rippled#2459]
curl -X POST -d '{ "method" : "ledger", "params" : [{"ledger":"current"}] }' https://s.altnet.rippletest.net:51234

{"result":{"error":"noNetwork","error_code":17,"error_message":"InsufficientNetworkMode","request":{"command":"ledger","ledger":"current"},"status":"error","warning":"load"}}

**Comment by passionofvc** [comment]
hi everyone,
does this problem fixed now?

**Comment by bachase** [comment]
Thanks for reporting. There is an issue with the validator list. I'll give an update when it is fixed, which should happen today.

**Comment by rhaps107** [comment]
@bachase thanks for replying

**Comment by bachase** [comment]
@rhaps107, it should be fixed. I'll close this issue, but please reopen if you are have any difficulties.

**Comment by JJNET** [comment]
Hi @bachase 

Thanks you for revival of TESTNET. I spent several hours to correct this problems.

I have a no one replying question :
https://github.com/ripple/ripple-lib/issues/874

=> My purpose is subscribing of my rippled's wallet account except other peer's accounts.
