### ISSUE TITLE
Account_tx method doesn't show transactions to self

### ISSUE THREAD

**Issue by mmitech** [ripple/rippled#2465]
We are trying to add Ripple to our App, so we went with the design where we use only one address account and give each user a tag to identify their transactions.

My issue is that when 2 users make a transaction where one is withdrawing using another user's tag to the same address (hotwallet, so basically an internal tx).  How do I identify this deposit if the account_tx method doesn't show it and if the tx return a "Transaction not found." error?

Example, the tx:
`{
  "result": {
    "engine_result": "temREDUNDANT",
    "engine_result_code": -276,
    "engine_result_message": "Sends same currency to self.",
    "status": "success",
    "tx_blob": "120000228000000024000000042EF50F92BD61400000000BED48A068400000000000000A7321031E2E212A9BBAE17970A1B3D62CB05F11F56822FC92B26B9260CB773E473A8B9B7446304402200207049C4494FF0A46764904A67A44430616DD82B158B5182E00480A8A91247502207D9A25107FD76BD04B486EAF7D9991F3377A6C12D032EDD0C97785AFE8313B1A81141338B774DD386DD3629921AA389B29322C4DBA6983141338B774DD386DD3629921AA389B29322C4DBA69",
    "tx_json": {
      "Account": "rpkd8PLVYBdr45XWNnphZtneppKtNoZP5R",
      "Amount": "200100000",
      "Destination": "rpkd8PLVYBdr45XWNnphZtneppKtNoZP5R",
      "DestinationTag": 4111438525,
      "Fee": "10",
      "Flags": 2147483648,
      "Sequence": 4,
      "SigningPubKey": "031E2E212A9BBAE17970A1B3D62CB05F11F56822FC92B26B9260CB773E473A8B9B",
      "TransactionType": "Payment",
      "TxnSignature": "304402200207049C4494FF0A46764904A67A44430616DD82B158B5182E00480A8A91247502207D9A25107FD76BD04B486EAF7D9991F3377A6C12D032EDD0C97785AFE8313B1A",
      "hash": "1B9DA1E0C0E73153A37276754EC8259388890B188A5666AFBB1E49364B3466DC"
    }
  }
}`

calling the tx method:

`{
  "result": {
    "error": "txnNotFound",
    "error_code": 29,
    "error_message": "Transaction not found.",
    "request": {
      "binary": false,
      "command": "tx",
      "transaction": "1B9DA1E0C0E73153A37276754EC8259388890B188A5666AFBB1E49364B3466DC"
    },
    "status": "error"
  }
}`

**Comment by MarkusTeufelberger** [comment]
Internal transactions are usually recorded off-ledger. Destination tags are not sub-accounts.

**Comment by mmitech** [comment]
OK, we will have a workaround for this.
