### ISSUE TITLE
Sum of accountState XRP balances differs from totalCoins

### ISSUE THREAD

**Issue by professorhantzen** [ripple/rippled#2474]
Would the correct way to do this be to sum the Balance fields from the AccountRoot nodes, the Amount fields from the Escrow nodes, and add in the PayChannel nodes somehow (either sum the Amount's, Balance's, or Amount minus Balance per node or something)?

Should this work or am I missing something?

When doing the above, my results are consistently ~65k XRP less than the totalCoins reported for any recent ledger. (The variation in summing PayChannel's differently appears minor by comparison.)  I've tried various ledgers going back a few months, and duplicated the parsing & addition on the raw json supplied by rippled in both node using bignumber.js, and bash using bc, with identical results.

**Comment by professorhantzen** [comment]
Also, this ~65k XRP discrepancy decreases over time. Over the past few months its gone down ~120 XRP, usually by some fraction of an XRP every 10k or 100k's of ledgers or so.

**Comment by sublimator** [comment]
In the early days there was a bug where XRP was destroyed, so you could be
seeing that.

As for the gradual drift, I'm not sure. I thought they checked invariants
related to that these days.

**Comment by professorhantzen** [comment]
Ok, interesting... I was sure this would be my error!

This makes me think there are/were floating points used in the rippled code where they shouldn't be.  Is there any reference for this bug?

If it is due to this, I wonder if it could make sense the shortfall is gradually disappearing, as complexity increases and the number of nodes in a given state gravitate toward a higher sum versus erroneous integer/floating point conversions that would have likely rounded down.

So, in principle what *is* the correct way to generate totalCoins from accountState?  How is it generated presently if not from that?  Is totalCoins just the previous totalCoins minus the new fees?

**Comment by sublimator** [comment]
It's actually tracked manually rather than being a function of the state
tree, and is really only supposed to be reduced by fees iirc. I suppose it
is just poorly done, and yeah, perhaps loses precision over time due to
rounding errors as well as the discrepancy bug.

**Comment by professorhantzen** [comment]
Manually?  I'm talking about the totalCoins/total_coins number here:

```
$ r ledger
Loading: "/etc/opt/ripple/rippled.cfg"
2018-Apr-09 07:03:34 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "result" : {
      "closed" : {
         "ledger" : {
            "accepted" : true,
            "account_hash" : "EB4CC88753E14FF900B43E0F27C1802F30405D63EE21087D614029EA3F211A55",
            "close_flags" : 0,
            "close_time" : 576572600,
            "close_time_human" : "2018-Apr-09 07:03:20",
            "close_time_resolution" : 10,
            "closed" : true,
            "hash" : "7566138ACDFDCB428A64EB847C04611A0020BA4F00AA3DC90BB4DD754C487282",
            "ledger_hash" : "7566138ACDFDCB428A64EB847C04611A0020BA4F00AA3DC90BB4DD754C487282",
            "ledger_index" : "37831772",
            "parent_close_time" : 576572591,
            "parent_hash" : "08E5E2A4857740BB66BDEBA312D9004F64A0F79CE687A14E22A632F1817CA321",
            "seqNum" : "37831772",
            "totalCoins" : "99992362016236441",
            "total_coins" : "99992362016236441",
            "transaction_hash" : "9AD56110989A99A35AFFF38F7E3E84E20BB3C8A949F7A87D27887C21790DA87C"
         }
      },
      "open" : {
         "ledger" : {
            "closed" : false,
            "ledger_index" : "37831773",
            "parent_hash" : "7566138ACDFDCB428A64EB847C04611A0020BA4F00AA3DC90BB4DD754C487282",
            "seqNum" : "37831773"
         }
      },
      "status" : "success"
   }
}
```

It changes every ledger.  You're telling me Ripple has some red-eyed monkey sweating over this on a Casio FX every three and half seconds?

**Comment by sublimator** [comment]
https://github.com/ripple/rippled/blob/cca574c9a9bb6f7fa416cf540fcf952cff7a14ce/src/ripple/app/tx/impl/Transactor.cpp#L723

Go down that rabbit hole ...

Basically, there's a total coins field in the ledger header ...

And with each transaction that field gets carried over to the new ledger
minus txn fees ...

So they don't actually look over the txn meta for actual changes, but
rather do very simple "manual" book keeping with a field and txn fees ...

**Comment by professorhantzen** [comment]
Ok - thanks!  So, [here in CashDiff.cpp](https://github.com/ripple/rippled/blob/1dbc5a57e6b0e90a9da0d6e56f2f5a99e6ac1d8c/src/ripple/ledger/impl/CashDiff.cpp). From skimming this, it looks like XRP is still being destroyed through rounding?

I get that totalCoins is just the previous totalCoins minus txn fees, though I'm still confused about the mechanism of the decreasing difference between that and the summed accountState balances.

If XRP is being rounded away constantly within the accountState and this is not tracked by totalCoins, shouldn't the difference *increase*?

Also, the amounts are confusing.  It appears that around 1-2 drops may be discarded here and there as edge-case transactions meet the criteria.  But the discrepancy appears to be on the move at a much higher rate than that would suggest.

**Comment by sublimator** [comment]
It could have changed. I haven't worked at ripple for 2 years now and
haven't been following along. Shrug.

It will probably require an amendment to fix it. Atm it's just an
approximation.

**Comment by scottschurr** [comment]
@professorhantzen I've not been following the conversation closely.  Only regarding the file [CashDiff.cpp](https://github.com/ripple/rippled/blob/develop/src/ripple/ledger/impl/CashDiff.cpp), you may be misinterpreting the point of that file.  It is used to look at the results of different ways of computing offer crossing.  One computation is done by [Taker.cpp](https://github.com/ripple/rippled/blob/develop/src/ripple/app/tx/impl/Taker.cpp), and the other by [FlowCross](https://github.com/ripple/rippled/blob/develop/src/ripple/app/tx/impl/CreateOffer.cpp#L639-L810).  At any rate, [CashDiff.cpp](https://github.com/ripple/rippled/blob/develop/src/ripple/ledger/impl/CashDiff.cpp) is not used to look a the total remaining XRP or to calculate anything that goes into the ledger.  It is a comparison tool only.

**Comment by scottschurr** [comment]
@professorhantzen CashDiff is only used here: https://github.com/ripple/rippled/blob/develop/src/ripple/app/tx/impl/CreateOffer.cpp#L836-L891.  The end result of executing CashDiff is the addition of warnings to the log.  That generation of warnings only occurs if `featureCompareFlowV1V2` is enabled (see https://github.com/ripple/rippled/blob/develop/src/ripple/app/paths/RippleCalc.cpp#L72-L223).  That particular `feature` is not on an amendment, so it can only be enabled using a local configuration file.  I don't believe it will take you in the direction you are currently intending to go.

**Comment by professorhantzen** [comment]
@scottschurr Alright, thank you!

**Comment by MarkusTeufelberger** [comment]
According to https://ripple.com/build/ledger-format/#header-format:

> The total number of drops of XRP owned by accounts in the ledger. This omits XRP that has been destroyed by transaction fees. The actual amount of XRP in circulation is lower because some accounts are "black holes" whose keys are not known by anyone.

@mDuo13 - could you clarify what this number (now that more ways than AccountRoot nodes exist) is supposed to represent exactly and if this potentially not being equal to the sum of all XRP in AccountState objects is a bug or just a problem with documentation?

**Comment by professorhantzen** [comment]
Thanks for looking into this.  It would be great if this was my error.  To be sure, can we get clear on exactly what should be summed?

As described in the original post, I am summing the Balance fields from the AccountRoot nodes, the Escrow Amount's, and the PayChannel Amounts, and continue to assume this is sufficient as I haven't been corrected.  The PayChannel's I'm sure I'm doing wrong - though it doesn't appear to be a large enough error to affect the main issue so I've ignored it thus far (though it'd be great to also have this clarified).

The main thing: should I also be summing *anything else* from any other node types?

Taking ledger 36300000, and running a simple node script to count node types, I get the following node types and their count:

```
{ RippleState: 708941,
  AccountRoot: 1121782,
  DirectoryNode: 383298,
  SignerList: 1371,
  Offer: 71816,
  PayChannel: 143,
  LedgerHashes: 555,
  Escrow: 171,
  FeeSettings: 1,
  Amendments: 1 }
```

With my present code, summing for this ledger I get:

```
AccountRoot Escrow PayChannel
46092524441133161 53900040602224844 950130140
Total
99992565993488145
node count
1121782 171 143
```

The last three numbers are a count of how many nodes were summed for each type (matching the node count listed above and serving as a rudimentary check).

My rippled reports a totalCoins of 99992631231694936 drops for that ledger (`$ rippled ledger 36300000`).  This is a 65238.206791 XRP difference.

The code that generates the above count is a (nasty) bash script I threw together in a couple of minutes initially, however it turns out to work surprisingly well. After this issue became more... "interesting", I duplicated the scripts functionality robustly in node.js using bignumber.js - and produced identical results.  I continue using the bash script however as its much faster to process the same data.  (Grep + bc for summing integers from json actually seems to be pretty efficient.)

Here's the script:

```
#!/bin/bash/
theASFile=$1
accounts_sum=`grep -B4 AccountRoot $theASFile | grep Balance | cut -f2 -d ':' | tr -d '"' | tr -d ',' | paste -sd+ | bc`
escrow_sum=`grep -B6 Escrow $theASFile | grep Amount | cut -f2 -d ':' | tr -d '"' | tr -d ',' | paste -sd+ | bc`
paychannel_sum=`grep -B5 PayChannel $theASFile | grep Amount | cut -f2 -d ':' | tr -d '"' | tr -d ',' | paste -sd+ | bc`
echo 'AccountRoot Escrow PayChannel'
echo $accounts_sum $escrow_sum $paychannel_sum
echo 'Total'
echo $accounts_sum $escrow_sum $paychannel_sum | tr ' ' '\n' | paste -sd+ | bc
accounts_num=`grep -B4 AccountRoot $theASFile | grep Balance | cut -f2 -d ':' | tr -d '"' | tr -d ',' | wc -l`
escrow_num=`grep -B6 Escrow $theASFile | grep Amount | cut -f2 -d ':' | tr -d '"' | tr -d ',' | wc -l`
paychannel_num=`grep -B5 PayChannel $theASFile | grep Amount | cut -f2 -d ':' | tr -d '"' | tr -d ',' | wc -l`
echo 'node count'
echo $accounts_num $escrow_num $paychannel_num
```

If I repeat the above process for later ledgers (eg, a few hundred thousand later), I arrive at differences betweem my sum and totalCoins that are decreasing over time.

**Comment by professorhantzen** [comment]
Just thinking, now that its been established the "correct" shortfall is 65306.139720, could I be seeing PayChannel fluctuations?

**Comment by bachase** [comment]
Hi @professorhantzen, I believe the calculation should be the sum over
```
1. AccountRoot.Balance
2. Escrow.Amount
3. PayChannel.Amount - PayChannel.Balance
```
where I'm not using valid notation exactly.  So that differs from your scripts `PayChannel` calculation. I' think the `Amount` ledger entry for payment channels is the cumulative XRP put into the channel, and the `Balance` is the cumulative XRP payed out.

**Comment by professorhantzen** [comment]
@bachase Awesome!  With that fix I'm getting 65306.139720 every time.

Thank goodness, now I can sleep at night... and wow, this thing really works.

**Comment by sublimator** [comment]
Lol, phew!

I vaguely recall invariant checks for this, but there being some issue to
do with spam or sth and they being disabled. Maybe they are reinstated
these days?

I recall going over early ledgers and there being some very rare (cant
recall exact frequency, but was checking millions and millions of txns)
txns where a few odd drops would disappear.

**Comment by professorhantzen** [comment]
I'll keep running this now and then, might package it up (the node version...) so others can easily verify any given ledger.  As a basic online test it would catch any number of issues, hopefully none of which will ever actually appear. As I see it, the big concern with rounding errors is that the mechanism creating them could be gamed to mint more of an asset from nowhere, or destroy it without owning it first. I guess in principle something should be worked out to audit IOU's too.

**Comment by sublimator** [comment]
See:
https://github.com/ripple/rippled/blob/develop/src/ripple/app/tx/impl/InvariantCheck.cpp#L26

**Comment by professorhantzen** [comment]
Thank you - I'm in love with this file. Looks like its called for every affected ledger entry, on every transaction.

Imagining a ledger with only one transaction, where 50 XRP is sent from one account to another, can anyone confirm I'm interpreting this code correctly?

```
InvariantCheck.h
drops_ = 0;                                   // #1

InvariantCheck.cpp
drops_ -= (*before)[sfBalance].xrp().drops(); // #2
drops_ += (*after)[sfBalance].xrp().drops();  // #3a & b
if(-1*fee <= drops_ && drops_ <= 0)           // #4
        return true;
// else fail

---

account_a.Balance: 100 XRP
txn: send 50 XRP with 12 drop fee to account_b

 1. drops_ = 0
 2. drops_ = (0 - 100000000)
    drops_ = -100000000
3a. drops_ = -100000000 + 49999988 (account_a)
    drops_ = -500000012
3b. drops_ = -500000012 + 50000000 (account_b)
    drops_ = -12
 4. if(-12 <= -12 && -12 <= 0)
--> true
```

If so, what would happen if less XRP was destroyed by the fee than expected?

**Comment by professorhantzen** [comment]
Yes, XRP left undestroyed. Ie, given the above scenario, if after the transaction, at step 3a, "account_a" showed -500,000,002 (because 49999998 was left in the account - so the fee somehow consumed only 2 drops, not 12), then "drops_" would go into finalize as "-2", which passes both sides of the conditional, but an extra 10 drops would actually be in account_a, and presumably unaccounted for.

In a sense then, XRPNotCreated would then not really be catching all "XRPNotCreated"'s.  Though I'm not 100% sure I read the code correctly. Mainly, I can't figure out how its being called.  I've just assumed it's called in an order that makes sense conceptually and the conditionals return true given a typical change in state.

**Comment by sublimator** [comment]
Oh, I haven't read the code properly ... so wasn't sure what you were
saying :)

Maybe you'll get a bug bounty! :)

Too tired to follow you atm

**Comment by nbougalis** [comment]
@professorhantzen: invariant checks are called for every transactions (and, thus, every ledger). If a transaction breaks an invariant, then any changes it made are undone, and the transaction returns a `tecINVARIANT_FAILED` which puts it in the ledger (doing nothing) so anyone can analyze it. See https://ripple.com/dev-blog/protecting-ledger-invariant-checking/

I'm looking at the code now and I _think_ that [this](https://github.com/ripple/rippled/blob/develop/src/ripple/app/tx/impl/InvariantCheck.cpp#L75) code can be improved by changing this:

    if(-1*fee <= drops_ && drops_ <= 0)

To this:

    if (-fee == drops_)

I'm going to try this, do a PR and tag you as a reviewer.

**Comment by ximinez** [comment]
There is one case where a transaction may not pay the full fee, and that is the case where the fee specified is larger than the account balance. In that case, rippled will "zero out" the account balance, and only destroy that balance amount. This is another reason (along with partial payments) why it's important to check the validated metadata and not just the transaction data.

**Comment by sublimator** [comment]
`if (-fee == drops_)`

Where `drops_ = -before + after` essentially right?
And where `fee` is the actual fee paid (per ed's case), not just as tx specified ?

Sounds about right to me ...
Would handle the drops accidentally gone missing case then too right ?

**Comment by professorhantzen** [comment]
@nbougalis PM'd you on xrpchat.

**Comment by professorhantzen** [comment]
@sublimator It's alright, had already been thought of.

**Comment by professorhantzen** [comment]
https://github.com/ripple/rippled/pull/2482
