### ISSUE TITLE
The rippled server have been in a cycle that synced completely and re-synce legder from the first one

### ISSUE THREAD

**Issue by zhangjinyang** [ripple/rippled#2476]
It let me collapse.The rippled server have been in the cycle for a long time.When the ledger synced completely, it always re-sync the ledger from the first one in minutes.I don't know why.

This is the  content of my config:
`[node_size]
tiny

[node_db]
type=RocksDB
path=/var/lib/rippled/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=2000
advisory_delete=0
[ledger_history]
2000

[database_path]
/var/lib/rippled/db

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
r.ripple.com 51235

[validators_file]
validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
1`

**Comment by MarkusTeufelberger** [comment]
How performant is your disk (especially the one(s) that host /var/lib/rippled/db)?

**Comment by zhangjinyang** [comment]
@MarkusTeufelberger You mean the performance of my disk? it's nearly 2.5G of transaction.db and 1G of ledger.db . I modified the "[ledger_history]" to "full" and deleted this filed "online_delete=2000".The rippled server has not performed like before.

**Comment by zhangjinyang** [comment]
![image](https://user-images.githubusercontent.com/11783190/38732310-57664574-3f50-11e8-9296-cd48b4c4f5dc.png)
So, I think this is what your mean.Sorry, I'm not an expert and don't no more professional vocabularies about computer

**Comment by MarkusTeufelberger** [comment]
26% iowait doesn't look good...

Is this an SSD or a HDD?

**Comment by zhangjinyang** [comment]
@MarkusTeufelberger  It's SSD. Are there anything else about the computer configs I need to pay attention to?
