### ISSUE TITLE
enable sign-compare warnings

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2479]
https://github.com/ripple/rippled/blob/1eece9b1fdbf58b8a4b52b738f53be4fd39dd37e/Builds/CMake/CMakeFuncs.cmake#L646-L647

disables a few warnings that might not be completely harmless all the time and especially sign-compare warnings are thrown all over the place.

See #2478 and #2006

**Comment by nbougalis** [comment]
Low priority atm, but we should be able to compile cleanly with the compiler at the highest warning level, and that should include signedness issues.

Closing this for now, but it's on the roadmap.
