### ISSUE TITLE
I'm using 'UBUNTU 16.04 LTS' and I've a problem on this

### ISSUE THREAD

**Issue by wjddnwjddn1** [ripple/rippled#2480]
https://ripple.com/build/build-run-rippled-ubuntu/
I was processing on 2nd chapter, 12 paragraph and i'm having a trouble on 'scons' error.
How can i solve this problem?(underline text is build process)

-----------------------------------------------------------------------------------------------------------
-Isrc/beast/extras -Isrc/nudb/include -Ibuild/proto -Isrc/soci/src -Isrc/soci/include src/ripple/beast/unity/beast_insight_unity.cpp
In file included from src/ripple/beast/net/IPAddressV4.h:23:0,
                 from src/ripple/beast/net/IPAddress.h:23,
                 from src/ripple/beast/net/IPEndpoint.h:23,
                 from src/ripple/beast/insight/StatsDCollector.h:26,
                 from src/ripple/beast/insight/Insight.h:35,
                 from src/ripple/beast/unity/beast_insight_unity.cpp:22:
src/ripple/beast/hash/hash_append.h:42:40: fatal error: boost/container/flat_set.hpp: No such file or directory
compilation terminated.
scons: *** [build/gcc.release/src/ripple/beast/unity/beast_insight_unity.o] Error 1
scons: building terminated because of errors.

**Comment by nbougalis** [comment]
If you still have issues with building, please open an new issue. Thanks!
