### ISSUE TITLE
rippled-0.90.1-1.fc27.x86_64.rpm

### ISSUE THREAD

**Issue by brdelphus** [ripple/rippled#2488]
Installing the binary rpm rippled-0.90.1-1.fc27.x86_64.rpm on debian using ripple docs procedures and rippled is consuming 90% of cpu, sometimes even worst than that. rippled version from rippled-0.90.0-1.fc27.x86_64.rpm at normal rate between 8-15% cpu 

thoughts anyone ? 
Thank you
Rodrigo

**Comment by nbougalis** [comment]
Rodrigo: I think we discussed this issue over e-mail and that the issue been addressed. I will close this issue, but feel free to re-open it if you are still encountering unexplained CPU spikes.
