### ISSUE TITLE
PaymentChannelClaim fails to close and credit the payer in full if given balance = 0

### ISSUE THREAD

**Issue by corak-ii** [ripple/rippled#2489]
Sorry if it's the incorrect repo to report this issue on. Ran into this by experimenting with moneyd and following the tutorial, with a livenet wallet rNe1Eg8h9JbivEh5BtXBxmDjwb59k2wrva that I created to experiment with.

It's not necessarily an implementation bug, and I still don't know if it's intended or not. I just thought this behavior is rather non-intuitive.

If I create a payment channel to somebody, make no payments and then the channel expires, I should be able to close it and reclaim my XRPs, right? When I tried to issue such a transaction from the WebSocket interface, it failed because the balance given was 0 (even though, indeed, no payments were made). I then changed it to 10000000 (10 XRP, all funds in the payment channel), and then it credited the payee for the entire amount and closed the channel. I suppose I should have tried setting it to 1 first. Still, I don't get why the 0 balance transaction should fail. If I initiated a payment channel and then changed my mind, I should be able to close it without being forced to pay a nonzero amount.

More details about the incident here:
https://www.xrpchat.com/topic/22674-tutorial-use-interledger-with-moneyd-gui/?tab=comments#comment-364024

**Comment by seelabs** [comment]
@corak-ii The balance field is optional, but if you do specify it, it must be > zero or the transaction will fail. You should be able to close the channel by specifying the `tfClose` flag and no balance (i.e. don't specify a balance at all).

If the channel expires, then the channel should close even if you don't specify `tfClose` (though if you specify a balance of <= zero the tx will fail). FYI, here is the relevant snippet of code that checks for this condition: https://github.com/ripple/rippled/blob/develop/src/ripple/app/tx/impl/PayChan.cpp#L366-L368

**Comment by corak-ii** [comment]
Fair enough, if that is a matter of consistency with other types of TX where sending a zero amount doesn't make sense, I can see why it works that way. 

We can probably close if you don't mind the asymmetry in this -
The payee takes full credit with balance = amount, but the payer can't say balance = 0, but must omit balance completely.

Another thing (sorry, again, it's unrelated), I ran this code from JS console:

const plugin = require('ilp-plugin')()
const SPSP = require('ilp-protocol-spsp')
async function run () {
  console.log('paying $spsp.ilp-test.com...')
  await SPSP.pay(plugin, {
    receiver: '$spsp.ilp-test.com',
    sourceAmount: '10'
  })
  console.log('paid!')
}
run().catch(e => console.error(e))

I was sure I was going to be paying 10 drops, but then the payment channel had 10 XRP capacity (which I accidentally moved out of my wallet to @sharafian_ due to this issue -- see the thread in my prior link.
moneyd cleanup would not destroy the payment channel even several hours after I ran this code.

**Comment by seelabs** [comment]
@corak-ii FYI, I'm not the right person to help with the ilp-plugin JS code; I pinged the person I believe would be best be able to address this.

**Comment by sharafian** [comment]
Hi @corak-ii ; I checked out your transactions on XRP ledger and sent back the XRP that you accidentally sent to me.

> I was sure I was going to be paying 10 drops, but then the payment channel had 10 XRP capacity

The default channel capacity that moneyd sets is 10 XRP. If you send 10 drops then the channel's balance would update from 0 to 10 drops. I'll update the medium post to be clearer on this point.

The idea is that any money in the channel can be reclaimed, so if you send 10 drops and then close out the channel, you'll only be out 10 drops (as well as the transaction fees).

It looks like something is wrong with the script I built into moneyd to close channels, so I'll investigate why that is and then follow up here: https://github.com/interledgerjs/moneyd-xrp/issues/33 . Thanks for letting us know about this bug.

**Comment by corak-ii** [comment]
Thanks for looking into this, and returning my zerps! 
Sorry for the hassle regarding the 'PaymentChannelClaim' topic, as it looks like that is intended behavior, as such we can probably close this topic, I'll follow the other one for the moneyd cleanup issue.
