### ISSUE TITLE
Does it make sense to put Date in transaction base class?

### ISSUE THREAD

**Issue by r0bertz** [ripple/rippled#2491]
Hey, guys,

I am working on a rippled library implemented in go.

In this library, we defined a TxBase struct which is supposed to contain fields common to all types of transactions.

We are having a debate whether we should put Date in TxBase here https://github.com/rubblelabs/ripple/issues/36

Can someone chime in? Thank you!

**Comment by r0bertz** [comment]
@nbougalis

**Comment by r0bertz** [comment]
Just realized Date probably shouldn't belong to TxBase since it's a property of ledger, not transaction. I will close this one.

**Comment by nbougalis** [comment]
Thanks for the post. As you said, this is a property of the ledger, not of the individual transactions within it.
