### ISSUE TITLE
Ripple upgrade required

### ISSUE THREAD

**Issue by mmitech** [ripple/rippled#2493]
On the staging infrastructure of our App we are using ripple testnet (started Ripple implementation recently), now when we try to send a TX we get the exception message from RPC "Ripple upgrade required".

I've pulled and built latest master and still have the same issue, what does this mean?

**Comment by nbougalis** [comment]
This message indicates that your server does not support an amendment that is enabled. The altnet will, on occasion, operate on code that is ahead of the **master** branch. You can try building **develop** instead.

**Comment by mmitech** [comment]
just checked out develop, SConstruct file is missing, I can't build it, any other way to build develop?

**Comment by MarkusTeufelberger** [comment]
With cmake.

**Comment by mmitech** [comment]
any docs on how to compile it?

**Comment by bachase** [comment]
You can check the platform-specific build instructions in the `Builds` subfolder of the repo. https://github.com/ripple/rippled/tree/develop/Builds/linux is the linux one.

**Comment by vhendriks81** [comment]
If you're familiar with docker you can get a testnet node up and running using https://hub.docker.com/r/vhendriks/docker-rippled/ (which is a fork from the gatehub repo, but with a special nightly build (vhendriks/docker-rippled:rippled-nightly)

**Comment by mmitech** [comment]
will probably just docker for now. thanks
