### ISSUE TITLE
Rippled "Current ledger is unavailable"

### ISSUE THREAD

**Issue by vhendriks81** [ripple/rippled#2495]
Hi!

I'm running a MainNet Ripple Node (v0.90.1) on an Azure VM. (B4MS, 4 cores, 16gb memory).

Last night it seems it wasn't up with the latest ledger anymore. It kept returning { "error":"noCurrent","error_code":16,"error_message":"Current ledger is unavailable." }. I looked at the logs and noticed it was spamming "Validations:WRN Unable to determine hash of ancestor from ledger hash=[Random hashes here]".

I am running using the node_size set to huge, using nudb and the db is stored on a seperate SSD drive for performance reasons. It is being run as a docker image. The node isn't out of memory afaik, usually doesn't use more than 8gb 

The problem resolved after i restarted the docker container (ie, the rippled process got restarted). +/- 8-9 hours later the problem occurred again.

Any idea what could be wrong or what i could do next time to see what is wrong?

**Comment by bachase** [comment]
The warning message you saw suggests your node was significantly behind the rest of the network. Causes could be network connectivity issues or an overloaded local server (slow disks are a frequent cause). It is not fatal though, and the node should automatically catch up with the network when the issue resolves.

It sounds like your server is adequate for the configuration you have. Does the issue occur regularly? Are there any other processes on the server that might be a cause? If you rule those out, the typical starting point for investigating `rippled` itself is to run `[server_info](https://ripple.com/build/rippled-apis/#server-info)` and `[peers](https://ripple.com/build/rippled-apis/#peers)` commands. I suggest running those 5-10 minutes after your server is started and running "normally" and keep them on hand to compare if you have trouble again.

**Comment by professorhantzen** [comment]
Check your SSD i/o rates, eg with [fio](https://github.com/axboe/fio).  When running in a virtualised environment, depending on your provider, an "SSD" can sometimes have an i/o performance closer to HDD (and as such, insufficient for nudb).

**Comment by vhendriks81** [comment]
Spinned up another node to experiment with. This one doesn't have any rpc load.
Had the problem again, this time on both servers. The first one had a gap in the ledgers. It got fixed after i requested the first missing ledger. Then after a minute or so it didn't have a gap at all anymore.

The second server had more gaps. When i requested the first missing ledger it gave my a response to that request saying it's not on the current ledger.

Here is a part of the logs of the first node (which currently has no gap(s)):
```
2018-Apr-26 07:13:32 LoadMonitor:WRN Job: processLedgerData run: 2114ms wait: 0ms
2018-Apr-26 07:13:32 LoadMonitor:WRN Job: acceptLedger run: 1729ms wait: 0ms
2018-Apr-26 07:13:32 LedgerConsensus:WRN By the time we got 0B56CDEDF3D7B11A3437B539E10734C51D598E37E2EB6428F1110550AF98FE72 no peers were proposing it
2018-Apr-26 07:13:33 LoadMonitor:WRN Job: advanceLedger run: 1057ms wait: 0ms
2018-Apr-26 07:13:39 LoadMonitor:WRN Job: acceptLedger run: 2056ms wait: 1ms
2018-Apr-26 07:13:39 LedgerConsensus:WRN By the time we got C15AC5507C13AF9F005C2F3D3EB0636E145962D6681B037BA9F3DFE8D6D472AB no peers were proposing it
2018-Apr-26 07:13:39 LedgerConsensus:WRN By the time we got 28194F3AC7687F74E32A61089E7DE4C288ED77087E207E5DA425FBCD52F23102 no peers were proposing it
2018-Apr-26 07:13:39 LedgerConsensus:WRN By the time we got C31660F191CCAE9F6A12316A7683DD892553B75206EF8B6B9946447649026844 no peers were proposing it
2018-Apr-26 07:13:43 LoadMonitor:WRN Job: processLedgerData run: 1183ms wait: 0ms
```

**Comment by vhendriks81** [comment]
I would assume that many Warnings isn't a good thing and probably indicates an io issue. Will see if i can get some info regarding the i/o rates

**Comment by professorhantzen** [comment]
After installing fio, you could try running something like this to get an idea:

`./fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=test --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75`

If it helps to have some other figures for comparison, on Digital Ocean using the above, an external SSD Volume benchmarked 15/5MB/s r/w, and 3500/1000 IOPS r/w.  This is in the region of HDD for i/o (when RAID'd). When running rippled on such a configuration the i/o was much too slow and reported errors similar to yours.  Conversely, the local SSD boot drives benchmark 10-20x times those figures.  I've no experience with Azure VM but I'm guessing you may have a similar issue.
