### ISSUE TITLE
seed生成 Private Key

### ISSUE THREAD

**Issue by weige502167** [ripple/rippled#2498]
seed 是通过什么算法和步骤？生成Private Key？

**Comment by vhendriks81** [comment]
What is your actual question? Please elaborate

**Comment by nbougalis** [comment]
@weige502167: the steps used to derive a private key from a seed depend on the type of key. The code can be found here: https://github.com/ripple/rippled/blob/develop/src/ripple/protocol/impl/SecretKey.cpp#L266-L283

**Comment by nbougalis** [comment]
@mDuo13: we should try to provide a more thorough text-based explanation of the key derivation process, along with a set of "sample" test vectors that show the intermediate results, so alternative implementations have a robust set of unit tests.

I'm closing this issue for now.
