### ISSUE TITLE
Consider adding clang-format file

### ISSUE THREAD

**Issue by JoeLoser** [ripple/rippled#2502]
Curious what peoples' thoughts are on having a simple `.clang-format` file to help adhere to the [coding style specified in the repo](https://github.com/ripple/rippled/blob/develop/docs/Coding).

**Comment by seelabs** [comment]
@JoeLoser There is an unofficial .clang-format included in this PR: https://github.com/ripple/rippled/pull/2204. If you use that to format your code before submitting a PR you won't likely receive formatting complaints. However, note that file is still unofficial and doesn't exactly match the code style in the document (I wasn't able to tweak everything to match, but it's pretty close).

In the longer term I do expect we'll commit an official .clang-format at some point.

**Comment by JoeLoser** [comment]
@seelabs Thanks for pointing me at the PR. I'll use that when contributing -- thanks! On that note, it may be helpful to start a doc for contributing/getting started for questions like this. 

It seems to have gotten some internal feedback and usage over time, so I'm hopeful that your proposed `.clang-format` will land into master soon. 

Going to close this as you've pointed me in the right direction.
