### ISSUE TITLE
amendment_blocked  on last version "0.90.1"

### ISSUE THREAD

**Issue by khodhor** [ripple/rippled#2519]
Loading: "/etc/opt/ripple/rippled.cfg"
2018-May-10 14:38:23 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "result" : {
      "state" : {
         "amendment_blocked" : true,
         "build_version" : "0.90.1",
         "complete_ledgers" : "9026729-9027073",
         "fetch_pack" : 410,
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time" : 2000,
            "proposers" : 16
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "ledgerData",
                  "per_second" : 1
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand",
                  "per_second" : 1
               },
               {
                  "job_type" : "transaction",
                  "per_second" : 1
               },
               {
                  "job_type" : "batch",
                  "per_second" : 1
               },
               {
                  "job_type" : "advanceLedger",
                  "peak_time" : 3
               },
               {
                  "job_type" : "fetchTxnData",
                  "per_second" : 2
               },
               {
                  "job_type" : "trustedValidation",
                  "per_second" : 3
               },
               {
                  "job_type" : "writeObjects",
                  "peak_time" : 1,
                  "per_second" : 5
               },
               {
                  "job_type" : "trustedProposal",
                  "per_second" : 5
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 53
               },
               {
                  "job_type" : "diskAccess",
                  "peak_time" : 1,
                  "per_second" : 3
               },
               {
                  "job_type" : "processTransaction",
                  "per_second" : 1
               },
               {
                  "job_type" : "SyncReadNode",
                  "per_second" : 2
               },
               {
                  "job_type" : "AsyncReadNode",
                  "per_second" : 3
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 14
               }
            ],
            "threads" : 4
         },
         "load_base" : 256,
         "load_factor" : 256,
         "load_factor_fee_escalation" : 256,
         "load_factor_fee_queue" : 256,
         "load_factor_fee_reference" : 256,
         "load_factor_server" : 256,
         "peer_disconnects" : "1",
         "peer_disconnects_resources" : "0",
         "peers" : 5,
         "pubkey_node" : "n9JeUczvKUbHdn74Y31KcEA8jpkqB2iAmXFbah8PwLAhkbBMFTSU",
         "pubkey_validator" : "none",
         "server_state" : "tracking",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "71766555",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "1351859",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "tracking" : {
               "duration_us" : "80469061",
               "transitions" : 1
            }
         },
         "uptime" : 154,
         "validated_ledger" : {
            "base_fee" : 10,
            "close_time" : 579278301,
            "hash" : "89315FE461843BCF8F492CBC60A2ED2080E46D69A5CD74C1990FA83D35DA414A",
            "reserve_base" : 20000000,
            "reserve_inc" : 5000000,
            "seq" : 9027073
         },
         "validation_quorum" : 11,
         "validator_list_expires" : 580089600
      },
      "status" : "success"
   }
}

I see this error "amendment_blocked" 
I work on altnet with this config

[ips]
r.altnet.rippletest.net 51235

[validator_list_sites]
https://vl.altnet.rippletest.net

[validator_list_keys]
ED264807102805220DA0F312E71FC2C69E1552C9C5790F6C25E3729DEB573D5860

I see this feature  
  "7117E2EC2DBF119CA55181D69819F1999ECEE1A0225A7FD2B9ED47940968479C": {
    "enabled": true,
    "supported": false,
    "vetoed": false
  }
not supported on  version 0.90.1

**Comment by wilsonianb** [comment]
hi @khodhor 
New amendments will sometimes be enabled on the altnet before they are included in an official rippled release.
You can avoid getting amendment blocked on the altnet by running the `nightly` rippled rpm. You can follow these instructions and replace `ripple-stable` with `ripple-nightly`:
https://ripple.com/build/rippled-setup/#installation-on-centosred-hat-with-yum

**Comment by khodhor** [comment]
Hello @wilsonianb 
It's running perfectly now.
Thank you very much
