### ISSUE TITLE
[ASIO latency] io_latency_ms measure does not update

### ISSUE THREAD

**Issue by rrozek** [ripple/rippled#2521]
Hi!
Recently I've found that `io_latency_ms` reported by `server_state `is last read value of `ApplicationImp::m_io_latency_sampler`. However it looks like measure which is started on Application startup stalls after few successful measures and never updates again.
(I added log in callback to 
`template <class Duration>
        void operator() (Duration const& elapsed)`
and it only executes for like... 2-5 seconds after startup

Its pretty easy to observe/reproduce but its hard for me to determine why it stalls...
for instance 
1. enable [insight] section in cfg file (or add some log in mentioned callback above, then step 2. is not necessary)
2. add delay to network speed so it is >= 10ms 
`tc qdisc add dev eth0 root netem delay 11ms`
3. start daemon
4. when finished, remove delay rule:
`tc qdisc del dev eth0 root netem`
---

**Comment by nbougalis** [comment]
Hmm! Thanks for this. Will look into this.

**Comment by mellery451** [comment]
@rrozek thanks for finding and reporting this issue. I've submitted a fix at https://github.com/ripple/rippled/pull/2542. If you'd like to verify the fix works for you, you can build from the source branch mentioned there.

**Comment by rrozek** [comment]
hi @mellery451 !
I can confirm that now measurements are running continuously.
Thank you for your fast problem identification and fix!
