### ISSUE TITLE
Does Ripple test support for old GCC ABI?

### ISSUE THREAD

**Issue by JoeLoser** [ripple/rippled#2528]
Problem:
When reading through some of our CMake, I see that we seem to support the "old" GCC ABI (e.g. < GCC 5 ABI).  See [here](https://github.com/ripple/rippled/blob/develop/Builds/CMake/CMakeFuncs.cmake#L276) for the particular CMake snippet.

I'm guessing this logic was here to support the old world from Scons.  Do we still want it/claim support for building Ripple with the old ABI?  Do we test building with the old ABI?  I didn't seem to see it in our Jenkins builds.  

Pinging @mellery451 since Brad told me you're rewriting some of the CMake now that Scons and the dual world is gone.

**Comment by nbougalis** [comment]
We are probably going to remove that going forward.

**Comment by JoeLoser** [comment]
Great.  If you would like some help with improving the `CMake` @mellery451, I'm happy to help.  I've spent a bit of time at my current place with `CMake`.

**Comment by mellery451** [comment]
Excellent...thanks for the offer. I’ll definitely add you as a reviewer as I submit changes.
