### ISSUE TITLE
Create clang-tidy list of checks to enable

### ISSUE THREAD

**Issue by JoeLoser** [ripple/rippled#2530]
**Problem:**
There are many simple, automatable things caught in code reviews manually when we could leverage clang tooling to help us out. These things come in a few different flavors: performance, security, modern C++ features, etc.

**Solution:**
Come up with a list of clang-tidy checks we would like to enable.  See the discussion that spawned from [this PR](https://github.com/ripple/rippled/pull/2529) initially.

I suggest a phased approach:

1. Identify checks that we would like to add to our list of ones that will run during a build configuration that will run clang-tidy.  When identifying ones in this list, it may be helpful to run it against the codebase in its current state to see what it flags, whether it's helpful, etc. before adding it to our list of checks we add.
2. Submit PRs one-by-one for each check likely we'd like to enable so they can be agreed upon in isolation in case a team member is adamantly against a given check.
3. Add a .clang-tidy file with those list of options. Use this `.clang-tidy` file with `-style=file` to leverage it within CMake. We will make use of `CMAKE_CXX_CLANG_TIDY` option. The idea would be just to add a build configuration knob like "tidy-build" which will invoke `clang-tidy` with our `.clang-tidy` that contains our list of checks.
4. After sufficient use and happiness with our "tidy-build" invocation, we can add it to our CI build with Jenkins as just another part of our pipeline.

Happy to hear others' thoughts:
@mellery451 @scottschurr @HowardHinnant @bachase

**Comment by nbougalis** [comment]
Thanks @JoeLoser. I'm supportive of your approach, especially incorporating this as part of the build process. Furthermore, as we incorporate some of the cleanups, we should also try to enable compiler warnings that can prevent reoccurence.

I'm going to close this issue. Please feel free to open new ones, as necessary, for specific issues.
