### ISSUE TITLE
Use-after-move in Manifest.cpp when logging that a validator master key has been compromised

### ISSUE THREAD

**Issue by JoeLoser** [ripple/rippled#2536]
**Problem:**
There is a code path where we are logging a member from a moved-from object. Accessing an object after it has been moved from is UB. The object in question is left in a "moved-from, but unspecified state".

Specifically, [Manifest.cpp line 304](https://github.com/ripple/rippled/blob/develop/src/ripple/app/misc/impl/Manifest.cpp#L304) moves `m` and then on [line 334](https://github.com/ripple/rippled/blob/develop/src/ripple/app/misc/impl/Manifest.cpp#L334) we access `m.masterKey` when logging.

**Comment by seelabs** [comment]
While I don't love this code as it's using `m` after moving, it is not a bug. The state of the members we access from the moved from Manifest is well defined. The member variables in a moved from Manifest will be affected in the following ways:

1) The `serialized` member will be moved into the "moved into" object and left in an empty state (with a possible exception for small object optimization; I'm unsure how that would be handled, so it may or may not be empty in that case). At any rate, we can't rely on accessing the original string after a move.
2) The `masterKey`, `signingKey` and `sequence` members will be copied into the "moved into" object and left in their original state. We can realy on accessing the origional state after a move.

However, in general it is bad style to access an object after a move and I see this code as fragile. If we changed the implementation of `PublicKey` so the moved from state is empty then this code no longer logs the original master key.

Let's leave the issue open and take a look at fixing the use after move.

**Comment by JoeLoser** [comment]
Thanks for the quick response, @seelabs. A lot of the issues (#2536 through #2541) related to this `use-after-move` idea, I agree, are not necessarily bugs, but I did want to get them written down so we can triage appropriately. The action for most of these may indeed be to do nothing.

So treat these issues with some delicacy in that I haven't dived deep into each of them whatsoever, but wanted to get them written down.

**Comment by seelabs** [comment]
@JoeLoser Thanks for the reports! They are very helpful.
