### ISSUE TITLE
Use-after-move in TxQ.cpp when asserting property in adding a transaction

### ISSUE THREAD

**Issue by JoeLoser** [ripple/rippled#2537]
**Problem:**
We move the object `txn` on [TxQ.cpp line 304](https://github.com/ripple/rippled/blob/develop/src/ripple/app/misc/impl/TxQ.cpp#L304) and then later assert a property about it [three lines later](https://github.com/ripple/rippled/blob/develop/src/ripple/app/misc/impl/TxQ.cpp#L307)

Note that this will only affect debug builds as we do not `assert` in Release builds.

**Comment by seelabs** [comment]
This is well defined and is not a bug. In this case we're checking the address of the object, which won't change after a move (assuming `operator&` isn't overloaded we can just use `&object` as we do here, to get the address).

I think the code is OK as-is.

**Comment by JoeLoser** [comment]
I agree with your assessment. It is valid to access the address so the moved from object.

Modulo overloading addressof operator, this would get flagged as a false positive often. We'll take that into account when considering the list of `clang-tidy` checks. I suspect we won't want false positives on something that may fail the build if clang-tidy catches something.
