### ISSUE TITLE
Use-after-move in ServerHandlerImp.cpp when logging RPC error

### ISSUE THREAD

**Issue by JoeLoser** [ripple/rippled#2538]
**Problem:**
We move the `result` object on [line 779](https://github.com/ripple/rippled/blob/develop/src/ripple/rpc/impl/ServerHandlerImp.cpp#L779) and then use it to log the error and error message right after on [line 781](https://github.com/ripple/rippled/blob/develop/src/ripple/rpc/impl/ServerHandlerImp.cpp#L779)

**Comment by seelabs** [comment]
This is a bug. Nice find! We will fix this.

**Comment by JoeLoser** [comment]
Thanks for fixing the bug @HowardHinnant
