### ISSUE TITLE
Ocassionally getting: "Not enabled in configuration." when requesting fee over RPC

### ISSUE THREAD

**Issue by gituser** [ripple/rippled#2558]
Hi.

I'm sending 500-600 transactions in the test network as well as in the production and before sending out the transaction, I'm getting `open_ledger_fee` via `fee` RPC call to make sure to set proper fee to get transaction included and verified and sometimes rippled just returns this instead:

```
  'command' => 'fee',
  'error' => 'notEnabled',
  'error_code' => 12,
  'error_message' => 'Not enabled in configuration.',
  'request' =>
  array (
    'command' => 'fee',
  ),
  'status' => 'error',
```

I've tested `rippled v1.0.0` and `rippled v1.1.0b` and both seems to be affected.

What is the reason and why it happens only sometimes?

**Comment by MarkusTeufelberger** [comment]
You are querying your own, local node - right?

**Comment by nbougalis** [comment]
That is interesting. Can you grab the `server_info` response from the server and see what status it is reporting at the time this occurs?

Also, does this happen on your own servers or servers operated by third parties?

**Comment by mDuo13** [comment]
This issue has gone stale without the ability to reproduce it, so I'm closing it. Feel free to reopen if you can provide more info.
