### ISSUE TITLE
Is there a testnet explorer?

### ISSUE THREAD

**Issue by shamoons** [ripple/rippled#2559]

**Comment by vimalbera92** [comment]
Try this: http://ripplerm.github.io/ripple-wallet/

**Comment by MarkusTeufelberger** [comment]
No, butr you can run your own instance of https://github.com/ripple/ripplecharts-frontend and https://github.com/ripple/rippled-historical-database

**Comment by ihomp** [comment]
@shamoons @vimalbera92 @MarkusTeufelberger 
There is: https://test.bithomp.com/explorer
