### ISSUE TITLE
[question] crawling peer network

### ISSUE THREAD

**Issue by rrozek** [ripple/rippled#2560]
Hi, is there a way to recursively crawl peer network with rippled Daemon? I know that aggregating the result could take some time and response could potentially be huge, so it could be admin-restricted. But is there a way to recursively crawl peers? (Or could it be potentially possible with little bit of tweaking the code?)

Any hints appreciated! :)

**Comment by ximinez** [comment]
Yes, it is possible, and we have some resources that can help:
* https://developers.ripple.com/peer-protocol.html describes the Peer Crawler functionality via `/crawl`
* https://github.com/ripple/rippled-network-crawler is an implementation of a crawler that uses the `/crawl` command.

**Comment by MarkusTeufelberger** [comment]
What data do you want to get with that "crawl"? There is already a public endpoints for crawling usually exposed on the peer port...
