### ISSUE TITLE
[question] Periodical InsufficientNetworkMode on account_info

### ISSUE THREAD

**Issue by dselyuzhitskiy** [ripple/rippled#2565]
Hi there! 
We have an installed rippled node in Docker. Our software gets payments from that node. It happens sometimes that the node answers the following: 

```
{
   "result": {
       "error": "noNetwork",
       "error_code": 17,
       "error_message": "InsufficientNetworkMode",
       "request": {
           "account": "",
           "command": "account_info"
       },
       "status": "error"
   }
}
```
Such kind of answers we get during a long period, so the ledger index goes far forward for a big number, so we actually miss the deposits because of a locally stored ledger quantity.

This situation can take from 10 minutes up to a whole day.
What is it? Not enough resources for the node? Or is it a system error?

**Comment by MarkusTeufelberger** [comment]
What does your monitoring say about resource usage, especially disk IO?

**Comment by dselyuzhitskiy** [comment]
Average Read IOPS 1500, Write IOPS  600, but during period of  InsufficientNetworkMode error occurs, read io and write io == 0.  Node logs didn't provide anything about possible error.

**Comment by nbougalis** [comment]
Can you see if there are any networking hiccups during the time periods when disk I/O drops to 0? It seems that this could be the result of network hiccups.
