### ISSUE TITLE
Websocket response from full ledger crashes python websocket-client library

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#257]
I have not debugged this enough to state whether the fault is with websocket-client (https://github.com/liris/websocket-client) or rippled, there must be an issue somewhere though.

Requesting a full recent ledger (4.4 million range) from a 0.20.1 rippled takes a minute or so of 0 activity and then (when data starts to arrive) errors out in the following way (paths omitted):

```
Opening websocket to ws://xxx:5006
Requesting the full ledger with index: 4421209
Sending command: {"command":"ledger","ledger_index":4421209,"full":1}
Sent
Receiving...
((here it takes a minute or so of waiting))
Traceback (most recent call last):
  File "xxx.py", line 251, in <module>
    ledger = load_full_ledger(4421209, ws)
  File "xxx", line 38, in load_full_ledger
    answer =  socket_conn.recv()
  File "C:\xxx\websocket.py", line 596, icv
    opcode, data = self.recv_data()
  File "C:\xxx\websocket.py", line 606, icv_data
    frame = self.recv_frame()
  File "C:\xxx\websocket.py", line 661, icv_frame
    payload = self._recv_strict(self._frame_length)
  File "C:\xxx\websocket.py", line 746, iecv_strict
    bytes = self._recv(shortage)
  File "C:\xxx\websocket.py", line 730, iecv
    bytes = self.sock.recv(bufsize)
MemoryError
```

I can provide a sample program in python2 if needed to debug further, my suspicion is that rippled is not strictly keeping to either some time limits or some other standards of websockets - there are other feature requests in that area anyways (#219, #214) so maybe this area of code could be looked over a bit? :-)

**Comment by rec** [comment]
This is old so I'm closing it, feel free to reopen if it isn't fixed and has importance!  :-)
