### ISSUE TITLE
Visual Studio 2017 Build Instructions

### ISSUE THREAD

**Issue by jaiswalvik** [ripple/rippled#2571]
While trying to setup server for development cannot find **OpenSSL Library 1.0.2n** to download from the given link **http://slproweb.com/products/Win32OpenSSL.html**

**Comment by nbougalis** [comment]
Unfortunately, the documentation is slightly out of date. Please use **v1.0.2o**. If you have continue to have issues, then try **v1.1.0h**.

Please leave this issue open even if this addresses your problem. We are going to use it to track updating the documentation.

**Comment by jaiswalvik** [comment]
ok.. i ran into another issue:
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\mswsock.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\netapi32.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\netutils.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\wkscli.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\srvcli.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Unloaded 'C:\Windows\System32\netutils.dll'
'rippled_classic.exe' (Win32): Unloaded 'C:\Windows\System32\wkscli.dll'
'rippled_classic.exe' (Win32): Unloaded 'C:\Windows\System32\srvcli.dll'
'rippled_classic.exe' (Win32): Unloaded 'C:\Windows\System32\netapi32.dll'
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\NapiNSP.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\pnrpnsp.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\nlaapi.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\dnsapi.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\nsi.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\IPHLPAPI.DLL'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\winrnr.dll'. Cannot find or open the PDB file.
'rippled_classic.exe' (Win32): Loaded 'C:\Windows\System32\wshbth.dll'. Cannot find or open the PDB file.
Exception thrown at 0x00007FFC2A72F218 in rippled_classic.exe: Microsoft C++ exception: std::runtime_error at memory location 0x000000AECDF7D098.
Unhandled exception at 0x00007FFC2A72F218 in rippled_classic.exe: Microsoft C++ exception: std::runtime_error at memory location 0x000000AECDF7D098.
The program '[12648] rippled_classic.exe' has exited with code 0 (0x0).

**Comment by ilianpinzon** [comment]
Check what's set in [node_db] type in your config. RocksDB is **not** available in Windows. Use NuDB instead. See rippled-example.cfg for more details.

**Comment by ilianpinzon** [comment]
I don't think the rippled build process includes RocksDB in Windows. See this [line](https://github.com/ripple/rippled/blob/fd4636b0560900bd040b03004a1efc7ddb8369a0/cfg/rippled-example.cfg#L803) in rippled-example.cfg. I also confirmed that by running rippled under the debugger.
