### ISSUE TITLE
processRequest in class ServerHandlerImp may cause memory leak

### ISSUE THREAD

**Issue by LoveULin** [ripple/rippled#2572]
We assign the moved `params[0u]` to `params`, which causes memory leak.

At first, `params[0u]` holds the object value, and `params` holds the array one, i.e. `params[0u]`. After the assigning, `params` holds the object value exactly, but where is the array value?? `params[0u]` is just a `Json::Value`, and we can never retrieve it again. Since the array/object value's `value_` field is a map which is allocated by `new`,  the memory leaks.

https://github.com/ripple/rippled/blob/fd4636b0560900bd040b03004a1efc7ddb8369a0/src/ripple/rpc/impl/ServerHandlerImp.cpp#L725

I think the reason for this problem is that we use the movement version of `operator=` of `Json::Value` which is caused by the use of std::move above. After assigning, `params[0u]` holds the array value, but can never be deconstructed.

https://github.com/ripple/rippled/blob/fd4636b0560900bd040b03004a1efc7ddb8369a0/src/ripple/json/impl/json_value.cpp#L373

In my test, after simply removing the `std::move`, there is no memory leak anymore.

**Comment by nbougalis** [comment]
This was a great catch, @LoveULin. Thank you.
