### ISSUE TITLE
[Question] ideas for contributing

### ISSUE THREAD

**Issue by JoeLoser** [ripple/rippled#2574]
I'm looking to gather suggestions on where to provide future valuable contributions. I know there are some internal JIRA tickets filed, but they may not be exactly suitable for a "first issue".

**Comment by MarkusTeufelberger** [comment]
There's https://www.xrpchat.com/topic/12498-new-features-for-xrplrcl/, some of these are harder than others, none are good "first issues" I guess. Actually, until Ripple provides a public roadmap and overview/feedback on such things, contributing actual features beyond some build scripts or small code fixes as an external is difficult.
