### ISSUE TITLE
[Question] Clarification on tx canonical order algo

### ISSUE THREAD

**Issue by ilianpinzon** [ripple/rippled#2578]
This may be a noob question but if I am reading [CanonicalTXSet::Key::operator<](https://github.com/ripple/rippled/blob/fd4636b0560900bd040b03004a1efc7ddb8369a0/src/ripple/app/misc/CanonicalTXSet.cpp#L25-L36) correctly:

```c++
bool CanonicalTXSet::Key::operator< (Key const& rhs) const
{
    if (mAccount < rhs.mAccount) return true;

    if (mAccount > rhs.mAccount) return false;

    if (mSeq < rhs.mSeq) return true;

    if (mSeq > rhs.mSeq) return false;

    return mTXid < rhs.mTXid;
}
```
it shows that if a transaction has the same account and sequence then order by transaction ID.

Does that mean that it's possible for one account to have multiple transactions in one sequence?

**Comment by scottschurr** [comment]
It's not possible for one account to have multiple transactions with one sequence _in the ledger_.  However we certainly have to deal with that possibility on the network _before_ they go into the ledger.  The `CanonicalTXSet` is used to order transactions for processing before they might potentially go into the ledger.

**Comment by ilianpinzon** [comment]
I see. Thanks.
