### ISSUE TITLE
The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by David-projects** [ripple/rippled#2580]
I am trying to setup a validator following this website https://developers.ripple.com/install-rippled.html but I am getting an error on step 3 off "Installation on Ubuntu with alien" can anyone help?

The error is below

yumdownloader --enablerepo=ripple-stable --releasever=el7 rippled
https://mirrors.ripple.com/rpm/el7/stable/arm/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Cannot retrieve repository metadata (repomd.xml) for repository: ripple-stable. Please verify its path and try again

I have internet access as you can see with the curl
root@Nas-Home:/data/website# curl https://mirrors.ripple.com/rpm/el7/stable/arm/repodata/repomd.xml
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by wilsonianb** [comment]
hi @David-projects 
What version of Ubuntu are you on?

**Comment by David-projects** [comment]
I was using wrong version
