### ISSUE TITLE
How to health check of rippled

### ISSUE THREAD

**Issue by yoyoyousei** [ripple/rippled#2596]
I need to monitor rippled by http-get or tcp request, to use rippled in an enterprise environment.

What is the best practice of rippled health check?
Is there any rest api to rippled? 

Any comments or advice are appreciated.

**Comment by mDuo13** [comment]
`rippled` does not have a RESTful API, but you can use the [JSON-RPC interface](https://developers.ripple.com/get-started-with-the-rippled-api.html#json-rpc), which is also HTTP-based like a RESTful API.

To check the health of `rippled`, use the [`server_info` method](https://developers.ripple.com/server_info.html). Example request:

```
POST http://s1.ripple.com:51234/

{
    "method": "server_info"
}
```

In the response, check the `result.info.server_state` field of the response:

- If the value of this field is `full`, `validating`, or `proposing`, that indicates that the server is in sync with the network.
- If the value of the field is `connected` or `syncing`, that indicates that the server is not in sync with the network. This could mean the server recently started, or it fell behind.

You can also look at the `result.info.load_factor` field of the response. The higher this number, the busier the server is. A value of `1` indicates that the server is operating normally. A higher number indicates that the server is busy.

There are some vague plans to introduce a dedicated, simpler health-checking method in a future `rippled` version. This method would also report whether the server is [amendment blocked](https://developers.ripple.com/amendments.html#amendment-blocked), but nothing has been started on that point.

I hope this answers your question. Please feel free to reopen if you need any more information.
