### ISSUE TITLE
Raise quorum / increase fault tolerance

### ISSUE THREAD

**Issue by wilsonianb** [ripple/rippled#2604]
Theorem 8 of the [Analysis of the XRP Ledger Consensus Protocol](https://arxiv.org/abs/1802.07242) says that:
>XRP LCP guarantees fork safety if O<sub>i,j</sub> > n<sub>j</sub>/2 + n<sub>i</sub> − q<sub>i</sub> + t<sub>i</sub>,j for every pair of nodes P<sub>i</sub>, P<sub>j</sub>.

The paper goes on to say that
>assuming 80% quorums and 20% faults, the overlap condition in theorem 8 can be summarized as requiring roughly >90% UNL overlaps

However, the [current rippled implementation](https://github.com/ripple/rippled/commit/d90a0647d66ee97563e965f50569002db1bf91d6) uses a quorum of (2/3)n + 1.

Even with two lists with 100% overlap, a quorum of (2/3)n + 1 quorum only tolerates n/6 + 1 Byzantine faults:

```
n > n/2 + n - ((2/3)n + 1) + t
t < n/6 + 1
```

Since we value safety over liveness, we should choose a quorum whose safety fault tolerance (t<sub>i,j</sub>) meets or exceeds its liveness tolerance (n - q)

### Theorem 8

O<sub>i,j</sub> > n<sub>j</sub>/2 + n<sub>i</sub> - q<sub>i</sub> + t<sub>i,j</sub>

n<sub>i</sub>: size of P<sub>i</sub>'s UNL

n<sub>j</sub>: size of P<sub>j</sub>'s UNL

O<sub>i,j</sub>: number of validators in both UNLs

t<sub>i</sub>, t<sub>j</sub>: the maximum number of allowed Byzantine faults in UNL<sub>i</sub> and UNL<sub>j</sub>

t<sub>i,j</sub>: min{t<sub>i</sub>, t<sub>j</sub>, O<sub>i,j</sub>}

### Smaller n -> bigger q

p = n<sub>j</sub> - n<sub>i</sub>

O<sub>i,j</sub> > (n<sub>i</sub> + p)/2 + n<sub>i</sub> - q<sub>i</sub> + t<sub>i,j</sub>

q<sub>i</sub> > (3/2)n<sub>i</sub> + p/2 + t<sub>i,j</sub> - O<sub>i,j</sub>

if p > 0 (n<sub>i</sub> < n<sub>j</sub>), then q<sub>i</sub> > q<sub>j</sub>

Since rippled nodes are currently unable to compare UNL sizes, they should be safe and assume they have the smaller UNL (and use the larger quorum to be determined below).

### Safety >= liveness

p<sub>i</sub> = n<sub>i</sub> - O<sub>i,j</sub>

p<sub>j</sub> = n<sub>j</sub> - O<sub>i,j</sub>

Assume n<sub>i</sub> < n<sub>j</sub>, meaning p<sub>i</sub> < p<sub>j</sub> and t<sub>i,j</sub> = t<sub>i</sub>

O<sub>i,j</sub> > n<sub>j</sub>/2 + n<sub>i</sub> − q<sub>i</sub> + t<sub>i,j</sub>

n<sub>i</sub> - p<sub>i</sub> > (n<sub>i</sub> - p<sub>i</sub> +p<sub>j</sub>)/2 + n<sub>i</sub> − q<sub>i</sub> + t<sub>i</sub>

t<sub>i</sub> < -n<sub>i</sub>/2 - p<sub>i</sub>/2 - p<sub>j</sub>/2 + q<sub>i</sub>

To obtain a q<sub>i</sub> whose safety tolerance >= its liveness tolerance, we use:

t<sub>i</sub> >= n<sub>i</sub> - q<sub>i</sub>

n<sub>i</sub> - q<sub>i</sub> < -n<sub>i</sub>/2 - p<sub>i</sub>/2 - p<sub>j</sub>/2 + q<sub>i</sub>

q<sub>i</sub> > (3/4)n<sub>i</sub> + p<sub>i</sub>/4 + p<sub>j</sub>/4

### Overlap requirements

At a minimum, we need to accommodate the following scenarios when P<sub>i</sub> and P<sub>j</sub> are using the same published list(s):

* P<sub>i</sub> and P<sub>j</sub> see the same list versions (100% overlap)
* P<sub>i</sub> and P<sub>j</sub> see versions of the list(s) that differ by one added or removed validator

| unlisted validator(s) | published lists | p<sub>i</sub> | p<sub>j</sub> | q<sub>i</sub> > (3/4)n<sub>i</sub> + p<sub>i</sub>/4 + p<sub>j</sub>/4 |
|---|---|---|---|---|
| none | same | 0 | 0 | q<sub>i</sub> > (3/4)n<sub>i</sub> |
| none | P<sub>i</sub> sees one less | 0 | 1 | q<sub>i</sub> > (3/4)n<sub>i</sub> + 1/4 |
| P<sub>j</sub> | same | 0 | 1 | q<sub>i</sub> > (3/4)n<sub>i</sub> + 1/4 |
| P<sub>j</sub> | P<sub>i</sub> sees one less | 0 | 2 | **q<sub>i</sub> > (3/4)n<sub>i</sub> + 1/2** |
| P<sub>j</sub> | P<sub>i</sub> sees one more | 1 | 1 | **q<sub>i</sub> > (3/4)n<sub>i</sub> + 1/2** |
| P<sub>i</sub>, P<sub>j</sub> | same | 1 | 1 | q<sub>i</sub> > (3/4)n<sub>i</sub> + 1/2 |
| P<sub>i</sub>, P<sub>j</sub> | P<sub>i</sub> sees one less | 1 | 2 | **q<sub>i</sub> > (3/4)n<sub>i</sub> + 3/4** |

In order to meet or exceed our desired fault tolerance, we use the largest quorum among all overlap scenarios:

* a non-validator or listed validator should use a quorum of **q > (3/4)n + 1/2**
* an unlisted validator should use a quorum of **q > (3/4)n + 3/4**

### 80% quorum

To allow less UNL overlap, we can increase p<sub>i</sub> and p<sub>j</sub> in the calculation above or simply use an 80% quorum.

With q<sub>i</sub> = .8n and t<sub>i,j</sub> = .2n, we could safely allow up to the following non-overlap: 

n - p<sub>i</sub>  > (n - p<sub>i</sub> + p<sub>j</sub>)/2 + n − .8\*n + .2\*n

p<sub>i</sub> + p<sub>j</sub> < .2\*n

So if we want a little more liveness, we should use the quorums above. Otherwise, we can use 80% and allow a little less overlap.

**Comment by bachase** [comment]
Typo in the smaller N-> bigger Q section:
```
if p > 0 (ni < nj), then qi > q**i**
```
If this goes into the repo later (it should!), it might be helpful to also add the explicit line for `$q_j$` overlap to make things clearer.

**Comment by bachase** [comment]
Nit, I would drop the i,j subscripts and just use `t` in the `Safety >= liveness` analysis since that is part of your assumptions at the start of that section.

I also find  t<sub>i</sub> >= n<sub>i</sub> - q<sub>i</sub> clearer then writing it as the fraction.

**Comment by bachase** [comment]
👍 great analysis

**Comment by wilsonianb** [comment]
Resolved by https://github.com/ripple/rippled/pull/2613
