### ISSUE TITLE
#2321 breaks unittests on all default Docker deployments

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2606]
As you already found out, #2321 breaks travis, e.g. https://travis-ci.org/MarkusTeufelberger/rippled-distrotest/jobs/396614314

More interestingly, this is NOT a build running in the container based instances, instead it runs in the virtualized test environment and spins up Docker in there (Travis offers a VERY limited range of distros and the ones offered are heavily modified). After checking around a bit, IPv6 is disabled by default in Docker: https://docs.docker.com/config/daemon/ipv6/

This means it is no longer possible to run the unit tests in Docker, I haven't checked if it is still possible to  even run `rippled` at all.

While I'm glad that there is finally IPv6 support, I'd like to be able to build and run rippled in Docker environments that I don't fully control and that have default settings.

**Comment by mellery451** [comment]
did you try adding `--unittest-ipv4` to your `rippled --unittest` invocation ?

**Comment by MarkusTeufelberger** [comment]
No, since I don't invoke that directly, I use `Test.py`.

**Comment by mellery451** [comment]
Ah, so what really broke is `Test.py` (not supporting the ipv4 option). I'd rather we didn't have this script, but here we are. I'll see how to patch it up.

**Comment by MarkusTeufelberger** [comment]
I'd argue that IPv6 is unfortunately still not the norm, so I'd rather see an optional `--unittest-ipv6` switch by the way. If you want to, I can add that option to Test.py too.

**Comment by mellery451** [comment]
sounds reasonable to me. Here is commit that switches the flag/default:  https://github.com/mellery451/rippled/commit/085ec279d6c57d2c81dc9948bd7a5b8123e302c0. If you want to drop some `Test.py` changes on top of that, we can then make a PR. Thanks.

**Comment by MarkusTeufelberger** [comment]
Will be fixed in #2616.
