### ISSUE TITLE
Is there a way to get the test coverage for the unit test suite written?

### ISSUE THREAD

**Issue by avinashmaheshjoshi** [ripple/rippled#2608]
Rippled seems to have an excellent suite of unit tests written and I am able to run them using the command

`ripple --unittest `

Is there anyway to get the coverage using lcov the way bitcoin repo gives?

**Comment by MarkusTeufelberger** [comment]
Yes, check out how the builds for https://codecov.io/gh/ripple/rippled/ are built.

**Comment by avinashmaheshjoshi** [comment]
Thanks. That answers my question.
