### ISSUE TITLE
Rippled service problem with not responding server

### ISSUE THREAD

**Issue by 0x49D1** [ripple/rippled#2620]
The problem is that once per 10 days our server, which runs rippled service just stops responding. It stops sending any network traffic, I can't SSH into it and only physical reboot helps. The server is just plain CentOS with rippled running on it, nothing more. We always tend to update to latest version (1.0.1 for now). Is this a known problem?
I've checked the debug log - it just stops, messages log says nothing special, just no logs of rippled operations (my custom calls).
Server is AWS EC2, other similar servers(not with rippled installed) work just fine.

**Comment by nbougalis** [comment]
This is the first report of this kind of problem and, frankly, I can't imagine that this is related to `rippled`. As is, this issue is not actionable. Please feel free to reopen if you have additional information to add.
