### ISSUE TITLE
Create rippled room on gitter.im?

### ISSUE THREAD

**Issue by xefdan3ms** [ripple/rippled#2624]
Can we create a gitter.im room for rippled? It could help build the community to have a place for veteran contributors and newcomers to discuss the rippled project. 

This would be created as a new room in the existing ripple community on gitter.im:
        https://gitter.im/ripple

So this would be created here:
        https://gitter.im/ripple/rippled

**Comment by nbougalis** [comment]
If you wish to create this, I'd join! :+1:
