### ISSUE TITLE
Rippled returns "Server is overloaded"

### ISSUE THREAD

**Issue by yoyoyousei** [ripple/rippled#2628]
My rippled works as I expected basically.
But when I conducted many rpc calls (about 30~50times per sec) , it returns "server is overloaded" after about 20 sec.

Is there any way to strengthen rippled against many rpc calls?
I'm giving 32GB memories and 8 cpus to rippled.

My rippled.cfg is:
```
[server]
port_peer
port_rpc
port_ws_public

[port_peer]
ip=0.0.0.0
port=51235
protocol=peer
admin=127.0.0.1

[port_rpc]
ip=127.0.0.1
port=5005
protocol=https

[port_ws_public]
ip=127.0.0.1
port=6006
protocol=wss

[database_path]
/var/lib/rippled/db

[node_db]
type=RocksDB
path=/var/lib/rippled/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=86400
advisory_delete=0

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
r.ripple.com 51235

[validators_file]
validators.txt

[node_size]
huge

# store ledgers for past 3 days (12GB/day)
[ledger_history]
86400

[fetch_depth]
full

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[rpc_startup]
{ "command": "log_level", "severity": "info" }

[ssl_verify]
1

```

**Comment by MarkusTeufelberger** [comment]
Depends on the rpc calls probably. "ping" means a different amount of work than "ledger full:true".

**Comment by yoyoyousei** [comment]
@MarkusTeufelberger Ping is good method to check state of ripple, but is there any way to improve capacity of rippled?
I want to query all payment transactions to rippled.

**Comment by MarkusTeufelberger** [comment]
As far as I remember, admin connections have higher limits. I'm not sure if they are configurable in the config file or if you need to recompile. https://github.com/ripple/rippled/blob/develop/src/ripple/rpc/impl/Tuning.h could be relevant.

**Comment by yoyoyousei** [comment]
@MarkusTeufelberger Thanks to your advice, I succeeded to remove limitation by running rippled with admin option (= enable admin call in port_rpc section of rippled.cfg).

Using rippled admin RPC api is enough capable to me, thank you!

My remaining concern is enabling admin RPC call is a bit risky. Of course, placing rippled and target service in the same network is one of the solutions, it is useful if there are any options to pull up the limitation of RPC call.

**Comment by yoyoyousei** [comment]
In the meanwhile, markus's advice is worked for me. close this issue.

**Comment by J1a-wei** [comment]
We are node operator,same issue with v2.4.0. How to fix it ?
