### ISSUE TITLE
[Question] about tx_history

### ISSUE THREAD

**Issue by rxx** [ripple/rippled#2632]
I can see that method `tx_histrory` is deprecated.
But what should be used instead?
I can't see any similar methods at the docs.
I currently use this method with json_rpc request.

**Comment by mDuo13** [comment]
`tx_history` returns a smattering of "recent" transactions from any source to any destination. I'm not sure what your use case is, but here are some possibilities:

- [`account_tx`](https://developers.ripple.com/account_tx.html) if you want recent transactions that affect a specific account.
- [`ledger`](https://developers.ripple.com/ledger.html) (with `"ledger": "validated"`, `"transactions": true` and `"expand": true`) if you want to see _all_ the transactions from the most recently-validated ledger.
- [`subscribe`](https://developers.ripple.com/subscribe.html) if you want to be notified every time there are new transactions validated.
