### ISSUE TITLE
The new CMake files cause issues on Arch Linux and OpenSUSE-TW

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2637]
On both distros (there are only 3 out there I could find that actually ship Boost 1.67 at the moment) there seems to be an issue with CMake not being able to find libcrypto.so. I am not sure if it is a bug in the upstream CMake script (https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindOpenSSL.cmake), some changes that are unrelated to the FindOpenSSL module (e.g. distro packagers put the library in an unexpected location?) or something in how this script is used in the rippled CMake files.

Weirdly enough on my (Arch based) server 1.1.0-b5 first refused to build, then after a few tries with resetting the git tree to beta4 and pulling beta5 again suddenly it compiled without any problems. I didn't check exactly what I did and am just happy that my server runs again, but I think it could be worth spinning up a container and checking out what's going on.

Here are sample Travis runs from failed and working default builds:

Failed:
Arch: https://travis-ci.org/MarkusTeufelberger/rippled-distrotest/jobs/406776341
Opensuse-tumbleweed: https://travis-ci.org/MarkusTeufelberger/rippled-distrotest/jobs/406776355
(Tumbleweed additionally seems to have issues with finding Boost libraries, for some reason it also seems to be looking for static ones)

Working:
Ubuntu 18.10: https://travis-ci.org/MarkusTeufelberger/rippled-distrotest/jobs/406776358

I'm unsure how to proceed, as there are at least 3 potential error sources (CMake, Distro packaging, rippled), but I hope it is already somewhat helpful to let you guys know that there's potentially some problem out there.

Btw, I'm also unsure why https://github.com/ripple/rippled/blob/develop/Builds/CMake/FindBoost.cmake exists in this repository instead of relying on the one installed with CMake (--> https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindBoost.cmake you might also want to check if you are fulfilling the license terms on that one).

**Comment by JoeLoser** [comment]
Hard to say what the root issue is, but with what you've described, it sure sounds like the CMakeCache was possibly populated with the crypto lib found when you reset to b4 after your b5 build failed. Did you completely wipe your build directory and re-run CMake or did you reuse your build directory? The lack of consistency seems a bit odd.  Given that it works now, it's hard to believe it's a distro packaging issue. If that were the case, I suspect you would have to go out of your way to define some variable (lib dir) when invoking CMake to help CMake find the crypto lib.

On another note, I agree with the idea of using the `FindBoost.cmake` module that ships with CMake. I suspect they did not use it as they didn't have a new enough min CMake version check to guarantee that this file is shipped with that version of CMake. Now that we require CMake 3.9, I don't see it as a problem.

**Comment by mellery451** [comment]
The reason that we've copied `FindBoost.cmake` into our repo is that we often upgrade to the latest boost *before* a new cmake build is available. Every new build of boost requires FindBoost to be updated at the moment, or else you will get unpleasant warnings about inter-module dependencies. I'd rather not require everyone to upgrade to the latest cmake just to support boost-latest. So we've copied that one and intend to update it whenever we upgrade boost versions that we build with.

I'll have a look at the Arch build to see if anything stands out.

**Comment by mellery451** [comment]
static deps builds are the default now which is why it's looking for static boost:

https://github.com/ripple/rippled/blob/09050a860be745c88a54fbcbce1e317c72f2f51e/CMakeLists.txt#L96

..just pass `-Dstatic=OFF` when you configure cmake and that should resolve. I think there's a chance it will resolve the openssl issues as well (you probably don't have static openssl installed).

**Comment by HowardHinnant** [comment]
On macOS with the latest Apple-clang I'm getting:
```
[ 18%] Linking CXX static library libxrpl_core.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libxrpl_core.a(Group.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libxrpl_core.a(Group.cpp.o) has no symbols
```

**Comment by JoeLoser** [comment]
@HowardHinnant this will be fixed in https://github.com/ripple/rippled/pull/2641

On Mac, the archiver complains when you generate an object with no symbols in it other than the default section symbols. In this case, `Group.cpp` generates no extra symbols because it's a blank file more or less.

**Comment by MarkusTeufelberger** [comment]
Thanks, the default changing to static builds was what causes these issues. Both Arch and OpenSUSE don't ship static libraries.
