### ISSUE TITLE
deposit_authorized doesn't check existence of source account

### ISSUE THREAD

**Issue by mDuo13** [ripple/rippled#2640]
If the destination account is not present, the command returns a `dstActMissing` error, but the (relatively) standard `actNotFound` is not used and the command can return success even if the source account isn't present in the ledger.

I suggest returning `actNotFound` if the source account from the request isn't a funded account in the ledger.

Tested on: v1.1.0-b4

**Comment by scottschurr** [comment]
Fixed in version 1.1.0-rc2 by commit d3258c7f1f882b1eed2fb4802fa2d79795b7f7e1
