### ISSUE TITLE
[question] listen new ledgers

### ISSUE THREAD

**Issue by frankegoesdown** [ripple/rippled#2646]
How can I listen new ledgers via json-rpc?
I need to get notifies on new ledgers in blockchain

**Comment by nbougalis** [comment]
You should take a look at https://developers.ripple.com, which contains a lot of very useful information along with examples.

Of particular interest for you might be:
1 https://developers.ripple.com/subscribe.html
2 https://developers.ripple.com/rippleapi-reference.html#ledger

**Comment by miguelportilla** [comment]
This [link](https://developers.ripple.com/subscribe.html) documents the use of the `subscribe`  RPC command. The following will notify you of new validated ledgers.

{
  "command": "subscribe",
  "streams": ["ledger"]
}

**Comment by frankegoesdown** [comment]
thanks a lot
