### ISSUE TITLE
[question] about addresses

### ISSUE THREAD

**Issue by frankegoesdown** [ripple/rippled#2661]
How can I generate a new address for account via rpc?

**Comment by MarkusTeufelberger** [comment]
https://developers.ripple.com/wallet_propose.html with rippled or (better) generate a keypair offline yourself.

**Comment by intelliot** [comment]
It's worth noting that you can install rippled on an offline machine and run
```./rippled wallet_propose```

Another good option is to use ripple-lib, which works offline as well. https://developers.ripple.com/rippleapi-reference.html#generateaddress

**Comment by frankegoesdown** [comment]
Thank you very much
