### ISSUE TITLE
testnet always get insufficient network mode 

### ISSUE THREAD

**Issue by lindachen-chicago** [ripple/rippled#2664]
I'm running rippled in testnet, and always got insufficient network mode. Any idea?

**Comment by BeOleg** [comment]
I get this one on main net as well

**Comment by intelliot** [comment]
@BeOleg If the issue persists, you can create a new issue on github. Include your `server_info`.

**Comment by BeOleg** [comment]
Thanks, we have solved it by settings `[validators_address]`

**Comment by GoLangBro** [comment]
> Thanks, we have solved it by settings `[validators_address]`

And what did you write?
