### ISSUE TITLE
Using 'limit' in book_offers fails in 0.21.0

### ISSUE THREAD

**Issue by sayright** [ripple/rippled#267]
When 'limit' parameter is used in book_offers command, it fails, returning a misleading error message ("error_code": 25,  "error_message": "Invalid field 'taker_pays.currency', not unsigned integer."). 

This is happening in rippled 0.21.0, it was working in 0.20.1

**Comment by HowardHinnant** [comment]
Confirmed that this is now working here: https://ripple.com/build/websocket-tool/#book_offers
