### ISSUE TITLE
rippled with rippled-historical-database

### ISSUE THREAD

**Issue by roma4u** [ripple/rippled#2670]
How to link rippled with rippled-historical-database (https://github.com/ripple/rippled-historical-database) to get the working GET / v2 / payments / method. If someone did, please tell me how?

**Comment by mDuo13** [comment]
It's very hard to do and some parts of the rippled-historical-database require ingestion scripts that are not open source. The nearest thing to instructions are here: https://github.com/ripple/rippled-historical-database#importing-data

And you should direct further questions about the rippled-historical-database software to that repository
