### ISSUE TITLE
How could i make a wallet notification?

### ISSUE THREAD

**Issue by AnkitRathore175** [ripple/rippled#2673]
I have successfully configured the private network using rippled configuration doc,
Now how could i set notification trigger to my wallet based service on recieving any transaction on particular wallet address.
I think there should be an option available to make walletnotify as like bitcoind configurations.
if it's not available than can you please help me to make such kind of implementation
Thanks

**Comment by MarkusTeufelberger** [comment]
https://developers.ripple.com/subscribe.html

**Comment by AnkitRathore175** [comment]
Thanks @MarkusTeufelberger,
Can you please tell me how can i use this subscribe on my rippled configurations, Where do i need to use it.

**Comment by MarkusTeufelberger** [comment]
Which part of the documentation is causing you troubles? rippled does not have something exactly like `walletnotify` though, `subscribe` is using websockets.

**Comment by AnkitRathore175** [comment]
Hi,
Actually I tried to use subscribe by RPC, but didn't get success.
Actually I didn't get the exact way to use subscribe for my each wallet
address on every deposit transactions found by my node. And notify my
remote service like webhook via post http request.
Please suggest me for same
Thanks

**Comment by yxxyun** [comment]
https://developers.ripple.com/subscription-methods.html

> Subscription Methods 
Use these methods to enable the server to push updates to your client when various events happen, so that you can know and react right away. WebSocket API only.
