### ISSUE TITLE
How to use destination tag

### ISSUE THREAD

**Issue by AnkitRathore175** [ripple/rippled#2674]
Hello,
First I would like to appreciate the rippled devs for implementing such great and unique concept for rippled configurations.
Now my query is that, i'm trying to use wallet_propose method by enabling the destination tag, so i can make centralized mechanism to control all the exchange from all sub wallets from Root Wallet.
But i din't get any doc or details regarding the same, by which i can enable my private node to serve new wallet address by using destination tag from root wallet address instead of creating new one
Can you please provide me details or doc to implement such kind of feature during my RPC call for "wallet_propose"  method.
Thanks

**Comment by MarkusTeufelberger** [comment]
https://developers.ripple.com/list-xrp-as-an-exchange.html#flow-of-funds

I'd STRONGLY recommend not using more than one single account per entity (NOT per customer!).

Also a destination tag is just a tag that is attached to a transaction, it doesn't change the address/account that is receiving the funds.

**Comment by intelliot** [comment]
rippled does not manage wallets or tags for you; that needs to be handled by your app or wallet. `wallet_propose` does not interact with destination tags and does not support them directly. Every payment can include a destination tag as part of its data. It's just extra information, but by convention, it is used to identify a "sub wallet."

The destination tag is simply a way for your app or wallet to distinguish between payments intended for different "sub wallets." The destination tag is just a number, and they are not created or given any meaning by the XRP Ledger itself.

Only your app can decide what a destination tag means. Typically, when you see a transaction affecting your account, you would use the destination (or source, as appropriate) tag to look up the corresponding "sub wallet" and adjust its balance accordingly (in your app's database).

**Comment by AnkitRathore175** [comment]
Thanks Guys for your quick and useful supports
