### ISSUE TITLE
Rippled is not syncing

### ISSUE THREAD

**Issue by AnkitRathore175** [ripple/rippled#2676]
I had configured my node for rippled and it was synced before
But after restarting it it stopped syncing and no progress till last 2 days

it's my server_info

{
   "result" : {
      "info" : {
         "build_version" : "1.0.1",
         "closed_ledger" : {
            "age" : 11,
            "base_fee_xrp" : 1e-05,
            "hash" : "EA44716836929D8527E6124E0F6B6D0C62EC103007E93DB62F0F40F11209B274",
            "reserve_base_xrp" : 200,
            "reserve_inc_xrp" : 50,
            "seq" : 976
         },
         "complete_ledgers" : "empty",
         "hostid" : "ip-172-31-0-226",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 2,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "untrustedValidation",
                  "per_second" : 7
               },
               {
                  "job_type" : "ledgerRequest",
                  "per_second" : 1
               },
               {
                  "job_type" : "untrustedProposal",
                  "per_second" : 33
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "job_type" : "writeObjects",
                  "per_second" : 20
               },
               {
                  "job_type" : "heartbeat",
                  "peak_time" : 1
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 475
               },
               {
                  "job_type" : "SyncReadNode",
                  "per_second" : 29
               },
               {
                  "job_type" : "AsyncReadNode",
                  "peak_time" : 9,
                  "per_second" : 670
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 27
               }
            ],
            "threads" : 4
         },
         "load_factor" : 1,
         "network_ledger" : "waiting",
         "peer_disconnects" : "0",
         "peer_disconnects_resources" : "0",
         "peers" : 10,
         "pubkey_node" : "n94pQ5h6q68XRkpFFDiU3EvEFhFTHD6UM3fCGiHavwfdeYcpkk1n",
         "pubkey_validator" : "nHB6saz1FB2P2pF5nyQh52hGTNFrgAsFQKtFpDPgtbYjFfsVghQx",
         "published_ledger" : "none",
         "server_state" : "connected",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "19886593849",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "1223542",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : 0
            }
         },
         "time" : "2018-Aug-31 13:45:01.652667",
         "uptime" : 19888,
         "validation_quorum" : 13,
         "validator_list_expires" : "2018-Sep-06 00:00:00.000000000"
      },
      "status" : "success"
   }
}

And My cfg as below-
[validator_token]
********************
********************

[node_size]
tiny #also used medium and large

[server]
port_rpc_admin_local
port_peer
port_ws_admin_local

[port_rpc_admin_local]
port = 5005
ip = 0.0.0.0
admin = 0.0.0.0
protocol = http

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 0.0.0.0
admin = 0.0.0.0
protocol = ws

#[port_ws_public]
#port = 5005
#ip = 0.0.0.0
#protocol = wss

[node_size]
tiny

[node_db]
type=RocksDB
path=/var/lib/rippled/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=2000
advisory_delete=0

[database_path]
/var/lib/rippled/db

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
#52.11.28.194 51235
#54.94.245.104 51235
#54.201.240.60 51235
#54.238.143.216 51235
r.altnet.rippletest.net 51235
#s.altnet.rippletest.net 51235

[validators_file]
validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
1

Note: i m configuring it for testnet

**Comment by AnkitRathore175** [comment]
Hi @wilsonianb 
Yes i did like that

**Comment by AnkitRathore175** [comment]
I m using aws t2.large instance having 
8 GB RAM,
SSD Volume,
Ubuntu 16.04 LTS

**Comment by AnkitRathore175** [comment]
Hi i got the issue
it's creating this problem only on testnet
it's working fine with main net.
So can anyone provide me latest updated details regarding testnet sync?

**Comment by miguelportilla** [comment]
If you decide to try NuDB, some settings apply only to RocksDB and can be commented out.

```
[node_db]
type=nudb
path=/var/lib/rippled/db/nudb
# open_files=2000
# filter_bits=12
# cache_mb=256
# file_size_mb=8
# file_size_mult=2
# advisory_delete=0
```

AWS SSD performance on some instances is not sufficient. I believe t2.large may have a max burst rate of 3k IOPS. Ideally, you want at least 10k IOPS sustained.

**Comment by AnkitRathore175** [comment]
Hello @intelliot and @miguelportilla 
Thanks for your help, but i tried it, it's working fine for only mainnet, and it's not syncing the testnet ledger.
Looks like some thing is wrong with testnet configurations.
Do anyone have their own live testnet example currenlty? and also please let me know all the configurations details implemented for that.
Thanks

**Comment by nbougalis** [comment]
Can you please show us the contents of your `validators.txt` file. For the testnet it should contain this and _only_ this:

```
[validator_list_sites]
https://vl.altnet.rippletest.net
[validator_list_keys]
ED264807102805220DA0F312E71FC2C69E1552C9C5790F6C25E3729DEB573D5860
```
