### ISSUE TITLE
not connect to network

### ISSUE THREAD

**Issue by shangmacun** [ripple/rippled#2681]
{
   "result" : {
      "state" : {
         "build_version" : "1.0.0",
         "closed_ledger" : {
            "base_fee" : 10,
            "close_time" : 589956380,
            "hash" : "2D6D521E0A716D7FA5F3714CEEA7733BB879B99E81BC8BDA6A8F2FB4F6905A1B",
            "reserve_base" : 200000000,
            "reserve_inc" : 50000000,
            "seq" : 9
         },
         "complete_ledgers" : "empty",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time" : 1999,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               }
            ],
            "threads" : 4
         },
         "load_base" : 256,
         "load_factor" : 256,
         "network_ledger" : "waiting",
         "peer_disconnects" : "0",
         "peer_disconnects_resources" : "0",
         "peers" : 0,
         "pubkey_node" : "n9MuyjPZ1c3v3rAfCRetxTSdFSNbKSoPfw5qThGJR6n58q8nS1zK",
         "pubkey_validator" : "none",
         "published_ledger" : "none",
         "server_state" : "full",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "55009408",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "1521805",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "373892210",
               "transitions" : 1
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : 0
            }
         },
         "time" : "2018-Sep-11 04:46:45.908815",
         "uptime" : 430,
         "validation_quorum" : 19,
         "validator_list_expires" : 590025600
      },
      "status" : "success"
   }
}

rippled.cfg:

[server]
port_rpc_admin_local
port_peer
port_ws_admin_local

[port_rpc_admin_local]
port = 5005
ip = 0.0.0.0
admin = 0.0.0.0
protocol = http

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws

#[port_ws_public]
#port = 5005
#ip = 127.0.0.1
#protocol = wss

#-------------------------------------------------------------------------------

[node_size]
medium

[node_db]
type=RocksDB
path=db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=2000
advisory_delete=0

[database_path]
db

[debug_logfile]
log/debug.log

[ips]
r.ripple.com 51235
54.84.21.230 51235
54.86.175.122 51235
54.186.248.91 51235
54.186.73.52 51235
184.173.45.38 51235
198.11.206.26 51235
169.55.164.29 51235
174.37.225.41 51235

[validators_file]
/opt/ripple/etc/validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "debug" }

[ssl_verify]
1

validators.txt:

[validators]
nHB1FqfBpNg7UTpiqEUkKcAiWqC2PFuoGY7FPWtCcXAxSkhpqDkm
nHUpwrafS45zmi6eT72XS5ijpkW5JwfL5mLdPhEibrqUvtRcMAjU
nHUBGitjsiaiMJBWKYsJBHU2shmYt9m29hRqoh8AS5bSAjXoHmdd
nHUXh1ELizQ5QLLqtNaVEbbbfMdq3wMkh14aJo5xi83xzzaatWWP
nHUgoJvpqXZMZwxh8ZoFseFJEVF8ryup9r2mFYchX7ftMdNn3jLT

[validator_list_sites]
https://vl.ripple.com

[validator_list_keys]
ED2677ABFFD1B33AC6FBC3062B71F1E8397C1505E1C42C64D11AD1B28FF73F4734

**Comment by nbougalis** [comment]
You should remove the following section for your **validators.txt** file:
```[validators]
nHB1FqfBpNg7UTpiqEUkKcAiWqC2PFuoGY7FPWtCcXAxSkhpqDkm
nHUpwrafS45zmi6eT72XS5ijpkW5JwfL5mLdPhEibrqUvtRcMAjU
nHUBGitjsiaiMJBWKYsJBHU2shmYt9m29hRqoh8AS5bSAjXoHmdd
nHUXh1ELizQ5QLLqtNaVEbbbfMdq3wMkh14aJo5xi83xzzaatWWP
nHUgoJvpqXZMZwxh8ZoFseFJEVF8ryup9r2mFYchX7ftMdNn3jLT```
