### ISSUE TITLE
Unable to connect to ripple testnet

### ISSUE THREAD

**Issue by biniama** [ripple/rippled#2683]
Hello,

I have been trying to connect to the JSON-RPC version of ripple testnet but it is timing out.
Can some tell me what is wrong?

Some of the calls I tried:
`curl -s -X POST "https://s.altnet.rippletest.net:51234" -d @- <<-END  
{
    "method": "server_info",
    "params": [ {} ]
}
END`

`curl -s -X POST "https://s.altnet.rippletest.net:51234" -d @- <<-END
{
    "method": "account_info",
    "params": [{ "account": "r4DwTvKKbmciwJQENXs9eekC6d4cuEmkB5" }]
}
END`

I also tried using https://s1.ripple.com but it didn't work.
`curl -s -X POST "https://s1.ripple.com:51234" -d @- <<-END
{
    "method": "server_info",
    "params": [ {} ]
}
END`

**Comment by intelliot** [comment]
What error do you get? I'm not familiar with the syntax you're using (with `@- <<-END`).

You can try something like:
```
curl -X POST -d '{"method": "server_info"}' https://s.altnet.rippletest.net:51234
```

**Comment by biniama** [comment]
The request was timing out and responding nothing. But now it is working.
Thanks, @intelliot.

I guess the server was down when I tried it (I am in CEST timezone).
