### ISSUE TITLE
Ripple enable public signing issue

### ISSUE THREAD

**Issue by antechdemo** [ripple/rippled#2705]
./rippled submit snoPBrXtMeMyMHUVTgbuqAfg1SUTb ' { "Account" : "r9M6gnmEPFEZYL1VEBxcV6oCg5MoEXLNVR", "TransactionType" : "Payment", "Destination" : "rNTwXNnrXhnzviKrDuuBFhjphfM988SD2B", "Amount" : "1000000000" }' 

Signing support in the 'submit' command has been deprecated and will be removed in a future version of the server. Please migrate to a standalone signing tool

[server]
port_rpc_admin_local
port_peer

[port_rpc_admin_local]
port = 5005
ip = 0.0.0.0
admin = 0.0.0.0
protocol = http

[port_peer]
port = 51235
ip = 127.0.0.1
protocol = peer

[node_size]
medium

[node_db]
type=RocksDB
path=/efs/.config/ripple/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=2000
advisory_delete=0

[database_path]
/efs/.config/ripple/db

[debug_logfile]
/efs/.config/ripple/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

 [ips]
 r.altnet.rippletest.net 51235
 52.11.28.194 51235
 54.94.245.104 51235
 54.201.240.60 51235
 54.238.143.216 51235

[validators_file]
validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[signing_support]
true

[ssl_verify]
1

**Comment by nbougalis** [comment]
Is there a question you had? I'm not sure what to respond here.

**Comment by nbougalis** [comment]
I am going to close this issue. If you have another question, please feel free to open another.
