### ISSUE TITLE
REQ: Something like Monero's integrated addresses.

### ISSUE THREAD

**Issue by Crypto2** [ripple/rippled#2709]
Request a new address format integrating the Ripple address and Destination Tag into one address. To keep things simple like account transaction APIs and stuff wouldn't need to report it or even know about the alternate address format; internally Ripple would just think it was received in the classic format.

**Comment by MarkusTeufelberger** [comment]
There used to be "Ripple URIs", but support for these throughout the ecosystem seems to have died with Ripple's end user strategy.

**Comment by yxxyun** [comment]
emmm, Just learned what‘s the integrated addresses.
https://monero.stackexchange.com/questions/3179/what-is-an-integrated-address

**Comment by yxxyun** [comment]
any update? @nbougalis

**Comment by Crypto2** [comment]
Any updates on this or #2708 ?

**Comment by sublimator** [comment]
I'm still getting emails now and then from people asking for help, after I posted my email once to help someone privately. Definitely an issue

**Comment by mDuo13** [comment]
See https://github.com/xrp-community/standards-drafts/issues/6 for discussion
