### ISSUE TITLE
Forbidden from rippled while using auth credentials

### ISSUE THREAD

**Issue by dselyuzhitskiy** [ripple/rippled#2716]
Hello!

I try to enable authentication for admin command requests adding admin_user and admin_password settings in ripped.cfg 

[server]
port_peer
port_rpc_admin

[port_rpc_admin]
port = 5006
ip = 0.0.0.0
admin = 0.0.0.0
protocol = http
admin_user = root
admin_password = root

But rippled response is Forbidden.

`curl --header "Content-Type: application/json" --request POST --data  '{ "method" : "peers", "admin_user" : "root", "admin_password" : "root" }' http://rippled:5006/
Forbidden`

Just dont understand whats wrong

**Comment by ximinez** [comment]
Hi @dselyuzhitskiy. Your request is malformed. Any parameters other than `method` need to be in a `params` array of objects. In this case:
`curl --header "Content-Type: application/json" --request POST --data '{ "method" : "peers", "params" : [ { "admin_user" : "root", "admin_password" : "xxx" } ] }' http://127.0.0.1:5006/`

I'm going to close this issue. Feel free to reopen it or create a new one if you have any more problems.
