### ISSUE TITLE
Comparison value in LexicalCast tests overflows

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2721]
To be specific, this line has issues if `in` is already the largest possible value for that type:

https://github.com/ripple/rippled/blob/63c3fc30d84d4ab4fa4510172470b336e7a5a89b/src/test/beast/LexicalCast_test.cpp#L39

**Comment by nbougalis** [comment]
That's right and the test should probably be changed, but this isn't really an issue. However, two points:

1. Edge cases are covered in [`testEdgeCases`](https://github.com/ripple/rippled/blob/63c3fc30d84d4ab4fa4510172470b336e7a5a89b/src/test/beast/LexicalCast_test.cpp#L126)
2. As we move to C++17 this code will go away in favor of [`std::to_chars`](https://en.cppreference.com/w/cpp/utility/to_chars) and [`std::from_chars`](https://en.cppreference.com/w/cpp/utility/from_chars).

I believe this can safely be closed, but if you feel strongly that the test needs to be corrected, we can incorporate a PR.

**Comment by MarkusTeufelberger** [comment]
This bug leaves errors in UB-sanitizer builds, this was just the easiest one to find the root cause for (and it also was one that happened in less critical code), so I thought I'd report it. No big deal on this one if it gets fixed or not I guess, but it might be worth checking out the other things it finds.
