### ISSUE TITLE
test network can not work

### ISSUE THREAD

**Issue by shangmacun** [ripple/rippled#2722]
use the test net  can not  down load the block , and hold in  "ledger_index" : "2" always, how to  resolve the problem

[ec2-user@ip-10-0-10-101 etc]$ rippled ledger
Loading: "/opt/ripple/etc/rippled.cfg"
2018-Oct-15 07:00:02.105652152 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "result" : {
      "closed" : {
         "ledger" : {
            "accepted" : true,
            "account_hash" : "183D5235C7C1FB5AE67AD2F6CC3B28F5FB86E8C4F89DB50DD85641A96470534E",
            "close_flags" : 0,
            "close_time" : 592901970,
            "close_time_human" : "2018-Oct-15 06:59:30.000000000",
            "close_time_resolution" : 30,
            "closed" : true,
            "hash" : "2B86DD90AACAFF43E42F8071FE3783C1ABDB8CD75DDCC25D5031C33556262820",
            "ledger_hash" : "2B86DD90AACAFF43E42F8071FE3783C1ABDB8CD75DDCC25D5031C33556262820",
            "ledger_index" : "2",
            "parent_close_time" : 0,
            "parent_hash" : "AB868A6CFEEC779C2FF845C0AF00A642259986AF40C01976A7F842B6918936C7",
            "seqNum" : "2",
            "totalCoins" : "100000000000000000",
            "total_coins" : "100000000000000000",
            "transaction_hash" : "0000000000000000000000000000000000000000000000000000000000000000"
         }
      },
      "open" : {
         "ledger" : {
            "closed" : false,
            "ledger_index" : "3",
            "parent_hash" : "2B86DD90AACAFF43E42F8071FE3783C1ABDB8CD75DDCC25D5031C33556262820",
            "seqNum" : "3"
         }
      },
      "status" : "success"
   }
}

**Comment by intelliot** [comment]
Here are some instructions for connecting to the test net: https://github.com/ripple/rippled/wiki/Running-an-XRP-Test-Net-node

If the issue persists, can you post your rippled.cfg and validators.txt files, redacting any private data?

**Comment by intelliot** [comment]
If you're running a server in stand-alone mode, use ledger_accept to advance the ledger: https://developers.ripple.com/advance-the-ledger-in-stand-alone-mode.html

**Comment by nbougalis** [comment]
I am going to close this issue. If you require further assistance, please feel free to open a new one.
