### ISSUE TITLE
Failed to install rippled with yum

### ISSUE THREAD

**Issue by billchengk** [ripple/rippled#2725]
Hi all,
I followed the official instruction to install rippled with yum, but failed at the first step. It seems something wrong with the connection to mirror, and shows as following:

sudo rpm -Uvh https://mirrors.ripple.com/ripple-repo-el7.rpm
Retrieving https://mirrors.ripple.com/ripple-repo-el7.rpm
curl: (35) TCP connection reset by peer
error: skipping https://mirrors.ripple.com/ripple-repo-el7.rpm - transfer failed

Could anyone help? Thanks!

**Comment by nbougalis** [comment]
Looking now, thanks for the report.

**Comment by nbougalis** [comment]
The server was down. It has been restarted, counseled and will try hard to be a better server.

Thank you for your report!
