### ISSUE TITLE
Error: noNetwork in Testnet

### ISSUE THREAD

**Issue by ianeinser** [ripple/rippled#2736]
Hello guys, 

i got a noNetwork situation. I am running docker version of ripple (xrptipbot/rippled). The output of server_info is 

 "result" : {
      "info" : {
         "build_version" : "1.1.0",
         "closed_ledger" : {
            "age" : 13,
            "base_fee_xrp" : 1e-05,
            "hash" : "44F6ED7F16CEAB330AC5CC002744CBF716987E46BAEADD853ABB71CB83BF631F",
            "reserve_base_xrp" : 200,
            "reserve_inc_xrp" : 50,
            "seq" : 2
         },
         "complete_ledgers" : "empty",
         "hostid" : "3e0ed0483ab7",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 0,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "untrustedValidation",
                  "per_second" : 2
               },
               {
                  "job_type" : "untrustedProposal",
                  "per_second" : 5
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "job_type" : "writeObjects",
                  "per_second" : 1
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 19
               },
               {
                  "job_type" : "diskAccess",
                  "per_second" : 1
               }
            ],
            "threads" : 6
         },
         "load_factor" : 1,
         "network_ledger" : "waiting",
         "peer_disconnects" : "0",
         "peer_disconnects_resources" : "0",
         "peers" : 2,
         "pubkey_node" : "n9LMNTAZrX5T4GiCj4P5kERUR7QiGbwwUd56D2u3ywYm2zznZJK3",
         "pubkey_validator" : "none",
         "published_ledger" : "none",
         "server_state" : "connected",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "23456150",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "1502338",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : 0
            }
         },
         "time" : "2018-Oct-23 23:20:43.351196",
         "uptime" : 25,
         "validation_quorum" : 4294967295,
         "validator_list_expires" : "2018-Nov-06 00:00:00.000000000"
      },
      "status" : "success"

The rippled.cfg is
[ips]
#Mainet
#r.ripple.com 51235
r.altnet.rippletest.net 51235
52.11.28.194 51235
54.94.245.104 51235
54.201.240.60 51235
54.238.143.216 51235
54.213.214.68 51235

and the validators.txt is
[validator_list_sites]
https://vl.altnet.rippletest.net

[validator_list_keys]
ED264807102805220DA0F312E71FC2C69E1552C9C5790F6C25E3729DEB573D5860

[validators]
nHUhG1PgAG8H8myUENypM35JgfqXAKNQvRVVAFDRzJrny5eZN8d5
nHBu9PTL9dn2GuZtdW4U2WzBwffyX9qsQCd9CNU4Z5YG3PQfViM8
nHUPDdcdb2Y5DZAJne4c2iabFuAP3F34xZUgYQT2NH7qfkdapgnz
nHB1X37qrniVugfQcuBTAjswphC1drx7QjFFojJPZwKHHnt8kU7v
nHUkAWDR4cB8AgPg7VXMX6et8xRTQb2KJfgv1aBEXozwrawRKgMB

[validation_quorum]
3

what do i miss? thanks

**Comment by MarkusTeufelberger** [comment]
It takes more than 25 seconds to sync with the network usually.

**Comment by ianeinser** [comment]
But I have left the server running for days and still got that problem. I am running it in Google Cloud

**Comment by MarkusTeufelberger** [comment]
The `server_info` output from above is only 25 seconds after startup. Also the config file is not the full one you're using, right? Anyways, you seem at least initially to have had 2 peers. What does `server_info` say now and what's your whole config file?

**Comment by nbougalis** [comment]
**Remove** the following from **validators.txt**:

```
[validators]
nHUhG1PgAG8H8myUENypM35JgfqXAKNQvRVVAFDRzJrny5eZN8d5
nHBu9PTL9dn2GuZtdW4U2WzBwffyX9qsQCd9CNU4Z5YG3PQfViM8
nHUPDdcdb2Y5DZAJne4c2iabFuAP3F34xZUgYQT2NH7qfkdapgnz
nHB1X37qrniVugfQcuBTAjswphC1drx7QjFFojJPZwKHHnt8kU7v
nHUkAWDR4cB8AgPg7VXMX6et8xRTQb2KJfgv1aBEXozwrawRKgMB

[validation_quorum]
3
```
