### ISSUE TITLE
Determine what addresses RippleState objects contribute to owner count?

### ISSUE THREAD

**Issue by whotooktwarden** [ripple/rippled#2741]
I can't find anything on the dev portal about **exactly** how to determine what RippleState objects are affecting my two accounts with owner counts of 5 and 25 so that I may reduce my Reserve to be able to reclaim my XRP.  

Ripple support will not respond since Larsen was kind enough to include a clause in our little agreement that Ripple Inc will not communicate with me anymore, so will someone from the team who isn't afraid of possibly being fired for assisting me with this issue please tell me how to determine what addresses' RippleState objects contribute to my owner count? I have been looking into how to accomplish reclaiming my XRP on these two accounts for months now & I just want it done and over with.

Thank you to anyone who decides to respond.

rGgS5Hw3PhSp3VNT43PDTXze9YfdthHUH
r3ADD8kXSUKHd6zTCKfnKT3zV9EZHjzp1S

**Comment by MarkusTeufelberger** [comment]
https://developers.ripple.com/ripplestate.html#contributing-to-the-owner-reserve might help.

You might also want to take a look at the output of https://developers.ripple.com/account_objects.html and tone down the aggressive tone.

**Comment by whotooktwarden** [comment]
I took a bit of time to take a look into the account objects and my accounts with the websocket tool and I have some questions about how this will exactly help me because I am having trouble understanding the whole abstract of the high & low account, an exactly how it applies to my case.

I will try to take a look at this again tomorrow and reply with a much needed attitude adjustment then (it's my birthday tomorrow so I won't be moody & air anymore dirty laundry with/about Ripple as a company).

**Comment by whotooktwarden** [comment]
Okay, so I was able to remove some trust-lines from both of these accounts, entirely reducing my reserve to 20 XRP on one of them but the other account still has an owner count of over 20 and a reserve of 135 XRP that I would like to reclaim.  

How with the websocket tool calling the account info can I determine which of these trust-lines I have to take action on?  I have over 1000 trust-lines on this one account, so I would like to know exactly what I am looking for within the output. I would appreciate it if someone is able to describe in more detail about how the whole high account & low account relationship works.  Thanks.
