### ISSUE TITLE
Native Debian/Ubuntu server version is required.   STATUS?

### ISSUE THREAD

**Issue by rafael5** [ripple/rippled#2756]
Rippled comes only with a CentOS/RHEL  yum installer, but no Debian/Ubuntu  apt-get installaller:   https://developers.ripple.com/install-rippled.html

I tried to install the yum-utils for the Debian version but __yum-utils does not exist on the apt-get repository__.  I therefore downloaded the yum-utils.deb package directly (https://launchpad.net/ubuntu/+source/yum-utils/1.1.31-3), but this has not been updated since 2015,  and has no current installation scripts.  __It is thus impossible to install Ripple on Ubuntu 18.04__

Since the most prevalent cloud server is Debian/Ubuntu (see links below), and the latest packages appear on Debian/Ubuntu (which developers need) could you please provide a native Debian installation under apt-get?  

Thank you! 
Rafael

W3TECHS - https://w3techs.com/technologies/details/os-linux/all/all
Ubuntu - 34.1%
Debian - 31.4%
CentOS - 20.6%
Red Hat - 3.7%
Gentoo - 2.7%

W3COOK - http://www.w3cook.com/os/ubuntu
Ubuntu - 29.9%
CentOS - 24.57%
Debian - 11.31%
Fedora - 0.68%
Red Hat - 0.01%

THE CLOUD MARKET - http://thecloudmarket.com/stats
Ubuntu - 57.5%
Windows - 7.8%
Red Hat - 4.8%
CentOS - 3.7%
Fedora 1.4%

OPENSTACK - http://www.openstack.org/assets/survey/April-2016-User-Survey-Report.pdf (Page 47)
Ubuntu - 55% (With an potential growth of up to 19%)
CentOS - 20% (With an potential growth of up to 7%)
Red Hat - 16% (With an potential growth of up to 4%)
SUSE - 2% (With an potential growth of up to 1%)
Debian - 3% (With an potential growth of up to 0%)

**Comment by nbougalis** [comment]
Apologies for the inconvenience and thank you for opening this issue and for providing these statistics.

Making a native Ubuntu package available is on the roadmap. I don’t have a timeframe at this point, but if the [instructions](https://developers.ripple.com/install-rippled.html#installation-on-ubuntu-with-alien), which require the use of `yum-utils` and `alien` don’t work on the latest version of Ubuntu, we are going to have to make a native package a much higher priority.

**Comment by rafael5** [comment]
Correct. The current instructions for Ubuntu installation fail.

This is  because one gets the error message  "yum-utils not found" when
attempting apt-get install.

Could you please provide a workaround?  Or at least specify which version
of Ubuntu server for which one can install yum-utils?
Ubuntu 16.04?  14.04?

**Comment by nbougalis** [comment]
I don’t have a workaround to provide at this time; we will have to look into this and get back to you.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MarkusTeufelberger** [comment]
If you manage to get a package into Debian Testing until beginning of next year, rippled would be already included in Debian Buster and also probably soon after end up in Ubuntu too.

A build process similar to the one in https://github.com/ripple/rippled-package-builder will however not be good enough to make it in any distribution (the one in that repo also likely won't make it into Fedora for example).

An easy solution would be to just build rippled yourself - since it requires a version of Boost that's only available on Ubuntu 18.10, you'll anyways have a hard time installing it from a package/PPA.

**Comment by rafael5** [comment]
Correct.  yum-utils exists for bionic, but it is not in the apt-get repository.    
This is the error message:

> rafael@u1804:~$ sudo apt-get install yum-utils
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package yum-utils

**Comment by MarkusTeufelberger** [comment]
What do you mean by "an apt-get repository"? What's in your `/etc/apt/sources.list` file? Try running `sudo apt-get update` before trying to install this...

There's no need for a PPA, this package is in universe and thus part of Ubuntu. Please post the output of `apt-cache show yum-utils`...

**Comment by drizzt** [comment]
Why don't do a docker container that uses centos image instead of wasting effort to support multiple distros?

**Comment by nbougalis** [comment]
@MarkusTeufelberger: what do you mean "rippled is packaed upstream"? Is a Alpine Linux package for `rippled` available? I looked at https://pkgs.alpinelinux.org/packages and didn't see anything?

I believe that we should continue to provide `rippled` packages for RHEL and CentOS, and add at a minimum, Ubuntu. I want to get an official Windows package out, complete with installer. Personally, I'd love an OpenBSD build (I know that @empatogen was tinkering there) as well, but it may be difficult to officially support one in the absence of a maintainer.

**Comment by MarkusTeufelberger** [comment]
>  Is an Alpine Linux package for rippled available? 

Yes. Currently in "edge" and probably will end up in Versions >=3.9: https://pkgs.alpinelinux.org/package/edge/community/x86_64/rippled

Ubuntu would be a good fit, but only Ubuntu 18.10 has recent enough boost libraries at the moment, so no LTS until 2020... but probably that's anyways not something you want.

**Comment by mDuo13** [comment]
Ubuntu `.deb` package is available as of version 1.3.1. See the [Updated Ubuntu install instructions](https://xrpl.org/install-rippled-on-ubuntu.html) for details.
