### ISSUE TITLE
About source tag and dest tag

### ISSUE THREAD

**Issue by qiluge** [ripple/rippled#2757]
If i have a ripple address and a tag 1234, when i send a tx to a rippled account that tag is 4321, should i use bitwise-or operator on 4321 and https://developers.ripple.com/transaction-common-fields.html#flags-field and set 1234 to SourceTag value or use bitwise-or operator on 1234 and SourceTag value?

**Comment by MarkusTeufelberger** [comment]
Tags are not flags, they are separate fields.

**Comment by qiluge** [comment]
So how can i set dest tag while call the RippleApi or send transaction?

**Comment by nbougalis** [comment]
This example `Payment` transaction (in `json` format) for 500 XRP shows how to set both the source and destination tags:

```
{
  "TransactionType" : "Payment",
  "Account" : "rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn",
  "Destination" : "ra5nK24KXen9AHvsdFTKHSANinZseWnPcX",
  "SourceTag": 1234,
  "DestinationTag": 5678,
  "Amount" : "500000000",
  "Fee": "12",
  "Flags": 2147483648,
  "Sequence": 1,
}
```

**Comment by qiluge** [comment]
thank you very much!
