### ISSUE TITLE
Remove deprecated --rpc_port commandline option

### ISSUE THREAD

**Issue by mDuo13** [ripple/rippled#2764]
As far as I can tell, the `--rpc_port` method is not just deprecated, but actually just _doesn't work_ anymore. In any case, it's been deprecated for a long time and the replacement (providing a port in the `--rpc_ip` command) works fine.

Still, it's [listed in the usage statement](https://github.com/ripple/rippled/blob/2a8b0e4b88ed03729506a758615c51b600717d38/src/ripple/app/main/Main.cpp#L350-L352).

It seems like [the code to use it is still there](https://github.com/ripple/rippled/blob/2a8b0e4b88ed03729506a758615c51b600717d38/src/ripple/app/main/Main.cpp#L616-L636), but I wasn't able to get it to work on v1.1.1, personally. I got the "WARNING: using deprecated rpc_port param." but it failed to connect, whereas specifying the port in the `--rpc_ip` parameter worked.

**Comment by thejohnfreeman** [comment]
Looks like [this line](https://github.com/ripple/rippled/blob/2a8b0e4b88ed03729506a758615c51b600717d38/src/ripple/app/main/Main.cpp#L624) is missing an assignment back to `res`. I'm adding it now, but if we think it's been deprecated long enough and ready for removal, please let me know (@nbougalis).
