### ISSUE TITLE
testnet not responding

### ISSUE THREAD

**Issue by d-yokoi** [ripple/rippled#2767]
I'm trying to connect to the testnet according to the document but the server does not respond at all.
https://developers.ripple.com/xrp-test-net-faucet.html

```
[NotConnectedError(connect ETIMEDOUT 35.158.96.209:51233, { Error: connect ETIMEDOUT 35.158.96.209:51233
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '35.158.96.209',
  port: 51233 })]
```

I first tried a week ago, and even now the situation does not change.

I can connect to the mainnet (`wss://s1.ripple.com:443`).

Thanks.

**Comment by MarkusTeufelberger** [comment]
What software are you using to connect to this machine? Rippled is not written in Javascript and I see some `*.js` files mentioned in your issue...

**Comment by d-yokoi** [comment]
@MarkusTeufelberger 
Thank you for your reply.

I'm actually using ripple-lib.
https://github.com/ripple/ripple-lib

I am not sure where to report this issue so I'm sorry if it's not appropriate.

**Comment by intelliot** [comment]
Are you using wss://s.altnet.rippletest.net:51233 ?

Feel free to open an issue on the ripple-lib repo

**Comment by d-yokoi** [comment]
@intelliot 

Yes, I'm trying to connect to `wss://s.altnet.rippletest.net:51233`.

I also tried JSON-RPC(`https://s.altnet.rippletest.net:51234`) but could not connect to it either.

**Comment by intelliot** [comment]
@d-yokoi Can you share the code that you're using to connect?

Here's a quick example that works for me:
```
let {RippleAPI} = require('ripple-lib');
let api = new RippleAPI({server: 'wss://s.altnet.rippletest.net:51233'}); 
api.connect().then(() => {
  console.log('connected');
  return api.getServerInfo().then(result => {
    console.log(JSON.stringify(result, null, 2));
  })
}).catch(console.error);
```

**Comment by d-yokoi** [comment]
@intelliot 

Now I find that the problem is in our office network settings.

I can connect to the testnet from my personal computer or virtual machines on AWS.

Anyway, many thanks for your kind advice.
