### ISSUE TITLE
Proposal:  Allow Government Entities to announce ownership of issuing account

### ISSUE THREAD

**Issue by whotooktwarden** [ripple/rippled#2771]
This is probably far out into the future and probably already on Ripple Inc's radar in some form already but I just have to be the annoying one and write this before someone else takes the opportunity away from me.

I propose that the rippled team of developers discuss internally with the Ripple Inc Legal/Regulation teams for their plans for the future if a Government Entity were to wish to cryptographically sign a promise that they are acting with some kind of authority provided through a Government.  I believe that they may wish to set an account flag.  I suggest that this action consume a large portion of the account's XRP and that the flag can not be unset unless some kind of condition is set/met that requires the flag to no longer be active I.E. by a specified ledger, collapse, or restructuring of Government.

That is all.  EDIT:  My exact [reasons](https://forum.ripple.com/viewtopic.php?f=1&t=9305&p=76027#p76027) why this issue and the previous two I have raised are necessary for my use case are a separate discussion best not to be raised on github available on the official Ripple forums.

**Comment by nbougalis** [comment]
I don't think this is an appropriate feature for XRP Ledger and I am very much opposed to it.

First, it's unclear how anyone could verify that such a transaction was performed by someone "acting with some kind of authority provided through a Government."

Second, if a government entity wants to announce "ownership" of an account, all they need to do is demonstrate the ability to sign a message with the account's secret key. No further on-ledger mechanism is necessary. For example, if [Robonia](https://futurama.fandom.com/wiki/Robonia) wanted to claim an account, Robonia's government could pass legislation requiring that a transaction with sequence number 1 and the following memo be signed with the secret key associated with the **rRobonia** account and submitted to the network for processing: 

>*The account **rRobonia** is the official account of the Grand Duchy of Robonia. This message is being submitted as a memo in a duly signed transaction with sequence number 1 on said account, in accordance with public law 123.456/3004, passed by the Robonian Assembly.*

Note that this applies to any entity really. Substitute [ACME Corporation](https://en.wikipedia.org/wiki/Acme_Corporation) for "Robonia", "Board of Directors" for "Robonian Assembly" and make other relevant tweaks.

Lastly, the Ledger has no way of knowing when many of the kinds of conditions you suggest should be met would be met to unset the flags; in fact, for several of them, it may not be possible to actually reach consensus about whether such an incident has in fact taken place even if you were to delegate the task to human operators.

I believe that this issue should be closed. As is, it's non-actionable and I intend to close it in 24 hours. If you are interested in discussing this issue further, feel free to do this on another forum.

**Comment by whotooktwarden** [comment]
I knew that there would be obvious problems that the ledger would have no way of dealing with really (collapse/restructuring of Government) which is why I wanted to see what could potentially be done to solve those problems.

Your idea of legislation plus a memo added to the ledger would satisfy most people that an issuer is acting with some kind of authority.  Perhaps adding a line to the memo stating that if another memo is not posted by a certain date/ledger sequence then to not trust that the account is operating with the express authority of the Government/Organization in question would in some way be able to satisfy the collapse/restructuring scenarios.

Just thinking about the future an I will discuss the topic on the forums in the future, this can be closed if no one else has anything they would like to contribute.
