### ISSUE TITLE
testnet is not sync

### ISSUE THREAD

**Issue by purplecity** [ripple/rippled#2775]
I've looked at some of the questions I've been asking。but still error。

server_info.   "complete_ledgers" : "empty"

{
   "result" : {
      "state" : {
         "build_version" : "1.1.1",
         "closed_ledger" : {
            "base_fee" : 10,
            "close_time" : 595941480,
            "hash" : "CA94B8C605A6479460AF158BC95E4143468E7A5CEBF30D42105A2FF8A88AD308",
            "reserve_base" : 200000000,
            "reserve_inc" : 50000000,
            "seq" : 7
         },
         "complete_ledgers" : "empty",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time" : 2000,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "untrustedValidation",
                  "per_second" : 5
               },
               {
                  "job_type" : "untrustedProposal",
                  "per_second" : 5
               },
               {
                  "job_type" : "ledgerData",
                  "peak_time" : 5
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "job_type" : "writeObjects",
                  "per_second" : 3
               },
               {
                  "avg_time" : 5,
                  "job_type" : "sweep",
                  "peak_time" : 19
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 26
               },
               {
                  "job_type" : "SyncReadNode",
                  "per_second" : 7
               },
               {
                  "job_type" : "AsyncReadNode",
                  "per_second" : 1
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 6
               }
            ],
            "threads" : 6
         },
         "load_base" : 256,
         "load_factor" : 256,
         "network_ledger" : "waiting",
         "peer_disconnects" : "0",
         "peer_disconnects_resources" : "0",
         "peers" : 2,
         "pubkey_node" : "n9Lz8wd1phnTaixzDvnEp1zHdGSqPUeSN9H1ajQ6gFXosPmtSWT9",
         "pubkey_validator" : "none",
         "published_ledger" : "none",
         "server_state" : "connected",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "311645645",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "1254422",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : 0
            }
         },
         "time" : "2018-Nov-19 11:18:09.192339",
         "uptime" : 314,
         "validation_quorum" : 4294967295,
         "validator_list_expires" : 0
      },
      "status" : "success"
   }
}

Here is my cfg 
<img width="753" alt="wechatimg3" src="https://user-images.githubusercontent.com/38914615/48704296-20a46f00-ec31-11e8-9cbc-dfe37382a5e7.png">
<img width="366" alt="wechatimg4" src="https://user-images.githubusercontent.com/38914615/48704297-213d0580-ec31-11e8-8073-c0aefc40dea1.png">

Here is log file:
![wechatimg5](https://user-images.githubusercontent.com/38914615/48704448-87c22380-ec31-11e8-9834-23251fe66a70.jpeg)

**Comment by purplecity** [comment]
node_size I had set: tiny

**Comment by nbougalis** [comment]
Your server encountered difficulties retrieving the UNL. I just checked locally and could retrieve the file just fine.

Can you change the line that says:

    https://vl.altnet.rippletest.net

To this:

    http://vl.altnet.rippletest.net

and try again please?We’ve had instances where this solved the problems that server operators had.

**Comment by mDuo13** [comment]
Closing this stale issue. Feel free to reopen if you have new details to add.
