### ISSUE TITLE
https://mirrors.ripple.com/rpm/2/stable/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found Trying other mirror.

### ISSUE THREAD

**Issue by purplecity** [ripple/rippled#2776]
this is my first to install ripple。 at ubuntu（last issue）failed。 so I get aws ec2 machine to install flowing ：
https://developers.ripple.com/install-rippled-on-centos-rhel-with-yum.html。
 but when ·sudo yum install --enablerepo=ripple-stable rippled·：

error happend，It's really bad。

<img width="1126" alt="wechatimg6" src="https://user-images.githubusercontent.com/38914615/48708713-3ff5c900-ec3e-11e8-9095-735db4301e22.png">

**Comment by nbougalis** [comment]
I will go ahead and check the repo to make sure there’s no issues, but the error message you encountered could be the result of a transient error; have you tried repeating the command?

**Comment by purplecity** [comment]
thanks。 i vmware install centos  and install ripple ok。 maybe  aws centos environment problem thanks

**Comment by nbougalis** [comment]
Thanks. We'll try to replicate this. In the meantime, I'm closing this issue.
