### ISSUE TITLE
Trying to Understand MessageKey

### ISSUE THREAD

**Issue by whotooktwarden** [ripple/rippled#2780]
https://developers.ripple.com/accountroot.html states that the MessageKey is "A public key that may be used to send encrypted messages to this account. In JSON, uses hexadecimal. No more than 33 bytes."  Is this field able to hold a PGP public key in the stated format or does it hold the public key (ripple address) of another ripple account?  I would have asked this on the official forums but it is a ghost town, I would not likely get a reply any time soon.

**Comment by MarkusTeufelberger** [comment]
33 bytes is enough for a public key if you use elliptic curves crypto, e.g. ed25519.

**Comment by whotooktwarden** [comment]
Alright, thanks for the answer.  It seems that Kleopatra already has ed25519 support so I created a new key and I converted the public block to hex but then my client refused me the opportunity to attempt to submit the transaction due to an invalid format error.  

I tried removing the spaces between the characters, shifting them from lower case to upper case, and etc but I could not get the client to accept my converted key.  I made sure when creating the PGP key that I unchecked the option to add further crypto to the key besides just the ed25519, so I am sure that the key I created is okay I just think it is something to do with the hexadecimal, any suggestions?  I'm using the ripplerm/ripple-wallet client to do this by the way.

**Comment by rrozek** [comment]
heyy, i know this topic is a bit old, but i might have found an answer to your question.

![image](https://user-images.githubusercontent.com/5141787/51264921-db45b900-19b7-11e9-9074-bf7a1fcb9c39.png)

(https://developers.ripple.com/cryptographic-keys.html)
so, you can go to:
http://ed25519.herokuapp.com/ 
generate a keypair, 
convert public key from base64 and then to hex, 
prepend 0xED
wrap that up and add to your tx json. good luck
