### ISSUE TITLE
Ripple doesn't update from 1.0.0 to 1.1.1 

### ISSUE THREAD

**Issue by Gillian17** [ripple/rippled#2787]
Hi I've started to run a ripple server I followed the installation at https://developers.ripple.com/install-rippled-on-ubuntu-with-alien.html 

usr@server:~$ sudo /opt/ripple/bin/rippled version
Loading: "/etc/opt/ripple/rippled.cfg"
2018-Nov-23 00:44:18.347213708 HTTPClient:NFO Connecting to 127.0.0.1:5125

{
   "result" : {
      "status" : "success",
      "version" : {
         "first" : "1.0.0",
         "good" : "1.0.0",
         "last" : "1.0.0"
      }
   }
}

I've tried to follow the update ripple version manually and followed https://developers.ripple.com/update-rippled-manually-on-ubuntu.html. It didn't show any error but when I check the version of ripple it still the same version.

Hope someone can help me.

**Comment by MarkusTeufelberger** [comment]
That's not the version of rippled...

Try running either `sudo /opt/ripple/bin/rippled server_info` or `sudo /opt/ripple/bin/rippled --version`

**Comment by intelliot** [comment]
@Gillian217 In `rippled.cfg`, delete or comment the line `54.213.214.68 51235`.

**Comment by mDuo13** [comment]
Closing this stale issue. Feel free to reopen if you have more details.
