### ISSUE TITLE
[Question] TxFormats LedgerFormats changes restrictions

### ISSUE THREAD

**Issue by rrozek** [ripple/rippled#2788]
Hello rippled team!

I'm wondering what are the restrictions of modifying/adding new TxFormats or LedgerFormats (new Ledger objects or new Tx types) to keep backward compatibility?

I've added an extra object to AccountRoot Ledger Object which is filled in with new Tx type.
When my own network gets an update it seems that nodes running 'old' version are crashing soon after first submission of new Tx type. I'm wondering if the reason for that is new Tx type (i doubt that) or that 'old' version cannot understand the new AccountRoot version proposed by other validators (more likely)?

Too keep backward compatibility is it required to only add new stuff as new ledger objects?

thanks a lot!
Jakub Rojek

**Comment by nbougalis** [comment]
You'd have to add new types as `SOE_OPTIONAL` (or, if it made sense and was supported for the type, `SOE_DEFAULT`) and you would need to create an amendment for your new feature.

**Comment by rrozek** [comment]
Hi Nik, thank you for your points.
I've added the field as `SOE_OPTIONAL` in `LedgerFormats` obviously, but not a 'simple type' like `SF_U32` but the 'inner object' (`SField`) which has its constraints defined in `InnerObjectFormats` class. And in the definition of that object there are two fields, one `SOE_REQUIRED` and one `SOE_OPTIONAL`. Maybe that's the case. I'll change all of them to optionals and see if it still breaks backward compatibility. 
thank you for that point!

**Comment by rrozek** [comment]
On the other hand... for older version it makes no difference if the field is required or optional as it does not know about existance of that field anyways... The same for marking that with relevant amendment. Also, i reviewed commits to `LedgerFormats` in rippled and couldn't find a commit which would extend the existing `LedgerFormats`. Maybe it is simply forbidden by protocol implementation? (which still has lots of mysteries for me ;) )

**Comment by nbougalis** [comment]
This sort of change needs to be coordinated: servers that don’t have the new code won’t be able to understand the objects.

**Comment by rrozek** [comment]
Hello Nik!
I guess i understand what you mean.
I'll close the issue now. thank you!
