### ISSUE TITLE
[QUESTION] rippled without fully sync

### ISSUE THREAD

**Issue by yura-sutnuk** [ripple/rippled#2792]
Hi, can i somehow install rippled for creating transactions and detect deposits for certain addresses and not download all 8.5 TB of blockchain?

**Comment by garay-daniel** [comment]
Yes, you can have a node up and running on the network very quickly. You need minimal ledger history to sync. 

Check out https://developers.ripple.com/manage-the-rippled-server.html for more.

**Comment by yura-sutnuk** [comment]
sorry, maybe i somesing missed but related to the topic i found only node_size at config page but if i right understand it is related to RAM memory which will be used. in config file of ripple i found discribed of ledger_history and it says that default is 256. it is big or small?

**Comment by yxxyun** [comment]
https://developers.ripple.com/capacity-planning.html#configuration-settings

> Historical Data
> The amount of historical data that a rippled server keeps online is a major contributor to required storage space. At the time of writing (2018-10-29), a rippled server stores about 12GB of data per day and requires 8.4TB to store the full history of the XRP Ledger. You can expect this amount to grow as transaction volume increases across the XRP Ledger network. You can control how much data you keep with the online_delete and advisory_delete fields.
> 
> Online deletion enables pruning of rippled ledgers from databases without any disruption of service. It only removes records that are not part of the current ledgers. Without online deletion, those databases grow without bounds. Freeing disk space requires stopping the process and manually removing database files.

**Comment by yura-sutnuk** [comment]
oh yes, i really missed it, thanks. so i need just set up online delete and  last question, how big the minimal ledger history?
