### ISSUE TITLE
Does the ripple testnet support locally generated account ?

### ISSUE THREAD

**Issue by readygo586** [ripple/rippled#2798]
step1.  Generate secrete and address in my computer first.  
step2. In XRP testnet,   try to  deposit 100 XRP to this new generated address, it shows the following message " _Destination does not exist. Too little XRP sent to create it._"

So, Dose Ripple testnet support locally generated account?

**Comment by MarkusTeufelberger** [comment]
You should really send 100 XRP, maybe you tried to send 100 drops instead? Alternatively the testnet could have a different reserve level, but I don't think that's the case.

**Comment by readygo586** [comment]
Tesnet does not accept locally generated address, and in mainnet, this address works well(can accept other's transfer as except)
