### ISSUE TITLE
Transaction hash missing from query

### ISSUE THREAD

**Issue by Silkjaer** [ripple/rippled#2803]
When querying for a ledger using the public rippled ledger command `expand: true` and `binary: true`, the transaction hash is not included. It seems that the only way to retrieve this is by querying for `expand: false`.

Looking in transaction.db the individual transaction hash is not in the blob either, so it makes sense. 

I suggest to include the hash as a key next to the binary blob in the response.

**Comment by mDuo13** [comment]
I think that's a good idea.

In the meantime, you _can_ calculate the hash of a transaction from the binary blob:

1. Read the hex blob into a buffer
2. Prefix with `0x54584E00`
3. Calculate the SHA-512 of the buffer (including the prefix)
4. Take the first half of the output (256 bits, aka 32 bytes, aka 64 characters of hex). That's the transaction hash.

**Comment by Silkjaer** [comment]
Thank you for the “workaround”! That will definitely work for me right now.

**Comment by JoelKatz** [comment]
The point of querying in binary is to not make the server do work that the client can easily do. This seems to defeat that point.

**Comment by Silkjaer** [comment]
I agree. Calculating the hash client-side works great!
