### ISSUE TITLE
Exception occurred constructing serialized transaction

### ISSUE THREAD

**Issue by songhungbk** [ripple/rippled#2806]
When I sign transaction by sign_for with tx_json:
tx_json = {
  "TransactionType": "TrustSet",
  "Account": "rfY4aCzLGNVchi1BW81EWK5juW72AuFfpU",
  "Destination": "rLyxUnFLCk3RX6u5qRKEs1TKHHjNpsFQsG",
  "Amount": "10000000",
  "Sequence": 3,
  "SigningPubKey": "",
  "Fee": "30000"
}

After sign with first key in signerlist of account "rfY4aCzLGNVchi1BW81EWK5juW72AuFfpU" which request return error:
{"deprecated"=>
  "This command has been deprecated and will be removed in a future version of the server. Please migrate to a standalone signing tool.",
 "error"=>"internal",
 "error_code"=>71,
 "error_message"=>"Exception occurred constructing serialized transaction",
 "request"=>
  {"account"=>"rHx3KQhZnRQjoyzYvKs76D3RG7kPFeFn4R",
   "command"=>"sign_for",
   "secret"=>"<masked>",
   "tx_json"=>
    {"Account"=>"rfY4aCzLGNVchi1BW81EWK5juW72AuFfpU",
     "Amount"=>"10000000",
     "Destination"=>"rLyxUnFLCk3RX6u5qRKEs1TKHHjNpsFQsG",
     "Fee"=>"30000",
     "Sequence"=>3,
     "SigningPubKey"=>"",
     "TransactionType"=>"TrustSet"}},
 "status"=>"error"}

I sign this transaction on testnet. Please help me. Thank you so much.

**Comment by scottschurr** [comment]
It looks to me like you have a malformed `TrustSet` transaction.  `"Amount"` is not a valid field for `TrustSet`.  Perhaps you meant `"LimitAmount"` (which must be a non-XRP currency)?  Documentation for `TrustSet` can be found here: https://developers.ripple.com/trustset.html.

By the way, you're probably thinking that's not a very good error message.  We agree.  The situation should be improved with the 1.2.0 release.

**Comment by songhungbk** [comment]
@scottschurr  Thank you so much.
