### ISSUE TITLE
Create new "health check" method

### ISSUE THREAD

**Issue by mDuo13** [ripple/rippled#2809]
The `server_info` command is very cluttered and in many cases it's not easy to diagnose whether the server is healthy or not from that. A simple "health check" method could make it easier to monitor `rippled` with industry-standard tooling and also easier to diagnose manually as well.

Ideally:

- It would be an HTTP GET call, to maximize compatibility with common monitoring software. (Maybe using the same port as "crawl"?)
- It would report a health score ("Healthy", "Warning", or "Critical") depending on several factors:
    - Age of last validated ledger is < 7s (healthy), <=20s (warning) or >20s (critical)
    - Not amendment blocked (critical) and amendments unknown to the server don't currently have a majority in the network (warning)
    - Number of peers is >7 (healthy) <5 (warning unless configured w/ `peer_private`), or 0 (critical)
    - `server_state` is `full`/`validating`/`proposing` (healthy), `syncing`/`tracking`/`connected` (warning), or `disconnected` (critical)
    - Maybe a `load_factor` based warning, too? Not sure what thresholds to use there.
- If the health score is not "healthy", it reports which factor(s) are not healthy. If it's healthy, the word "HEALTHY" is the only thing in the response.

**Comment by ximinez** [comment]
Speaking as an engineer, not an end-user, I think that reporting the values of the individual factors _along with_ the health score could be valuable. 
Reasons:
1. Some people just like to watch the blinkenlites, and having these top factors only may be interesting.
2. Advanced users may want to monitor _how_ healthy their node is. For example, if I'm running a hub, I would expect hundreds of peers, not just 7. It would be handy to get this information in one place so I can confirm the node thinks itself is healthy, but I can keep an extra watch on the number of peers, and have some local alert if it drops below my own threshold. Yes, an advanced user can get this info from `server_info`, but including it here, when we also return it when there are problems, saves an RPC call.

**Comment by MarkusTeufelberger** [comment]
It might be useful to split this up into "liveness" and "readiness" (see https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ for example) and I'm not convinced that a server that has constant 6 seconds lag is "healthy".

**Comment by garay-daniel** [comment]
Agree with Ed's point. I think this also pushes operators to understand what metrics are important to monitor. 

If we make this compatible with crawl, then it would be easy for anyone to scrape this data to build dashboards and monitoring of the network, which would be great.

**Comment by MarkusTeufelberger** [comment]
If you want people to build dashboards, implement https://openmetrics.io/ instead of the current statsd-only metrics framework.

I currently collect metrics via `server_status` and a custom prometheus exporter, so most/all of the data mentioned is anyways already available. It is just clunky to extract.

**Comment by carlhua** [comment]
Lets discuss this as part of 1.6. I added a tag to this issue.
