### ISSUE TITLE
Sqlite should be upgraded to avoid vulnerability

### ISSUE THREAD

**Issue by yxxyun** [ripple/rippled#2810]
https://www.zdnet.com/article/sqlite-bug-impacts-thousands-of-apps-including-all-chromium-based-browsers/

Rippled currently use sqlite 3.24.0

**Comment by nbougalis** [comment]
Based on a cursory review, I do not believe that this necessitates releasing a hotfix for `rippled`, but we will upgrade to version 3.26.0 for the **1.2.0** release.
