### ISSUE TITLE
when will the 'sign' function be removed?

### ISSUE THREAD

**Issue by choyohan** [ripple/rippled#2813]
In version 1.1.0 release notes, ripple mentioned that 'sign' will be removed in a future release.

when will the 'sign' function be removed?

In the version 1.1.2, can I still use the 'sign' and 'sign_api' if I set [signing_support] is true.

**Comment by sublimator** [comment]
Seems like the solution (though needs to be maintained) is: https://github.com/ripple/ripple-libpp

Along with some `extern C` and  ctypes wrappers for various languages

**Comment by MarkusTeufelberger** [comment]
...or just using a JSON-RPC call to a local server. No wrappers necessary.

**Comment by mDuo13** [comment]
There is not a specific version number in which the sign command is due to be removed. I think we will remove it when we feel that alternative libraries for signing transactions are mature and prevalent enough. For the time being, the `sign` command will continue to work as an admin command.
