### ISSUE TITLE
[TX Change] [Feature Request] New tx type “CreateAccount" and only this tx type can create account on XRPL

### ISSUE THREAD

**Issue by yxxyun** [ripple/rippled#2821]
New tx type “CreateAccount" and only this tx type can activate account on XRPL, the other tx like payment send to a inactivated account will be failed.

If you want to implement deletable accounts, eg use "DeleteAccount" transaction to delete account, when you send a payment you need to make sure did not send to a already deleted account and re-activate it. So this change is necessary.

**Comment by nbougalis** [comment]
This is a **HUGE** API change. I'm not opposed to this, but it can't be as simple as you suggest. At best, we'd be able to add the new transaction, and retain the ability to fund an account with a regular payment for the foreseeable future (and perhaps forever).
