### ISSUE TITLE
systemd - start rippled after network.target

### ISSUE THREAD

**Issue by jnr101** [ripple/rippled#2822]
Hi,

I have my rippled server running on a VM in a cloud and noticed that rippled failed to start up automatically after reboot. It turns out that the network is not available yet when the rippled server is being started. A fix that works for me is by adjusting the `/lib/systemd/system/rippled.service`, adding the line `After=syslog.target network.target` in the `[Unit]` section as follows:

```
[Unit]
Description=Ripple Daemon
After=syslog.target network.target
 
[Service]
Type=simple
ExecStart=/opt/ripple/bin/rippled --net --silent --conf /etc/opt/ripple/rippled.cfg
# Default KillSignal can be used if/when rippled handles SIGTERM
KillSignal=SIGINT
Restart=no
User=rippled
Group=rippled
 
[Install]
WantedBy=multi-user.target
```

**Comment by MarkusTeufelberger** [comment]
Why do you start the server silenced instead of logging to stdout?

**Comment by jnr101** [comment]
I can't remember to have changed it after installation, except for the 'After' line .. So it must have been in there from the start

**Comment by jnr101** [comment]
ok so there it was. Couldn't find it :-) I will do that and close this one. Thanks
