### ISSUE TITLE
[QUESTION] rippled asset

### ISSUE THREAD

**Issue by Gillian217** [ripple/rippled#2833]
Hi,
Just want to ask if it possible to add other assets in rippled other than XRP. 
If it is possible can you show me how to create one for example I want to add an asset of USD.

Hope you can help me.

**Comment by yxxyun** [comment]
https://developers.ripple.com/issued-currencies.html

**Comment by will-yijinin** [comment]
https://developers.ripple.com/issued-currencies.html

This link has word explanations but no code example. I tried to follow the instructions to issue an asset to no avail. Do you know anywhere I can find some examples?
