### ISSUE TITLE
Json library could use a "tryGet" pattern to avoid boilerplate

### ISSUE THREAD

**Issue by jwbusch** [ripple/rippled#2834]
There's a lot of code that uses the `Json::Value` and has the same boilerplate of 1.) checking if the member exists, 2.) checking if the member is the correct type, 3.) finally accessing the member.

Example for a string member:
``` 
if (value.has_member("member") && value["member"].isString()) {
    auto str = value["member"].asString();
}
```

which could be replaced with 

```
if (auto v = value.tryAsString("member")) {
    auto str = *v; 
}

// or provide a default value
auto str = value.tryAsString("member").value_or("Default String"); 

```

This would require adding some new APIs to `Json::Value` for all the possible types where they return a `std::optional<T>` (or `boost::optional<T>`) and prefix with "try" in the name to indicate it might return a `nullopt`

**Comment by nbougalis** [comment]
I'm supportive. My first thought was to use an interface similar to [`std::get`](https://en.cppreference.com/w/cpp/utility/variant/get) since our Json::Value is, in essence, a variant.

```
template<class T> std::optional<T> get(Json::Value const& v, char const* name) = delete;

template<> std::optional<std::string> test<std::string>(Json::Value const& v, char const* name)
{
    // ... return string if possible, otherwise an empty optional
    return {};
}

template<> std::optional<std::uint32_t> test<std::uint32_t>(Json::Value const& v, char const* name)
{
    // ... 
    return {};
}

```

I'm not suggesting we adopt this style; just thinking out loud because I haven't really given this much thought. I leave the details to your good judgement.

**Comment by JoelKatz** [comment]
I've always hated having to do the search for the member twice. A lookup by string key seems like something you wouldn't want to do any more than you had to.

**Comment by mDuo13** [comment]
Better yet, I would love to have an interface that validates the schema of the JSON interface before it even gets to the try/get code portion...

**Comment by nbougalis** [comment]
We will be migrating to `boost::json` soon.
