### ISSUE TITLE
Exceptions thrown with the `Throw<>` helper are not logged by default

### ISSUE THREAD

**Issue by jwbusch** [ripple/rippled#2839]
The `Throw<>` helper function uses `LogThrow` which uses `debugLog` to log messages to the log file/console. The current default has `debugLog` being set to essentially a `null` sink, so all messages are dropped. 

Passing `--debug` to rippled will result in exceptions being logged, but should using `--debug` be required to see these exception messages? An unhandled exception is just going to crash the app, and there won't be a log to show what might have gone wrong.

**Comment by nbougalis** [comment]
The `Throw<>` helper is used to throw many exceptions, including several that are caught; polluting the logs with that seems counterproductive.

Per the recommendation of @HowardHinnant, we rely on the operating system to print out the details of unhandled exceptions and it can usually do a much better job that we can.
