### ISSUE TITLE
 GO ripple api ?

### ISSUE THREAD

**Issue by linuxMengfan** [ripple/rippled#2841]
When I call rippled submit method there is a deprecated field in result json with message.

Signing support in the 'submit' command has been deprecated and will be removed in a future version of the server. Please migrate to a standalone signing tool.

I use GO and I couldn't find any ripple api implementations (as I understand there's only one implementation for JS).

**Comment by r0bertz** [comment]
https://github.com/rubblelabs/ripple

**Comment by linuxMengfan** [comment]
@r0bertz  thank you.  I try it.
