### ISSUE TITLE
Partner in coin development

### ISSUE THREAD

**Issue by Willem2003** [ripple/rippled#2848]
Hi everyone i need someone from github who can partner with me to create a coin like ripple or if someone can email me everything i need to create a coin like xrp and also tell me how xrp confirm transactions

**Comment by nbougalis** [comment]
This is not the proper venue for your question, so I will be closing this issue. To learn more about the XRP Ledger consensus algorithm, I recommend reading [the paper](https://arxiv.org/abs/1802.07242) by Ethan MacBrough.

Good luck!
