### ISSUE TITLE
RocksDB stalls once Node_DB reaches ~95 GB

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#285]
Might be possibly related to:
https://github.com/facebook/rocksdb/issues/54

RocksDB is set up according to the tips in https://ripple.com/wiki/Latest_rippled_release_notes#New_RocksDB_back_end and the DB has been built from scratch. Rippled runs on a 4 GB RAM, AMD X2 CPU machine with 1 SSD as system drive (and for temp_db), node_db is on a HDD.

Generally rippled stops advancing its ledger forward for ~30-45 minutes, then catches up for ~5 minutes, then stalls again for the same amount of time and so on. Restarting makes it (sometimes) work for ~4 hours, then the stalling + catching up starts again.

This results in rippled having a large amount of xxxxx-yyyyy ranges in the "complete ledgers" field of the server_info output which show "holes" of ~200 ledgers.

iostats indicates that the HDD with node_db is under very high load (CPU is quite low), increasing the node size (currently "medium"... large seems already stretching it on 4 GB RAM?) is not really an option.

How can I help to troubleshoot/fix this? Any benchmarks/logs you need?

My suspicion is that data comes in faster than it can be added to the database - which (at these meager size and rates) shouldn't happen or at least not hurt rippled THAT much... most likely RocksDB just needs to be tuned (or updated?) more to fit rippled's workloads even more.

**Comment by MarkusTeufelberger** [comment]
Closing this one, I use NuDB these days. (RocksDB is getting quite outdated in rippled though)

**Comment by gituser** [comment]
what about those who still use hdds?

i'm having this issue as well, i've tried setting different settings, e.g. `tiny`, `medium`, `large` size of the node - didn't help.

i'm not even using full ledger history, only 256 (which is default).

would be nice if someone could take a look to make it possible to run rippled on hdds.

**Comment by gituser** [comment]
just an update for those who still want to run rippled on hdds here is a config I'm using which seems to be using memory more and less I/O (for validating and sending payments its a good configuration, but not for historic data).

The VM has 32gb of memory, rippled seems to be working fine.

```
[node_db]
type=RocksDB
path=/home/ripple/.ripple/db/rocksdb
open_files=512
filter_bits=12
cache_mb=1024
file_size_mb=64
file_size_mult=2
online_delete=2000
advisory_delete=0

[database_path]
/home/ripple/.ripple/db

[shard_db]
type=RocksDB
path=/home/ripple/.ripple/db/shards/rocksdb
max_size_gb=5
```
