### ISSUE TITLE
Synchronization problem

### ISSUE THREAD

**Issue by WalkerBuldog** [ripple/rippled#2853]
After two or three days, synchronization gaps begin.

For what reasons is this happening?
"complete_ledgers": "45023388-45034998,45035024-45035413,45035515-45035653,45035742-45037574,45037859-45038083,45038493-45038930,45039029-45039300,45039426-45039429,45039530-45076651,45077119-45077120,45077378,45077469-45077649,45077787-45077801,45078454-45079670,45081398,45081619-45081622,45081686-45081947,45082100-45083737,45084292,45085012-45085183,45085592-45085654,45085775-45085935,45086010-45087182,45087605-45087614,45087834-45087881,45088167-45088202,45088306-45088334,45088441-45088446,45088551-45088594,45088721-45088790,45088868-45089730,45091631-45091632,45093122-45093133,45093235,45093340-45093372,45093473-45093554,45093767-45093769,45093872,45093974-45094234,45094329-45095097",

server_info:

{
    "result": {
        "info": {
            "build_version": "1.1.2",
            "complete_ledgers": "45023388-45034998,45035024-45035413,45035515-45035653,45035742-45037574,45037859-45038083,45038493-45038930,45039029-45039300,45039426-45039429,45039530-45076651,45077119-45077120,45077378,45077469-45077649,45077787-45077801,45078454-45079670,45081398,45081619-45081622,45081686-45081947,45082100-45083737,45084292,45085012-45085183,45085592-45085654,45085775-45085935,45086010-45087182,45087605-45087614,45087834-45087881,45088167-45088202,45088306-45088334,45088441-45088446,45088551-45088594,45088721-45088790,45088868-45089730,45091631-45091632,45093122-45093133,45093235,45093340-45093372,45093473-45093554,45093767-45093769,45093872,45093974-45094234,45094329-45095097",
            "fetch_pack": 5997,
            "hostid": "Ubuntu-1604-xenial-64-minimal",
            "io_latency_ms": 1,
            "jq_trans_overflow": "64219",
            "last_close": {
                "converge_time_s": 2,
                "proposers": 0
            },
            "load": {
                "job_types": [
                    {
                        "avg_time": 1261,
                        "job_type": "ledgerRequest",
                        "peak_time": 3085,
                        "per_second": 3
                    },
                    {
                        "avg_time": 23978,
                        "in_progress": 2,
                        "job_type": "ledgerData",
                        "peak_time": 65773,
                        "per_second": 3,
                        "waiting": 25
                    },
                    {
                        "avg_time": 1728,
                        "in_progress": 1,
                        "job_type": "clientCommand",
                        "peak_time": 4290,
                        "per_second": 3
                    },
                    {
                        "avg_time": 14,
                        "job_type": "advanceLedger",
                        "peak_time": 32,
                        "per_second": 44
                    },
                    {
                        "avg_time": 1686,
                        "job_type": "trustedValidation",
                        "over_target": true,
                        "peak_time": 4527,
                        "per_second": 22
                    },
                    {
                        "avg_time": 48,
                        "job_type": "writeObjects",
                        "peak_time": 193,
                        "per_second": 17
                    },
                    {
                        "avg_time": 1716,
                        "job_type": "trustedProposal",
                        "over_target": true,
                        "peak_time": 4341,
                        "per_second": 39
                    },
                    {
                        "avg_time": 3236,
                        "job_type": "heartbeat",
                        "over_target": true,
                        "peak_time": 12944
                    },
                    {
                        "job_type": "peerCommand",
                        "per_second": 599
                    },
                    {
                        "avg_time": 52,
                        "job_type": "diskAccess",
                        "peak_time": 208,
                        "per_second": 16
                    },
                    {
                        "avg_time": 1,
                        "job_type": "SyncReadNode",
                        "peak_time": 26,
                        "per_second": 10
                    },
                    {
                        "avg_time": 1,
                        "job_type": "AsyncReadNode",
                        "peak_time": 52,
                        "per_second": 183
                    },
                    {
                        "job_type": "WriteNode",
                        "per_second": 4
                    }
                ],
                "threads": 6
            },
            "load_factor": 5.20703125,
            "load_factor_local": 5.20703125,
            "peer_disconnects": "9",
            "peer_disconnects_resources": "0",
            "peers": 10,
            "pubkey_node": "n9JkbbGAwQPxvAvB6wYBXRvujDpb5SCz26Dv4tybSfCtZAv8LuWR",
            "pubkey_validator": "none",
            "server_state": "full",
            "state_accounting": {
                "connected": {
                    "duration_us": "2225252730",
                    "transitions": 1
                },
                "disconnected": {
                    "duration_us": "1352589",
                    "transitions": 1
                },
                "full": {
                    "duration_us": "579875709946",
                    "transitions": 960
                },
                "syncing": {
                    "duration_us": "2892535357",
                    "transitions": 964
                },
                "tracking": {
                    "duration_us": "179910814",
                    "transitions": 964
                }
            },
            "time": "2019-Feb-13 07:27:23.903005",
            "uptime": 585181,
            "validated_ledger": {
                "age": 7131,
                "base_fee_xrp": 1e-05,
                "hash": "E884707B7AFF2C9557D1C6D16797B704AFD4D4DE937F695FD820207386661696",
                "reserve_base_xrp": 20,
                "reserve_inc_xrp": 5,
                "seq": 45095097
            },
            "validation_quorum": 21,
            "validator_list": {
                "count": 1,
                "expiration": "2019-Feb-20 00:00:00.000000000",
                "status": "active"
            }
        },
        "status": "success"
    }
}

ripple.cfg

[server]
port_rpc_admin_local
port_peer
port_ws_admin_local
#port_ws_public
#ssl_key = /etc/ssl/private/server.key
#ssl_cert = /etc/ssl/certs/server.crt

[port_rpc_admin_local]
port = 5005
ip = 0.0.0.0
admin = 0.0.0.0
protocol = http

[port_peer]
port = 51235
ip = 127.0.0.1
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws

[node_size]
medium

[ledger_history]
10000

[node_db]
type=RocksDB
path=/var/lib/rippled/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=12000
advisory_delete=0

[database_path]
/var/lib/rippled/db

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
r.ripple.com 51235

[validators_file]
validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
1

**Comment by nbougalis** [comment]
Your server seems to be falling behind (see, inter alia, `"age": 7131` under `validated_ledger`. This suggests your server hasn't seen a new ledger validate for almost 2 hours). The last round also seems to have closed with 0 proposers.

This suggests, at a minimum, poor connectivity to other servers (which does not necessarily mean slow Internet). Also are you using an mechanical (rotating) drive or a solid state (SSD) drive?

As a preliminary step,I would suggest upgrading your server to the **1.2.0** release and restarting your server.

**Comment by WalkerBuldog** [comment]
Two days everything is doing fine, now again, it began to skip the blocks.

{
    "result": {
        "info": {
            "build_version": "1.2.0",
            "complete_ledgers": "45262510-45274571,45274681-45274774,45274884-45274928,45275103-45275125",
            "fetch_pack": 190,
            "hostid": "Ubuntu-1604-xenial-64-minimal",
            "io_latency_ms": 1,
            "jq_trans_overflow": "25850",
            "last_close": {
                "converge_time_s": 2,
                "proposers": 0
            },
            "load": {
                "job_types": [
                    {
                        "avg_time": 1,
                        "job_type": "untrustedValidation",
                        "peak_time": 2
                    },
                    {
                        "avg_time": 3,
                        "job_type": "untrustedProposal",
                        "peak_time": 225,
                        "per_second": 37
                    },
                    {
                        "avg_time": 3476,
                        "in_progress": 2,
                        "job_type": "ledgerData",
                        "peak_time": 11370,
                        "per_second": 1,
                        "waiting": 14
                    },
                    {
                        "in_progress": 1,
                        "job_type": "clientCommand"
                    },
                    {
                        "in_progress": 1,
                        "job_type": "updatePaths"
                    },
                    {
                        "avg_time": 8,
                        "job_type": "transaction",
                        "peak_time": 232,
                        "per_second": 6
                    },
                    {
                        "job_type": "batch",
                        "per_second": 6
                    },
                    {
                        "avg_time": 2,
                        "job_type": "advanceLedger",
                        "peak_time": 51,
                        "per_second": 15
                    },
                    {
                        "avg_time": 47,
                        "job_type": "trustedValidation",
                        "peak_time": 225,
                        "per_second": 6
                    },
                    {
                        "job_type": "writeObjects",
                        "peak_time": 137,
                        "per_second": 96
                    },
                    {
                        "job_type": "trustedProposal",
                        "peak_time": 28,
                        "per_second": 9
                    },
                    {
                        "job_type": "peerCommand",
                        "per_second": 610
                    },
                    {
                        "avg_time": 6,
                        "job_type": "diskAccess",
                        "peak_time": 186,
                        "per_second": 5
                    },
                    {
                        "job_type": "processTransaction",
                        "per_second": 6
                    },
                    {
                        "job_type": "SyncReadNode",
                        "peak_time": 105,
                        "per_second": 683
                    },
                    {
                        "job_type": "AsyncReadNode",
                        "peak_time": 130,
                        "per_second": 2509
                    },
                    {
                        "job_type": "WriteNode",
                        "per_second": 139
                    }
                ],
                "threads": 6
            },
            "load_factor": 1,
            "peer_disconnects": "23",
            "peer_disconnects_resources": "0",
            "peers": 10,
            "pubkey_node": "n9JkbbGAwQPxvAvB6wYBXRvujDpb5SCz26Dv4tybSfCtZAv8LuWR",
            "pubkey_validator": "none",
            "published_ledger": 45275125,
            "server_state": "full",
            "server_state_duration_us": "817026943",
            "state_accounting": {
                "connected": {
                    "duration_us": "353835808",
                    "transitions": 4
                },
                "disconnected": {
                    "duration_us": "1100524",
                    "transitions": 1
                },
                "full": {
                    "duration_us": "181472169126",
                    "transitions": 1638
                },
                "syncing": {
                    "duration_us": "4854630808",
                    "transitions": 1655
                },
                "tracking": {
                    "duration_us": "211384689",
                    "transitions": 1655
                }
            },
            "time": "2019-Feb-20 14:47:20.091550",
            "uptime": 186897,
            "validated_ledger": {
                "age": 128,
                "base_fee_xrp": 1e-05,
                "hash": "E0AA2718A1E53994CB0739A380F14A54BABE9927B2C2C8D54E11273ADF3CCBA2",
                "reserve_base_xrp": 20,
                "reserve_inc_xrp": 5,
                "seq": 45275152
            },
            "validation_quorum": 21,
            "validator_list": {
                "count": 1,
                "expiration": "2019-Mar-06 00:00:00.000000000",
                "status": "active"
            }
        },
        "status": "success"
    }
}

**Comment by MarkusTeufelberger** [comment]
So... what's the IO performance of your disk storage? Also 10 peers sounds like you didn't properly open the peer port (by default 51235).

**Comment by mDuo13** [comment]
Closing this stale issue. Feel free to reopen if you provide more detail.
