### ISSUE TITLE
'tecINSUFFICIENT_RESERVE  141 error

### ISSUE THREAD

**Issue by qq976739120** [ripple/rippled#2857]
when i creaTE mul-address,i get error.How to solve?

```
signedSignerListSet---- { resultCode: 'tecINSUFFICIENT_RESERVE',
  resultMessage: 'Insufficient reserve to complete requested operation.',
  engine_result: 'tecINSUFFICIENT_RESERVE',
  engine_result_code: 141,
  engine_result_message: 'Insufficient reserve to complete requested operation.',
  tx_blob: '12000C2200000000240000001320230000000368400000000000010073210283D7ED66CA7B83579EF2B7E24242BE82BC8BC6E28B78734B9A7952D4D261C36374463044022008F51236E063B59DA34005EEF1C0CBDBA6B173A55E18AF899EC8314D85008BB20220142DB8D57F3847E6FB7144CE63A6214C26D3E600ED6AA1AFD9344B92B7E1CCD28114F01F8FED33003D4348CD884B0E859698D1612A5DF4EB13000281149CA5CB06855792E03DCA44BFF83D5B5DD6A2D0C1E1EB1300028114F7C00B1701DFDDA6EBC0A0205B1EB5AB3154DC97E1EB130002811438BA5187670CA23683519152B96D44755F40B190E1F1',
  tx_json: 
   { Account: 'r4tezpBLWezPQC5PJ6DiUx6K4JZtzuUPdP',
     Fee: '256',
     Flags: 0,
     Sequence: 19,
     SignerEntries: [ [Object], [Object], [Object] ],
     SignerQuorum: 3,
     SigningPubKey: '0283D7ED66CA7B83579EF2B7E24242BE82BC8BC6E28B78734B9A7952D4D261C363',
     TransactionType: 'SignerListSet',
     TxnSignature: '3044022008F51236E063B59DA34005EEF1C0CBDBA6B173A55E18AF899EC8314D85008BB20220142DB8D57F3847E6FB7144CE63A6214C26D3E600ED6AA1AFD9344B92B7E1CCD2',
     hash: '26ABE074EEED6AB36D5804F521BE0D3FB446DA37023B852E4A1E61FF567CD1B9' } }
```

**Comment by qq976739120** [comment]
i have enough balance 
```
account_data": {
            "Account": "r4tezpBLWezPQC5PJ6DiUx6K4JZtzuUPdP",
            "Balance": "36685972",
            "Flags": 0,
            "LedgerEntryType": "AccountRoot",
            "OwnerCount": 0,
            "PreviousTxnID": "50853BF13979D3C5D0A2AFEE1CB777F263B06574697DEE7E6F6D4318D574B994",
            "PreviousTxnLgrSeq": 45172123,
            "Sequence": 21,
            "index": "2C2D999482DA731DC0BEEF1174D0189E4D9C4910EBCC8A0173CD0486D10316EA",
            "signer_lists": []
        },
```

**Comment by nbougalis** [comment]
Thanks four opening this issue!

Under the current rules simply having a {{SignerList}} locks up 2 incremental reserve units, and each signer in the list locks up 1 more incremental reserve unit ([reference](https://github.com/ripple/rippled/blob/develop/src/ripple/app/tx/impl/SetSignerList.cpp#L348-L374)).

The reserve is currently 20 XRP and the incremental reserve is 5. You are attempting to create a signer list with three entries, so the new reserve for your account is (20 XRP + (5 entries * 5 XRP per entry) = 45 XRP. The account you show has ~36 XRP, which is less than the required 45 XRP.

So this is working correctly. For now, anyways: when the [`MultiSignReserve` amendment](https://developers.ripple.com/known-amendments.html#multisignreserve) activates, the rules for calculating the additional reserve associated with a signer list will change, reducing the amount of XRP that must be locked up; a list, regardless of the number of entries, will cost only one incremental reserve.

I'm going to close this issue. If you believe this is in error, please feel free to reopen.
