### ISSUE TITLE
Append default port (51235) in [ips_fixed] when no port specified

### ISSUE THREAD

**Issue by alloyxrp** [ripple/rippled#2861]
If a port is not specified against an IP in `[ips_fixed]`, `rippled` fails to start. The daemon should try with the default port if it is not specified.

**Comment by nbougalis** [comment]
Yep that’s a bug. Thanks for reporting it!

**Comment by alloyxrp** [comment]
This fix should also apply to `[ips]`.

**Comment by MarkusTeufelberger** [comment]
The example config currently says "A port may must be specified after adding a space to the address."

https://github.com/ripple/rippled/commit/b39c1eb92c5884c248baaaf2af62e88cd8681b83 sounds like this was intentionally set to "must", so this is a feature, not a bug.

**Comment by nbougalis** [comment]
While the original intent may have been to require a port number, it doesn't mean this isn't a bug, albeit not a code bug. The decision to mandate a port when a port isn't mandatory in any other instance is, at best, curious. Our config is complex enough as is; having arcane differences here and there is not good.

I believe that this should be corrected.

**Comment by movitto** [comment]
Figured this would be a good easy one to get my feet wet with rippled contributions! Just submitted a first stab, let me know if specific changes are needed/preferred.
