### ISSUE TITLE
stop sync with "Unable to determine hash of ancestor seq"

### ISSUE THREAD

**Issue by dream4you** [ripple/rippled#2875]
After installing the ripple server and running it for 1 ~ 2 days, the warning is displayed as below log, and the seq value of "./rippled server_info" seems to be out of sync.

**************************************************************************************************************
2019-Mar-15 00:14:11.988635085 Validations:WRN Unable to determine hash of ancestor seq=45804420 from ledger hash=9C17DFBB729480DBE4C68B0E98D73594AC331139B30DB60BAE92A22E6E6C4F62 seq=45805106
2019-Mar-15 00:14:12.989111458 Validations:WRN Unable to determine hash of ancestor seq=45804420 from ledger hash=9C17DFBB729480DBE4C68B0E98D73594AC331139B30DB60BAE92A22E6E6C4F62 seq=45805106
2019-Mar-15 00:14:13.989486461 Validations:WRN Unable to determine hash of ancestor seq=45804420 from ledger hash=9C17DFBB729480DBE4C68B0E98D73594AC331139B30DB60BAE92A22E6E6C4F62 seq=45805106
2019-Mar-15 00:14:14.989813689 Validations:WRN Unable to determine hash of ancestor seq=45804420 from ledger hash=9C17DFBB729480DBE4C68B0E98D73594AC331139B30DB60BAE92A22E6E6C4F62 seq=45805106
2019-Mar-15 00:14:15.990135351 Validations:WRN Unable to determine hash of ancestor seq=45804420 from ledger hash=9C17DFBB729480DBE4C68B0E98D73594AC331139B30DB60BAE92A22E6E6C4F62 seq=45805106
2019-Mar-15 00:14:16.990447043 Validations:WRN Unable to determine hash of ancestor seq=45804420 from ledger hash=9C17DFBB729480DBE4C68B0E98D73594AC331139B30DB60BAE92A22E6E6C4F62 seq=45805106
2019-Mar-15 00:14:17.990768861 Validations:WRN Unable to determine hash of ancestor seq=45804420 from ledger hash=9C17DFBB729480DBE4C68B0E98D73594AC331139B30DB60BAE92A22E6E6C4F62 seq=45805106
2019-Mar-15 00:14:18.991116606 Validations:WRN Unable to determine hash of ancestor seq=45804420 from ledger hash=9C17DFBB729480DBE4C68B0E98D73594AC331139B30DB60BAE92A22E6E6C4F62 seq=45805106
2019-Mar-15 00:14:19.991467094 Validations:WRN Unable to determine hash of ancestor seq=45804420 from ledger hash=9C17DFBB729480DBE4C68B0E98D73594AC331139B30DB60BAE92A22E6E6C4F62 seq=45805106
**************************************************************************************************************

**************************************************************************************************************
"./rippled server_info" and "rippled.cfg" are as follows.
{
   "result" : {
      "info" : {
         "build_version" : "1.2.2",
         "complete_ledgers" : "45796648-45798725,45798801-45799220,45799243-45799644,45799760-45801238,45801364-45801715,45801827-45801948,45802089-45802645,45802752-45802949,45803050-45804448",
         "fetch_pack" : 5039,
         "hostid" : "WEB4",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "340",
         "last_close" : {
            "converge_time_s" : 2,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "avg_time" : 1320,
                  "job_type" : "untrustedValidation",
                  "peak_time" : 3483
               },
               {
                  "avg_time" : 1198,
                  "job_type" : "ledgerRequest",
                  "peak_time" : 3692,
                  "per_second" : 5
               },
               {
                  "avg_time" : 1255,
                  "job_type" : "untrustedProposal",
                  "over_target" : true,
                  "peak_time" : 3188,
                  "per_second" : 72
               },
               {
                  "in_progress" : 2,
                  "job_type" : "ledgerData",
                  "waiting" : 22
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "avg_time" : 1,
                  "job_type" : "advanceLedger",
                  "peak_time" : 4,
                  "per_second" : 26
               },
               {
                  "avg_time" : 837,
                  "job_type" : "trustedValidation",
                  "over_target" : true,
                  "peak_time" : 2314,
                  "per_second" : 13
               },
               {
                  "avg_time" : 34,
                  "job_type" : "writeObjects",
                  "peak_time" : 1318,
                  "per_second" : 10
               },
               {
                  "avg_time" : 1040,
                  "job_type" : "trustedProposal",
                  "over_target" : true,
                  "peak_time" : 2662,
                  "per_second" : 19
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 1339
               },
               {
                  "avg_time" : 39,
                  "job_type" : "diskAccess",
                  "peak_time" : 151,
                  "per_second" : 9
               },
               {
                  "avg_time" : 1,
                  "job_type" : "SyncReadNode",
                  "peak_time" : 20
               },
               {
                  "avg_time" : 1,
                  "job_type" : "AsyncReadNode",
                  "peak_time" : 395,
                  "per_second" : 776
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 1
               }
            ],
            "threads" : 6
         },
         "load_factor" : 1,
         "peer_disconnects" : "343",
         "peer_disconnects_resources" : "0",
         "peers" : 21,
         "pubkey_node" : "n9KnqqGrhK5EjjpwXbDG2bJ5qCZAArAmiHnUDVshX6vZHgB2DVVR",
         "pubkey_validator" : "none",
         "server_state" : "full",
         "server_state_duration_us" : "12185310511",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "96025950",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "3228887",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "139245710001",
               "transitions" : 95
            },
            "syncing" : {
               "duration_us" : "392486403",
               "transitions" : 95
            },
            "tracking" : {
               "duration_us" : "12426930",
               "transitions" : 95
            }
         },
         "time" : "2019-Mar-14 23:47:35.796060",
         "uptime" : 139750,
         "validated_ledger" : {
            "age" : 12073,
            "base_fee_xrp" : 1e-05,
            "hash" : "EF3B099687F2E241F56E10E84F2449F897A37268FEE4BFF64EAECD8AC01CCEBB",
            "reserve_base_xrp" : 20,
            "reserve_inc_xrp" : 5,
            "seq" : 45804448
         },
         "validation_quorum" : 21,
         "validator_list" : {
            "count" : 1,
            "expiration" : "2019-Mar-19 00:00:00.000000000",
            "status" : "active"
         }
      },
      "status" : "success"
   }
}
**************************************************************************************************************

**************************************************************************************************************
[server]
port_rpc_admin_local
port_peer
port_ws_admin_local
port_rpc_admin

[port_rpc_admin_local]
port = 5005
ip = 127.0.0.1
admin = 127.0.0.1
protocol = http

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws

[port_rpc_admin]
port = 51234
ip = 0.0.0.0
admin = 0.0.0.0
protocol = http, https
user=test1
password=test1

[node_size]
medium

[node_db]
type=RocksDB
path=/var/lib/rippled/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=2000
advisory_delete=0

[database_path]
/var/lib/rippled/db

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
r.ripple.com 51235

[validators_file]
validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
1
**************************************************************************************************************

And the hardware specifications are as follows.
Memory : 16GB, HDD : 350GB(not SSD)

**Comment by JoelKatz** [comment]
What's in your "validators.txt" file?

**Comment by JoelKatz** [comment]
The warning you're seeing is a symptom of not being able to keep up with the network. I don't think it's the primary issue.

There's logic in the server that should stop trying to fetch history when it thinks the server is not caught up to the network. This logic should trigger since the most recent ledger your server has personally validated is more than 200 times older than the cutoff. So your server should be exclusively trying to re-sync to the network.

The job queue stats show that some jobs are taking longer than would be ideal, but the only job type that's actually backing up is "ledgerData" jobs. These are the jobs that process ledger data received from the network to keep you caught up. In other words, your server is getting data from the network faster than it can process it, likely due to disk I/O limitations and inadequate or ineffective caching.

The thing that worries me is that you're only reading 776 nodes per second. I would expect you to be reading about three times that amount as that includes reads from RocksDB's cache. It may help to increase the cache size -- the "cache_mb" entry under "node_db".

**Comment by nbougalis** [comment]
Track in #2746
