### ISSUE TITLE
Transaction Query: Filter by destination tag fails

### ISSUE THREAD

**Issue by nbougalis** [ripple/rippled#2877]
According to *NetScr1be* on [xrpchat](https://www.xrpchat.com/topic/30774-transaction-query-filter-by-destination-tag-fails-not-implemented/), filtering by destination tag is broken:

>T﻿he﻿ documentation says
>
>>Get Account Payments
>>
>>Retrieve a payments for a specified account
>>
>>Request Format
>>
>>REST﻿
>>
>>GET /v2/accounts/{address}/payments
>>
>>This method requires the following URL parameters:
>>
>>Field  |  Value  |  Description
>>address  |  String  |  XRP Ledger address to query.
>>Optionally, you can provide the following query parameters:﻿
>>
>>Field  |  Value  |  Description
>>start  |  String - Timestamp  |  Filter results to this time and later.
>>end  |  String - Timestamp  |  Filter results to this time and earlier.
>>type  |  String  |  Type of payment - sent or received.
>>currency  |  String - Currency Code  |  Filter results to specified currency.
>>issuer  |  Stri﻿ng - Address  |  Filter results to specified issuer.
>>source_tag  |  Integer  |  Filter results to specified source tag.
>>destination_tag  |  Integer  |  Filter results to specified destination tag.
>>limit  |  Integer  |  Maximum results per page. The default is 200. Cannot be more than 1,000.
>>marker  |  String  |  Pagination key from previously returned response.
>>format  |  String  |  Format of returned results: csv or json. The default is json.
>>Response Format
>>A successful response uses the HTTP code 200 OK and has a JSON body with the following:
>>Field  |  Value  |  Description
>>result  |  String  |  The value success indicates that this is a successful response.
>>count  |  Integer  |  The number of objects contained in the payments﻿ field.
>>marker  |  String  |  May be omitted) Pagination marker.
>>payments  |  Array of payment objects  |  All payments matching the reque﻿st, sorted with oldest first
>
>So, while it doesn't (seem to) return the destination tags, it is implied that we can filter by destination tag.
>
>Querying an address without a filter is successful. I know the address has destination tags of the value I want to filter becau﻿se they be seen using 'GET /v2/accounts/{address}/transactions'.
>
>Specifying the destination_tag=<integer> 'succeeds' with;﻿
>
>{"result":"success","count":0,"payments":[]}
>>
>Has anyone tried this and/or got it to work?﻿

**Comment by MarkusTeufelberger** [comment]
This is not about rippled though?

**Comment by nbougalis** [comment]
I know. I need a way to track it though - thisis just temporary.

**Comment by mDuo13** [comment]
I think this is a Data API bug ( https://github.com/ripple/rippled-historical-database )

**Comment by nbougalis** [comment]
I'm assigning this to @bachase, who can coordinate with the data team to fix this (if it hasn't been fixed already). Brad, feel free to close this issue if you're tracking it elsewhere.

**Comment by bachase** [comment]
Per the [reply](https://www.xrpchat.com/topic/30774-transaction-query-filter-by-destination-tag-fails-not-implemented/?tab=comments#comment-683069) on xrpchat, `destination_tag` filtering appears to be working on other queries. Given the age of this request, I'll close this for now.
