### ISSUE TITLE
ledger_closed and ledger_current rpc no reply data from server

### ISSUE THREAD

**Issue by qiluge** [ripple/rippled#2885]
the ledger_closed and ledger_current rpc return 
![image](https://user-images.githubusercontent.com/19525062/55215629-643d6400-5235-11e9-90d2-42ecc3fb4229.png)

![image](https://user-images.githubusercontent.com/19525062/55215615-5687de80-5235-11e9-9caa-0730bcf9779f.png)

the server config is 
![image](https://user-images.githubusercontent.com/19525062/55215643-73241680-5235-11e9-92b7-956604cc5dc1.png)

**Comment by MarkusTeufelberger** [comment]
You are sending these requests to the peer port, not the RPC port.
This can't work.

Also you are exposing administrative access to your server to the whole internet. This is NOT good. Don't do this.

**Comment by qiluge** [comment]
thank you very much.
