### ISSUE TITLE
Report to WebSocket clients connection refusal reason

### ISSUE THREAD

**Issue by miguelportilla** [ripple/rippled#2887]
Report connection refusal reason to WebSocket clients when the rate limit threshold has been surpassed.

[issue 2883](https://github.com/ripple/rippled/issues/2883)

**Comment by movitto** [comment]
Ran into this locally as well so decided to implement a fix. Let me know if the style needs updating, etc.

**Comment by miguelportilla** [comment]
@movitto Thank you!

**Comment by mDuo13** [comment]
The fix has been released in 1.3.1. I plan to add documentation sometime soon.
