### ISSUE TITLE
Upgrade 1.2.2, server crash

### ISSUE THREAD

**Issue by Sayplaydiv** [ripple/rippled#2890]
I don't know what's going on. When I upgrade to version 1.2.2（https://github.com/ripple/rippled/releases）, my server will crash. It's the third time since I upgraded the day before yesterday. Can you tell me the reason or the solution?

**Comment by Sayplaydiv** [comment]
ripple.cfg：

[signing_support]
true

[server]
port_rpc_admin_local
port_peer
port_ws_admin_local

[port_rpc_admin_local]
port = 5005
ip = 0.0.0.0
admin = 127.0.0.1
protocol = http

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws



[node_size]
medium

[node_db]
type=RocksDB
path=/data/ripple_data/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=2048
file_size_mb=8
file_size_mult=2
online_delete=80000
advisory_delete=0


[database_path]
/data/ripple_data/db

[debug_logfile]
/data/ripple_data/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
r.ripple.com 51235
[validators_file]
validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
1

**Comment by Sayplaydiv** [comment]
ubuntu 18.04 32G ram

**Comment by MarkusTeufelberger** [comment]
"crash" is a bit unspecific...

**Comment by nbougalis** [comment]
The information you've provided doesn't help us to isolate the issue. You'll need to provide more information.
What happens if you attempt to start `rippled` in "foreground" mode? After you `su` to the username that you typically run `rippled` as, what happens if you try the following command? (I'm assuming you instaled the package):

`/opt/rippled/bin/rippled --fg`

**Comment by mDuo13** [comment]
Closing this stale issue. Please feel free to reopen if you can provide more detail.
