### ISSUE TITLE
Sync issue. (version 1.2.3)

### ISSUE THREAD

**Issue by lambda2003** [ripple/rippled#2898]
Hello,

I just recently upgrade 1.1.1. to 1.2.3. After upgrading, I wait for full sync during a few days. However, It is still in "proposing" in server_state. Could you help me? 

Cores: 8
Ram: 32G
SSD: 500G

My server_info:
{
   "result" : {
      "info" : {
         "build_version" : "1.2.3",
         "complete_ledgers" : "46310381-46310469,46310754-46310774,46310877-46310878,46311002-46311007                                 ,46311115-46311144,46311298-46311303,46311409-46311450,46311567-46311574,46311685-46311768",
         "fetch_pack" : 700,
         "hostid" : "ip-10-0-10-56",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "16095",
         "last_close" : {
            "converge_time_s" : 2.001,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "untrustedValidation",
                  "per_second" : 5
               },
               {
                  "job_type" : "untrustedProposal",
                  "per_second" : 39
               },
               {
                  "avg_time" : 7180,
                  "in_progress" : 2,
                  "job_type" : "ledgerData",
                  "peak_time" : 27659,
                  "per_second" : 2,
                  "waiting" : 15
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "job_type" : "advanceLedger",
                  "per_second" : 16
               },
               {
                  "job_type" : "trustedValidation",
                  "peak_time" : 3,
                  "per_second" : 7
               },
               {
                  "job_type" : "writeObjects",
                  "peak_time" : 2,
                  "per_second" : 126
               },
               {
                  "job_type" : "trustedProposal",
                  "per_second" : 11
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 611
               },
               {
                  "job_type" : "diskAccess",
                  "peak_time" : 2,
                  "per_second" : 7
               },
               {
                  "job_type" : "SyncReadNode",
                  "peak_time" : 4,
                  "per_second" : 419
               },
               {
                  "job_type" : "AsyncReadNode",
                  "peak_time" : 11,
                  "per_second" : 1135
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 138
               }
            ],
            "threads" : 6
         },
         "load_factor" : 1,
         "peer_disconnects" : "3",
         "peer_disconnects_resources" : "0",
         "peers" : 10,
         "pubkey_node" : "n9LFhRMkzemDMULAANicF7Bp9g2earNGAnrciEjJt6BB7b8ajHsn",
         "pubkey_validator" : "nHBX3ipdipAsp1HwSFjQr7AXVVx1Z6vByD7ckWKqvwbdCWb6V1JH",
         "server_state" : "proposing",
         "server_state_duration_us" : "5442189899",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "2201212992",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "2221818",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "5442189899",
               "transitions" : 1
            },
            "syncing" : {
               "duration_us" : "44763841",
               "transitions" : 1
            },
            "tracking" : {
               "duration_us" : "2",
               "transitions" : 1
            }
         },
         "time" : "2019-Apr-05 05:32:02.250482",
         "uptime" : 7690,
         "validated_ledger" : {
            "age" : 440,
            "base_fee_xrp" : 1e-05,
            "hash" : "645BD63E5114E980A52154354819CF84A2D8389ABCE6F7657A9383B604B87F08",
            "reserve_base_xrp" : 20,
            "reserve_inc_xrp" : 5,
            "seq" : 46311768
         },
         "validation_quorum" : 24,
         "validator_list" : {
            "count" : 1,
            "expiration" : "2019-May-01 00:00:00.000000000",
            "status" : "active"
         }
      },
      "status" : "success"
   }
}

debug log file. 
2019-Apr-05 05:32:35.469147805 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:35.469164315 Validations:WRN Unable to determine hash of ancestor seq=0 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:36.465989546 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:36.466038290 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:36.466058972 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:36.466082550 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:36.466098349 Validations:WRN Unable to determine hash of ancestor seq=0 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:37.466790410 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:37.466844635 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:37.466864719 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:37.466881438 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:37.466898619 Validations:WRN Unable to determine hash of ancestor seq=0 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:38.467251778 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:38.467300216 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:38.467313313 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:38.467325107 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:38.467336598 Validations:WRN Unable to determine hash of ancestor seq=0 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:38.467440025 Validations:WRN Unable to determine hash of ancestor seq=46310448 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:38.467456226 Validations:WRN Unable to determine hash of ancestor seq=46310448 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:38.468248298 Validations:WRN Unable to determine hash of ancestor seq=46310448 from ledger hash=847EDD811523DFD7E2DE5F17ACA770B6A91C07FDE8C6DAF471F603B39C650D6D seq=46311150
2019-Apr-05 05:32:38.468274268 Validations:WRN Unable to determine hash of ancestor seq=46310448 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:38.468493379 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:38.468518128 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:38.468534221 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:38.468544898 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:38.468556220 Validations:WRN Unable to determine hash of ancestor seq=0 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:39.467863428 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:39.467921249 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:39.467934083 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:39.467944672 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:39.467955672 Validations:WRN Unable to determine hash of ancestor seq=0 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:40.468848316 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:40.468896532 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:40.468908851 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:40.468920084 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:40.468931111 Validations:WRN Unable to determine hash of ancestor seq=0 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:41.473853017 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:41.473902147 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:41.473914444 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:41.473924983 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:41.473935560 Validations:WRN Unable to determine hash of ancestor seq=0 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:41.480226900 Validations:WRN Unable to determine hash of ancestor seq=46310448 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:41.480260473 Validations:WRN Unable to determine hash of ancestor seq=46310448 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:41.481144019 Validations:WRN Unable to determine hash of ancestor seq=46310448 from ledger hash=BE5B636FFF2010A36CB861D150C97046B30CF79F26BB3A2FEA725170A1196B06 seq=46311151
2019-Apr-05 05:32:41.481180557 Validations:WRN Unable to determine hash of ancestor seq=46310448 from ledger hash=FE8863A4C7D7DD1C923F50BE585BF77B58306D9FAECA884F503A0530A352C295 seq=46311152
2019-Apr-05 05:32:41.489798366 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:41.489832208 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=FE8863A4C7D7DD1C923F50BE585BF77B58306D9FAECA884F503A0530A352C295 seq=46311152
2019-Apr-05 05:32:41.489851609 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=FE8863A4C7D7DD1C923F50BE585BF77B58306D9FAECA884F503A0530A352C295 seq=46311152
2019-Apr-05 05:32:41.489867744 Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=A270A07FEE3413EF4B5C26B6AA957DAF2A4425B298E1B340949E61855E0564D6 seq=46310448
2019-Apr-05 05:32:41.489892611 Validations:WRN Unable to determine hash of ancestor seq=0 from ledger hash=FE8863A4C7D7DD1C923F50BE585BF77B58306D9FAECA884F503A0530A352C295 seq=46311152

**Comment by lambda2003** [comment]
I just updated new validator_token in ripple.conf with validator-keys.
and network_ledger is now "waiting" in server_state.

Also I can see below warning in debug file.
2019-Apr-08 08:29:00.689921407 LedgerConsensus:WRN View of consensus changed during est                                                ablish status=establish,  mode=wrongLedger

Could you guys give me any direction to fix my issue?? 
Thank  you.

Below is my debug log.
2019-Apr-08 08:28:25.640070069 LedgerConsensus:WRN {"accepted":true,"account_hash":"AF1EC5AB71459F15F7CC090EE557B59FB6D847A406BD81BCDF5FB79BCD090CB7","close_flags":0,"close_time":608027301,"close_time_human":"2019-Apr-08 08:28:21.000000000","close_time_resolution":10,"closed":true,"hash":"311B1CA6BD7FA41EC5025CD1F2167C0DB6322430D1EFFBB5B79DE6DF53FAFE6C","ledger_hash":"311B1CA6BD7FA41EC5025CD1F2167C0DB6322430D1EFFBB5B79DE6DF53FAFE6C","ledger_index":"482","parent_close_time":608027300,"parent_hash":"C993DAFF16D3F46E7E63E0D5FEFDD5811811415421AC2540092B14366E99829F","seqNum":"482","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2019-Apr-08 08:28:25.640267440 LedgerConsensus:WRN Need consensus ledger 976E3553CF5742996D87511273B4A19D83D2B318DD247F7A68AA8F5D1B66A92E
2019-Apr-08 08:28:25.773158193 LoadMonitor:WRN Job: processLedgerData run: 229ms wait: 10125ms
2019-Apr-08 08:28:28.656396207 NetworkOPs:WRN We are not running on the consensus ledger
2019-Apr-08 08:28:29.645949528 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2019-Apr-08 08:28:29.646006760 LedgerConsensus:WRN 976E3553CF5742996D87511273B4A19D83D2B318DD247F7A68AA8F5D1B66A92E to 94312E973E1D6F0452A0BD48F8B0250B2F13C8C141748B9CD7291B5A5A57E097
2019-Apr-08 08:28:29.646079612 LedgerConsensus:WRN {"accepted":true,"account_hash":"512B2B7F8BBD965EB6A9B8D9353B03E176993726FE00BE9AA80698E8036AF920","close_flags":0,"close_time":608027310,"close_time_human":"2019-Apr-08 08:28:30.000000000","close_time_resolution":10,"closed":true,"hash":"64256638713E2DA57E9B775ADF6C28386B80A55E46763A37427E991265717BCF","ledger_hash":"64256638713E2DA57E9B775ADF6C28386B80A55E46763A37427E991265717BCF","ledger_index":"483","parent_close_time":608027301,"parent_hash":"311B1CA6BD7FA41EC5025CD1F2167C0DB6322430D1EFFBB5B79DE6DF53FAFE6C","seqNum":"483","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2019-Apr-08 08:28:29.646331977 LedgerConsensus:WRN Need consensus ledger 94312E973E1D6F0452A0BD48F8B0250B2F13C8C141748B9CD7291B5A5A57E097
2019-Apr-08 08:28:31.634096500 LoadMonitor:WRN Job: processLedgerData run: 6038ms wait: 10103ms
2019-Apr-08 08:28:31.647957978 LoadMonitor:WRN Job: processLedgerData run: 5875ms wait: 9950ms
2019-Apr-08 08:28:32.656398868 NetworkOPs:WRN We are not running on the consensus ledger
2019-Apr-08 08:28:33.650650359 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2019-Apr-08 08:28:33.651112781 LedgerConsensus:WRN 94312E973E1D6F0452A0BD48F8B0250B2F13C8C141748B9CD7291B5A5A57E097 to 89FA8578F7484576101FC4A42D75A80238EEA3D49A4EDE60FB2E5BDDC8E0EBEB
2019-Apr-08 08:28:33.651496148 LedgerConsensus:WRN {"accepted":true,"account_hash":"8E85FF284358E40DAEBE2A5F4DE8D29F87278862B9AE0797608139282A7699A4","close_flags":0,"close_time":608027311,"close_time_human":"2019-Apr-08 08:28:31.000000000","close_time_resolution":10,"closed":true,"hash":"9E9270AB86BC8CA0FE0C8BA7215B7AB05C0C60A493A5F09FD433B7F311FECFBA","ledger_hash":"9E9270AB86BC8CA0FE0C8BA7215B7AB05C0C60A493A5F09FD433B7F311FECFBA","ledger_index":"484","parent_close_time":608027310,"parent_hash":"64256638713E2DA57E9B775ADF6C28386B80A55E46763A37427E991265717BCF","seqNum":"484","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2019-Apr-08 08:28:33.652518063 LedgerConsensus:WRN Need consensus ledger 89FA8578F7484576101FC4A42D75A80238EEA3D49A4EDE60FB2E5BDDC8E0EBEB
2019-Apr-08 08:28:36.665498359 NetworkOPs:WRN We are not running on the consensus ledger
2019-Apr-08 08:28:37.656545564 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2019-Apr-08 08:28:37.656973939 LedgerConsensus:WRN 89FA8578F7484576101FC4A42D75A80238EEA3D49A4EDE60FB2E5BDDC8E0EBEB to 5BB75B04F5D4D08A99AF9612AA8D2945EE31BD2905D87972D37FB5B237EF1411
2019-Apr-08 08:28:37.657322791 LedgerConsensus:WRN {"accepted":true,"account_hash":"2D6C15B8743003EE63366BA4F94B0B7E894AFB189666461E31D525FD1775C9E9","close_flags":0,"close_time":608027312,"close_time_human":"2019-Apr-08 08:28:32.000000000","close_time_resolution":10,"closed":true,"hash":"9E81E1079744F593082379B553398A7C2E399A46A0A8A175FE19523A3B060C22","ledger_hash":"9E81E1079744F593082379B553398A7C2E399A46A0A8A175FE19523A3B060C22","ledger_index":"485","parent_close_time":608027311,"parent_hash":"9E9270AB86BC8CA0FE0C8BA7215B7AB05C0C60A493A5F09FD433B7F311FECFBA","seqNum":"485","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2019-Apr-08 08:28:37.658683687 LedgerConsensus:WRN Need consensus ledger 5BB75B04F5D4D08A99AF9612AA8D2945EE31BD2905D87972D37FB5B237EF1411
2019-Apr-08 08:28:40.661003132 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2019-Apr-08 08:28:40.661058853 LedgerConsensus:WRN 5BB75B04F5D4D08A99AF9612AA8D2945EE31BD2905D87972D37FB5B237EF1411 to BDC53B4DC96C4B6B77A450D53E97BC18396447E3DBF21A4ED2FBB18E23AE6CB8
2019-Apr-08 08:28:40.661108450 LedgerConsensus:WRN {"accepted":true,"account_hash":"2D6C15B8743003EE63366BA4F94B0B7E894AFB189666461E31D525FD1775C9E9","close_flags":0,"close_time":608027312,"close_time_human":"2019-Apr-08 08:28:32.000000000","close_time_resolution":10,"closed":true,"hash":"9E81E1079744F593082379B553398A7C2E399A46A0A8A175FE19523A3B060C22","ledger_hash":"9E81E1079744F593082379B553398A7C2E399A46A0A8A175FE19523A3B060C22","ledger_index":"485","parent_close_time":608027311,"parent_hash":"9E9270AB86BC8CA0FE0C8BA7215B7AB05C0C60A493A5F09FD433B7F311FECFBA","seqNum":"485","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2019-Apr-08 08:28:40.661249899 LedgerConsensus:WRN Need consensus ledger BDC53B4DC96C4B6B77A450D53E97BC18396447E3DBF21A4ED2FBB18E23AE6CB8
2019-Apr-08 08:28:44.663613186 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2019-Apr-08 08:28:44.663674899 LedgerConsensus:WRN BDC53B4DC96C4B6B77A450D53E97BC18396447E3DBF21A4ED2FBB18E23AE6CB8 to EDD6974A430254CF4C83EB799A880E1DCDE917B55F371A62FAA24AFCBBC011BC
2019-Apr-08 08:28:44.663735667 LedgerConsensus:WRN {"accepted":true,"account_hash":"2D6C15B8743003EE63366BA4F94B0B7E894AFB189666461E31D525FD1775C9E9","close_flags":0,"close_time":608027312,"close_time_human":"2019-Apr-08 08:28:32.000000000","close_time_resolution":10,"closed":true,"hash":"9E81E1079744F593082379B553398A7C2E399A46A0A8A175FE19523A3B060C22","ledger_hash":"9E81E1079744F593082379B553398A7C2E399A46A0A8A175FE19523A3B060C22","ledger_index":"485","parent_close_time":608027311,"parent_hash":"9E9270AB86BC8CA0FE0C8BA7215B7AB05C0C60A493A5F09FD433B7F311FECFBA","seqNum":"485","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2019-Apr-08 08:28:44.663902807 LedgerConsensus:WRN Need consensus ledger EDD6974A430254CF4C83EB799A880E1DCDE917B55F371A62FAA24AFCBBC011BC
2019-Apr-08 08:28:44.669840801 NetworkOPs:WRN We are not running on the consensus ledger
2019-Apr-08 08:28:48.667530136 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2019-Apr-08 08:28:48.667601165 LedgerConsensus:WRN EDD6974A430254CF4C83EB799A880E1DCDE917B55F371A62FAA24AFCBBC011BC to 140058FED74F58E0C55B622AAD23BE3D9E39D930BC3C29DF526E4E0B0BF3573D
2019-Apr-08 08:28:48.667668954 LedgerConsensus:WRN {"accepted":true,"account_hash":"1502092CE1694D022E2A51D8D1DA898278E6E4ADE97513F1EC8AE4FD57058C77","close_flags":0,"close_time":608027320,"close_time_human":"2019-Apr-08 08:28:40.000000000","close_time_resolution":10,"closed":true,"hash":"CB4609A19B1491DB97B5CCE1B7ED68E35C8E354068F4C7E11C207DABF6862EE5","ledger_hash":"CB4609A19B1491DB97B5CCE1B7ED68E35C8E354068F4C7E11C207DABF6862EE5","ledger_index":"486","parent_close_time":608027312,"parent_hash":"9E81E1079744F593082379B553398A7C2E399A46A0A8A175FE19523A3B060C22","seqNum":"486","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2019-Apr-08 08:28:48.667930869 LedgerConsensus:WRN Need consensus ledger 140058FED74F58E0C55B622AAD23BE3D9E39D930BC3C29DF526E4E0B0BF3573D
2019-Apr-08 08:28:48.678012820 NetworkOPs:WRN We are not running on the consensus ledger
2019-Apr-08 08:28:52.671411840 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2019-Apr-08 08:28:52.671473371 LedgerConsensus:WRN 140058FED74F58E0C55B622AAD23BE3D9E39D930BC3C29DF526E4E0B0BF3573D to 587E3E06CCB4C33265F6B7859C4C14C890822E2EAF9231A6FFA8603B3E5AC690
2019-Apr-08 08:28:52.671520822 LedgerConsensus:WRN {"accepted":true,"account_hash":"9F17126288FF01E7D57059D0F63604202F3869793183CAF2313468182C0EB7DE","close_flags":0,"close_time":608027330,"close_time_human":"2019-Apr-08 08:28:50.000000000","close_time_resolution":10,"closed":true,"hash":"430510A74CE071746F755BCE5F6BA2D6D8E627C877A35ED4EC2310720715B940","ledger_hash":"430510A74CE071746F755BCE5F6BA2D6D8E627C877A35ED4EC2310720715B940","ledger_index":"487","parent_close_time":608027320,"parent_hash":"CB4609A19B1491DB97B5CCE1B7ED68E35C8E354068F4C7E11C207DABF6862EE5","seqNum":"487","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2019-Apr-08 08:28:52.671675619 LedgerConsensus:WRN Need consensus ledger 587E3E06CCB4C33265F6B7859C4C14C890822E2EAF9231A6FFA8603B3E5AC690
2019-Apr-08 08:28:52.681068585 NetworkOPs:WRN We are not running on the consensus ledger
2019-Apr-08 08:28:55.693344351 NetworkOPs:WRN We are not running on the consensus ledger
2019-Apr-08 08:28:56.678327327 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2019-Apr-08 08:28:56.678391354 LedgerConsensus:WRN 587E3E06CCB4C33265F6B7859C4C14C890822E2EAF9231A6FFA8603B3E5AC690 to CD6C1177DFF4E8D45F5DA91B229AAD0529D0F54F72CEA5E8CA1B238E6A54BAF5
2019-Apr-08 08:28:56.678465781 LedgerConsensus:WRN {"accepted":true,"account_hash":"D49369BE5E80FA6AAED6C5754A6BB43FC5F4BC20528C378988092503B4E91403","close_flags":0,"close_time":608027332,"close_time_human":"2019-Apr-08 08:28:52.000000000","close_time_resolution":10,"closed":true,"hash":"2DCD25A1BCF9FF9F3CE4644DD61099FCB68A8078E3F25FA7F0D6DF5DF4D5CB76","ledger_hash":"2DCD25A1BCF9FF9F3CE4644DD61099FCB68A8078E3F25FA7F0D6DF5DF4D5CB76","ledger_index":"489","parent_close_time":608027331,"parent_hash":"0600DAC9A0ED84AB1E037F7D7157543A04AEF86A02EF12B91FDC504864891714","seqNum":"489","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2019-Apr-08 08:28:56.678793456 LedgerConsensus:WRN Need consensus ledger CD6C1177DFF4E8D45F5DA91B229AAD0529D0F54F72CEA5E8CA1B238E6A54BAF5
2019-Apr-08 08:28:59.719798450 NetworkOPs:WRN We are not running on the consensus ledger
2019-Apr-08 08:29:00.689921407 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2019-Apr-08 08:29:00.691014996 LedgerConsensus:WRN CD6C1177DFF4E8D45F5DA91B229AAD0529D0F54F72CEA5E8CA1B238E6A54BAF5 to 91EA6601986CBEDCD2FA5B2EAC57CC6BDC637DCA0C185437DE2E0179719A7C1C
2019-Apr-08 08:29:00.691548787 LedgerConsensus:WRN {"accepted":true,"account_hash":"D978907A2705E0743F24AA26C8F239CFD1230BA5061490468CB7CE42BE356592","close_flags":0,"close_time":608027340,"close_time_human":"2019-Apr-08 08:29:00.000000000","close_time_resolution":10,"closed":true,"hash":"AA7EA8274374AD0EFA324FF59061B193AC08273BC37F66C6E0C274A3F6F10E09","ledger_hash":"AA7EA8274374AD0EFA324FF59061B193AC08273BC37F66C6E0C274A3F6F10E09","ledger_index":"490","parent_close_time":608027332,"parent_hash":"2DCD25A1BCF9FF9F3CE4644DD61099FCB68A8078E3F25FA7F0D6DF5DF4D5CB76","seqNum":"490","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2019-Apr-08 08:29:00.692584188 LedgerConsensus:WRN Need consensus ledger 91EA6601986CBEDCD2FA5B2EAC57CC6BDC637DCA0C185437DE2E0179719A7C1C
2019-Apr-08 08:29:03.717965569 NetworkOPs:WRN We are not running on the consensus ledger

**Comment by yxxyun** [comment]
if you are running validator, the server state should  be proposing.

**Comment by MarkusTeufelberger** [comment]
The holes in available ledgers still look like some IO issues, either with slow internet or slow disks (not every SSD is equal).

**Comment by lambda2003** [comment]
Thank you for your response. It is still in proposing. 
Question 1: Before I upgrade, I use V1.1.1 and it supports Multisign.  Does V1.2.3 support old multisign??
Question 2: In "Proposing" status, out-going transaction works?? I mean send XRP??

**Comment by lambda2003** [comment]
@MarkusTeufelberger just curious, how many peers do you have?? Is there any option in ripple.cfg??

**Comment by lambda2003** [comment]
@MarkusTeufelberger  Sorry for my silly question. Answer by myself. 5-50 peers are normal. 

Mine is still in proposing, but it seems working. 
Thank you,
