### ISSUE TITLE
why rippled sync node lost last synced ledger?

### ISSUE THREAD

**Issue by qiluge** [ripple/rippled#2903]
My ripple sync node completed ledger is ```46435033-46455809```, and then I restart rippled service, the completed ledger is ```46455839-46455876```. Where are these ledger? How can I restore the lost ledger while I restart rippled service at next time?

**Comment by MarkusTeufelberger** [comment]
They will re-appear in `complete_ledgers` once you have fetched enough history to cover the gap from `46455839` to `46455809`.

**Comment by qiluge** [comment]
Is the gap amount limited? Such as no more than ledger_history value?

**Comment by MarkusTeufelberger** [comment]
https://github.com/ripple/rippled/blob/fa57859477441b60914e6239382c6fba286a0c26/cfg/rippled-example.cfg#L599-L619

**Comment by qiluge** [comment]
thank you!
