### ISSUE TITLE
Special addresses transactions' synchronization problem

### ISSUE THREAD

**Issue by dwjpeng** [ripple/rippled#2906]
A transaction sychronization error occurred within ledger 46599937  on  Apr 17 2019 .
. I can not get  the transaction's details (hash: C421E1D08EFD78E6B8D06B085F52A34A681D0B51AE62A018527E1B8F54C108FB,the amendment transaction)  by command "rippled tx {hash}". It is  an admendation of the special address 'rrrrrrrrrrrrrrrrrrrhoLvTp' .  Only this one can not be fetched.
**I wonder  whether all of transactions from these special addresses could not be synchronized and how to get the details by ripple command ?**
my ripple server version is 1.2.3, operations system is Ubuntu 16 LS

**Comment by yxxyun** [comment]
https://developers.ripple.com/pseudo-transaction-types.html

**Comment by dwjpeng** [comment]
> https://developers.ripple.com/pseudo-transaction-types.html

Is there any way to fetch the transaction details?

**Comment by yxxyun** [comment]
> > https://developers.ripple.com/pseudo-transaction-types.html
> 
> Is there any way to fetch the transaction details throught rpc command ?

https://developers.ripple.com/transaction_entry.html

**Comment by dwjpeng** [comment]
> > > https://developers.ripple.com/pseudo-transaction-types.html
> > 
> > 
> > Is there any way to fetch the transaction details throught rpc command ?
> 
> https://developers.ripple.com/transaction_entry.html

very kind of you, thanks a lot!
