### ISSUE TITLE
Ripple node didn't sync after a month running it

### ISSUE THREAD

**Issue by skinderis** [ripple/rippled#2925]
I have a running ripple node for about a month and it wasn't able to sync since then. Hardware resources should be enough and internet is fast on the server.

`server_info` method returns:
```
{'info': {'build_version': '1.2.4',
  'complete_ledgers': '4-39234',
  'hostid': '8e27ef7c8d59',
  'io_latency_ms': 1,
  'jq_trans_overflow': '0',
  'last_close': {'converge_time_s': 2, 'proposers': 0},
  'load': {'job_types': [{'job_type': 'untrustedValidation', 'per_second': 12},
    {'in_progress': 2, 'job_type': 'ledgerData', 'waiting': 11},
    {'in_progress': 1, 'job_type': 'clientCommand'},
    {'job_type': 'peerCommand', 'per_second': 560},
    {'job_type': 'AsyncReadNode', 'peak_time': 41, 'per_second': 1062}],
   'threads': 6},
  'load_factor': 1,
  'peer_disconnects': '5',
  'peer_disconnects_resources': '0',
  'peers': 10,
  'pubkey_node': 'n9Kp8JVVwXpG9SQFiaWKyFNycVfT5Kmv8SvQgZ7dAAVdFFJBicCH',
  'pubkey_validator': 'none',
  'server_state': 'syncing',
  'server_state_duration_us': '784695265370',
  'state_accounting': {'connected': {'duration_us': '68011351',
    'transitions': 6},
   'disconnected': {'duration_us': '2259117', 'transitions': 1},
   'full': {'duration_us': '0', 'transitions': 0},
   'syncing': {'duration_us': '784980308254', 'transitions': 6},
   'tracking': {'duration_us': '0', 'transitions': 0}},
  'time': '2019-May-03 13:53:18.783878',
  'uptime': 785050,
  'validated_ledger': {'age': 8,
   'base_fee_xrp': 1e-05,
   'hash': '2C54C9B9C7314B6959F6FB39A685EC0401787FBAB632592E6108DA1225072FD7',
   'reserve_base_xrp': 200,
   'reserve_inc_xrp': 50,
   'seq': 39234},
  'validation_quorum': 0,
  'validator_list': {'count': 0,
   'expiration': 'unknown',
   'status': 'unknown'}},
 'status': 'success'}
```

My config **ripple.cfg** file:
```
[server]
port_peer

[port_peer]
ip=0.0.0.0
port=13132
protocol=peer
admin=127.0.0.1

[database_path]
/root/ripple/data

[node_db]
type=NuDB
path=/root/ripple/data
online_delete=350000
advisory_delete=0

[ips]
r.ripple.com 51235

[node_size]
medium

[ledger_history]
350000

[fetch_depth]
full

[validation_quorum]
3

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[rpc_startup]
{ "command": "log_level", "severity": "error" }
{ "command": "log_level", "severity": "warning" }
```

**Comment by MarkusTeufelberger** [comment]
You need to configure a UNL, either by choosing to follow the one Ripple publishes or by configuring your own. Currently your server runs on its own without trusting anyone else's opinion on the network.

**Comment by intelliot** [comment]
See `[validators_file]` and the example in https://github.com/ripple/rippled/tree/develop/cfg

**Comment by mDuo13** [comment]
The recommended settings at this time are:

1. **Remove** the `[validation_quorum]` stanza from your `rippled.cfg` file.

2. **Add** the following stanza to your `rippled.cfg` file:

        [validators_file]
        validators.txt

3. In the same folder as the `rippled.cfg` file, add a file named `validators.txt` with the following info (or copy it from the link @intelliot posted):

        [validator_list_sites]
        https://vl.ripple.com
        
        [validator_list_keys]
        ED2677ABFFD1B33AC6FBC3062B71F1E8397C1505E1C42C64D11AD1B28FF73F4734
	

This configures your server to use a UNL that matches Ripple's recommendations, as served from vl.ripple.com and signed by Ripple's key pair. If you don't want to use Ripple's exact list, you can choose validators yourself or follow a different list like [Coil's](https://vl.coil.com/) but **beware**: per [the research](https://arxiv.org/abs/1802.07242), the fork-safety of the network depends on the overlap of UNLs. If your UNL has <90% overlap with the UNL another server, it's technically possible those two servers can fork apart. (The likelihood of this happening in practice is unknown, and depends on specific byzantine behavior and network conditions, but the chance of a fork increases with less overlap.)
