### ISSUE TITLE
Installing ripple on CentOS Repo Not Found

### ISSUE THREAD

**Issue by melvjoshua** [ripple/rippled#2939]
Hi, I tried to install rippled on CentOs and I got error like this :

```
failure: repodata/repomd.xml from ripple-stable: [Errno 256] No more mirrors to try.
https://mirrors.ripple.com/rpm/7/stable/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

Are there any trouble with repo server?

**Comment by movitto** [comment]
Just tried the [official installation instructions](https://developers.ripple.com/install-rippled-on-centos-rhel-with-yum.html) on a fresh CentOS7 install (7.6.1810) and rippled installed & started without a hitch.

![Screenshot from 2019-05-18 20-09-59](https://user-images.githubusercontent.com/166845/57976257-9bb0cd00-79a9-11e9-86df-426576af795b.png)

Perhaps a temporary network issue?

**Comment by melvjoshua** [comment]
I already installed it today. Maybe the repo server already fixed. Thanks
