### ISSUE TITLE
"error_code":17,"error_message":"InsufficientNetworkMode"

### ISSUE THREAD

**Issue by sgrmoharil** [ripple/rippled#2940]
Hi
I am trying to run account_info on rippled but it gives following error
{"result":{"error":"noNetwork","error_code":17,"error_message":"InsufficientNetworkMode","request":{"account":"*************************************","command":"account_info","ledger_index":"current","queue":true,"strict":true},"status":"error"}}

my server_info is 

{
   "result" : {
      "info" : {
         "build_version" : "1.0.0",
         "closed_ledger" : {
            "age" : 2,
            "base_fee_xrp" : 1e-05,
            "hash" : "*****************************************8",
            "reserve_base_xrp" : 200,
            "reserve_inc_xrp" : 50,
            "seq" : 605
         },
         "complete_ledgers" : "empty",
         "fetch_pack" : 2566,
         "hostid" : "pbxrp",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 4,
            "proposers" : 29
         },
         "load" : {
            "job_types" : [
               {
                  "avg_time" : 1,
                  "job_type" : "ledgerRequest",
                  "peak_time" : 6
               },
               {
                  "avg_time" : 2,
                  "job_type" : "untrustedProposal",
                  "peak_time" : 37,
                  "per_second" : 31
               },
               {
                  "in_progress" : 2,
                  "job_type" : "ledgerData",
                  "waiting" : 9
               },               
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "job_type" : "transaction",
                  "per_second" : 2
               },
               {
                  "job_type" : "advanceLedger",
                  "peak_time" : 15,
                  "per_second" : 21
               },
               {
                  "job_type" : "fetchTxnData",
                  "per_second" : 2
               },
               {
                  "job_type" : "trustedValidation",
                  "peak_time" : 4,
                  "per_second" : 9
               },
               {
                  "job_type" : "writeObjects",
                  "peak_time" : 12,
                  "per_second" : 10
               },
               {
                  "avg_time" : 1,
                  "job_type" : "trustedProposal",
                  "peak_time" : 47,
                  "per_second" : 7
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 564
               },
               {
                  "job_type" : "diskAccess",
                  "peak_time" : 1,
                  "per_second" : 9
               },
				{
                  "avg_time" : 1,
                  "job_type" : "AsyncReadNode",
                  "peak_time" : 40,
                  "per_second" : 587
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 1
               }
            ],
            "threads" : 3
         },
         "load_factor" : 1,
         "network_ledger" : "waiting",
         "peer_disconnects" : "0",
         "peer_disconnects_resources" : "0",
         "peers" : 11,
         "pubkey_node" : "*************************************************",
         "pubkey_validator" : "none",
         "published_ledger" : "none",
         "server_state" : "connected",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "2671593572",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "1272124",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
			"tracking" : {
               "duration_us" : "0",
               "transitions" : 0
            }
         },
         "time" : "2019-May-17 09:41:03.954345",
         "uptime" : 2673,
         "validation_quorum" : 23,
         "validator_list_expires" : "2019-Jun-03 00:00:00.000000000"
      },
      "status" : "success"
   }
}

**Comment by sgrmoharil** [comment]
Also I am running Rippled version 1.0.0

**Comment by MarkusTeufelberger** [comment]
Firstly, update your software to the most recent release. I'm not sure if you can even sync with 1.0.0 any more.

**Comment by sgrmoharil** [comment]
> Firstly, update your software to the most recent release. I'm not sure if you can even sync with 1.0.0 any more.

Hi don't want to loose my XRP during process of software update. Can you help me with check points to make sure XRP are safe before I do the update to rippled server.

**Comment by MarkusTeufelberger** [comment]
XRP are not stored on the server, they are accessible through a key pair that you hopefully have backed up safely (and privately) in multiple locations. You don't need to run your own server to access your XRP and there should be no way to actually put any key pair that manages your XRP into rippled.

**Comment by sgrmoharil** [comment]
> XRP are not stored on the server, they are accessible through a key pair that you hopefully have backed up safely (and privately) in multiple locations. You don't need to run your own server to access your XRP and there should be no way to actually put any key pair that manages your XRP into rippled.

I have all the keys with me. But like in ether we keep backup of keystore file, I thought may be there is some file which is holding all the encrypted private keys. Is there anything I have to do after updating rippled to latest version? Like entering Passphrase, Master Key or Master Seed Hex.

**Comment by intelliot** [comment]
rippled 1.0.0 will not work because new [amendments](https://developers.ripple.com/known-amendments.html) have been activated. Refer to the [Dev Blog](https://developers.ripple.com/blog/) for release announcements.

rippled does not store private keys for accounts/wallets. If you run rippled as a validator, see [Run rippled as a Validator](https://developers.ripple.com/run-rippled-as-a-validator.html).

**Comment by sgrmoharil** [comment]
Hi @intelliot , thank you for your reply. I have updated rippled server to latest version 1.2.4. But still when I run server_info I get following response. 

{
   "result" : {
      "info" : {
         "build_version" : "1.2.4",
         "closed_ledger" : {
            "age" : 8,
            "base_fee_xrp" : 1e-05,
            "hash" : "************************************************************",
            "reserve_base_xrp" : 200,
            "reserve_inc_xrp" : 50,
            "seq" : 1522
         },
         "complete_ledgers" : "empty",
         "fetch_pack" : 4308,
         "hostid" : "pbxrp",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 2.007,
            "proposers" : 28
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "untrustedProposal",
                  "peak_time" : 12,
                  "per_second" : 41
               },
               {
                  "in_progress" : 2,
                  "job_type" : "ledgerData",
                  "waiting" : 9
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               }
            ],
            "threads" : 4
         },
         "load_factor" : 1,
         "network_ledger" : "waiting",
         "peer_disconnects" : "1",
         "peer_disconnects_resources" : "0",
         "peers" : 10,
         "pubkey_node" : "*************************************************",
         "pubkey_validator" : "none",
         "published_ledger" : "none",
		 "server_state" : "connected",
         "server_state_duration_us" : "6628981500",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "6628981500",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "3261245",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : 0
            }
         },
         "time" : "2019-May-18 09:47:49.006062",
         "uptime" : 6632,
         "validation_quorum" : 28,
         "validator_list" : {
            "count" : 2,
            "expiration" : "2019-Jun-03 00:00:00.000000000",
            "status" : "active"
         }
      },
      "status" : "success"
   }
}

**Comment by intelliot** [comment]
See [Troubleshooting rippled](https://developers.ripple.com/troubleshoot-the-rippled-server.html). You can also try [switching the database type to nudb](https://github.com/ripple/rippled/wiki/server_state-stuck-in-connected-or-syncing).

**Comment by mDuo13** [comment]
Closing this stale issue. Feel free to reopen if you have any updates.
