### ISSUE TITLE
RPM-GPG-KEY-ripple-release return 404 

### ISSUE THREAD

**Issue by haruki515** [ripple/rippled#2943]
I have Install rippled on Ubuntu with Alien refer refer to [this page](https://developers.ripple.com/install-rippled-on-ubuntu-with-alien.html).
However `https://mirrors.ripple.com/rpm/RPM-GPG-KEY-ripple-release` return 404 and I could not Verify the signature on the rippled software package .

```
Retrieving https://mirrors.ripple.com/ripple-repo-el7.rpm 
Preparing...                          ######################################## 
Updating / installing... 
ripple-repo-1-2.el7.centos            ######################################## 
curl: (22) The requested URL returned error: 404 Not Found 
error: https://mirrors.ripple.com/rpm/RPM-GPG-KEY-ripple-release: import read failed(2). 
```

**Comment by mellery451** [comment]
thanks for reporting this issue - this was a temporary service outage and should be working again now.
