### ISSUE TITLE
About building a ripple authentication server locally

### ISSUE THREAD

**Issue by liyong520** [ripple/rippled#2946]
I am now setting up a local authentication server for testing, but how do other nodes trust this authentication server, without the https domain name, can I cancel this domain authentication and trust directly?

**Comment by MarkusTeufelberger** [comment]
...authentication server?

**Comment by liyong520** [comment]
> ...authentication server?
I want to try to build a set of ripple private chains, but I can't get my validator to be trusted. Is there a tutorial on this?

**Comment by nbougalis** [comment]
Check out https://github.com/ripple/rippled/blob/develop/cfg/validators-example.txt
