### ISSUE TITLE
Allow validator list propagation over the peer network

### ISSUE THREAD

**Issue by ximinez** [ripple/rippled#2953]
Any time a Server downloads or receives a validator list, it should broadcast a message reporting the contents of the validator list to all of its immediately connected peers, except those which have recently sent the same list to the Server.

The message should NOT be flooded throughout the peer network; just to a server's immediate peers. Optionally, servers could track (on an ephemeral per-connection basis) which sequence number a particular peer has and avoid sending the notification to servers known to have that list already. 

Additionally, the Server should save the updated validator list into its local data directory with a file name like: `unl.<publickey>`. On startup, the Server should read that file, validate it, and use it as its starting validator list.

Finally, the Server should send all of its trusted validator lists to new peers when they first connect.

Replaces Jira issue RIPD-1673.

**Comment by MarkusTeufelberger** [comment]
This sounds a lot like disclosing a UNL (or at least your chosen UNL strategy: a validator list or a hand-picked config) to untrusted third parties - and I'm probably right now burning quite some actual money in bug bounties by pointing this out before y'all implement it...
It also sounds a bit like a DoS or spam vector, depending on the content of such files. Maybe something like a "block header" for validator lists could be done that's only a sequence number, a PoW and a signature, but that gets flooded through the network, BitMessage style and that then can help servers that don't have DNS or the ability to download stuff on ports 80 or 443 to get the data via IPFS or from peers?

I'm unsure if storing state in a file (why not one of the several databases, e.g. wallet.db?) is a good idea, but if it gets verified correctly, it can't hurt I guess and might allow for offline updating/seeding. If you're already storing such files (I don't like the idea of only calling validator site lists "UNL" by the way), then it might also make sense to store older versions of them too. I anyways find it strange that these lists don't seem to be built for auditing historic recommendations of a certain registry.

Is it really that common that servers aren't able to get data via HTTP/S reliably that a workaround like this is even necessary? To me it sounds like enabling bad practices and adding complexity for people that operate servers in configurations that are out of the norm to begin with.

**Comment by mDuo13** [comment]
> Is it really that common that servers aren't able to get data via HTTP/S reliably that a workaround like this is even necessary?

It has certainly amazed me how often servers fail to get a validator list over HTTPS. For something like six months it felt like that was the only source of validator issues.

**Comment by mellery451** [comment]
I think the biggest (past) issue was that we didn't have a timeout on the VL request/download, so it was demonstrably possible to get stuck on a half-open read situation. That was fixed in dd99bf479f9f2289081a7c765e9f1405c2fdf1be and I'm not aware of any *persistent* download failures since.
