### ISSUE TITLE
NuDB backend should store inner node object type (?)

### ISSUE THREAD

**Issue by movitto** [ripple/rippled#2960]
Greetings & happy monday everyone. I'm opening this issue in part due to some confusion I encountered while continuing to work through the codebase. Particularly with a difference between data retrieved between the rocksdb and nudb backends. If this is a non-issue and a "designed by choice" sort of thing, feel free to close this, though I'd be curious as to the rationale behind this design.

When parsing the same inner node stored in both backends (particularily node: "001b46daaea7a40d9dcdc30f83918db8c8f9110c22e1207bcd8f9145dbe032dd") I noticed that in rocksdb the NodeObjectType field was stored correctly (eg set to '3' indicating this is an 'account' inner node) while in nudb it was not set at all.

We can see in the [node_object compressor](https://github.com/ripple/rippled/blob/develop/src/ripple/nodestore/impl/codec.h#L367) (invoked only from the nudb backend), the node_type (inner_node), mask, and node data are stored, but the node object type is not. And in the [decompressor](https://github.com/ripple/rippled/blob/develop/src/ripple/nodestore/impl/codec.h#L156) above, this value is set to the default '0' for 'unknown'.

Grepping the codebase, I cannot find any place where it semantically swaps 'hotUNKNOWN' to the correct node object type based on context, though perhaps I missed something. Should the node object type be stored in the NuDB backend in the same way it is stored in rocksdb? Or does this not matter for this situation?

Any insight would be greatly appreciated.

**Comment by JoelKatz** [comment]
This was an intentional decision, but it's certainly one that you can argue either way. We don't need to store the node type. And at the time, we were really trying to squeeze every possible byte out of the storage requirements because that also affects memory requirements, I/O requirements, and so on.

**Comment by movitto** [comment]
Cool, thanks for the info @JoelKatz. Figured it was something like this, one should be able to deduce the  inner node object type from the tree in which it resides. Closing this out.

**Comment by MarkusTeufelberger** [comment]
When traversing the Trie that's definitely true. If you only get a random InnerNode, you'd need to do a depth-first search until you reach a leaf to actually know what it is. I'm not sure that this matters in practice...

Still would be great if that's documented somewhere or alternatively if the distinctions between the 2 inner node types get removed.

**Comment by movitto** [comment]
> When traversing the Trie that's definitely true. If you only get a random InnerNode, you'd need to do a depth-first search until you reach a leaf to actually know what it is. I'm not sure that this matters in practice...

Agreed

> Still would be great if that's documented somewhere or alternatively if the distinctions between the 2 inner node types get removed.

It's documented in this issue! Kidding aside, I agree on this one too. We're continuing to expand our [nodestore parser](https://github.com/DevNullProd/XRBP/tree/master/lib/xrbp/nodestore) to address these edge cases, so perhaps when that's 100% complete, we can throw a formal spec together as to the binary data format & structures and upload that to ripple-labs doc's. No guarantees on when that'll happen though, and if anyone wants to do it first, don't let me stop you!
