### ISSUE TITLE
rippled account_info lgrNotFound error.

### ISSUE THREAD

**Issue by dmitriano** [ripple/rippled#2961]
I made an attempt to run rippled both versions 1.1.2 and 1.2.4 on Ubuntu 18.04 and I would not say it does not work at all, because it utilizes CPU and Disk, creates database of 3GB size, and I even was able to create a wallet from the command line, but if I do

`./rippled account_info r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59 true`

I always get something similar to the result described in [this](https://github.com/ripple/rippled/issues/2442) post:

```
Loading: "/home/xrp/.config/ripple/rippled.cfg"
2019-May-29 10:04:10.273909186 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "result" : {
      "error" : "lgrNotFound",
      "error_code" : 21,
      "error_message" : "ledgerNotFound",
      "request" : {
         "account" : "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
         "command" : "account_info",
         "ledger_index" : 0
      },
      "status" : "error"
   }
}

```
I am not sure the error is caused by the low hardware performance. I run rippled on virtual machine with SSD and 16GB RAM, disk IO rate periodically riches 40+M/s, but my CPU is Intel Celeron 2.8GHz with 2 cores, periodically CPU usage reaches 100%, can CPU be the bottleneck? See the [screenshot](https://developernote.com/2019/01/building-and-running-rippled-on-ubuntu/htop/).

What else can be wrong?

See [Building and running rippled on Ubuntu](https://developernote.com/2019/01/building-and-running-rippled-on-ubuntu/) for more information on what steps I did.

**Comment by MarkusTeufelberger** [comment]
Looks to me like you have a slow SSD and the weak CPU probably doesn't help either... do you do continuous monitoring of that machine (e.g. wih Prometheus) or are you running blindly?

You also should check if you are actually able to receive incoming connections on your peer port, since you only have 10 peers.

Why do you want to store history on a validator or why do you want to validate if you want to use a server as RPC endpoint?

Lastly according to your screenshots, you are also running another very IO heavy program (`geth`) on the same machine. I suspect that this also will not help, performance wise.

**Comment by dmitriano** [comment]
See my [SSD benchmark results](https://developernote.com/2019/01/building-and-running-rippled-on-ubuntu/#ssd). Currently I do there is no monitoring software on this machine.

I opened port 51235 for incoming connections and now I have about 20 [peers](https://developernote.com/2019/01/building-and-running-rippled-on-ubuntu/#peers).

I thought that validator may help, but if I do not need it I switch if off. Does it affect the performance?

'geth' is in 'light' mode, so its unlikely it consume resources, however it can be turned off to make a clean experiment.

Currently I still have the same 'lgrNotFound' error. What to do next? Install Prometheus and upgrade CPU?

**Comment by nbougalis** [comment]
I love the writeup you link to. Thanks for taking the time to compile, and try out `rippled`!

On first glance, your SSD _seems_ like it should be plenty fast. Are you running this in a VM or cloud environment? Some of them impose restrictions.

The output from your `server_state` calls suggests you synced up to the network and, at some point, were tracking it pretty well but then fell behind; see the `age` of the `validated_ledger` object: it should never really be more than about 7 seconds on a healthy server.

 It's hard to know why you fell so far behind. This can be for a number of reasons, connectivity being one of them, although your server seems to have had 10 peers at the time. It's possible that it's disk I/O.

I don't think upgrading the CPU is needed at this time. I don't think will help and I doubt you're truly CPU-bound. My educated _guess_ is that you're running on a virtual environment.

Can you explain your setup a little more?

**Comment by dmitriano** [comment]
I am running rippled on Ubuntu 18.04 Desktop inside Hyper-V virtual machine on Windows 10 Pro (version 1903). See [my Ubuntu system summary](https://developernote.com/2019/01/building-and-running-rippled-on-ubuntu/#ss) (for some reason inxi unable to detect the network card). Hyper-V has a typical configuration with 2 Processors, 16GB RAM (with disabled Dynamic Memory), about 200GB hard drive and External Network adapter (with IP address visible in the local network).

I left rippled running for several days and it stopped working at all, at least the commands from the command line hangs up for a long time and then show this:

```
 {
   "error" : "internal",
   "error_code" : 71,
   "error_message" : "Internal error.",
   "error_what" : "no response from server"
}
```
and there were multiple occurrences of a string like this in logs:

`rippled[687]: 2019-Jun-15 22:54:30.584170705 LoadManager:WRN Server stalled for 31820 seconds.`

htop displayed me [this](https://developernote.com/2019/01/building-and-running-rippled-on-ubuntu/rippled-stalled/).

I tried to restart the service with `sudo service rippled restart` and got `Failed to restart rippled.service: Unit rippled.service not found.` (I am not a linux expert and I do not know exactly what does this mean).

At the same time `geth` (Ethereum node) running on the same virtual machine along with `rippled` worked fine.

I rebooted the machine and `rippled` started to work normally as before, see [htop screenshot](https://developernote.com/2019/01/building-and-running-rippled-on-ubuntu/rippled-reboot/).

Right after reboot I run `./rippled server_info` multiple times and `age` varied between 0 and 11. If I run `./rippled server_state` there is no `age` at all. The number of peers was 10 or 11, but previously it reaches 20 (after I opened the port for incoming connections).

**Comment by dmitriano** [comment]
For the last two days 'rippled' worked normally with the age in the rage [0, 8] and 21 peers, but with the same "lgrNotFound" error.

**Comment by dmitriano** [comment]
@nbougalis For the last two days 'rippled' worked normally with the age in the rage [0, 8] and 21 peers, but with the same "lgrNotFound" error. 

Also today I noticed that validators expiration date is not in future, see [the full output](https://developernote.com/2019/01/building-and-running-rippled-on-ubuntu/#validators) of `./rippled validators` command.  At the moment of running the command the server date/time was 2019-Jul-17 12:42:16 UTC, but the expiration date was 2019-Jul-17 00:00:00

**Comment by dmitriano** [comment]
I tried the same `account_info` command with **s1.ripple.com** and **s2.ripple.com** and got the same "lgrNotFound" error:

`./rippled -v --rpc_ip 34.213.185.56:51234 account_info r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59 true`

```
Loading: "/home/guber/.config/ripple/rippled.cfg"
2019-Jun-17 14:23:44.826270902 RPCParser:TRC Method: 'account_info'
2019-Jun-17 14:23:44.826345101 RPCParser:TRC Params: [ "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59", "true" ]

2019-Jun-17 14:23:44.826364401 RPCParser:TRC RPC Request:
{
        "account" : "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
        "ledger_index" : 0
}


2019-Jun-17 14:23:44.826431800 HTTPClient:NFO Connecting to 34.213.185.56:51234

2019-Jun-17 14:23:44.826492499 HTTPClient:TRC Fetch: 34.213.185.56
2019-Jun-17 14:23:44.826536799 HTTPClient:TRC expires_from_now: Success
2019-Jun-17 14:23:44.826550999 HTTPClient:TRC Resolving: 34.213.185.56
2019-Jun-17 14:23:44.826761896 HTTPClient:TRC Resolve complete.
2019-Jun-17 14:23:45.037269225 HTTPClient:TRC Connected.
2019-Jun-17 14:23:45.037315124 HTTPClient:TRC Session started.
2019-Jun-17 14:23:45.037321424 HTTPClient:DBG requestRPC: strPath=''
2019-Jun-17 14:23:45.037367524 HTTPClient:TRC Wrote.
2019-Jun-17 14:23:45.248605244 HTTPClient:TRC Header: "HTTP/1.1 200 OK
Date: Mon, 17 Jun 2019 14:23:45 +0000
Connection: Keep-Alive
Content-Length: 204
Content-Type: application/json; charset=UTF-8
Server: ripple-json-rpc/rippled-1.2.4

{"result":{"error":"lgrNotFound","error_code":21,"error_message":"ledgerNotFound","request":{"account":"r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59","command":"account_info","ledger_index":0},"status":"error"}}

"
2019-Jun-17 14:23:45.248702543 HTTPClient:DBG invokeComplete: Deadline popping: 1
2019-Jun-17 14:23:45.248726343 HTTPClient:DBG RPC reply: {"result":{"error":"lgrNotFound","error_code":21,"error_message":"ledgerNotFound","request":{"account":"r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59","command":"account_info","ledger_index":0},"status":"error"}}



2019-Jun-17 14:23:45.248752043 HTTPClient:TRC Deadline cancelled.
{
   "result" : {
      "error" : "lgrNotFound",
      "error_code" : 21,
      "error_message" : "ledgerNotFound",
      "request" : {
         "account" : "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
         "command" : "account_info",
         "ledger_index" : 0
      },
      "status" : "error"
   }
```

But

`./rippled -v --rpc_ip 34.213.185.56:51234 server_info`

works fine, for example.

What does this mean?

**Comment by mDuo13** [comment]
I'm not sure why `account_info` would work over JSON-RPC with curl but not with the commandline. The commandline is just an interface to the JSON-RPC anyway. The only things I can think of are:

- Your commandline client is hitting a different server than curl. Possibly that's because there was a bug in 1.1.x (#2777) that ignored the port?
- Maybe the server lost sync in between the two calls?

I suspect it's the former, in which case, that much is a known issue, but also... I guess one of your servers doesn't have the necessary ledger history?

**Comment by dmitriano** [comment]
@mDuo13 Looks like the command like arguments were wrong. If I replace 'true' with 'strict' it works:

`./rippled account_info r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59 strict`

**Comment by carlhua** [comment]
Closing this issue.
