### ISSUE TITLE
RippledNotInitializedError error while connecting through WS to local node

### ISSUE THREAD

**Issue by dmitryrn** [ripple/rippled#2965]
I just started node and trying to connect with default config and WS API returning error ``RippledNotInitializedError: Rippled not initialized``

How long I need to wait to node being initialised? As I can see it starts from ledger 1 and continue to sync. Do I need to use some settings to adjust sync? My task is send and receive transactions. Thank you.

```js
const Ri = require('ripple-lib').RippleAPI

Promise.resolve().then(async () => {
  const r = new Ri({
    server: 'ws://localhost:6006',
  })
  await r.connect()
  
  console.log(await r.isConnected())
}).catch(e => console.log(e))

```

**Comment by intelliot** [comment]
It usually does not take long for a node to initialize; typically 10-20 minutes, depending on the speed of your machine and network connection.

It should not start at ledger 1, but from the latest ledger and sync in reverse chronological order. The settings that affect syncing are found in [rippled.cfg](https://github.com/ripple/rippled/blob/develop/cfg/rippled-example.cfg) and your `validators_file`. In particular, you can set the `ledger_history` setting. But if it is not set, the default is 256, which should be fine for sending and receiving transactions.

**Comment by intelliot** [comment]
Looks like this is solved. If the problem persists, feel free to create a new issue (include your `rippled.cfg` with any sensitive information redacted).
