### ISSUE TITLE
[need help] Ripple node performance site

### ISSUE THREAD

**Issue by naoyukitakada66** [ripple/rippled#2966]
I'm looking for a site that is visualizing node performance like stellar.

https://dashboard.stellar.org/

Please let me know if you know ripple node perfomance site.

**Comment by HowardHinnant** [comment]
Are you aware of these sites?

https://xrpcharts.ripple.com/#/metrics
https://xrpcharts.ripple.com/#/topology
https://xrpcharts.ripple.com/#/validators

**Comment by movitto** [comment]
We also provide metrics via Wipple (beta): https://wipple.devnull.network/

**Comment by naoyukitakada66** [comment]
Thank you for your reply.

Is there a testnet on this site?

**Comment by movitto** [comment]
> Thank you for your reply.
> 
> Is there a testnet on this site?

Which site? With Wipple, we do have limited testnet support:

Set the testnet URI here: https://wipple.devnull.network/live/settings
And see live transactions / issue new ones on the test net here: https://wipple.devnull.network/live/transactions

**Comment by naoyukitakada66** [comment]
Thank you for your reply.
