### ISSUE TITLE
I want to restart "rippled" and leave it as "complete_ledgers"

### ISSUE THREAD

**Issue by h6dworker** [ripple/rippled#2968]
Even with the command option "--load" or "--ledger [ledger]"
The past ledger disappears.

How do I leave a ledger?

Also, the stanza's [import_db] and [ips_fixed] settings do not work well with the description.

The past ledger will not be returned even if "--import" is specified.

**Comment by nbougalis** [comment]
When you restart, the server first needs to catch up to the network and then it will backfill (if configured) to do so. Once it finds an ledger in the database, it will import it. So `complete_ledgers` will always be empty on startup.

**Comment by h6dworker** [comment]
thank you very much for your help.

"complete_ledgers" : "47910508-47913510"
"fetch_pack": 9844,
"server_state": "tracking"
(by server_info)

In the environment of ripple net
"complete_ledgers" seem to be backfilling at random.
Is this a backfill situation?
(Past ledgers also get data from peers and backfill them.)
https://developers.ripple.com/ledger-history.html#fetching-history
https://developers.ripple.com/online-deletion.html

Starting with [5], I tried in the ledger environment.
(Too many ledgers 9 TB?)
I did not backfill on my net.It is different from ripple net.
I am not in a state of "Backfilling history " with ripples.

**Comment by nbougalis** [comment]
Pardon me but I'm not sure what you're asking at this point. Can you explain what you see and how it's not what you _expect_ to see?

**Comment by h6dworker** [comment]
thank you for your help and support.
By source file setting,
Before 32570, it turned out that it was not backfilled.

**Comment by h6dworker** [comment]
Before 32570, it turned out that it was not backfilled.
