### ISSUE TITLE
Trim whitespace in config

### ISSUE THREAD

**Issue by alloyxrp** [ripple/rippled#2979]
Whitespace is not trimmed before evaluating section headings in the config. And the code uses `strValue[0]` to evaluate. This causes sections with a whitespace before them to be ignored.

https://github.com/ripple/rippled/blob/efa926676c1b63fddb88f7686fb3e6edc26b169c/src/ripple/core/impl/Config.cpp#L70-L90

The code
```
if (bTrim)
    boost::algorithm::trim (strValue);
```
needs to be moved up in order to handle section heading trimming.
Additionally, trimming of key/value pairs is handled elsewhere in the code, and not within the config parser.
@nbougalis @mellery451

**Comment by mellery451** [comment]
merged in 2c4b3d515d6aa3a4ae91986196f15e0cd212c4df
