### ISSUE TITLE
slow sync of full history node

### ISSUE THREAD

**Issue by salisbury-espinosa** [ripple/rippled#2985]
https://xrpl.org/configure-full-history.html

> To get a faster start on acquiring ledger history, you may want to find another server operator who has a large amount of history already downloaded, who can give you a database dump or at least allow your server to explicitly peer with theirs for a long time to acquire history. 

Hello! can anyone share a full history snapshot for xrp, don't want to wait six months when it stumbles) or share shards archives

**Comment by MarkusTeufelberger** [comment]
This is quite a lot of data (about 10 TB - give or take a few), how would you suggest to have this shared with you?

**Comment by sublimator** [comment]
How big is a single ledger json dump these days?

**Comment by MarkusTeufelberger** [comment]
> How big is a single ledger json dump these days?

Ledger 48 000 000 in "binary" format and json:

1121170669 bytes (~1 GiB)

**Comment by sublimator** [comment]
Hasn’t really grown much since I last looked

**Comment by sublimator** [comment]
@MarkusTeufelberger 
> share shards archives
I think he wanted some shards.

**Comment by salisbury-espinosa** [comment]
@sublimator  i want full history node

**Comment by sublimator** [comment]
I wish they had history packs on S3 :)

Just a log stream of binary deltas between the ledgers

Snapshots packs with full state every N ledgers

>

**Comment by carlhua** [comment]
Sorry, we do not provide full history via S3 at the moment. Shards will be released in the future which will improve this situation.
