### ISSUE TITLE
Please Triage the Open Issues

### ISSUE THREAD

**Issue by ghost** [ripple/rippled#2989]
It is difficult for a newcomer to get an project-overview, simply because several issues are unprocessed.

Issues should get at a minimum a category (bug, enhancement) and possibly a priority.

This would be something for the existent maintainers to do.

https://github.com/ripple/rippled/issues?q=is%3Aopen+is%3Aissue+no%3Alabel

**Comment by mDuo13** [comment]
I've added labels to all the open issues and closed several stale issues. Hopefully that is a bit more helpful.

I believe there are still issues that are only in Ripple's private Jira instance, but the team hopes to stop using Jira soon and have all issues in GitHub.
