### ISSUE TITLE
Source Compile Fatal Error

### ISSUE THREAD

**Issue by gitslagga** [ripple/rippled#2991]
Within this link https://xrpl.org/build-run-rippled-ubuntu.html 
I using camke 3.14.5, boost 1.70.0,  ripple 1.2.4 to compile ripple source 
Finally command  `cmake --build .` 
Got this error :

In file included from /root/code/rippled/src/ripple/beast/container/aged_unordered_map.h:23:0,
                 from /root/code/rippled/src/ripple/ledger/CachedSLEs.h:25,
                 from /root/code/rippled/src/ripple/ledger/CachedView.h:23,
                 from /root/code/rippled/src/ripple/app/ledger/Ledger.h:25,
                 from /root/code/rippled/src/ripple/app/consensus/RCLCxLedger.h:23,
                 from /root/code/rippled/src/ripple/app/consensus/RCLConsensus.h:23,
                 from /root/code/rippled/src/ripple/app/consensus/RCLConsensus.cpp:20,
                 from /root/code/rippled/src/ripple/unity/app_consensus.cpp:20:
/root/code/rippled/src/ripple/beast/container/detail/aged_unordered_container.h:27:10: **fatal error: boost/beast/core/detail/empty_base_optimization.hpp: No such file or directory**
 #include <boost/beast/core/detail/empty_base_optimization.hpp>

**Comment by MarkusTeufelberger** [comment]
> Version 1.2.0 of rippled requires Boost version 1.67.0 exactly.

**Comment by nikitasius** [comment]
> > Version 1.2.0 of rippled requires Boost version 1.67.0 exactly.

1.67?.. ohh. https://github.com/boostorg/beast/issues/967#issuecomment-508402576

**Comment by gitslagga** [comment]
Thank you very much.

**Comment by gitslagga** [comment]
Thank you very much.

**Comment by MarkusTeufelberger** [comment]
The current Release Candidate compiles with Boost 1.70 by the way.

**Comment by vinniefalco** [comment]
`boost::empty_value` replaces `beast::detail::empty_base_optimization`  (and the syntax is slightly different)
