### ISSUE TITLE
Clarify "rippled-package-builder" vs. "./Builds/containers"

### ISSUE THREAD

**Issue by ghost** [ripple/rippled#2993]
Those two seem to do the same things:

https://github.com/ripple/rippled-package-builder

https://github.com/ripple/rippled/tree/develop/Builds/containers

Which one should be used?

**Comment by mellery451** [comment]
The former was used for 1.2 and earlier rpms. The latter will be used for 1.3 debs and rpms.

**Comment by lazaridiscom** [comment]
Thus https://github.com/ripple/rippled-package-builder is more or less legacy?

* Add a remark to readme
* close the open issues: https://github.com/ripple/rippled-package-builder/issues and PR's
* Archive project

?

**Comment by thejohnfreeman** [comment]
Ilias, a "please" or a "can I suggest?" here and there would go a long way. :)

**Comment by lazaridiscom** [comment]
Now that's kind of a disturbing non-technical comment (thus essentially off-topic).

Additionally: I intentionally mention only "Lazaridis" within github, so please, stick with it.

(see, there was a "please", a natural one. I would never(!) use a "please")

Anyone to comment on the essence, instead on my individual expression style?

**Comment by lazaridiscom** [comment]
(@thejohnfreeman , here's another natural "please": #2989 )

**Comment by mellery451** [comment]
I added deprecation note to rippled-package-builder. Eventually I expect that project to be archived.
