### ISSUE TITLE
Testnet broken

### ISSUE THREAD

**Issue by bert2002** [ripple/rippled#2997]
Hi,
i think the testnet broke this morning at 12:30AM UTC.
First I thought it is my node:

```
$ /opt/ripple/bin/rippled ledger current
Loading: "/etc/opt/ripple/rippled.cfg"
2019-Jul-11 03:11:23.260559663 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "result" : {
      "error" : "noNetwork",
      "error_code" : 17,
      "error_message" : "InsufficientNetworkMode",
      "request" : {
         "command" : "ledger",
         "ledger_index" : "current"
      },
      "status" : "error"
   }
}
```
but also the public nodes of s.altnet.rippletest.net seems to be unavailable:
```
$ /opt/ripple/bin/rippled --rpc_ip 35.158.96.209:51234 ledger current
Loading: "/etc/opt/ripple/rippled.cfg"
2019-Jul-11 03:10:56.365452043 HTTPClient:NFO Connecting to 35.158.96.209:51234

{
   "error" : "internal",
   "error_code" : 71,
   "error_message" : "Internal error.",
   "error_what" : "no response from server"
}
```

Seems that `https://test.bithomp.com/explorer` is not working either.

Anyone working on this or am I on the wrong track?

Cheers,
bert

**Comment by nbougalis** [comment]
Thanks for the report, we are aware of the issue with the altnet/testnet and are working on it. We'll add updates here, since you opened this issue.

**Comment by nbougalis** [comment]
The altnet should be back. As of a few minutes ago:

```"validated_ledger" : {
            "age" : 2,
            "base_fee_xrp" : 1e-05,
            "hash" : "77FF0FFD02A0061B747AB28DACA93B5429F5DAD45BF8F896595A2EDCF9D92EFF",
            "reserve_base_xrp" : 20,
            "reserve_inc_xrp" : 5,
            "seq" : 20914719
         },
```

**Comment by MarkusTeufelberger** [comment]
What was the cause of that full network outage?

**Comment by nbougalis** [comment]
We'll be publishing a more detailed post-mortem soon, but briefly: the initial evidence suggests that the upgrade rulebook wasn't followed, and as a result, multiple validators were taken down at once, resulting a loss of quorum (the altnet has 6 validators and the quorum is 4). The "unexpected" stall caused us to try and understand the circumstances, which resulted in an extended delay.

**Comment by MarkusTeufelberger** [comment]
Ah, ok - so mostly operator error rather than something related to the actual algorithm or software used.

Would be nice to have some playbooks/rulebooks pulished by Ripple on how to operate rippled btw. :-)

**Comment by gituser** [comment]
I'm still seeing my testnet node OOM'in (out of memory) on the latest tag (beta) v1.3.0-rc1 from time to time. Any ideas what might be causing this?

Thanks.

**Comment by MarkusTeufelberger** [comment]
Too little memory maybe? What's your `node_size` set at and how much RAM can `rippled` use in your setup?

**Comment by gituser** [comment]
@MarkusTeufelberger yeah, I guess. I had `medium` and 8GB memory. Changed now back to `tiny`. But it has been working for months like that without any issues even on `1.2.4`.

**Comment by MarkusTeufelberger** [comment]
You have 8 GB RAM in total or available for rippled to use?What is the usage pattern for this node (e.g. executing RPC commands, just passively running along in the network, validator...)?

**Comment by gituser** [comment]
@MarkusTeufelberger No. Simple node for sending transactions with trumped history to 2000 ledgers.

**Comment by MarkusTeufelberger** [comment]
> trumped history

So the node just makes up some conflicting ledger states and declares them all to be valid while spending resources to build a firewall towards the southbridge? :-P

**Comment by gituser** [comment]
@MarkusTeufelberger 

rippling Donald 24/7

**Comment by gituser** [comment]
Jokes aside, but it seems testnet rippled still OOM's for me with `tiny` setting on 8GB VM.

It started a month ago or so before that rippled was working just fine.

**Comment by intelliot** [comment]
Just curious: How long does the testnet rippled server generally stay running for, before it OOMs?

**Comment by gituser** [comment]
@intelliot the time varies, but generally it is between 2 to 5 hours.

**Comment by nbougalis** [comment]
That's interesting. I'm running a server myself and I haven't seen an OOM but I may be using more than 8GB. I'll double-check and follow up.

**Comment by nbougalis** [comment]
The altnet has been reset and this should no longer be an issue. If you continue to experience OOM problems, please reopen.

**Comment by bagikh** [comment]
Hello, is https://testnet.data.api.ripple.com still working?

I cannot get results for these /v2/ledgers and /v2/ledgers/ledgerIndex methods. Does anybody have any idea how to solve it?
