### ISSUE TITLE
InsufficientNetworkMode

### ISSUE THREAD

**Issue by tropa** [ripple/rippled#2998]
Server in stock mode. Main network. I created an account, credited it 30 xrp. api.getBalances returns the correct response, but api.accountInfo returns InsufficientNetworkMode.

server_info

{
   "result": {
      "info": {
         "build_version": "1.2.4",
         "complete_ledgers": "48584141-48584194,48585338-48585339,48585345-48585544,48585917-48585922.48586027-48586028,4858613048488686141.48586233-48586864.48586353-48587310",
         "hostid": "DS4298.example.com",
         "io_latency_ms": 1,
         "jq_trans_overflow": "0",
         "last_close": {
            "converge_time_s": 2.001,
            "proposers": 0
         },
         "load": {
            "job_types": [
               {
                  "avg_time": 4,
                  "job_type": "ledgerRequest",
                  "peak_time": 55
               },
               {
                  "job_type": "untrustedProposal",
                  "peak_time": 10,
                  "per_second": 27
               },
               {
                  "in_progress": 2,
                  "job_type": "ledgerData",
                  "waiting": 227
               },
               {
                  "in_progress": 1,
                  "job_type": "clientCommand",
                  "per_second": 1
               },
               {
                  "job_type": "advanceLedger",
                  "per_second": 16
               },
               {
                  "avg_time": 3,
                  "job_type": "trustedValidation",
                  "peak_time": 24,
                  "per_second": 5
               },
               {
                  "job_type": "writeObjects",
                  "peak_time": 23,
                  "per_second": 5
               },
               {
                  "job_type": "trustedProposal",
                  "peak_time": 6,
                  "per_second": 9
               },
               {
                  "job_type": "peerCommand",
                  "per_second": 519
               },
               {
                  "job_type": "diskAccess",
                  "peak_time": 23,
                  "per_second": 5
               },
               {
                  "avg_time": 2,
                  "job_type": "AsyncReadNode",
                  "peak_time": 38,
                  "per_second": 347
               },
               {
                  "avg_time": 2,
                  "job_type": "WriteNode",
                  "peak_time": 38,
                  "per_second": 347
               }
            ],
            "threads": 6
         },
         "load_factor": 1,
         "peer_disconnects": "2",
         "peer_disconnects_resources": "0",
         "peers": 10,
         "pubkey_node": "n9M9VpLPHKECVKSURcAyCRZCmKTnKdZkvjYK49sk8re6CJjuXWsg",
         "pubkey_validator": "none",
         "published_ledger": 48587310,
         "server_state": "full",
         "server_state_duration_us": "10450699947",
         "state_accounting": {
            "connected": {
               "duration_us": "134249408",
               "transitions": 1
            },
            "disconnected": {
               "duration_us": "2685052",
               "transitions": 1
            },
            "full": {
               "duration_us": "41969616736",
               "transitions": 39
            },
            "syncing": {
               "duration_us": "426441263",
               "transitions": 39
            },
            "tracking": {
               "duration_us": "52",
               "transitions": 39
            }
         },
         "time": "2019-Jul-11 20: 02: 31.525190",
         "uptime": 42533,
         "validated_ledger": {
            "age": 3221,
            "base_fee_xrp": 1e-05,
            "hash": "EF4ABD9B3E3EE9521FA1245AC6E825974F373BC28C8549841CC28D7E7544D0FF",
            "reserve_base_xrp": 20,
            "reserve_inc_xrp": 5,
            "seq": 48587384
         },
         "validation_quorum": 25,
         "validator_list": {
            "count": 1,
            "expiration": "2019-Jul-17 00: 00: 00.000000000",
            "status": "active"
         }
      },
      "status": "success"
   }
}

I broke my head already.

**Comment by tropa** [comment]
Advise to wait for synchronization, replace the hard drive, buy a wider channel, what else is there? Other ideas, why this shit does not work, I see, no? Maybe wipe the headlights and knock on the wheel?

**Comment by MarkusTeufelberger** [comment]
Get an SSD and make sure your peer port is actually externally reachable.

**Comment by gituser** [comment]
I got this issue too from time to time on NVME drives the thing is:

Confirmed balance is being returned correctly, whilst unconfirmed balance returns `noNetwork`
I query unconfirmed balance via: 
```
./rippled -q json account_info "{
        \"account\": \"$ACCOUNT\",
        \"queue\": \"true\"
}"
```

```
Unconfirmed balance:
{
   "result" : {
      "error" : "noNetwork",
      "error_code" : 17,
      "error_message" : "InsufficientNetworkMode",
      "request" : {
         "account" : "XXXX",
         "command" : "account_info",
         "method" : "account_info",
         "queue" : "true"
      },
      "status" : "error"
   }
}
```

rippled is running on 20GB VM with plenty of space and iops on NVME drives, so there must be an issue with rippled itself.

**Comment by intelliot** [comment]
@gituser What's the output of server_info?

**Comment by gituser** [comment]
@intelliot 

```
./rippled server_info
Loading: "/home/ripple/rippled.cfg"
2019-Jul-17 18:35:57.785047407 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "result" : {
      "info" : {
         "build_version" : "1.2.4",
         "complete_ledgers" : "48716243-48719995",
         "hostid" : "ripple-prod",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 2.899,
            "proposers" : 31
         },
         "load" : {
            "job_types" : [
               {
                  "avg_time" : 6,
                  "job_type" : "untrustedProposal",
                  "peak_time" : 277,
                  "per_second" : 27
               },
               {
                  "avg_time" : 35,
                  "job_type" : "ledgerData",
                  "peak_time" : 784,
                  "per_second" : 1
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand",
                  "per_second" : 8
               },
               {
                  "avg_time" : 5,
                  "job_type" : "transaction",
                  "peak_time" : 227,
                  "per_second" : 11
               },
               {
                  "job_type" : "batch",
                  "peak_time" : 2,
                  "per_second" : 8
               },
               {
                  "avg_time" : 51,
                  "job_type" : "advanceLedger",
                  "peak_time" : 417,
                  "per_second" : 6
               },
               {
                  "job_type" : "fetchTxnData",
                  "per_second" : 6
               },
               {
                  "avg_time" : 70,
                  "job_type" : "trustedValidation",
                  "peak_time" : 422,
                  "per_second" : 5
               },
               {
                  "job_type" : "writeObjects",
                  "peak_time" : 2,
                  "per_second" : 2
               },
               {
                  "avg_time" : 4,
                  "job_type" : "trustedProposal",
                  "peak_time" : 88,
                  "per_second" : 12
               },
               {
                  "avg_time" : 1,
                  "job_type" : "heartbeat",
                  "peak_time" : 4
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 576
               },
               {
                  "job_type" : "diskAccess",
                  "peak_time" : 2,
                  "per_second" : 2
               },
               {
                  "job_type" : "processTransaction",
                  "per_second" : 11
               },
               {
                  "job_type" : "SyncReadNode",
                  "peak_time" : 1,
                  "per_second" : 55
               },
               },
               {
                  "job_type" : "WriteNode",
                  "peak_time" : 22,
                  "per_second" : 197
               }
            ],
            "threads" : 6
         },
         "load_factor" : 511.97265625,
         "load_factor_fee_escalation" : 511.97265625,
         "load_factor_server" : 1,
         "peer_disconnects" : "15",
         "peer_disconnects_resources" : "0",
         "peers" : 10,
         "pubkey_node" : "XXXX",
         "pubkey_validator" : "none",
         "server_state" : "full",
         "server_state_duration_us" : "37902026125",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "230820194",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "2094857",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "37902026125",
               "transitions" : 1
            },
            "syncing" : {
               "duration_us" : "5391713",
               "transitions" : 1
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : 1
            }
         },
         "time" : "2019-Jul-17 18:35:57.785355",
         "uptime" : 38140,
         "validated_ledger" : {
            "age" : 6,
            "base_fee_xrp" : 1e-05,
            "hash" : "71599B64D6EEAC77C5B712EC2BEE41917F7240D0059FD65175C1197E3223C627",
            "reserve_base_xrp" : 20,
            "reserve_inc_xrp" : 5,
            "seq" : 48719995
         },
         "validation_quorum" : 25,
         "validator_list" : {
            "count" : 1,
            "expiration" : "2019-Aug-14 00:00:00.000000000",
            "status" : "active"
         }
      },
      "status" : "success"
   }
}

```

**Comment by MarkusTeufelberger** [comment]
Looks fine except for the load factor, only 10 peers (no incoming connections possible?) and 230 seconds already only in "connected" state.

**Comment by gituser** [comment]
@MarkusTeufelberger i'm not a fan of opening ports outside, so yeah port is not reachable p2p.

Is it a problem officer?

**Comment by MarkusTeufelberger** [comment]
Apparently it is for you. ;-)

Since you don't have incoming connections, you rely on the (very few and rare) testnet servers to give you an incoming connection slot. It might be the case that your node performs badly enough, that they kick you out from time to time, so you end up with connections to only mainnet nodes.

What does the `peers` command say, especially concerning peer "sanity"?

**Comment by gituser** [comment]
@MarkusTeufelberger it's not testnet. It happens on mainnet.

**Comment by MarkusTeufelberger** [comment]
Ah sorry, I must have confused you with a similar report. Still might be useful to open the port, even if you are not a fan(?) of doing so.

**Comment by gituser** [comment]
@MarkusTeufelberger 

```
./rippled peers
Loading: "/home/ripple/rippled.cfg"
2019-Jul-17 19:17:56.496153183 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "result" : {
      "cluster" : {},
      "peers" : [
         {
            "address" : "52.90.42.69:51235",
            "complete_ledgers" : "48720388 - 48720644",
            "latency" : 173,
            "ledger" : "514784EDBBB92ABCFCA9B8C695C767026984B298F67A4694E2F58FDB4202B60A",
            "load" : 296,
            "public_key" : "n9Jt8awsPzWLjBCNKVEEDQnw4bQEPjezfcQ4gttD1UzbLT1FoG99",
            "uptime" : 40453,
            "version" : "rippled-1.2.4"
         },
         {
            "address" : "[::ffff:34.239.128.122]:51235",
            "complete_ledgers" : "48720388 - 48720644",
            "latency" : 166,
            "ledger" : "514784EDBBB92ABCFCA9B8C695C767026984B298F67A4694E2F58FDB4202B60A",
            "load" : 283,
            "public_key" : "n9JuCLD7Cpq6xyKUWcWe53RQQmcty7uQM1WWZN1Ckrod42JNiqpw",
            "uptime" : 40502,
            "version" : "rippled-1.2.4"
         },
         {
            "address" : "[::ffff:184.173.45.36]:51235",
            "complete_ledgers" : "48720388 - 48720644",
            "latency" : 229,
            "ledger" : "514784EDBBB92ABCFCA9B8C695C767026984B298F67A4694E2F58FDB4202B60A",
            "load" : 241,
            "public_key" : "n9LwVv4w65bw5cHm2UriGnnfj6Y1jfERXTmj3cVfVJDz2vbwEjLD",
            "uptime" : 40510,
            "version" : "rippled-1.2.4"
         },
         {
            "address" : "3.216.68.48:51235",
            "complete_ledgers" : "48700644 - 48720644",
            "latency" : 185,
            "ledger" : "514784EDBBB92ABCFCA9B8C695C767026984B298F67A4694E2F58FDB4202B60A",
            "load" : 278,
            "public_key" : "n9JewiDJszSGRWdb4HenbzPuAGVe2W7LFSr3DZn2vEKDHmQ6cTV4",
            "uptime" : 40511,
            "version" : "rippled-1.3.0"
            "latency" : 291,
            "ledger" : "514784EDBBB92ABCFCA9B8C695C767026984B298F67A4694E2F58FDB4202B60A",
            "load" : 232,
            "public_key" : "n94fJaCbrUZuLxWgYe5Y9PugLqAJqHbaT2arXb5tz8NTe5w1xfK1",
            "uptime" : 40522,
            "version" : "rippled-1.3.0"
         },
         {
            "address" : "[::ffff:34.205.233.231]:51235",
            "complete_ledgers" : "48700644 - 48720644",
            "latency" : 183,
            "ledger" : "514784EDBBB92ABCFCA9B8C695C767026984B298F67A4694E2F58FDB4202B60A",
            "load" : 269,
            "public_key" : "n9Mqwsfvh98BWgtVzWRc5MZeCyAfKYJe1KeND937Pj3GoT7U9UJ7",
            "uptime" : 40441,
            "version" : "rippled-1.3.0"
         },
         {
            "address" : "198.11.206.10:51235",
            "complete_ledgers" : "32570 - 48720644",
            "latency" : 258,
            "ledger" : "514784EDBBB92ABCFCA9B8C695C767026984B298F67A4694E2F58FDB4202B60A",
            "load" : 246,
            "public_key" : "n9LbkoB9ReSbaA9SGL317fm6CvjLcFG8hGoierLYfwiCDsEXHcP3",
            "uptime" : 40654,
            "version" : "rippled-1.3.0"
         },
         {
            "address" : "54.200.82.201:51235",
            "complete_ledgers" : "48720388 - 48720644",
            "latency" : 300,
            "ledger" : "514784EDBBB92ABCFCA9B8C695C767026984B298F67A4694E2F58FDB4202B60A",
            "load" : 228,
            "public_key" : "n9Mgyq4NuCm1DyDHDY1AZsKymLPxfsmdwDj5T6gB21wYaByqkXSt",
            "uptime" : 40510,
            "version" : "rippled-1.2.4"
         },
         {
            "address" : "184.173.45.62:51235",
            "complete_ledgers" : "48720388 - 48720644",
            "latency" : 241,
            "ledger" : "514784EDBBB92ABCFCA9B8C695C767026984B298F67A4694E2F58FDB4202B60A",
            "load" : 248,
            "public_key" : "n9MP4F2Wfh3JUJ1vJmqNyYrmJst1qGmh5MRu73oxWjuqeyHCvGpR",
            "uptime" : 40410,
            "version" : "rippled-1.2.4"
         },
         {
            "address" : "95.216.5.218:51235",
            "complete_ledgers" : "48718644 - 48720644",
            "latency" : 69,
            "ledger" : "514784EDBBB92ABCFCA9B8C695C767026984B298F67A4694E2F58FDB4202B60A",
            "load" : 341,
            "public_key" : "n9MLs6ZmdozaCpRaFnCcjEdYKGPfmarkNVhsQTeu79fBsnr4unMP",
            "uptime" : 40470,
            "version" : "rippled-1.2.4"
         }
      ],
      "status" : "success"
   }
}
```

**Comment by gituser** [comment]
I'll check next time `peers` result when rippled starts misbehaving again..

**Comment by tropa** [comment]
Meanwile

`{
   "result" : {
      "info" : {
         "build_version" : "1.2.4",
         "complete_ledgers" : "48784698-48786761",
         "hostid" : "DS4298.example.com",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 2.001,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "avg_time" : 25,
                  "job_type" : "ledgerRequest",
                  "peak_time" : 343,
                  "per_second" : 2
               },
               {
                  "avg_time" : 79,
                  "job_type" : "untrustedProposal",
                  "peak_time" : 625,
                  "per_second" : 25
               },
               {
                  "in_progress" : 2,
                  "job_type" : "ledgerData",
                  "waiting" : 54
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "job_type" : "advanceLedger",
                  "peak_time" : 28,
                  "per_second" : 11
               },
               {
                  "avg_time" : 32,
                  "job_type" : "trustedValidation",
                  "peak_time" : 1024,
                  "per_second" : 5
               },
               {
                  "avg_time" : 10,
                  "job_type" : "writeObjects",
                  "peak_time" : 1046,
                  "per_second" : 5
               },
               {
                  "avg_time" : 73,
                  "job_type" : "trustedProposal",
                  "over_target" : true,
                  "peak_time" : 664,
                  "per_second" : 10
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 821
               },
               {
                  "avg_time" : 10,
                  "job_type" : "diskAccess",
                  "over_target" : true,
                  "peak_time" : 1046,
                  "per_second" : 5
               },
               {
                  "avg_time" : 1,
                  "job_type" : "AsyncReadNode",
                  "peak_time" : 26,
                  "per_second" : 504
               },
               {
                  "avg_time" : 1,
                  "job_type" : "WriteNode",
                  "peak_time" : 26,
                  "per_second" : 504
               }
            ],
            "threads" : 6
         },
         "load_factor" : 1,
         "peer_disconnects" : "363",
         "peer_disconnects_resources" : "1",
         "peers" : 21,
         "pubkey_node" : "n9M9VpLPHKECVKSURcAyCRZCmKTnKdZkvjYK49sk8re6CJjuXWsg",
         "pubkey_validator" : "none",
         "server_state" : "full",
         "server_state_duration_us" : "723402198",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "9531070985",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "2464784",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "8430862503",
               "transitions" : 4
            },
            "syncing" : {
               "duration_us" : "147862052",
               "transitions" : 4
            },
            "tracking" : {
               "duration_us" : "5",
               "transitions" : 4
            }
         },
         "time" : "2019-Jul-20 18:38:42.820038",
         "uptime" : 18112,
         "validated_ledger" : {
            "age" : 600,
            "base_fee_xrp" : 1e-05,
            "hash" : "6BCE94247DC1D54987E44E17DD1B14E2FEDC2491FFE4B7E94E5B2727EFEBE769",
            "reserve_base_xrp" : 20,
            "reserve_inc_xrp" : 5,
            "seq" : 48786761
         },
         "validation_quorum" : 25,
         "validator_list" : {
            "count" : 1,
            "expiration" : "2019-Aug-14 00:00:00.000000000",
            "status" : "active"
         }
      },
      "status" : "success"
   }
}

17 error...`

**Comment by skinderis** [comment]
@tropa  did you manage to solve the issue? Because I am facing the same issue from time to time... rippled works fine for a while and after some days start returning 'InsufficientNetworkMode' on sending XRP. 
Getting this log:
```
2020-Jan-22 16:26:32.752950417 NetworkOPs:WRN We are not running on the consensus ledger
2020-Jan-22 16:26:33.161762669 LoadMonitor:WRN Job: processLedgerData run: 863ms wait: 12083ms
2020-Jan-22 16:26:33.750527278 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2020-Jan-22 16:26:33.750860246 LedgerConsensus:WRN AC42AFDC1EC8867757806CF11CA5C032E0A74FD213E27465BEF2922F3439359B to CCF6C56D8C4D4EBEA0E53905FBCD3F4BD7053FB059311161EBBAF30A634C7A93
2020-Jan-22 16:26:33.751048591 LedgerConsensus:WRN {"accepted":true,"account_hash":"80B87C02A39B37DEADF1BA9D1AE34AE8866AACAD65C39AF48CD621DA09EAF314","close_flags":0,"close_time":633025591,"close_time_human":"2020-Jan-22 16:26:31.000000000","close_time_resolution":10,"closed":true,"hash":"7F569FE9DE50AF5ED549EC5DF30375D262A29C1CDE1BB5558CE9660B2DFFD5F9","ledger_hash":"7F569FE9DE50AF5ED549EC5DF30375D262A29C1CDE1BB5558CE9660B2DFFD5F9","ledger_index":"94","parent_close_time":633025590,"parent_hash":"C16F8D5D05A2B722185EAFDA77B4735F6A917329E5E3465CB804A774A4E46D73","seqNum":"94","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2020-Jan-22 16:26:33.751489492 LedgerConsensus:WRN Need consensus ledger CCF6C56D8C4D4EBEA0E53905FBCD3F4BD7053FB059311161EBBAF30A634C7A93
```

**Comment by tropa** [comment]
No, I refused to use it. With similar technical support, they will go far.

**Comment by skinderis** [comment]
@mDuo13  you could help maybe?

**Comment by BeOleg** [comment]
@mDuo13 👍 please help

**Comment by MarkusTeufelberger** [comment]
You need to post a more info. Output of `server_info` and `peers`, hardware specs of the machine running this server (especially network connection + actual disk IO speed)...

**Comment by mDuo13** [comment]
I'm not tech support, but you could start by following the steps for [Diagnosing Problems](https://xrpl.org/diagnosing-problems.html) and reading [Troubleshooting: `rippled` Doesn't Sync](https://xrpl.org/server-doesnt-sync.html).

Almost every time, the problem is that your hardware isn't powerful enough.

**Comment by gopherine** [comment]
I get the same error , the first time it ran all good, but as soon as i restarted the service i kept getting same error,. i installed rippled on default settings. Just to test as mentioned in the docs i did reset db also uninstalled and reinstalled it, but the error does not seem to go away not sure what could be the reason

**Comment by gituser** [comment]
@gopherine, make sure you're running latest `rippled v1.6.0`

**Comment by sh4dowb** [comment]
I was getting this error on testnet, what I did was adding this to conf:
```
[ips]
s.altnet.rippletest.net 51235
```
as stated in https://xrpl.org/connect-your-rippled-to-the-xrp-test-net.html

and then I was still getting the same problem, server_info was returning these: `server_state: connected, complete_ledgers: empty, network_ledger: waiting`
then I realized it was using %99 disk on `iotop` so I removed databases and switched to an SSD disk. it works well now!
