### ISSUE TITLE
Delete account with zero balance from XRPL.

### ISSUE THREAD

**Issue by yxxyun** [ripple/rippled#3002]
There are some account try move all the XRP out by set the fee to 20 XRP﻿ and left﻿ account with 0 balanc﻿﻿e ﻿. 
like rBP11q4wnzyuVSaV5MAbkBEciVHk6T9mMr
r4chMnBD1cWumyCmBUAcJ7T8YvVehqS2eQ
rhKY7ASWefvg2nsB6ctwNEpW941yxMZq35﻿

I suggest todo a state clearing as ethereum did before. 
https://www.reddit.com/r/ethereum/comments/5es5g4/a_state_clearing_faq/

**Comment by MarkusTeufelberger** [comment]
These are 3 accounts, Ethereum has 19 millions of these...

**Comment by yxxyun** [comment]
Well, canbe used as an optional method to delete account since the DeleteAccount tx can't came out

**Comment by nbougalis** [comment]
Veto. We can't go around deleting others' accounts.

Once deletable accounts are available, the owners of such accounts could send funds and then proceed to delete these accounts using the regular technique.
