### ISSUE TITLE
Validations Stream Subscription Does Not Report Master Public Key

### ISSUE THREAD

**Issue by crypticrabbit** [ripple/rippled#3005]
It would be helpful to have a field for a proposing validator's master key in the validation stream subscription JSON responses.

Validation stream subscription responses include a proposing validator's ephemeral signing key but not the master public key. This makes identifying the validator that message is referring to difficult, particularly if one does not have a current validator manifest or if an operator generates a new validation token/signing key.

I think this would make it easier to record validaton votes generally, as software would not have to query for a new manifest every time it encounters a novel signing key.

**Comment by MarkusTeufelberger** [comment]
Are master keys for validators even communicated/available to rippled or is it an external mechanism?

**Comment by crypticrabbit** [comment]
I believe so - For example, the `signing_keys` object returned by the `validators` command returns a mapping of master:ephemeral keys.

https://xrpl.org/validators.html
