### ISSUE TITLE
undefined reference to `beast::Socket::async_handshake

### ISSUE THREAD

**Issue by verwilst** [ripple/rippled#301]
When compiling on Ubuntu 13.10, with boost 1.55, getting the following error:

g++ -o build/rippled -pthread -rdynamic -pthread build/proto/ripple.pb.o build/obj/src/ripple/beast/ripple_beast.o build/obj/src/ripple/beast/ripple_beastc.o build/obj/src/ripple/http/ripple_http.o build/obj/src/ripple/json/ripple_json.o build/obj/src/ripple/peerfinder/ripple_peerfinder.o build/obj/src/ripple/radmap/ripple_radmap.o build/obj/src/ripple/resource/ripple_resource.o build/obj/src/ripple/rocksdb/ripple_rocksdb.o build/obj/src/ripple/sitefiles/ripple_sitefiles.o build/obj/src/ripple/sslutil/ripple_sslutil.o build/obj/src/ripple/testoverlay/ripple_testoverlay.o build/obj/src/ripple/types/ripple_types.o build/obj/src/ripple/validators/ripple_validators.o build/obj/src/ripple/common/ripple_common.o build/obj/src/ripple_app/ripple_app.o build/obj/src/ripple_app/ripple_app_pt1.o build/obj/src/ripple_app/ripple_app_pt2.o build/obj/src/ripple_app/ripple_app_pt3.o build/obj/src/ripple_app/ripple_app_pt4.o build/obj/src/ripple_app/ripple_app_pt5.o build/obj/src/ripple_app/ripple_app_pt6.o build/obj/src/ripple_app/ripple_app_pt7.o build/obj/src/ripple_app/ripple_app_pt8.o build/obj/src/ripple_basics/ripple_basics.o build/obj/src/ripple_core/ripple_core.o build/obj/src/ripple_data/ripple_data.o build/obj/src/ripple_hyperleveldb/ripple_hyperleveldb.o build/obj/src/ripple_leveldb/ripple_leveldb.o build/obj/src/ripple_net/ripple_net.o build/obj/src/ripple_overlay/ripple_overlay.o build/obj/src/ripple_rpc/ripple_rpc.o build/obj/src/ripple_websocket/ripple_websocket.o -lssl -lcrypto -ldl -lprotobuf -lz -lpthread -lboost_date_time -lboost_filesystem -lboost_program_options -lboost_regex -lboost_system -lboost_thread -ldl -lrt
build/obj/src/ripple_net/ripple_net.o:(.rodata._ZTVN6ripple11MultiSocketE[_ZTVN6ripple11MultiSocketE]+0xb0): undefined reference to `beast::Socket::handshake(boost::asio::ssl::stream_base::handshake_type, beast::BuffersType<boost::asio::const_buffer> const&, boost::system::error_code&)'
build/obj/src/ripple_net/ripple_net.o:(.rodata._ZTVN6ripple11MultiSocketE[_ZTVN6ripple11MultiSocketE]+0xb8): undefined reference to `beast::Socket::async_handshake(boost::asio::ssl::stream_base::handshake_type, beast::BuffersType<boost::asio::const_buffer> const&, beast::SharedHandlerPtr)'
collect2: error: ld returned 1 exit status
scons: *** [build/rippled] Error 1
scons: building terminated because of errors.

**Comment by rec** [comment]
Can't reproduce, feel free to reopen with a new testcase!
