### ISSUE TITLE
[Need Help] My node returns "InsufficientNetworkMode" error!

### ISSUE THREAD

**Issue by Brochao** [ripple/rippled#3010]
My node runs correctly for days, the error just appears.

the websocket API returns :
`{"error":"noNetwork","error_code":17,"error_message":"InsufficientNetworkMode","id":"1","request":{"accounts":false,"command":"ledger","expand":false,"full":false,"id":"1","ledger_index":"validated","owner_funds":false,"transactions":false},"status":"error","type":"response"} }`

and the log of my node is :

`2019-Jul-26 02:31:20.911757121 LedgerConsensus:WRN Need consensus ledger 214243173477CB59A6AFDA2B9F3A268F7CA5CF0EF3780CF9CD8BB1DA1298FA3F
2019-Jul-26 02:31:20.913719374 NetworkOPs:WRN We are not running on the consensus ledger
2019-Jul-26 02:31:24.918221030 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2019-Jul-26 02:31:24.918277456 LedgerConsensus:WRN 214243173477CB59A6AFDA2B9F3A268F7CA5CF0EF3780CF9CD8BB1DA1298FA3F to 695F21D437CE49A7879BBAFFB9B99600337EC7E721360937863AA020037BB2BA
2019-Jul-26 02:31:24.918334456 LedgerConsensus:WRN {"accepted":true,"account_hash":"6B8DDAAB3E8939F2EA5EBCB5B9B5327E09B74651C1F73AF617538D84C401F854","close_flags":0,"close_time":617423480,"close_time_human":"2019-Jul-26 02:31:20.000000000","close_time_resolution":10,"closed":true,"hash":"0CAAC3EFE71B58701B35DBB9468A8BE4EA098C8DB461DA2125B88E59DBB51442","ledger_hash":"0CAAC3EFE71B58701B35DBB9468A8BE4EA098C8DB461DA2125B88E59DBB51442","ledger_index":"116","parent_close_time":617423471,"parent_hash":"65738A3D4294E60035EFAEA820DBD06E355B3F91519218E1ED7F8267DD2FEFAA","seqNum":"116","totalCoins":"100000000000000000","total_coins":"100000000000000000","transaction_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
2019-Jul-26 02:31:24.918501235 LedgerConsensus:WRN Need consensus ledger 695F21D437CE49A7879BBAFFB9B99600337EC7E721360937863AA020037BB2BA
2019-Jul-26 02:31:24.920237971 NetworkOPs:WRN We are not running on the consensus ledger
2019-Jul-26 02:31:27.933416408 NetworkOPs:WRN We are not running on the consensus ledger
2019-Jul-26 02:31:28.929570936 LedgerConsensus:WRN View of consensus changed during establish status=establish,  mode=wrongLedger
2019-Jul-26 02:31:28.929618667 LedgerConsensus:WRN 695F21D437CE49A7879BBAFFB9B99600337EC7E721360937863AA020037BB2BA to 2F769D98B822C9A7717BF784076B7247EABB5444AF8309F4883D2CA52A34A6CA`

Can anyone help please!

**Comment by Mblac** [comment]
You can try to restart the solution.
$ rippled stop; sleep 5; rippled

**Comment by Brochao** [comment]
It turns out that this problem occurs because of memory constraints.

**Comment by skinderis** [comment]
> It turns out that this problem occurs because of memory constraints.

Can you be more precise about this problem? As I have the same issue right now, don't know whats the problem.

**Comment by lucasobsidiam** [comment]
I'm having the same issue on an m5.large on Amazon even after setting the node_size to tiny and letting it sync again. If it's memory constraints lowering the size of the node should allow it to work again?

**Comment by intelliot** [comment]
You are more likely to see issues if you set `node_size` to `tiny` or `small`. With tiny or small, only a single service ASIO service thread is spawned. I recommend ensuring that your machine has at least 16GB RAM and then setting the `node_size` to `medium` or `large`. If you have more RAM, then try using `huge`.

**Comment by lucasobsidiam** [comment]
We're building an exchange so I just went ahead and used a 32GB RAM instance with ephemeral storage. It's working fine and we're using huge, since it will be for production we're going to go with this. Thanks for the assistance.
