### ISSUE TITLE
SHAMap::snapShot maybe exist an error

### ISSUE THREAD

**Issue by NewChinese** [ripple/rippled#3020]
std::shared_ptr<SHAMap>
SHAMap::snapShot (bool isMutable) const
{
    auto ret = std::make_shared<SHAMap> (type_, f_, get_version());
    SHAMap& newMap = *ret;

    if (!isMutable)
        newMap.state_ = SHAMapState::Immutable;

    newMap.seq_ = seq_ + 1;
    newMap.ledgerSeq_ = ledgerSeq_;
    newMap.root_ = root_;
    newMap.backed_ = backed_;

    **if ((state_ != SHAMapState::Immutable) || !isMutable)**
    {
        // If either map may change, they cannot share nodes
        newMap.unshare ();
    }

    return ret;
}

In the above codes, this line  "if ((state_ != SHAMapState::Immutable) || !isMutable)" ,
it seems that it should be "if ((state_ != SHAMapState::Immutable) || isMutable)"

**Comment by HowardHinnant** [comment]
Thanks for submitting this issue!

**Comment by JoelKatz** [comment]
The code does look wrong. I think it's not hurting us because I don't believe the code ever tries to take a mutable snapshot of a ledger that isn't already unshared. But I suspect it would be possible to create a unit test that fails with the current code and works correctly with this fixed.
