### ISSUE TITLE
Stop synchronization

### ISSUE THREAD

**Issue by prettyCoders** [ripple/rippled#3041]
![image](https://user-images.githubusercontent.com/36216120/62855433-cdc19900-bd24-11e9-99d9-c2679c5e9eb7.png)
my node often stop sync

**Comment by MarkusTeufelberger** [comment]
Make sure you don't have the connection to your validation list source blocked in a firewall...

**Comment by prettyCoders** [comment]
It work when i restart the node. Every time

发自我的iPhone

------------------ Original ------------------

**Comment by nbougalis** [comment]
Your server appears to have connectivity issues (as indicated by your server dropping to 0 peers and by the reported DNS resolution issues).

Do other processes on the server experience connectivity issues? Do any messages related to connectivity appear on the system logs?

**Comment by carlhua** [comment]
Stale issue - closing
