### ISSUE TITLE
rippled 1.3.1 std::bad_alloc

### ISSUE THREAD

**Issue by snowman0200** [ripple/rippled#3063]
Recently ripple full node (testnet) keep restarting with the error **std::bad_alloc**.

![image](https://user-images.githubusercontent.com/49179796/63825016-aeb14100-c98b-11e9-82fb-3b3c8a970bd3.png)

Here is the part of the ripple setting.
![image](https://user-images.githubusercontent.com/49179796/63825223-84ac4e80-c98c-11e9-84d2-74a46e01b34a.png)

Anyone is encounter this issue ? Any feedback would be appreciated.

**Comment by nbougalis** [comment]
Related to #3050—please discuss there.
