### ISSUE TITLE
Testnet reset

### ISSUE THREAD

**Issue by bert2002** [ripple/rippled#3064]
Hi,
did you just reset the testnet? It was funky the last two days and since this morning it started again from block 1.

Thanks,
bert

**Comment by MarkusTeufelberger** [comment]
May I suggest that you (Ripple) run a full history server (even if only reachable via the peer protocol) for the TestNet?

**Comment by quietnan** [comment]
> May I suggest that you (Ripple) run a full history server (even if only reachable via the peer protocol) for the TestNet?

They do. http://testnet.data.api.ripple.com/v2/ is running https://github.com/ripple/rippled-historical-database. Seems though that the news of the testnet reset has not yet propagated there. Currently both report inconsistent information.

**Comment by MarkusTeufelberger** [comment]
> They do.

No offense, but I'd rather have confirmation from someone at the company. The Data API != rippled and it doesn't store the same (or all) data that rippled stores and makes available.

**Comment by quietnan** [comment]
None taken, but you don't have to trust me, just look for yourself. E.g. https://testnet.data.api.ripple.com/v2/accounts/r3kmLJN5D28dHuH8vZNUZpMC43pEHpaocV/transactions delivers data that is not available in rippled. Except for it not yet following through on the testnet reset, it is fully functional. Obviously it is not well maintained as a test system. We had several problems over the last year (see e.g. https://github.com/ripple/rippled-historical-database/issues/197),  but it is there and under the ripple.com domain. And yes, I do understand the difference between the data api and rippled.

**Comment by quietnan** [comment]
@intelliot was the testnet reset *again*?
Yesterday eiter DAVY or IRMA answered to https://s.altnet.rippletest.net:51234, today it's always MIT, with an uptime of currently less than 6 hours and seq 7400-ish. And the addresses that we set up again yesterday for our tests are gone again.

**Comment by quietnan** [comment]
Not to be pushy, but what's the plan here? Do we have to expect another reset or is two enough? We spent hours yesterday to set our automated tests up again yesterday just to find it reset today. Would be really great to get an idea about the lifetime of the testnet this time.

**Comment by intelliot** [comment]
The testnet was reset again in order to change the enabled amendments to match mainnet.

**Comment by RyoMoriyama** [comment]
Seems SignerListSet not working.Error code 'temDISABLED' returned.
I want to know when will this fixed. Please let me know more info.

**Comment by bert2002** [comment]
Stellar has scheduled resets for the testnet every three month, not ideal but may be ripple needs something similar. I somehow doubt this was planned though.

**Comment by intelliot** [comment]
At approximately 7:56 PM PDT on 2019-08-30, the Testnet ledger was reset again. The enabled amendments should now match the ones enabled in production.

If your test app relies on data being present in the Testnet ledger, we recommend building testing scripts that repopulate the Testnet with data after a reset.

@RyoMoriyama This should be fixed now.

If anyone encounters any issues, please open a new Issue here on GitHub. Thank you!

**Comment by MarkusTeufelberger** [comment]
> we recommend building testing scripts that repopulate the Testnet with data after a reset

How does one programmatically (re-)fund an account? One has to rely on Ripple sending t-XRP funds on demand, right?

**Comment by intelliot** [comment]
Good question. You can programmatically generate a new Testnet account with (currently) 1,000 test XRP from the faucet by making a `POST` request to `https://faucet.altnet.rippletest.net/accounts`. For example, [here is the code used by the faucet itself](https://xrpl.org/assets/js/test-net.js).

Feel free to open a new issue if you have further questions.

**Comment by bagikh** [comment]
Is testnet.data.api still working? if not, what rpc endpoint i can use for testing v2 data api?. Thank you
