### ISSUE TITLE
backup wallet from rippled

### ISSUE THREAD

**Issue by Apollo-IT** [ripple/rippled#3074]
Hi,@passionofvc. I  wanna backup rippled wallet.
In bitcoin or ethereum(parity), I can backup and restore with saving following directory.
bitcoin: $HOME/.bitcoin/wallet.dat
ethereum: $HOME/.local/share/io.parity.ethereum/keys
Anything similar in rippled?

I know rippled wallet.db is not same as above.

**Comment by movitto** [comment]
This is more of a [ripple-lib](https://github.com/ripple/ripple-lib) issue as the logic to generate new wallets (XRPL accounts) is implemented there.

Regardless, the specific ripple-lib API method used to generated new accounts is [generateAddress](https://xrpl.org/rippleapi-reference.html#generateaddress) which returns the public address and corresponding the private secret. Back this up to backup your wallet (write to a text file on encrypted flash-disks, etc, make sure to use best security practices!)

**Comment by MarkusTeufelberger** [comment]
Rippled has no user facing wallet functionality. Users need to submit signed transactions, the software to sign these transactions (typically called "wallet") is out of scope for this repository and can be implemented elsewhere.

**Comment by nbougalis** [comment]
@Apollo-IT, as @MarkusTeufelberger said, `rippled` is not a wallet. And while you _can_ use it to generate credentials (see [**`wallet_propose`**](https://xrpl.org/wallet_propose.html)) it *never* stores keys for accounts.

Generally, if you generated credentials using **`wallet_propose`**, what you want to *securely* back up is either the **`master_key`** field (a string of short English words) or the **`master_seed`** (a case-sensitive string of numbers and digits, with a built-in error-detecting checksum.

_Please note that *neither* of those two formats have **any** error-correction capability; so be **very** sure that you don't make any transcription mistakes!_
