### ISSUE TITLE
TransactionMaster::fetch

### ISSUE THREAD

**Issue by nbougalis** [ripple/rippled#3079]
There are two overloads of `TransactionMaster::fetch` and both accept a parameter called `checkDisk`:

```
std::shared_ptr<Transaction>
fetch (
    uint256 const& txnID,
    bool checkDisk);

std::shared_ptr<STTx const>
fetch (
    std::shared_ptr<SHAMapItem> const& item,
    SHAMapTreeNode::TNType type,
    bool checkDisk,
    std::uint32_t uCommitLedger);
```

The second variant _never_ uses `checkDisk` at all. The first variant uses `Transaction::load` if the transaction isn't found in the cache and `checkDisk` is `true`.

The function is called with `checkDisk` set to `true` in a single place. Such boolean parametrs to choose codepaths inhibit understanding; we should investigate having a separate function whose raison d'être _is_ to load the transaction, and push that responsibility off to the caller.

**Comment by MishraShivendra** [comment]
Not sure what you meant by - 
> whose raison d'être is to load the transaction

Any input on how would the signature of those expected APIs would look like?

**Comment by movitto** [comment]
@nbougalis is this issue still valid? It seems the checkDisk parameter was removed with this patch :

https://github.com/ripple/rippled/commit/11cf27e00698dbfc099b23463927d1dac829ed19
