### ISSUE TITLE
Can't sign with RegularKey.

### ISSUE THREAD

**Issue by ripplerm** [ripple/rippled#308]
If we send a transaction for Rippled to sign with secret of Regular-key, a "badsecret" error was returned.

I think the bug is in the codes of Transactor.cpp (https://github.com/ripple/rippled/blob/develop/src/ripple_app/transactors/Transactor.cpp)

the checking of Regular key:
[line287: mHasAuthKey     = mTxnAccount->isFieldPresent (sfRegularKey);] 

should be done before precheck () is called.

**Comment by rec** [comment]
Can't reproduce, feel free to reopen with a new testcase!
