### ISSUE TITLE
Investigate basic_seconds_clock_main_hook

### ISSUE THREAD

**Issue by nbougalis** [ripple/rippled#3092]
The function [`basic_seconds_clock_main_hook`](https://github.com/ripple/rippled/blob/5834fbbc5d5f7354f2ba4e8426391f8ff112c744/src/ripple/beast/clock/basic_seconds_clock.h#L141) is called before main exits to terminate the utility thread as a workaround for a Visual Studio 2012/2013 issue. 

The following URLs document and explain the problem, but the first one is broken, so maybe someone can unbreak it?
 
http://connect.microsoft.com/VisualStudio/feedback/details/786016/creating-a-global-c-object-that-used-thread-join-in-its-destructor-causes-a-lockup
http://stackoverflow.com/questions/10915233/stdthreadjoin-hangs-if-called-after-main-exits-when-using-vs2012-rc

The question is, is this still necessary or has the underlying issue been fixed? If so, the workaroud code should be removed.

**Comment by HowardHinnant** [comment]
I'm 90% sure we can remove this workaround with VS-2015 and later.  But someone with VS should test that theory.

**Comment by nbougalis** [comment]
Removed in commit dbee3f01b7bde4b0b662c
