### ISSUE TITLE
Unable to connect peers in standalone mode

### ISSUE THREAD

**Issue by Monarth-s** [ripple/rippled#3097]
I had started one rippled server in standalone mode in LAN.

Now I want to connect peers to that server, I had already tried using `[ips]`:

```
[ips]
192.168.11.91 51235
```
But, it always connect to main server `https://vl.ripple.com`.

So, how can I configure one pc as server and another pc as peer?

**Comment by MarkusTeufelberger** [comment]
I think I remember something about rippled usually refusing to connect to IPs in local ranges (since often this would be peers leaking local IPs instead of their public ones).

Maybe try `[ips_fixed]`?

**Comment by nbougalis** [comment]
You **cannot** connect to anyone when in **standalone** mode; the server is literally running by itself and will not attempt to make any outgoing connections nor will it allow incoming connections to other `rippled` servers.

**https://vl.ripple.com** is not a `rippled` server; it's a web server.

>So, how can I configure one pc as server and another pc as peer?

It's not clear to me what the difference is between a "server" and a "peer". `rippled` is a server and connects to other `rippled` instances ("peers"). What exactly are you trying to achieve?

**Comment by Monarth-s** [comment]
@MarkusTeufelberger, I had already tried `[ips_fixed]` but it doesn't work.

@nbougalis, I want rippled to connect standalone server with other rippled instance (peer).

**Comment by Monarth-s** [comment]
I also see that `[port_peer]` is not starting in standalone mode.

![image](https://user-images.githubusercontent.com/42800570/66455770-52ad0280-ea89-11e9-860b-02adf5b7e18a.png)

**Comment by MarkusTeufelberger** [comment]
That's the definition of "standalone", yes. As was already explained, you will not be able to do what you are trying to do ("I want rippled to connect standalone server with other rippled instance (peer)."). Maybe you have some misunderstandings about what you want to achieve? A server that is not clustered doesn't need to be in standalone mode for example.

**Comment by mDuo13** [comment]
Precisely what @MarkusTeufelberger said: the _definition_ of "standalone" mode is that it does not connect to any peers.

If you want to connect a server _only_ to specific other peers, use [private peering](https://xrpl.org/peer-protocol.html#private-peers) instead.
