### ISSUE TITLE
Allow server to report its current manifest

### ISSUE THREAD

**Issue by nbougalis** [ripple/rippled#3099]
We need `rippled` to improve its manifest support:

1) A `rippled` instance configured as a validator should offer an admin-only RPC command that can report the master public key, the ephemeral public key, the manifest sequence number and, if present, the domain associated with the manifest that the server is using. The command can be `validator_info`. If the server is not configured as a validator, the command should report an error.
2) Any `rippled` instance should offer an RPC command that, given a master or ephemeral public key, should report the master public key, the ephemeral public key, the manifest sequence number the domain associated with the given manifest (if present), and the manifest in base64-encoded format. The command can be `manifest`. If the server does not have the given manifest, the command should report an error.

Optionally, for (1) a `--validator-info` command line should parse the config file, load the **`validator_token`** if one is present, and report the master and ephemeral public keys, the manifest sequence number and, if present, the domain associated with the manifest. Additionally, the command should report the base64 encoded manifest. Once completed, the program would terminate (similar to, e.g. `--version`)

**Comment by intelliot** [comment]
1. [`validator_info`](https://xrpl.org/validator_info.html) has been implemented
2. [`manifest`](https://xrpl.org/manifest.html) has been implemented*

*(`manifest` was implemented as an admin-only command, but I think it would be fine to make it public)

I'm not certain of the status of the command line feature idea, but if it is still needed, we should create a new issue for it. The title of this issue (`Allow server to report its current manifest`) is done.
