### ISSUE TITLE
Amendment blocked, need upgrade

### ISSUE THREAD

**Issue by prettyCoders** [ripple/rippled#3102]
Response of Transfer:

{"error_message":"Amendment blocked, need upgrade.","request":{"tx_blob":"120000228000000024000003882E0001A9886140000002797D764068400000000000000A7321039FD6376241CA8BC459BBF83BDCC440AE906399D1BD3F253295EA7C8833F294007446304402202B2ED0321B4830A2382A028FA4FBCFFEB7D52C5721BD5D9E52E8BCA78A5FF4EB0220022008CE3FEB000039A341CE12849349E5424EFB39EEB5A648F720D4696F6E2C8114B2788C5EB572563D497BB9EC5D6D6F89CB2ED4B38314310DC41A84715D5C838E732515DBDA8FD417EDE0","command":"submit"},"error_code":14,"error":"amendmentBlocked","status":"error"}

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/66467379-f1038d00-eab6-11e9-8ba6-042a8a8b12c7.png)

**Comment by MarkusTeufelberger** [comment]
https://groups.google.com/forum/#!topic/ripple-server/ktSwzfNPyIY

Your server runs version 1.2.4.
This is too old.
Update your server.

**Comment by prettyCoders** [comment]
thanks

**Comment by nbougalis** [comment]
Thanks for the report @prettyCoders. As @MarkusTeufelberger said, you need to upgrade to a newer version.

We need to improve the messaging from `rippled` to help operators understand what "amendment blocked" means, and to provide improved health-reporting capabilties to operators.

**Comment by mDuo13** [comment]
Here's the [documentation on being amendment blocked](https://xrpl.org/amendments.html#amendment-blocked). I've opened https://github.com/ripple/xrpl-dev-portal/pull/703 to add this to the list of errors that can occur on any command to hopefully raise awareness of this.
