### ISSUE TITLE
Display XRP symbol  in standalone mode.

### ISSUE THREAD

**Issue by YuvrajUpadhyay** [ripple/rippled#3109]
How can we display XRP symbol in command line in standalone mode?

**Comment by MarkusTeufelberger** [comment]
...display a symbol? This is a software that typically runs on servers without displays attached. Could you describe what you would expect to do and see with this feature?

**Comment by YuvrajUpadhyay** [comment]
Okay Got it. solved issue 👍 . @MarkusTeufelberger
