### ISSUE TITLE
cmake build error while building rippled on ubuntu 18.04

### ISSUE THREAD

**Issue by ReddyArunreddy** [ripple/rippled#3118]
/rippled/build$ cmake ..
-- Found Git: /usr/bin/git (found version "2.23.0") 
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using 2 cores for ExternalProject builds.
-- Build type not specified - defaulting to Release
-- rippled version: 1.3.1
-- NIH-EP cache path: /home/blocmatrix/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release
-- docker NOT found -- won't be able to build containers for packaging
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- BOOST_ROOT: /home/my_user/boost_1_71_0
-- BOOST_LIBRARYDIR: 
CMake Error at Builds/CMake/FindBoost.cmake:2153 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:717 (find_package)

-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.a (found suitable version "1.1.1", minimum required is "1.0.2")  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
CMake Error at CMakeLists.txt:1114 (get_target_property):
  get_target_property() called with non-existent target "Boost::date_time".

-- Pausing to download NuDB...
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a;-pthread (found version "3.0.0") 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- doxygen executable not found -- skipping docs target
-- Configuring incomplete, errors occurred!
See also "/home/blocmatrix/rippled/build/CMakeFiles/CMakeOutput.log".
See also "/home/blocmatrix/rippled/build/CMakeFiles/CMakeError.log".

**Comment by ReddyArunreddy** [comment]
I'm following the steps from https://xrpl.org/build-run-rippled-ubuntu.html

**Comment by ReddyArunreddy** [comment]
got resolved

**Comment by MarkusTeufelberger** [comment]
how?
