### ISSUE TITLE
How can i use rippled code for my project

### ISSUE THREAD

**Issue by beginertoprogram** [ripple/rippled#3136]
I want to use rippled code to create blockchain project for understanding so what changes should i make.
The address should be diff and want to create my own network with two three systems.

**Comment by MarkusTeufelberger** [comment]
Well, you could always try to put in changes here that abstract away the naming on the native token (`XRP`), I am not so sure if different address schemas would be also a welcome addition, but you can try.

In general so far (Stellar, Casinocoin) people that created a project based on this code base tended to not contribute anything back and instead completely forked the code.

**Comment by beginertoprogram** [comment]
Thanks.

**Comment by beginertoprogram** [comment]
Hi
I have followed ur above suggestions. And 
I have created 4 servers A, B, C, D. i have made them validators with the instruction given in this link https://xrpl.org/run-rippled-as-a-validator.html .

so i have 4 validators now i placed all validator in validators section in validators.txt(in 5 system i.e four above created servers and one my local node.) is this correct?

The server_info output is as follows.
rippled server_info
2019-Nov-08 11:04:09.959170614 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "result" : {
      "info" : {
         "build_version" : "1.3.1",
         "closed_ledger" : {
            "age" : 9,
            "base_fee_xrp" : 1e-05,
            "hash" : "124C1C50D25B0D73C9846D85A7D2B9898DC29A400D4F585676ABEC1EED7A2CDA",
            "reserve_base_xrp" : 200,
            "reserve_inc_xrp" : 50,
            "seq" : 42
         },
         "complete_ledgers" : "empty",
         "hostid" : "blocmatrix-HP-Pavilion-Desktop-PC-570-p0xx",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 2,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 1
               }
            ],
            "threads" : 6
         },
         "load_factor" : 1,
         "peer_disconnects" : "0",
         "peer_disconnects_resources" : "0",
         "peers" : 4,
         "pubkey_node" : "n9Je92BmWHFzcTT19BNSYBeB2PitNoNes3KpNARB7NQEro1yztfz",
         "pubkey_validator" : "none",
         "published_ledger" : "none",
         "server_state" : "full",
         "server_state_duration_us" : "184957328",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "877373396",
               "transitions" : 3
            },
            "disconnected" : {
               "duration_us" : "2315786",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "285081272",
               "transitions" : 3
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "tracking" : {
               "duration_us" : "5",
               "transitions" : 3
            }
         },
         "time" : "2019-Nov-08 11:04:09.959880",
         "uptime" : 1165,
         "validation_quorum" : 4,
         "validator_list" : {
            "count" : 1,
            "expiration" : "never",
            "status" : "active"
         }
      },
      "status" : "success"
   }
but when i submiting transaction  i got following error.
   "result" : {
      "error" : "noCurrent",
      "error_code" : 16,
      "error_message" : "Current ledger is unavailable.",
      "request" : {
         "command" : "submit",
         "tx_blob" : "12000022800000002400000001614000002E90EDD00068400000000000271073210330E7FC9D56BB25D6893BA3F317AE5BCF33B3291BD63DB32654A313222F7FD02074473045022100D058639B357292E3E07B143C13A2C995FFE51A4BEC8646E4D9B8B8CEDFF79AED0220301FC3BCF5DAFC603915B8BF9EDADC829CDFB5B90730777F62A32048184ADA6F8114B5F762798A53D543A014CAF8B297CFF8F2F937E883145E63C07F8C5102DC24CFDDE31D33DA32A3683B71"
      },
      "status" : "error"

**Comment by beginertoprogram** [comment]
And all the configured validated server states are "  "server_state":"full"  "
