### ISSUE TITLE
Advance the Ledger in Stand-Alone Mode Automatic

### ISSUE THREAD

**Issue by MonarthS** [ripple/rippled#3148]
Currently, in `rippled` stand-alone mode we have to manually advance the ledger index using the `ledger_accept` method: 

```
rippled ledger_accept --conf=/path/to/rippled.cfg
```
Is there any way to do this automatically in stand-alone mode?

**Comment by MarkusTeufelberger** [comment]
What should the automatism be based upon? If time, then just write a while loop in bash and call the `ledger_accept` RPC call every few seconds for example...

**Comment by MonarthS** [comment]
Already done the same and working with it, but is there any other way like change in config?

**Comment by nbougalis** [comment]
No, there is not. One of the defining characteristics of standalone mode is that it requires the server operator to _explicitly_ instruct the server to close the currently open ledger, accept it and generate a new one. There is no configuration option or other mechanism built into the code to automate this.

**Comment by nbougalis** [comment]
No, there is not. One of the defining characteristics of standalone mode is that it requires the server operator to _explicitly_ instruct the server to close the currently open ledger, accept it and generate a new one. There is no configuration option or other mechanism built into the code to automate this.
