### ISSUE TITLE
How to run a private network？

### ISSUE THREAD

**Issue by XieXiaomei-ptr** [ripple/rippled#3149]
I am learning blockchain knowledge. How to run a private blockchain network based on the rippled code? The network is completely independent of the XRP Ledger network, but it's not Stand-Alone Mode, which has its own Validators, a new Genesis Ledger, and more. This way I can try to modify the code and debug without being affected by the XRP Ledger network. How should I do it?

**Comment by movitto** [comment]
@XieXiaomei-ptr I think you're convoluting a few concepts here. An independent network by definition will have it's own nodes and validators that are different than the mainnet, though theoretically I can see it being able to be seeded from the data in the mainnet database (someone please correct, if this is not possible). If you run a node, it will connect to the mainnet by default, but will only be in 'read-only' mode, just tracking the network and not participating in consensus.... modify away!

https://xrpl.org/rippled-server-modes.html

**Comment by nbougalis** [comment]
@XieXiaomei-ptr, if you want to spin up your own network you're going to need (at a minimum) a server configured to operate as a validator and you'll have to start a fresh genesis ledger of your own.

Alternatively, you can always connect to an existing testnet; Ripple hosts a testnet (which tracks the latest stable version of the software and mirrors the network configuration) and a devnet (which runs release candidates). For more, see https://xrpl.org/connect-your-rippled-to-the-xrp-test-net.html.

**Comment by maybeTomorrow** [comment]
so ,how to start a new Genesis Ledger not in  Stand-Alone Mode
