### ISSUE TITLE
node_db importing has no status updates

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#315]
As it can take a quite long time to import a node_db database, having frequent status updates and, if possible, estimates on completion times would be great. For example an "info" log message every 5 seconds or so would be great.

**Comment by nbougalis** [comment]
I agree that we should improve this, but I would prefer a standalone utility to do the conversion, and that could have all sorts of nice reporting.

I'm closing this issue because we're unlikely to make any change to this code at this time.
