### ISSUE TITLE
Error occurs after leger 256 is stand-alone mode Amendments 

### ISSUE THREAD

**Issue by MonarthS** [ripple/rippled#3153]
What is Amendment and how to use it in rippled stand-alone mode?

When I reached up to 256 ledger, then it send one transaction automatically called `EnableAmendment` & shows error like `Transaction in ledger 257 affects no accounts`.

So, how can I use this in rippled stand-alone mode?

**Comment by nbougalis** [comment]
The _"`Transaction in ledger 257 affects no accounts`"_ message that you see is not an error. It is a warning and should not affect the operation of the system. As for amendments, they are a way of introducing new features and achieving consensus about which ones to activate and when in a decentralized manner without causing disruptions to the network.  For more you can check out https://xrpl.org/amendments.html.

**Issue:** While technically correct, a message warning that a transaction affects no accounts should not be displayed for transaction types like `EnableAmendment` which are designed to not affect any accounts.
