### ISSUE TITLE
[HELP!!!!] Why a DestinationTag is required when I send coins to a normal address started with 'r' ?

### ISSUE THREAD

**Issue by Brochao** [ripple/rippled#3158]
The address is "rBYsv4HgPDZzVwDjm58vfMPbWoECPzCY55"

As far as I know, a DestinationTag is required when send coins to a new 'X'-started-address, 
but when I send coins to the address above , I got error message like :
"result":{"engine_result":"tecDST_TAG_NEEDED","engine_result_code":143,"engine_result_message":"A destination tag is required.","tx_blob":...............}

I don't understand how this could happen, and how can I get the DestinationTag from a normal address?

**Comment by yxxyun** [comment]
https://xrpl.org/source-and-destination-tags.html

**Comment by Brochao** [comment]
> https://xrpl.org/source-and-destination-tags.html

So I should ask the address-owner to provide his destination tag?
我应该要地址持有者给我他的Tag才行吧？

**Comment by okanaganrusty** [comment]
The new 𝗫-address format will replace the combination of an 'r...' address in combination with a destination tag. By using one address that contains both the destination account and the destination tag, users can no longer make mistakes by making mistakes entering, or omitting the destination tag.

**Comment by mDuo13** [comment]
@Brochao Yes, you should ask what destination tag they want you to use.

Technically, you could specify any destination tag, such as `0` or `1234` but if the address is shared somehow (i.e. an exchange's deposit address), then they may not be able to credit the correct person/service for the XRP.

**Comment by Brochao** [comment]
@okanaganrusty  @mDuo13  
thanks for reply!

I got another question.
If I own a normal address which is not created via ripple's tools,   how to make it DestinationTag-required?   aka transactions to the address without a tag will be rejected?

**Comment by MarkusTeufelberger** [comment]
Set asfRequireDest via https://xrpl.org/accountset.html - this is not a support forum for XRPL by the way and not really related to `rippled`. The official forum is at https://forum.ripple.com/

**Comment by Brochao** [comment]
@MarkusTeufelberger 
got it!
thanks!

**Comment by intelliot** [comment]
> The official forum is at forum.ripple.com/

This forum has been shut down; we suggest the community-run https://www.xrpchat.com/ instead.
