### ISSUE TITLE
two rippled performance much different  read throughput

### ISSUE THREAD

**Issue by sampleblood** [ripple/rippled#3168]
two rippled with the same config, running at 2 AWS ec2 with 3200 iops EBS,  one rippled is running smoothly with 1000 Ops/s read throughput, ledger without gap. but the other rippled with 
2000+ Ops/s read throughput and  many gaps  can not backfill.

these two AWS ec2 with the same specification
please help

**Comment by nbougalis** [comment]
Unfortunately, this is not unexpected.

EBS uses a "credit-based" system to allocate/throttle I/O, so even slight differences in I/O patterns can result in dramatically different performance, depending on how many I/O credits the application has at any given time.

We experienced similar issues when operating instances on AWS: one instance would be fine, while another struggled. Ultimately, it was that experience that resulted in us diving through the EBS documentation to try and understand the EBS performance chracteristics and, finally, led to us not recommending using EBS as the backing store for a `rippled` instance's data store.

I'm happy to dive deeper, if you have additional questions; but if you feel that this post satisfactorily answers your questions, please go ahead close this issue.

Thanks and happy Thanksgiving! :turkey:

**Comment by sampleblood** [comment]
> Unfortunately, this is not unexpected.
> 
> EBS uses a "credit-based" system to allocate/throttle I/O, so even slight differences in I/O patterns can result in dramatically different performance, depending on how many I/O credits the application has at any given time.
> 
> We experienced similar issues when operating instances on AWS: one instance would be fine, while another struggled. Ultimately, it was that experience that resulted in us diving through the EBS documentation to try and understand the EBS performance chracteristics and, finally, led to us not recommending using EBS as the backing store for a `rippled` instance's data store.
> 
> I'm happy to dive deeper, if you have additional questions; but if you feel that this post satisfactorily answers your questions, please go ahead close this issue.
> 
> Thanks and happy Thanksgiving! 🦃

ok, I will close this issue.
Thanks for your help and happy Thanksgiving!

**Comment by JoelKatz** [comment]
It may help to reduce the amount of querying you allow other nodes to do to your node. Reducing the number of peer connections and reducing the fetch depth, for example, could help. Also, using RocksDB and as much RAM as possible can help reduce the amount of I/O needed, but you can't keep very much history that way.

**Comment by sampleblood** [comment]
> It may help to reduce the amount of querying you allow other nodes to do to your node. Reducing the number of peer connections and reducing the fetch depth, for example, could help. Also, using RocksDB and as much RAM as possible can help reduce the amount of I/O needed, but you can't keep very much history that way.

thanks for your advice.

these three parameters have been tried to modify, did not work.
```
[overlay]
ip_limit=1
[peers_max]
10
[fetch_depth]
128
```
after that , I deleted all my history data and re-sync, read iops almost to 0 and work well by now.
