### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by chrisvdb** [ripple/rippled#317]
Hi,

I have created and uploaded a .deb package to Debian unstable as mentioned in https://ripple.com/forum/viewtopic.php?f=2&t=6151&start=10#p44427. This package should ultimately make it to Debian test/stable and Ubuntu. Unfortunately the package got auto-rejected because of two Lintian errors: static linking of sqlite and libjsoncpp.

E: rippled: embedded-library usr/bin/rippled: sqlite
N:
N: The given ELF object appears to have been statically linked to a
N: library. Doing this is strongly discouraged due to the extra work needed
N: by the security team to fix all the extra embedded copies or trigger the
N: package rebuilds, as appropriate.
N:
N: If the package uses a modified version of the given library it is highly
N: recommended to coordinate with the library's maintainer to include the
N: changes on the system version of the library.
N:
N: Refer to Debian Policy Manual section 4.13 (Convenience copies of code)
N: for details.
N:
N: Severity: serious, Certainty: possible
N:
N: Check: binaries, Type: binary, udeb
N:
E: rippled: embedded-library usr/bin/rippled: libjsoncpp
W: rippled: hardening-no-relro usr/bin/rippled
N:
N: This package provides an ELF binary that lacks the "read-only
N: relocation" link flag. This package was likely not built with the
N: default Debian compiler flags defined by dpkg-buildflags. If built using
N: dpkg-buildflags directly, be sure to import LDFLAGS.
N:
N: Refer to http://wiki.debian.org/Hardening for details.
N:
N: Severity: normal, Certainty: certain
N:
N: Check: binaries, Type: binary, udeb
N:
W: rippled: binary-without-manpage usr/bin/rippled
N:
N: Each binary in /usr/bin, /usr/sbin, /bin, /sbin or /usr/games should
N: have a manual page
N:
N: Note that though the man program has the capability to check for several
N: program names in the NAMES section, each of these programs should have
N: its own manual page (a symbolic link to the appropriate manual page is
N: sufficient) because other manual page viewers such as xman or tkman
N: don't support this.
N:
N: If the name of the man page differs from the binary by case, man may be
N: able to find it anyway; however, it is still best practice to make the
N: case of the man page match the case of the binary.
N:
N: If the man pages are provided by another package on which this package
N: depends, lintian may not be able to determine that man pages are
N: available. In this case, after confirming that all binaries do have man
N: pages after this package and its dependencies are installed, please add
N: a lintian override.
N:
N: Refer to Debian Policy Manual section 12.1 (Manual pages) for details.
N:
N: Severity: normal, Certainty: possible
N:
N: Check: manpages, Type: binary

There are 3 options:
- fix upstream in Rippled source
- ignore Lintian error
- fix in Debian package

Thoughts?

Also, happy to commit this package to Github. Would Builds/Debian be the right place?

Cheers,
Chris.

**Comment by nbougalis** [comment]
Sorry it took us a while to get to this. On response time alone, I'm going to close this issue, but I will add I'd be very interested in a Debian package for our **`master`** branch. If you're still interested in this, please open a new issue and let us know how we can help!

**Comment by MarkusTeufelberger** [comment]
Just as a side note, rippled will need to be buildable against upstream packages first - and even Debian Testing ships with Boost 1.62 by default (https://packages.debian.org/sid/libboost-all-dev). There's a 1.67 package though, so there might be hope.
