### ISSUE TITLE
Block hight increase slowly , that has ran 3 weeks. Bandwidth=5M。

### ISSUE THREAD

**Issue by garysdevil** [ripple/rippled#3186]
#Syncing issue
question1:
rippled.cfg: The [node_size] is tyny.
Block hight increase slowly , I think it blame to "WRN Unable to determine hash of ancestor seq=452" which last 3 weeks.  
![图片](https://user-images.githubusercontent.com/41293784/70692877-43e80380-1cf7-11ea-848c-62efa6246e09.png)
question2:
rippled.cfg: The [node_size] is medium.
![图片](https://user-images.githubusercontent.com/41293784/70694576-f077b480-1cfa-11ea-82e2-19ad33425c9f.png)
Block hight stop increase but "status" : "active".
question3:
After I ran "systemctl restart rippled". The picture was capture after it has ran 28minutes .
![图片](https://user-images.githubusercontent.com/41293784/70695927-a217e500-1cfd-11ea-89bb-5b3e21aad13f.png)
The incoming netwoking monitoring picture was capture after it has ran 24 hour .
![IMG_20191213_150630](https://user-images.githubusercontent.com/41293784/70777332-67c04d80-1dba-11ea-99e2-cecd4015ee4f.jpg)

question4: How to prove it blame to bandwidth or who can help me resolve this question.

**Comment by nbougalis** [comment]
This is not what I'd expect to see. Can you provide the output of the `server_info` command? If you used the package to install, you can execute:

*`/opt/ripple/bin/rippled --conf /opt/ripple/etc/rippled.cfg server_info`*

**Comment by garysdevil** [comment]
> 
> 
> This is not what I'd expect to see. Can you provide the output of the `server_info` command? If you used the package to install, you can execute:
> 
> **`/opt/ripple/bin/rippled --conf /opt/ripple/etc/rippled.cfg server_info`**

I have two ripple node deployed in different virtual machine. I redeployed these both node last week.
ripple_node02:
server_info:
{
   "result" : {
      "info" : {
         "build_version" : "1.3.1",
         "complete_ledgers" : "empty",
         "hostid" : "xrp_node02",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 1.999,
            "proposers" : 34
         },
         "load" : {
            "job_types" : [
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               }
            ],
            "threads" : 6
         },
         "load_factor" : 1,
         "network_ledger" : "waiting",
         "peer_disconnects" : "7013",
         "peer_disconnects_resources" : "1",
         "peers" : 0,
         "pubkey_node" : "n9KSpQss58RpEceGP2T5oPShNRc6PiZ58YQgj3tK3yiJX8iePgeJ",
         "pubkey_validator" : "none",
         "server_state" : "disconnected",
         "server_state_duration_us" : "52832645",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "225997726790",
               "transitions" : 2055
            },
            "disconnected" : {
               "duration_us" : "115988357800",
               "transitions" : 2055
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "syncing" : {
               "duration_us" : "18031382",
               "transitions" : 1
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : 0
            }
         },
         "time" : "2019-Dec-16 07:08:35.929939",
         "uptime" : 342004,
         "validated_ledger" : {
            "age" : 285555,
            "base_fee_xrp" : 1e-05,
            "hash" : "7C750CAC482527DE6EE0E3CAE1811EFCC91F447B16BB9BD7A88233E9BBFF8DCB",
            "reserve_base_xrp" : 20,
            "reserve_inc_xrp" : 5,
            "seq" : 52013207
         },
         "validation_quorum" : 28,
         "validator_list" : {
            "count" : 1,
            "expiration" : "2020-Jan-14 00:00:00.000000000",
            "status" : "active"
         }
      },
      "status" : "success"
   }
}


ripple_node01:  It occured a weired phenomenon.
/opt/ripple/bin/rippled ledger | grep seqNum =  "seqNum" : "52009073"
but  the folder that save blcok only use 4.6G.
![图片](https://user-images.githubusercontent.com/41293784/70886950-b0c10d80-2017-11ea-9c63-9982e6ec2417.png)
server_info:
{
   "result" : {
      "info" : {
         "build_version" : "1.3.1",
         "complete_ledgers" : "52008930-52008939",
         "hostid" : "xrp_node01",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 2.001,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "avg_time" : 7,
                  "job_type" : "untrustedProposal",
                  "peak_time" : 35,
                  "per_second" : 25
               },
               {
                  "job_type" : "ledgerData",
                  "per_second" : 4
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "avg_time" : 7,
                  "job_type" : "advanceLedger",
                  "peak_time" : 36,
                  "per_second" : 4
               },
               {
                  "avg_time" : 7,
                  "job_type" : "trustedValidation",
                  "peak_time" : 65,
                  "per_second" : 1
               },
               {
                  "job_type" : "writeObjects",
                  "peak_time" : 18
               },
               {
                  "job_type" : "trustedProposal",
                  "peak_time" : 1,
                  "per_second" : 7
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 46
               },
               {
                  "job_type" : "diskAccess",
                  "peak_time" : 18
               }
            ],
            "threads" : 6
         },
         "load_factor" : 1,
         "peer_disconnects" : "6508",
         "peer_disconnects_resources" : "8",
         "peers" : 1,
         "pubkey_node" : "n94Ev8tBxnbMChynJrUfT4YWyJ2egs2Yq1deJ4wXo8GztXiYvyk2",
         "pubkey_validator" : "none",
         "server_state" : "full",
         "server_state_duration_us" : "88335606",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "37409921196",
               "transitions" : 1951
            },
            "disconnected" : {
               "duration_us" : "112792315883",
               "transitions" : 1910
            },
            "full" : {
               "duration_us" : "190386486646",
               "transitions" : 1802
            },
            "syncing" : {
               "duration_us" : "18024794",
               "transitions" : 1
            },
            "tracking" : {
               "duration_us" : "718716102",
               "transitions" : 1804
            }
         },
         "time" : "2019-Dec-16 07:21:42.881800",
         "uptime" : 341325,
         "validated_ledger" : {
            "age" : 303072,
            "base_fee_xrp" : 1e-05,
            "hash" : "FEED584AC12300053E4B6CA42F898E28146D7B190C896193F53941D0FFE8012C",
            "reserve_base_xrp" : 20,
            "reserve_inc_xrp" : 5,
            "seq" : 52008939
         },
         "validation_quorum" : 28,
         "validator_list" : {
            "count" : 1,
            "expiration" : "2020-Jan-14 00:00:00.000000000",
            "status" : "active"
         }
      },
      "status" : "success"
   }
}

**Comment by garysdevil** [comment]
It blame to bandwidth.
I failed to run the ripple at 5M bandwidth
I can run the ripple at 10M bandwidth, but there are still  some other problems.

**Comment by garysdevil** [comment]
It blame to bandwidth.
I failed to run the ripple at 5M bandwidth
I can run the ripple at 10M bandwidth, but there are still some other problems.
