### ISSUE TITLE
how to install ripple from the source code?

### ISSUE THREAD

**Issue by yuexk** [ripple/rippled#3192]
when i use the source install ripple, i meet the some problem as follow:
`[ 57%] No install step for 'rocksdb'
[ 58%] No test step for 'rocksdb'
[ 58%] Completed 'rocksdb'
[ 61%] Built target rocksdb
[ 62%] Linking CXX executable rippled
/home/test/boost_1_70_0/boost/regex/v4/cpp_regex_traits.hpp:966: error: undefined reference to 'boost::re_detail_107000::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
/home/test/boost_1_70_0/boost/regex/v4/cpp_regex_traits.hpp:962: error: undefined reference to 'boost::re_detail_107000::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
collect2: error: ld returned 1 exit status
CMakeFiles/rippled.dir/build.make:1369: recipe for target 'rippled' failed
make[2]: *** [rippled] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/rippled.dir/all' failed
make[1]: *** [CMakeFiles/rippled.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`
how to solution this prolem? Thanks

**Comment by mellery451** [comment]
this looks like a problem linking with the boost you built. Which compiler version are you using? Depending on the compiler version, I'm thinking you might want to add `cxxflags="-std=c++14"` to your `b2` command when building boost (e.g. see https://github.com/mellery451/rippled/blob/4a1148eb2849513dd1e7ae080288fd47ab57a376/Builds/containers/shared/install_boost.sh#L53).

**Comment by mDuo13** [comment]
This issue hasn't seen any updates for a while, so I'm closing it. Feel free to reopen if you have more information to add.
