### ISSUE TITLE
Release Notes for 1.4.0

### ISSUE THREAD

**Issue by alloyxrp** [ripple/rippled#3195]
https://github.com/ripple/rippled/releases shows 1.3.1 as the latest release. Aren't there any release notes for 1.4.0? @mDuo13 @nbougalis

**Comment by nbougalis** [comment]
Assigning this to @mDuo13. Thanks for calling this out!

**Comment by mDuo13** [comment]
Copied the release notes from the blog article into the GitHub release tag. https://github.com/ripple/rippled/releases/tag/1.4.0
