### ISSUE TITLE
Running scons gives error in ubuntu 12.04

### ISSUE THREAD

**Issue by EMRJ** [ripple/rippled#320]
Building:
scons: done reading SConscript files.
scons: Building targets ...
    src/ripple_data/protocol/ripple.proto
    build/proto/ripple.pb.cc
    src/ripple/beast/ripple_beast.cpp
In file included from src/leveldb/../beast/modules/beast_asio/beast_asio.h:27:0,
                 from src/leveldb/../beast/modules/beast_asio/beast_asio.cpp:26,
                 from src/ripple/beast/ripple_beast.cpp:30:
src/leveldb/../beast/modules/beast_asio/system/BoostIncludes.h:55:54: fatal error: boost/asio/detail/handler_cont_helpers.hpp: No such file or directory
 #include <boost/asio/detail/handler_cont_helpers.hpp>
                                                      ^
compilation terminated.
scons: *** [build/obj/src/ripple/beast/ripple_beast.o] Error 1
scons: building terminated because of errors.

**Comment by rec** [comment]
Can't reproduce, feel free to reopen with a new testcase!
