### ISSUE TITLE
Several mistypes

### ISSUE THREAD

**Issue by 0x49D1** [ripple/rippled#3208]
The release description for 1.4 says:
https://github.com/ripple/rippled/releases/tag/1.4.0
Ripple has released **version 1.3.1** of rippled, the reference implementation of the core XRP Ledger protocol. To learn more about how to build and run a rippled server, see Manage the rippled Server.
Why 1.3.1? Seems like copy paste problem..

And another one in the blog: 
https://xrpl.org/blog/2019/rippled-1.4.0.html
Impact of Not Upgrading
Ripple expects the DeletableAccounts Amendment to become enabled no earlier than **Monday**, **2019-12-16**. When this happens, if you are not running release 1.4.0 or greater, your server will become amendment blocked, meaning that it...
Why 2019-12-16?! It's already the date from the past.

**Comment by intelliot** [comment]
@0x49D1 I updated the release description; thanks for catching that!

The date in the blog post is correct. It is the earliest date that the DeletableAccounts Amendment could have become enabled. The DeletableAccounts Amendment was not enabled at that time, so it was not actually necessary to upgrade (yet). At this time, this amendment does not have enough validator support to become enabled, so upgrading to 1.4.0 is not yet required. However, it - or some other amendment(s) in 1.4.0 - may be enabled in the near future, so it is best to upgrade as soon as possible.
