### ISSUE TITLE
XRP Ledger reference architecture

### ISSUE THREAD

**Issue by GiancarloLelli** [ripple/rippled#3211]
Hi all
I'm trying to set up a bunch of VMs on Cloud to understand how much money it would take to run a fully configured XRP Ledger. Are there any recommendation for this? For example: at least 3 validator nodes and 3 other nodes serving each one a different protocol (maybe even with at least 3 VMs per protocol)

Are there any examples of configuration for a validator node and for a stock server node?

**Comment by MarkusTeufelberger** [comment]
It mostly depends on the network you want to run on - if you want to run on the current mainnet, you can check out https://xrpl.org/system-requirements.html#recommended-specifications

I'm not sure what you mean by "different protocol". Could you clarify?

**Comment by GiancarloLelli** [comment]
I mean, one (or a group of three) node for HTTP/HTTPS another node for WSS and another node peer connection.

**Comment by MarkusTeufelberger** [comment]
All of them should have their peer port open, I don't think that there's much use in having a whole VM + `rippled` instance just to separate Websockets from JSON-RPC.
