### ISSUE TITLE
error: Unit test failing on Windows and unhandled exceptions

### ISSUE THREAD

**Issue by GiancarloLelli** [ripple/rippled#3217]
Hi team,
I've followed the steps to build rippled on Windows and now I am trying to run the embedded unit test to make sure everything works. I'm building the master branch, so rippled 1.4.0 - the code base is untouched.

Unfortunately thought once I get to the *ripple.app.Manifest validator token* test the program crashes. Below a screenshot:

![image](https://user-images.githubusercontent.com/6195018/72015856-d9c56e80-3262-11ea-8dd7-29ca023bab27.png)

I'm compiling using Boost 1.7.0, OpenSSL 1.0.2u and Visual Studio 2019.

Can somebody tell me if I'm doing something wrong? Maybe something configuration related.

**Comment by nbougalis** [comment]
@GiancarloLelli, thanks for this report. I know that you were looking to make changes to the code. I know you said this in your original post, but I just want to confirm: you have not made **any changes yet** and the code is issue is manifesting with the 1.4.0 branch that is presently on **`master`** (tip commit is 06c371544acc3b488b9d9c057cee4e51f6bef7a2).

I'll ask someone else with Windows to verify this issue and see if we can reproduce and identity the problem.

**Comment by ximinez** [comment]
I notice that you've got several test failures in that screenshot leading up to the crash. That hints that something else odd is going on. Try these two things:
1. Make sure no other instances of rippled are running on that system.
2. Delete the folder where you're building rippled and start over.

If you continue having problems, please post the exact steps that you're using to build and run the unit tests, including any command lines if appropriate.

**Comment by GiancarloLelli** [comment]
Hi @ximinez 
Still facing the same issue. These are the steps I do:

1. Download Win64 OpenSSL v1.0.2u in C:\lib\OpenSSL-Win64
2. Download Boot 1.71 in C:\lib\boost
3. Run bootstrap.bat
4. Run b2.exe
5. Run C:\lib\boost\tools\build\src\engine\bjam.exe -j4 --toolset=msvc-14.2 address-model=64 architecture=x86 link=static threading=multi runtime-link=shared,static stage
6. Open VS2019 and "Generate Cache"
7. Open VS2019 and "Rebuild All"
8. Debug rippled with --unittest flag (launch.vs.json)

And this are the errors I see in the console.
The "missing account root" is repeated multiple time since the start of the tests.

![image](https://user-images.githubusercontent.com/6195018/72352951-7ebccd00-36e3-11ea-9882-9694020d1e15.png)

**Comment by ximinez** [comment]
Hi @GiancarloLelli 

Could you paste the output of `git status`, then run `git reset --hard upstream/master`?

**Comment by GiancarloLelli** [comment]
Hi @ximinez 
Apparently after nuking the folder again and cloning/building everything again all the test pass successfully. I'm sorry if I've wasted your time, but I'm glad I've solved this.

Thanks!

**Comment by ximinez** [comment]
@GiancarloLelli That's great! I'm happy we were able to help and that things are back on track. I'm going to go ahead and close this issue, but if you have further problems, feel free to reopen it, or create a new one.
