### ISSUE TITLE
account_lines method does not return no_ripple / no_ripple_peer in non-default state

### ISSUE THREAD

**Issue by mDuo13** [ripple/rippled#3245]
Migrated from internal issue [RIPD-1031](https://ripplelabs.atlassian.net/browse/RIPD-1031).

By convention, the [account_lines method](https://xrpl.org/account_lines.html) returns booleans for flags that are in their non-default states. In the vast majority of cases, this means it returns flags when the values are `true` and omits them when the values are `false`. The NoRipple flags of a trust line are exceptions, and the API doesn't handle them properly. This is probably because the API was not changed after DefaultRipple was added, because DefaultRipple _changes what's considered the default state_ of the NoRipple flag.

The API should explicitly include the `no_ripple` and `no_ripple_peer` flags when their current value is non-default as determined by the lsfDefaultRipple flags of their respective accounts. This would make it far, far easier to recognize when a NoRipple flag (on either side) is causing a trust line to be in a non-default state.

For an example of a trust line like this, see [rPRvq4qwRgtsUy7JM911swhESfDDc5tm1D←→rGatEqm5MDi5bk8FSZEi9xmJiiNpdZx5VU](https://xrpl.org/websocket-api-tool.html?server=wss%3A%2F%2Fs2.ripple.com%2F&req=%7B%22id%22%3A2%2C%22command%22%3A%22account_lines%22%2C%22account%22%3A%22rPRvq4qwRgtsUy7JM911swhESfDDc5tm1D%22%2C%22ledger_index%22%3A%22validated%22%7D).

```json
{
  "id": 2,
  "result": {
    "account": "rPRvq4qwRgtsUy7JM911swhESfDDc5tm1D",
    "ledger_hash": "6467B8AE06B83BFE136CD2E7039CCB116800123EB03AE8A654E44BFDC7A9D4A1",
    "ledger_index": 53188407,
    "lines": [
      {
        "account": "rGatEqm5MDi5bk8FSZEi9xmJiiNpdZx5VU",
        "balance": "0",
        "currency": "USD",
        "limit": "0",
        "limit_peer": "0",
        "quality_in": 0,
        "quality_out": 0
      }
    ],
    "validated": true
  },
  "status": "success",
  "type": "response"
}
```

It's impossible to tell from just this information, but this trust line counts against rPRv...'s owner reserve, even though it appears that the trust line has no balances, no limits, no quality settings, and no flags enabled. So why's it considered to be in a non-default state? It's because rPRv...'s NoRipple setting for this trust line is _off_, but the default for rPRv...'s trust lines should be for NoRipple to be _on_, because rPRv's DefaultRipple setting is _off_. (All these double negatives make it confusing, which is kind of a different problem.)

Anyway, the point here is that a more user-friendly API would provide `no_ripple` and `no_ripple_peer` in the response whenever their values are preventing a trust line from being in its default state. Of course, right now clients are instructed to assume that any flags which are omitted are false, so we can't omit them if they're in a default state of `true`. So, to be backwards-compatible with the existing API, I propose the following logic:

For a trust line between accounts A and B, where A is the "perspective account" used in the API request's `account` field and B is the "peer account" for a given trust line:

- If A's side of the trust line has NoRipple enabled, return `"no_ripple": true` always.
- Else, if A has DefaultRipple disabled, explicitly return `"no_ripple": false`. (This is the case where "false" is the non-default value.)
- Else, omit `no_ripple`. (NoRipple is off and that's the default.)

Also apply the exact same logic to the peer account "B" for the field `no_ripple_peer`.

**Comment by cjcobb23** [comment]
Why don't we just not omit any fields? This seems a lot simpler to me than.

**Comment by mDuo13** [comment]
Delivered in #3587
