### ISSUE TITLE
Rippled full history node can't syncup after upgrade to 1.4.0 from 1.3.1

### ISSUE THREAD

**Issue by ksemaev** [ripple/rippled#3253]
I have 6 full history nodes, all were started at the same time about a year ago (they are located in separate environments, that's why I need so much).
All of them are equal: 4 CPU, 32 GB RAM, 12 Tb SSD volumes (all use the same 85% of that volume).

After absolutely simular procedure of upgrade:
- one node restarted, looked like stuck for ~40 min, then started to syncup (I know that it was doin DB management, no questions here), and now it's fine;
- two nodes restarted, loked like stuck for ~30 hours, then started to syncup, now it's fine;
- one node took 20 hours, and since then restarting every 4-6 hours with errors like:

> Logic error: Deadlock detected
> 2020-Feb-10 10:06:52.244179000 Protocol:NFO [009] Transaction queue is full

- two other nodes I tried to start with the volume, created from  snapshot of upgraded first node, and they can't syncup for 3 days already with same error like:

> NetworkOPs:WRN We are not running on the consensus ledger

My questions are:
1) Why absolutely same nodes take that different time to cleanup DB after upgrade?
2) Could I just upgrade one node, and then clone it's volume and spawn new full history nodes from them? Or maybe some cleanup and maitenance required before using the cloned volume? Some unique ids maybe?
3) Is this ` Logic error: Deadlock detected` error after upgrade is a know issue? Can I fix it somehow?

TY very much for any advice!

**Comment by nbougalis** [comment]
Apologies for the delay with this. Are you still encountering deadlock issues?
