### ISSUE TITLE
Choose [node_size] Automatically

### ISSUE THREAD

**Issue by mDuo13** [ripple/rippled#3265]
## Summary

The `[node_size]` parameter is an important setting for performance but the preferable setting is almost always [based just on available RAM](https://xrpl.org/capacity-planning.html#node-size). The `rippled` server should choose the appropriate value automatically.

## Motivation

Users need to customize the `[node_size]` based on their hardware specs, but this is added complexity for administrating a `rippled` server. For something as basic as this, we should automate the solution as much as we can.

## Solution
The server should be able to read the amount of RAM available and choose the recommended `[node_size]` value automatically. That reduces the amount of customization an admin has to do to their config file.

It might be worth removing the config field entirely, or leaving it as an override. I'm fine with either one, but we'd have to be wary of people not updating their existing file (to keep other customizations) and thus not getting the benefit. Still, that's probably... fine.

## Paths Not Taken

We could change the recommended values from magic words like `small` and `huge` to instead be explicit amounts of RAM the server should optimize for, but... why make the user do more work? I don't think it's bad to let users do more fine-grained performance tuning, but that should not be a requirement for the server to run well out of the box.

**Comment by intelliot** [comment]
What if the user runs other processes, in addition to rippled, on the same server?

**Comment by mDuo13** [comment]
If they do, then they should configure the `[node_size]` manually for the amount of RAM they expect it to use. But I think we generally don't recommend running much else on the same server if you want it to be reliable.

**Comment by MarkusTeufelberger** [comment]
One thing that caused an issue on my machine was the automatic assumption that a larger node_size (= more caches used) also means a larger internet bandwidth.

I'd rather see node_size being removed completely and the ~5 settings it actually controls being exposed directly and individually tuneable. Maybe with a documentation attached which set of settings corresponded to which node_size.

**Comment by mDuo13** [comment]
This was completed in [v1.8.1](https://xrpl.org/blog/2021/rippled-1.8.1.html#new-and-improved-features).
