### ISSUE TITLE
Questions about the order

### ISSUE THREAD

**Issue by XieXiaomei-ptr** [ripple/rippled#3275]
There is a trading pair, xrp/ust.
Now, I have 10 ust, with 10 ust to pay a bill, and then I immediately transferred 10 ust to other addresses, found that just the order can no longer be traded.

How to solve this problem？

**Comment by carlhua** [comment]
Hi @XieXiaomei-ptr I am glad you are interested in learning more about XRP. Unfortunately this Github issue tracker is meant for bug reporting/new features. I am going to close this issue. For this type of questions I suggest you give https://xrpl.org/ or https://forum.xpring.io/c/community/ a try!
