### ISSUE TITLE
Enhance rippled's HTTP Response for empty requests (Version: 1.5 RC2)

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3307]
## Summary

Existing rippled's HTTP response to an empty request is HTTP 400. For example:
```
/ # curl -I localhost:51233
HTTP/1.1 400 Bad Request
```
Consider enhancing the response to give HTTP 200 when an empty request is received.
## Motivation

This allows conventional load balancers to properly detect the state of rippled

## Solution

Consider checking for empty request here
https://github.com/ripple/rippled/blob/develop/src/ripple/rpc/impl/ServerHandlerImp.cpp#L569
```
  if ((request.size () > RPC::Tuning::maxRequestSize) ||
            ! reader.parse (request, jsonOrig) ||
            ! jsonOrig ||
            ! jsonOrig.isObject ())
        {
            HTTPReply (400, "Unable to parse request: " +
                       reader.getFormatedErrorMessages(), output, rpcJ);
            return;
        }

```
## Paths Not Taken

N/A

**Comment by intelliot** [comment]
If this is used by load balancers, then rippled should probably not respond with 200 if the server is not in sync with the network.

It might be similar to calling `server_info` and checking that the `result.info.server_state` is `full`, `validating`, or `proposing`.

**Comment by mDuo13** [comment]
If you want to check the status of rippled with a load balancer, you should be calling the [Health Check method](https://xrpl.org/health-check.html). 

I think this ticket does not need to be done now that the Health Check exists, and it is still appropriate to return 400 Bad Request if you call with no info.
