### ISSUE TITLE
Status has became amendment blocked(Version: 1.4.0)

### ISSUE THREAD

**Issue by findShota** [ripple/rippled#3324]
## Issue Description
In spite of running rippled v1.4.0, my rippled server connected to testnet has became status `amendment blocked` and doesn't work some commands.
```
2020-Mar-25 04:30:41.598365568 Amendments:ERR Unsupported amendment 00C1FC4A53E60AB02C864641002B3172F38677E29C26C5406685179B37E1EDAC activated.
2020-Mar-25 04:30:41.598401734 Amendments:ERR Unsupported amendment 89308AF3B8B10B7192C4E613E1D2E4D9BA64B2EE2D5232402AE82A6A7220D953 activated.
2020-Mar-25 04:30:41.598420372 LedgerMaster:ERR One or more unsupported amendments activated: server blocked.
```

How to solve it?
Upgrade to the newest version is what's written [here](https://xrpl.org/amendments.html) as a solution to this kind of ploblem, but I think `v1.4.0` is the newest version except release candidates.

## Steps to Reproduce
After March 25, I can't submit any transactions via my rippled server.
`ledger current` command returns an error as well.

## Expected Result
`ledger current` command returns the unique identifiers of the current in-progress ledger.

## Actual Result
```
2020-Mar-25 04:29:52.259105041 RPC:TRC HTTP Reply 200 {"result":{"error":"noNetwork","error_code":17,"error_message":"Not synced to Ripple network.","request":{"command":"ledger_current"},"status":"error"}}
```

## Environment
rippled v1.4.0 on AmazonLinux 2
network: testnet

## Supporting Files

Also, as a response of `peer` commands, I found out that my server is connected to the servers who are runnning `rippled-1.5.0-rc3`.
```
{
   "result" : {
      "cluster" : {},
      "peers" : [
         {
            "address" : "34.210.87.206:51235",
            "complete_ledgers" : "5749768 - 5750024",
            "latency" : 140,
            "ledger" : "6DCFF09F5715B3AEDF45DCAFFEF1B914D1BE6257D0AD271F6A41CA2FBB670A3D",
            "load" : 123,
            "public_key" : "n9LqqEzsuHd36vGxwdeSxQpWFxdxY5D17wqgBNrqNhpxEHS1Hod9",
            "uptime" : 7200,
            "version" : "rippled-1.5.0-rc3"
         },
         {
            "address" : "183.238.91.249:51235",
            "complete_ledgers" : "5748024 - 5750024",
            "latency" : 6162,
            "ledger" : "6DCFF09F5715B3AEDF45DCAFFEF1B914D1BE6257D0AD271F6A41CA2FBB670A3D",
            "load" : 138,
            "public_key" : "n9LVqefWp7Bvda7MrLgvQQLi5jZcHqyzXgPRcP5xCtMj8A4BGqQa",
            "uptime" : 978,
            "version" : "rippled-1.4.0"
         },
         {
            "address" : "35.158.96.209:51235",
            "complete_ledgers" : "5749768 - 5750024",
            "latency" : 473,
            "ledger" : "6DCFF09F5715B3AEDF45DCAFFEF1B914D1BE6257D0AD271F6A41CA2FBB670A3D",
            "load" : 195,
            "public_key" : "n9L9E46AjmQh1VNAUnhLt8mFMdnVWnyHETcBwjMU5ctxssjWrSNL",
            "uptime" : 7199,
            "version" : "rippled-1.5.0-rc3"
         }
      ],
      "status" : "success"
   }
}
```

validatots.txt
```
[validator_list_sites]
https://vl.altnet.rippletest.net
 
[validator_list_keys]
ED264807102805220DA0F312E71FC2C69E1552C9C5790F6C25E3729DEB573D5860
```

**Comment by intelliot** [comment]
(Duplicate of https://github.com/ripple/rippled/issues/3315)

On March 13, 2020, the Testnet and Devnet validators were upgraded to rippled version 1.5.0-rc2.

As of March 24, 2020, all rippled servers connecting to the Testnet should be upgraded to rippled 1.5.0-rc3 to continue operating.

Details: https://groups.google.com/forum/#!topic/ripple-server/21htQzq4zz0

Subscribe to the ripple-server list for future updates: https://groups.google.com/forum/#!forum/ripple-server

Does this resolve your issue?

**Comment by findShota** [comment]
@intelliot 
Excuse me for making a duplicate issue.
Thank you, I close this issue.

**Comment by sammy1991106** [comment]
@intelliot Why is this still happening in the testnet instead of only the devnet? Based on comment from @nbougalis here at #3149 (comment), the testnet tracks the latest stable version of the software and the devnet runs release candidates. We use the same docker image of a stable version for both our mainnet and testnet nodes for the production and non-production environments, respectively. Using a release candidate temporarily for our testnet nodes is doable, but certainly not convenient and proper.
