### ISSUE TITLE
Add GRPCServer to Stoppable hierarchy

### ISSUE THREAD

**Issue by cjcobb23** [ripple/rippled#3359]
## Summary
`GRPCServer` is not part of the `Stoppable` hierarchy, yet it uses the `JobQueue` (which is part of the `Stoppable` hierarchy) in an asynchronous manner. This issue is to investigate whether `GRPCServer` should be part of the `Stoppable` hierarchy, and to implement the change if necessary.

**Comment by scottschurr** [comment]
@thejohnfreeman, I wonder if this change has been addressed by your `Stoppable` work?  Would it be appropriate to close this issue?

**Comment by cjcobb23** [comment]
This was actually completed as part of https://github.com/ripple/rippled/pull/3554. Closing.
