### ISSUE TITLE
[compilation failed] (Version: [1.5.0 ])

### ISSUE THREAD

**Issue by maef2018** [ripple/rippled#3390]
hi,I encountered the following problems when deploying the latest version of xrp node. Could you give me some help, thank you very much!
Deployment plan one:
Operating system: ubuntu16.04
Reference documents:  https://github.com/ripple/rippled/tree/develop/Builds/linux

 #  cmake --build .        The error is reported as follows:
/data/rippled/my_build/proto_gen/ripple.pb.cc:10159:3: error: 'GOOGLE_SAFE_CONCURRENT_WRITES_END' was not declared in this scope
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/rippled/my_build/proto_gen/ripple.pb.cc: In member function 'int protocol::TMPing::ByteSize() const':
/data/rippled/my_build/proto_gen/ripple.pb.cc:10393:3: error: 'GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN' was not declared in this scope
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/rippled/my_build/proto_gen/ripple.pb.cc:10395:3: error: 'GOOGLE_SAFE_CONCURRENT_WRITES_END' was not declared in this scope
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/rippled/my_build/proto_gen/ripple.pb.cc: In member function 'virtual void protocol::TMPing::MergeFrom(const google::protobuf::Message&)':
/data/rippled/my_build/proto_gen/ripple.pb.cc:10402:35: error: 'dynamic_cast_if_available' is not a member of 'google::protobuf::internal'
     ::google::protobuf::internal::dynamic_cast_if_available<const TMPing*>(
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~
/data/rippled/my_build/proto_gen/ripple.pb.cc:10402:61: error: expected primary-expression before 'const'
     ::google::protobuf::internal::dynamic_cast_if_available<const TMPing*>(
                                                             ^~~~~
CMakeFiles/pbufs.dir/build.make:70: recipe for target 'CMakeFiles/pbufs.dir/proto_gen/ripple.pb.cc.o' failed
make[2]: *** [CMakeFiles/pbufs.dir/proto_gen/ripple.pb.cc.o] Error 1
CMakeFiles/Makefile2:143: recipe for target 'CMakeFiles/pbufs.dir/all' failed
make[1]: *** [CMakeFiles/pbufs.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Install dependent environment according to reference document:
Boost 1.70
gcc-7

root@b3ebf9e093f5:/data# which protoc
/usr/bin/protoc
root@b3ebf9e093f5:/data# /usr/bin/protoc --version
libprotoc 2.6.1

root@b3ebf9e093f5:/data# gcc --version
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@b3ebf9e093f5:/data# g++ --version
g++ (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

git clone https://github.com/ripple/rippled
cd rippled
git checkout master

mkdir my_build
cd my_build

cmake ..
cmake --build .  

root@b3ebf9e093f5:/data/rippled/my_build# cmake ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Using 4 cores for ExternalProject builds.
-- Build type not specified - defaulting to Release
-- rippled version: 1.5.0
CMake Warning at Builds/CMake/RippledSettings.cmake:10 (message):
  unity option only supported for with cmake 3.16+ (please upgrade)
Call Stack (most recent call first):
  CMakeLists.txt:28 (include)

-- NIH-EP cache path: /data/rippled/.nih_c/unix_makefiles/GNU_7.3.0/Release
-- docker NOT found -- won't be able to build containers for packaging
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- BOOST_ROOT: /data/boost_1_70_0
-- BOOST_LIBRARYDIR: 
-- Found Boost: /data/boost_1_70_0 (found suitable version "1.70.0", minimum required is "1.70") found components:  chrono context coroutine date_time filesystem program_options regex serialization system thread atomic 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.a (found suitable version "1.0.2g", minimum required is "1.0.2") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Using local build of RocksDB.
-- Could NOT find Protobuf: Found unsuitable version "2.6.1", but required is at least "3.8" (found /usr/lib/x86_64-linux-gnu/libprotobuf.a;-pthread)
-- using local protobuf build.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- doxygen executable not found -- skipping docs target
-- Configuring done
-- Generating done
-- Build files have been written to: /data/rippled/my_build

Deployment plan two:
Install dependent environment according to reference document: https://xrpl.org/build-run-rippled-ubuntu.html
Operating system: ubuntu16.04

The error is reported as follows:
root@e6b37ce94322:/data/rippled/my_build# cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Using 4 cores for ExternalProject builds.
-- Build type not specified - defaulting to Release
-- rippled version: 1.5.0
CMake Warning at Builds/CMake/RippledSettings.cmake:10 (message):
  unity option only supported for with cmake 3.16+ (please upgrade)
Call Stack (most recent call first):
  CMakeLists.txt:28 (include)

-- NIH-EP cache path: /data/rippled/.nih_c/unix_makefiles/GNU_7.5.0/Release
-- docker NOT found -- won't be able to build containers for packaging
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- BOOST_ROOT: 
-- BOOST_LIBRARYDIR: 
CMake Error at /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR chrono context coroutine
  date_time filesystem program_options regex serialization system thread)
  (Required is at least version "1.70")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  Builds/CMake/deps/FindBoost.cmake:1994 (find_package_handle_standard_args)
  Builds/CMake/deps/Boost.cmake:41 (find_package)
  CMakeLists.txt:44 (include)

-- Configuring incomplete, errors occurred!
See also "/data/rippled/my_build/CMakeFiles/CMakeOutput.log".
See also "/data/rippled/my_build/CMakeFiles/CMakeError.log".

root@e6b37ce94322:/data/rippled/my_build# cat /data/rippled/my_build/CMakeFiles/CMakeError.log
Determining if the pthread_create exist failed with the following output:
Change Dir: /data/rippled/my_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_89490/fast"
/usr/bin/make -f CMakeFiles/cmTC_89490.dir/build.make CMakeFiles/cmTC_89490.dir/build
make[1]: Entering directory '/data/rippled/my_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_89490.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_89490.dir/CheckSymbolExists.c.o   -c /data/rippled/my_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_89490
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_89490.dir/link.txt --verbose=1
/usr/bin/cc      CMakeFiles/cmTC_89490.dir/CheckSymbolExists.c.o  -o cmTC_89490 
CMakeFiles/cmTC_89490.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_89490.dir/build.make:86: recipe for target 'cmTC_89490' failed
make[1]: *** [cmTC_89490] Error 1
make[1]: Leaving directory '/data/rippled/my_build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_89490/fast' failed
make: *** [cmTC_89490/fast] Error 2

File /data/rippled/my_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

root@e6b37ce94322:/data/rippled/my_build# cmake --build .
make: *** No targets specified and no makefile found.  Stop.

**Comment by nbougalis** [comment]
Thanks for reporting this! We'll get back to you shortly.

**Comment by seelabs** [comment]
Hi @maef2018 Thanks for reporting this! I just made a fresh install of ubuntu 16.04 on a VM and I was able to compile both the release and develop version of rippled. I'll spend some more time trying to figure out what's going on here, but (at least initially) I'm not able to reproduce this.

**Comment by maef2018** [comment]
hi，@seelabs Could you provide me a binary deployment package that you compiled successfully, I am running on our production environment (ubuntu16.04), I will resume the deposit and withdrawal of our exchange first, my email is 3118064263@qq.com, Thank you!

**Comment by seelabs** [comment]
Hi @maef2018, one option would be to install rippled from the package manager. There are instructions here: https://xrpl.org/install-rippled-on-ubuntu.html

BTW, I did not send you an email, so just be careful in case you get an email from someone pretending to be me. Especially if they try to get you to install a rippled executable of unknown provenance.
-Scott

**Comment by nbougalis** [comment]
>BTW, I did not send you an email, so just be careful in case you get an email from someone pretending to be me. Especially if they try to get you to install a rippled executable of unknown provenance.

First of all, thank you for not sending an unsigned binary!

With that said, I'll take the opportunity to issue a sternly-worded note of caution to everyone—and please forgive my use of bolded caps:

**PLEASE, PLEASE, PLEASE DO NOT RUN RANDOM BINARIES, _ESPECIALLY_ IF YOU ARE OPERATING AN EXCHANGE!**

Either compile one yourself from scratch on a machine that you can trust or, if that is not possible for you, please download and install **signed packages** from a **trusted source**. Scott has pointed you to instructions on how to download and install packages built and signed by Ripple.

The security of your infrastructure is only as good as its weakest link, and installing unsigned software, especially software received over an insecure medium like email, is a huge risk.

**Comment by maef2018** [comment]
success，thank you!
