### ISSUE TITLE
Offer Expiration doesn't work according to specification

### ISSUE THREAD

**Issue by SteelBRS** [ripple/rippled#3408]
I've been setting a 30 second expiration on the offers I create, but they keep lingering in the ledger, so I need to manually cancel them.

```
    offerCreate.expiration(UInt32(get30SecondExpiration()))

...

    private const val RIPPLE_EPOCH_SECONDS_AFTER_UNIX_EPOCH = 946684800L

    fun get30SecondExpiration(): Long {
        val currentTimeInSecondsSinceUnixEpoch = System.currentTimeMillis() / 1000L
        return currentTimeInSecondsSinceUnixEpoch - RIPPLE_EPOCH_SECONDS_AFTER_UNIX_EPOCH + 30L
    }
```

**Comment by yxxyun** [comment]
It is expired and will never filled, it will be canceled when other tx want fill it.

**Comment by SteelBRS** [comment]
I'm sorry to say it, but you're gonna have to learn english a little bit better.
I don't understand what you mean.
Do you mean that expired offers are visible forever on the ledger? And that they can be looked up with the command 'account_offers' to the end of time? That sounds incredibly expensive data-wise over time and sounds like a design error.
Also ... when an offer is fulfilled ... I hope internally something different happens than when the offer is cancelled.

**Comment by MarkusTeufelberger** [comment]
Please quote the part of the specification that is violated in your opinion.

**Comment by SteelBRS** [comment]
The specification is not violated.
https://xrpl.org/offers.html#offer-expiration

But it would be cleaner to delete non-fulfilled expired offers immediately after expiry.
Not to mention all the data you'd save pushing all over the network ... there is no reason to keep those ... from my point-of-view ... perhaps you have a different opinion?

**Comment by MarkusTeufelberger** [comment]
> But it would be cleaner to delete non-fulfilled expired offers immediately after expiry.

The explanation why this is not possible currently is also included in the link you gave. Generally data is deduplicated, so there's not much network traffic because of expired offers. A larger concern might be state inflation, but I'd like to see actual numbers for that to call it an actual problem.

**Comment by carlhua** [comment]
> 
> 
> I'm sorry to say it, but you're gonna have to learn english a little bit better.
> I don't understand what you mean.
> Do you mean that expired offers are visible forever on the ledger? And that they can be looked up with the command 'account_offers' to the end of time? That sounds incredibly expensive data-wise over time and sounds like a design error.
> Also ... when an offer is fulfilled ... I hope internally something different happens than when the offer is cancelled.
Please be considerate and polite in your responses, even if you disagree with someone else. Also please be mindful that this project is international in nature and although English may feel like it is the lingua franca in the coding space, the reality is that contributors come from walks of life and all corners of the world. Let’s all work together to make this project inclusive and fun to work on!

**Comment by movitto** [comment]
> But it would be cleaner to delete non-fulfilled expired offers immediately after expiry.

The only way the ledger gets modified is through transactions. This why for example Escrows are not automatically resolved when their 'Finish' or 'Close' time transpires, they require EscrowFinish and EscrowCancel transactions to release the funds. For the same reason expired offers do not disappear until cancelled by OfferCancel or overwritten by OfferCreate (specifying offer_sequence)

**Comment by SteelBRS** [comment]
Sorry for my impolite response @yxxyun 

@movitto does this mean that expired offers will stay on the ledger forever if no-one cancels them explicitly via. another transaction?

**Comment by MarkusTeufelberger** [comment]
Not movitto, but yes.

**Comment by scottschurr** [comment]
Um, also not movitto, but it depends on what you mean by "explicitly via another transaction".  For example, if a Payment or OfferCreate transaction attempts to use an offer and discovers that offer is expired, then that transaction will make a best effort at removing the expired offer from the ledger.  There are rare circumstances where that doesn't happen, but I think that's too far down in the weeds for this question.

So, yes, a transaction must be involved in removing the offer.  But it depends on your world view as to whether attempting to consume an expired offer is an _explicit_ operation.

**Comment by SteelBRS** [comment]
That is quite interesting @scottschurr - thank you for the detailed explanation

**Comment by intelliot** [comment]
Scott is correct. This is also explained the documentation:

> **Note:**
> Since only new transactions can modify the ledger, an expired offer can stay on the ledger after it becomes inactive. The offer is treated as unfunded and has no effect, but it can continue to appear in results (for example, from the [ledger_entry](https://xrpl.org/ledger_entry.html) command). Later on, the expired offer can get finally deleted as a result of another transaction (such as another OfferCreate) if the server finds it while processing.

https://xrpl.org/offers.html#offer-expiration


I believe that resolves this issue. If not, you can open a new issue as needed.
