### ISSUE TITLE
Convert  `boost::optional` usage to `std::optional` as possible

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3433]
## Summary

rippled use boost::optional a ton. Uses of std::optional are starting to creep into the code base because they are required by external libraries. The mixture of these two is not yet a problem, but it will eventually cause confusion and difficulties.

We should convert the usage of `boost::optional` to `std::optional` as part of C++17 enhancements. 

Exported from RIPD-1788

**Comment by scottschurr** [comment]
This can be closed once https://github.com/ripple/rippled/pull/3759 is merged.

**Comment by jesseli2002** [comment]
@scottschurr 
Stumbled across this issue from unrelated search but just pinging to note that this issue can be closed (#3759 was closed by #3792)

**Comment by scottschurr** [comment]
Thanks @jesseli2002! Closed, since https://github.com/ripple/rippled/pull/3759 was merged by https://github.com/ripple/rippled/pull/3792 on March 12, 2021.
