### ISSUE TITLE
Create repositories for latest Ubuntu and Debian versions

### ISSUE THREAD

**Issue by alloyxrp** [ripple/rippled#3457]
Repositories for Ubuntu 20.04 (focal) and Debian 10 (buster) do not exist as of now. New installations may want to use these LTS releases as the base OS.

**Comment by manojsdoshi** [comment]
@alloyxrp we have packages available for both Ubuntu 20.04 (focal) and Debian 10 (buster). We are updating our docs to reflect that.  

**To install nightly builds on focal follow these step:**

apt -y update && apt -y install apt-transport-https ca-certificates wget gnupg
wget -q -O - "https://repos.ripple.com/repos/api/gpg/key/public" | apt-key add -
echo "deb https://repos.ripple.com/repos/rippled-deb focal nightly" | tee -a /etc/apt/sources.list.d/ripple.list
apt -y update && apt -y install rippled


**To install nightly builds on buster follow these step:**

apt -y update && apt -y install apt-transport-https ca-certificates wget gnupg
wget -q -O - "https://repos.ripple.com/repos/api/gpg/key/public" | apt-key add -
echo "deb https://repos.ripple.com/repos/rippled-deb buster nightly" | tee -a /etc/apt/sources.list.d/ripple.list
apt -y update && apt -y install rippled

**Comment by alloyxrp** [comment]
Why nightly? And not stable.

**Comment by manojsdoshi** [comment]
@alloyxrp I believe 1.5 was released before (or in the same timeframe as) Ubuntu 20.04 (focal) so we don't have 1.5 packages for 1.5 it.

**Comment by alloyxrp** [comment]
Thanks. So I presume that stable will be available for 1.6?

**Comment by manojsdoshi** [comment]
Yes, stable will be available for 1.6?

**Comment by alloyxrp** [comment]
Great. However, I don't think it's a good idea to update docs till stable is available.
