### ISSUE TITLE
Allow importing of peer_reservations

### ISSUE THREAD

**Issue by alloyxrp** [ripple/rippled#3464]
The `rippled peer_reservations_list` command can be piped to a JSON file. For large hubs that may need to either reinstall or deploy additional infrastructure, this could run into a significant number of reservations.

Requesting the addition of a complementary command `rippled peer_reservations_import < file.json` . This will greatly ease the work flow on a hub, and eliminate manual addition.

**Comment by MarkusTeufelberger** [comment]
Wouldn't you just set these in the `[ips_fixed]` section in the config file? Or rather: Maybe peer reservations should be added to the config file instead of being defined at runtime? On the other hand, you can just write something with `jq` and `curl` yourself that adds these reservations regularly. Importing them from a file at runtime sounds a bit like an anti-pattern to me.

**Comment by alloyxrp** [comment]
Defining in the config may not be possible, since it would require a restart for every addition. This is mainly of interest to large hubs.  You are correct, it can be done via external code.

**Comment by MarkusTeufelberger** [comment]
Well, you need to/should restart every once in a while anyways. Between restarts you could just enter the peer keys in your config and add them to the online node, so at the next restart it would automatically get applied. A "reload config" functionality would of course be great too, but a restart already is fast and easy enough to do.

**Comment by alloyxrp** [comment]
Of course I do. But restarting a bootstrap pool of hubs is a planned and lengthy process. In excess of 400 peers connect to them. So, I need to have coherent ways of doing it without restarting. And replicating across the servers in the pool.
Anyway, your point is taken, and I will loop and do it externally.

**Comment by alloyxrp** [comment]
Since there seem to be alternative methods which I can pursue, I will close this issue now.
