### ISSUE TITLE
Fail if no unit tests are run when --unittest is specified

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3474]
If rippled is compiled without unit tests, and rippled --unittest is run, the exit code indicates success, and the output is.

0ms, 0 suites, 0 cases, 0 tests total, 0 failures
To prevent this from being overlooked in a CI situation, the exit code should indicate failure. I don't see any need to change the output.

Example: https://travis-ci.org/ximinez/rippled/jobs/159977989#L1006

Exported from RIPD-1296

**Comment by ximinez** [comment]
This also applies when specifying unittest names on the command line. For example:
```
$ rippled --unittest=nope && echo Success
0ms, 0 suites, 0 cases, 0 tests total, 0 failures
Success
```
That should also be a failure.
