### ISSUE TITLE
Site dropped off validators list

### ISSUE THREAD

**Issue by kailu18** [ripple/rippled#3497]
## Issue Description

After network outage, our site dropped off validator list and can not be found from the URL (https://livenet.xrpl.org/network/validators). The server looks running fine, but it has been in a state of "Tracking" since then. 
We also re-validated our site, but our site is still not listed in there. What is the issue? and how to get our site listed in validators list? 

+++
 /opt/ripple/bin/rippled peers
Loading: "/etc/opt/ripple/rippled.cfg"
2020-Jul-08 19:31:33.845034186 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "result" : {
      "cluster" : {},
      "peers" : [
         {
            "address" : "184.173.45.38:51235",
            "complete_ledgers" : "56682839 - 56683095",
            "latency" : 259,
            "ledger" : "46B49FD74DDF584A2501D6357A275028D0A7224DE0729403330C76C35A2CC80B",
            "load" : 272,
            "metrics" : {
               "avg_bps_recv" : "19876",
               "avg_bps_sent" : "13273",
               "total_bytes_recv" : "3713788491",
               "total_bytes_sent" : "1608441967"
            },
            "public_key" : "n9JAeNYjfb1Uzf5RHRpvDbYTvVNgPWiUfPUhdDtakQ1yXJ32n51c",
            "uptime" : 129730,
            "version" : "rippled-1.5.0"
         },
         {
            "address" : "[::ffff:184.173.45.35]:51235",
            "complete_ledgers" : "56682839 - 56683095",
            "latency" : 296,
            "ledger" : "46B49FD74DDF584A2501D6357A275028D0A7224DE0729403330C76C35A2CC80B",
            "load" : 261,
            "metrics" : {
               "avg_bps_recv" : "18677",
               "avg_bps_sent" : "14028",
               "total_bytes_recv" : "2761237942",
               "total_bytes_sent" : "1510772086"
            },
            "public_key" : "n9K6gh1AU85GVEVbL7gph7cYLQmp2mMsEYDhbpn6Tiiapcf6byLV",
            "uptime" : 112903,
            "version" : "rippled-1.6.0-b4"
         },
         {
            "address" : "202.36.220.91:51235",
            "complete_ledgers" : "56681095 - 56683095",
            "latency" : 98,
            "ledger" : "46B49FD74DDF584A2501D6357A275028D0A7224DE0729403330C76C35A2CC80B",
            "load" : 718,
            "metrics" : {
               "avg_bps_recv" : "47433",
               "avg_bps_sent" : "15480",
               "total_bytes_recv" : "6128326282",
               "total_bytes_sent" : "4087847578"
            },
            "public_key" : "n9KtoXy89a6F5ZopaR9SMGx9MT8RprFwehQ7aiL59VdK6oUer8XB",
            "uptime" : 129730,
            "version" : "rippled-1.5.0"
         },
         {
            "address" : "34.214.5.202:51235",
            "complete_ledgers" : "56682839 - 56683095",
            "latency" : 235,
            "ledger" : "46B49FD74DDF584A2501D6357A275028D0A7224DE0729403330C76C35A2CC80B",
            "load" : 239,
            "metrics" : {
               "avg_bps_recv" : "22262",
               "avg_bps_sent" : "13402",
               "total_bytes_recv" : "3780427293",
               "total_bytes_sent" : "1565594064"
            },
            "public_key" : "n9KqRUH5doEcJncjDFsxKj7nmLcjn3RbccaWJvZVzGzQghRBoDnr",
            "uptime" : 129730,
            "version" : "rippled-1.5.0"
         },
         {
            "address" : "202.36.220.90:51235",
            "complete_ledgers" : "56681095 - 56683095",
            "latency" : 99,
            "ledger" : "46B49FD74DDF584A2501D6357A275028D0A7224DE0729403330C76C35A2CC80B",
            "load" : 567,
            "metrics" : {
               "avg_bps_recv" : "55112",
               "avg_bps_sent" : "19255",
               "total_bytes_recv" : "6702799759",
               "total_bytes_sent" : "4084218379"
            },
            "public_key" : "n9MXmaikukRpnBfqQBW91C3y5nw6Kp9GioAkrVbJd9xcKZ83bZJU",
            "uptime" : 129730,
            "version" : "rippled-1.5.0"
         },
         {
            "address" : "198.11.206.6:51235",
            "complete_ledgers" : "56682839 - 56683095",
            "latency" : 252,
            "ledger" : "46B49FD74DDF584A2501D6357A275028D0A7224DE0729403330C76C35A2CC80B",
            "load" : 259,
            "metrics" : {
               "avg_bps_recv" : "21244",
               "avg_bps_sent" : "12520",
               "total_bytes_recv" : "3929409033",
               "total_bytes_sent" : "1598492411"
            },
            "public_key" : "n9MGChK9EgiCBM6s15EwF9d6m4LWZHh1UnJcgr16kQr4xBpx71fS",
            "uptime" : 129730,
            "version" : "rippled-1.6.0-b4"
         },
         {
            "address" : "198.11.206.4:51235",
            "complete_ledgers" : "32570 - 56683095",
            "latency" : 269,
            "ledger" : "46B49FD74DDF584A2501D6357A275028D0A7224DE0729403330C76C35A2CC80B",
            "load" : 210,
            "metrics" : {
               "avg_bps_recv" : "14094",
               "avg_bps_sent" : "14658",
               "total_bytes_recv" : "1807920088",
               "total_bytes_sent" : "1622633261"
            },
            "public_key" : "n9LgvjdEaRM6AtiRX82mzCeqxX2Z9jJiQTqxmLWh3T8iwWNMXPs5",
            "uptime" : 114931,
            "version" : "rippled-1.5.0"
         },
         {
            "address" : "[::ffff:198.11.206.10]:51235",
            "complete_ledgers" : "32570 - 56683095",
            "latency" : 241,
            "ledger" : "46B49FD74DDF584A2501D6357A275028D0A7224DE0729403330C76C35A2CC80B",
            "load" : 243,
            "metrics" : {
               "avg_bps_recv" : "17993",
               "avg_bps_sent" : "13362",
               "total_bytes_recv" : "3144274980",
               "total_bytes_sent" : "1646346808"
            },
            "public_key" : "n9LhQHpv1aFTAW6mVZVyzFDSe8TSS2Sx4zaKjAde8CvScH1Nu9nE",
            "uptime" : 129730,
            "version" : "rippled-1.5.0"
         },
         {
            "address" : "54.202.1.233:51235",
            "complete_ledgers" : "56682839 - 56683095",
            "latency" : 244,
            "ledger" : "46B49FD74DDF584A2501D6357A275028D0A7224DE0729403330C76C35A2CC80B",
            "load" : 245,
            "metrics" : {
               "avg_bps_recv" : "32352",
               "avg_bps_sent" : "12699",
               "total_bytes_recv" : "3713507651",
               "total_bytes_sent" : "1631524089"
            },
            "public_key" : "n9MSA757umjWR9FXUoisWg4urZNW7SzaubptwhutbrbpCn46dRCy",
            "uptime" : 129730,
            "version" : "rippled-1.5.0"
         },
         {
            "address" : "54.203.128.96:51235",
            "complete_ledgers" : "56682839 - 56683095",
            "latency" : 224,
            "ledger" : "46B49FD74DDF584A2501D6357A275028D0A7224DE0729403330C76C35A2CC80B",
            "load" : 252,
            "metrics" : {
               "avg_bps_recv" : "28338",
               "avg_bps_sent" : "12654",
               "total_bytes_recv" : "3957218787",
               "total_bytes_sent" : "1615843037"
            },
            "public_key" : "n9Jdc67V53rXDp47AQEdvZ1nSj6yNLc3iKDMKS5xG36zh1oK1ZNS",
            "uptime" : 129730,
            "version" : "rippled-1.5.0"
         }
      ],
      "status" : "success"
   }
}

**Comment by pwang200** [comment]
Hello @kailu18 Could you please run a server_info RPC (https://xrpl.org/server_info.html) to collect some information of your server?

**Comment by mDuo13** [comment]
The ["tracking" state](https://xrpl.org/rippled-server-states.html) indicates that your server isn't validating. Not sure if something changed about your config or if the server got stuck in some bugged state.

Can you run some troubleshooting steps like using the [info collection script](https://xrpl.org/diagnosing-problems.html#info-collection-script) to get more details? (Since this is a validator, you probably want to check the output for things like IP address before sharing the output of that script.) Alternatively, just the [server_info](https://xrpl.org/server_info.html) would be useful; specifically, I'd look at the server state, the completed ledgers, and the number of transitions in and out of various states.

**Comment by pwang200** [comment]
In addition to the "tracking" state issue, sometimes a validator cannot be reliably seen by the data API used by the validator list site (https://livenet.xrpl.org/network/validators). Because if a validator isn't on an overlay peer's UNL, its validation messages don't get forwarded by this peer. So these messages may or may not reach the rippled node used to monitor the network. This problem should go away after 1.6.0  is released, because all validations messages will be forwarded by default.

**Comment by kailu18** [comment]
Thanks for your reponse. Below is the server info:
+++ 
/opt/ripple/bin/rippled server_state
Loading: "/etc/opt/ripple/rippled.cfg"
2020-Jul-08 21:58:00.450134450 HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "result" : {
      "state" : {
         "amendment_blocked" : true,
         "build_version" : "1.4.0",
         "complete_ledgers" : "56645820-56685330",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time" : 3000,
            "proposers" : 36
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "untrustedValidation",
                  "per_second" : 11
               },
               {
                  "job_type" : "ledgerRequest",
                  "per_second" : 1
               },
               {
                  "job_type" : "untrustedProposal",
                  "per_second" : 39
               },
               {
                  "avg_time" : 4,
                  "job_type" : "ledgerData",
                  "peak_time" : 89,
                  "per_second" : 3
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand",
                  "per_second" : 9
               },
               {
                  "job_type" : "transaction",
                  "per_second" : 9
               },
               {
                  "job_type" : "batch",
                  "peak_time" : 1,
                  "per_second" : 7
               },
               {
                  "job_type" : "advanceLedger",
                  "peak_time" : 10,
                  "per_second" : 7
               },
               {
                  "job_type" : "fetchTxnData",
                  "per_second" : 3
               },
               {
                  "job_type" : "trustedValidation",
                  "peak_time" : 1,
                  "per_second" : 10
               },
               {
                  "job_type" : "writeObjects",
                  "per_second" : 43
               },
               {
                  "job_type" : "trustedProposal",
                  "per_second" : 16
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 819
               },
               {
                  "job_type" : "processTransaction",
                  "per_second" : 9
               },
               {
                  "job_type" : "SyncReadNode",
                  "per_second" : 1096
               },
               {
                  "job_type" : "AsyncReadNode",
                  "per_second" : 3882
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 314
               }
            ],
            "threads" : 6
         },
         "load_base" : 256,
         "load_factor" : 256,
         "load_factor_fee_escalation" : 256,
         "load_factor_fee_queue" : 256,
         "load_factor_fee_reference" : 256,
         "load_factor_server" : 256,
         "peer_disconnects" : "2",
         "peer_disconnects_resources" : "0",
         "peers" : 10,
         "pubkey_node" : "n9LV2mGc4S9pLBbmA6vikP9hUf7X3fciJJ3AhgNEJVg9TDparvDW",
         "pubkey_validator" : "nHUbgDd63HiuP68VRWazKwZRzS61N37K3NbfQaZLhSQ24LGGmjtn",
         "server_state" : "tracking",
         "server_state_duration_us" : "138404263904",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "112382906",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "2169008",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "tracking" : {
               "duration_us" : "138404263904",
               "transitions" : 1
            }
         },
         "time" : "2020-Jul-08 21:58:00.451262",
         "uptime" : 138518,
         "validated_ledger" : {
            "base_fee" : 10,
            "close_time" : 647560680,
            "hash" : "BBD77D3A7BC8D9852E78F1B9C847A3F6C75CCEC7CE43B46DFBC07FCF1C98E9B2",
            "reserve_base" : 20000000,
            "reserve_inc" : 5000000,
            "seq" : 56685330
         },
         "validation_quorum" : 30,
         "validator_list_expires" : 651110400
      },
      "status" : "success"
   }
}

**Comment by kailu18** [comment]
Any ideas how to get the site listed in validator list? any information you need me to provide?

**Comment by pwang200** [comment]
Let's first make sure the server can advance from the "Tracking" state. See the 3rd line in the server_info reply, `"amendment_blocked" : true`? You need to upgrade to the latest stable release (https://xrpl.org/amendments.html#amendment-blocked).

**Comment by kailu18** [comment]
Thanks. The server had been running fine before network outage. It is weird why the state of "amendment_blocked" become true. 
I will upgrade the server from 1.4 to 1.5. Could you please provide how to upgrade? Does the server need to be stopped while upgrading? Does the db need to be backed up (/var/lib/ripple/db)? Will the upgrading overwrite ripple.conf and db files?

**Comment by kailu18** [comment]
The server state is now in a state of "proposing" after upgrading and what should the normal server working state be?
+++ 
/opt/ripple/bin/rippled server_state
Loading: "/etc/opt/ripple/rippled.cfg"
2020-Jul-09 00:39:56.370735966 UTC HTTPClient:NFO Connecting to 127.0.0.1:5005

{
   "result" : {
      "state" : {
         "build_version" : "1.5.0",
         "complete_ledgers" : "56645820-56687805",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time" : 3000,
            "proposers" : 36
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "untrustedValidation",
                  "per_second" : 7
               },
               {
                  "job_type" : "untrustedProposal",
                  "per_second" : 34
               },
               {
                  "avg_time" : 5,
                  "job_type" : "ledgerData",
                  "peak_time" : 116,
                  "per_second" : 1
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand",
                  "per_second" : 10
               },
               {
                  "job_type" : "transaction",
                  "per_second" : 10
               },
               {
                  "job_type" : "batch",
                  "per_second" : 8
               },
               {
                  "job_type" : "advanceLedger",
                  "peak_time" : 12,
                  "per_second" : 3
               },
               {
                  "job_type" : "fetchTxnData",
                  "per_second" : 9
               },
               {
                  "job_type" : "trustedValidation",
                  "per_second" : 5
               },
               {
                  "job_type" : "writeObjects",
                  "per_second" : 798
               },
               {
                  "job_type" : "trustedProposal",
                  "per_second" : 15
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 673
               },
               {
                  "job_type" : "processTransaction",
                  "per_second" : 10
               },
               {
                  "job_type" : "SyncReadNode",
                  "per_second" : 80
               },
               {
                  "job_type" : "AsyncReadNode",
                  "per_second" : 4011
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 3146
               }
            ],
            "threads" : 6
         },
         "load_base" : 256,
         "load_factor" : 256,
         "load_factor_fee_escalation" : 256,
         "load_factor_fee_queue" : 256,
         "load_factor_fee_reference" : 256,
         "load_factor_server" : 256,
         "peer_disconnects" : "0",
         "peer_disconnects_resources" : "0",
         "peers" : 10,
         "pubkey_node" : "n9LV2mGc4S9pLBbmA6vikP9hUf7X3fciJJ3AhgNEJVg9TDparvDW",
         "pubkey_validator" : "nHUbgDd63HiuP68VRWazKwZRzS61N37K3NbfQaZLhSQ24LGGmjtn",
         "server_state" : "proposing",
         "server_state_duration_us" : "1602334657",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "113033052",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "2285963",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "1602334657",
               "transitions" : 1
            },
            "syncing" : {
               "duration_us" : "3048411",
               "transitions" : 1
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : 1
            }
         },
         "time" : "2020-Jul-09 00:39:56.371152 UTC",
         "uptime" : 1720,
         "validated_ledger" : {
            "base_fee" : 10,
            "close_time" : 647570391,
            "hash" : "2AD77CA40D21BBD7B63B58F7C8D62341AADA8758965049F4316630EE61B9DC1F",
            "reserve_base" : 20000000,
            "reserve_inc" : 5000000,
            "seq" : 56687805
         },
         "validation_quorum" : 30,
         "validator_list_expires" : 651110400
      },
      "status" : "success"
   }
}

**Comment by pwang200** [comment]
The "proposing" is the normal operating state of a validator. So it is good. I see "xrp-col.anu.edu.au" in https://livenet.xrpl.org/network/validators. Is it your site?

**Comment by kailu18** [comment]
Yay, it is Thanks guys for helps!!

**Comment by kailu18** [comment]
I noticed that some nodes are in a state of "FULL" and does it mean that it is fully loaded? Is it normal? Also, our server node is still in a state of "Proposing" and should it have a state of "sync"?

**Comment by pwang200** [comment]
Here is the definition of [FULL] (https://github.com/ripple/rippled/blob/7b048b423e8ae08a54018a89231d050b9f562855/src/ripple/app/misc/NetworkOPs.h#L73). Basically, it means the server has the latest ledgers and considered in sync with the network. 

In the state of Proposing means FULL and configured as a validator (and not amendment_blocked etc).

**Comment by kailu18** [comment]
Is there a script for checking if the web site is listed in here (https://livenet.xrpl.org/network/validators)?

**Comment by pwang200** [comment]
@mDuo13 @intelliot , is there such script?

**Comment by nbougalis** [comment]
@kailu18, what do you mean "if the web site is listed in here"? Which website are you referring to? Are you asking if there's a way to see if your **validator** is listed on https://livenet.xrpl.org/network/validators?

**Comment by PacoCotera** [comment]
Related to this, i have a node that if it is not assigned a domain name, it shows up on the validator list, but as soon as I update the domain name, create the TOML file and update the token, it gets dropped of the validator list.

Checking the server info, it is active and proposing in both scenarios, the only difference is non-domain, shows on the validator registry, with domain, it gets dropped off.

**Comment by intelliot** [comment]
This is due to a bug in the ETL that populates the data shown on the Explorer (livenet.xrpl.org). Specifically, when doing manifest signature verification, it fails to consider the Domain field.

@PacoCotera We just deployed a change that may fix the issue. Could you try again?

**Comment by PacoCotera** [comment]
Hi,

Yes, the validator, with the updated manifest with set_domain is back on
the list and tracking the ledger number correctly in real time. The domain
name, however, is not shown

public key: nHU65ddi4kPdNvdbqQMzvtaosAdcrLtSyTrFox9LTyZDFkVEkDU8

**Comment by intelliot** [comment]
This should be fixed here: https://livenet.xrpl.org/network/validators
