### ISSUE TITLE
Improve serialization of the "FeeSettings" ledger node

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3502]
The JSON serialization of the "FeeSettings" ledger node is inconsistent:

```
{
   "BaseFee": "000000000000000A",
   "Flags": 0,
   "LedgerEntryType": "FeeSettings",
   "ReferenceFeeUnits": 10,
   "ReserveBase": 20000000,
   "ReserveIncrement": 5000000,
   "index": "4BC50C9B0D8515D3EAAE1E74B29A95804346C491EE1A95BF25E4AAB854A6A651"
}
```
The BaseFee, ReserveBase, and ReserveIncrement should all be integer strings since they represent XRP.

The ReferenceFeeUnits can stay as a JSON number since it's in fee units, not XRP, so it's limited to 32 bits.

Exported from RIPD-1550

**Comment by movitto** [comment]
This is a duplicate of #3165

**Comment by carlhua** [comment]
Thanks @movitto - closing
