### ISSUE TITLE
account_objects is null in some cases

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3504]
I noticed at least one case where the `account_objects` array in the response to the `account_objects` method is replaced by the value null when it was expected to contain a real value.

```
{
  "id": 17,
  "status": "success",
  "type": "response",
  "result": {
    "account": "rEhw9vD98ZrkY4tZPvkZst5H18RysqFdaB",
    "account_objects": null,
    "ledger_hash": "D96726F81502F5ADDC05FBDFF23C0EBFC5FDBB5639429FC0E6D90BE815818CE2",
    "ledger_index": 1801206,
    "validated": true
  }
}
```
In this case, the same method returns an empty array if the account actually doesn't own anything, but null if the account should own something (a pending, possibly-expired escrow).

Exported from RIPD-1524

**Comment by gregtatcam** [comment]
Created escrow with expiration. `account_objects` returns valid data before and after expiration:
    python3 -c '
    import requests
    import json
    import time
    
    cmd = """
    {
      "method": "submit",
      "params": [{
        "secret": "snoPBrXtMeMyMHUVTgbuqAfg1SUTb",
        "tx_json": {
            "Account": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
            "TransactionType": "Payment",
            "Amount": "400000000",
            "Destination": "rE1KTotoShipZH1LRhbs1EET5rYfhCq8iB"
        }
      }]
    }
    """
    res = requests.post("http://172.1.1.100:5005", json=json.loads(cmd))
    print (res.status_code, res.text)
    
    cmd = """
    {
      "method": "submit",
      "params": [{
        "secret": "snoPBrXtMeMyMHUVTgbuqAfg1SUTb",
        "tx_json": {
            "Account": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
            "TransactionType": "Payment",
            "Amount": "400000000",
            "Destination": "rK8q7vY3o5SGnNZBxz6Tj9kXaJz6bADNRF"
        }
      }]
    }
    """
    res = requests.post("http://172.1.1.100:5005", json=json.loads(cmd))
    print (res.status_code, res.text)
    
    cmd = """
    {
      "method": "submit",
      "params": [{
        "secret": "sswvAWgQZV6XqGNHULaCUWCeQmbYm",
        "tx_json": {
            "Account": "rE1KTotoShipZH1LRhbs1EET5rYfhCq8iB",
            "TransactionType": "EscrowCreate",
            "Amount": "10000",
            "Destination": "rK8q7vY3o5SGnNZBxz6Tj9kXaJz6bADNRF",
            "CancelAfter": %d
        }
      }]
    }
    """ % (time.mktime(time.gmtime()) + 180 - 946684800)
    res = requests.post("http://172.1.1.100:5005", json=json.loads(cmd))
    print (res.status_code, res.text)
    '
Request:

    account="rE1KTotoShipZH1LRhbs1EET5rYfhCq8iB"
    destination="rK8q7vY3o5SGnNZBxz6Tj9kXaJz6bADNRF"
    
    get=$account
    while [ "$1" != "" ]
    do
        if [ "$1" = "--get-by" ]
        then
            shift
            if [ "$1" = "destination" ]
            then
                get=$destination
            fi
        fi
        shift
    done
    
    python3 -c '
    import requests
    import json
    import pprint
    
    cmd = """
    {
      "method": "account_objects",
      "params": [{
        "account": "'$get'",
        "type": "escrow",
        "ledger": "validated"
      }]
    }
    """
    res = requests.post("http://172.1.1.100:5005", json=json.loads(cmd))
    print (res.status_code, pprint.pformat(json.loads(res.text)))'

Return:

    {'result': {'account': 'rE1KTotoShipZH1LRhbs1EET5rYfhCq8iB',
            'account_objects': [{'Account': 'rE1KTotoShipZH1LRhbs1EET5rYfhCq8iB',
                                 'Amount': '10000',
                                 'CancelAfter': 651030038,
                                 'Destination': 'rK8q7vY3o5SGnNZBxz6Tj9kXaJz6bADNRF',
                                 'DestinationNode': '0000000000000000',
                                 'Flags': 0,
                                 'LedgerEntryType': 'Escrow',
                                 'OwnerNode': '0000000000000000',
                                 'PreviousTxnID': '5C72AF4F056BBE73D5A2BB74640B057F994525E0E92505F5E7B8D24B22D42772',
                                 'PreviousTxnLgrSeq': 157,
                                 'index': 'C9CCCA66FA8455912B5C51E55357844D4A05815823094DFD0B88F30E8E2AD43F'}],
            'ledger_hash': '0B904833CFA2C6C2A88A793BE3BB5529DE4531F957F234C9B54687FEB3564351',
            'ledger_index': 1027,
            'status': 'success',
            'validated': True}}
