### ISSUE TITLE
Inconsistency in reported ledger range and the ledgers stored in the database

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3527]
I found a problem extracting a ledger from a client handler--namely, a ledger request for a ledger in the complete_ledgers range came back not found.

Ledger not found: 50336754 when such ledger exists.

Here's the error response (containing the request):
{"error": "lgrNotFound", "error_code": 21, "error_message": "ledgerNotFound", "request":

{"command": "ledger", "expand": true, "ledger_index": 50336754, "transactions": true}
, "status": "error"}

Here are debug.log entries showing instances of that ledger number:

2019-Nov-04 15:57:21.503367549 LedgerConsensus:DBG Entering RippleCalc in payment: CFE8E3495BBB308E513EC2B08649771A891A9CB98E1E52F59AA3D6FC0A694AA6
"ledger_index" : 50336754,
2019-Nov-04 20:08:40.888818959 LedgerMaster:DBG Can't get seq 50336754 from 51176084 past
2019-Nov-04 20:08:40.889575506 Server:DBG Reply: {"result":{"error":"lgrNotFound","error_code":21,"error_message":"ledgerNotFound","request":

{"command":"ledger","expand":true,"ledger_index":50336754,"transactions":true}
,"status":"error"}}
2019-Nov-04 20:08:44.003171829 LedgerMaster:DBG Can't get seq 50336754 from 51176085 past
2019-Nov-04 20:08:44.003526418 LedgerMaster:DBG Ledger 50336754 accepted :F2D617E622ED99ED6AFA27713DCB0760364A86E38CD5C4DA3383D6A803B4C55C
2019-Nov-04 20:08:44.004062404 Ledger:ERR Missing node in 50336754
2019-Nov-04 20:08:44.779820195 LedgerMaster:DBG Ledger 50336754 accepted :F2D617E622ED99ED6AFA27713DCB0760364A86E38CD5C4DA3383D6A803B4C55C
2019-Nov-04 20:08:44.779923001 Ledger:DBG Double pend save for 50336754
2019-Nov-04 20:08:45.934459805 InboundLedger:DBG Done: complete 50336754

online_delete was not running at the time.

The issue is that online_delete and LedgerMaster::setFullLedger can result in discrepancies between the reported ledger range and the ledgers stored in the database.

Exported from RIPD-1767

**Comment by jc0803kevin** [comment]
You can use the server_info command to query whether info.complete_ledgers includes the ledger

**Comment by gregtatcam** [comment]
What are the steps to reproduce this issue?

**Comment by gregtatcam** [comment]
I tested on thin-client-public-usw2-005; complete ledgers: 57017987-57489327. I tried to fetch 1,000 ledgers down from the top ledger and 1,000 ledgers up from the bottom ledger. All worked fine.
