### ISSUE TITLE
[question] how to find if one account's destionaton tag is required

### ISSUE THREAD

**Issue by past2017** [ripple/rippled#3537]
some xrp account's destionation tag is set to required, so how to get this properties by API? then we can notify user if user withdraw to this address without destination tag
![image](https://user-images.githubusercontent.com/25541244/87520528-a81bdd00-c6b5-11ea-8abb-e27d46fa9364.png)

**Comment by MarkusTeufelberger** [comment]
https://xrpl.org/account_info.html --> check the "Flags" --> https://xrpl.org/accountroot.html#accountroot-flags --> `lsfRequireDestTag` (`0x00020000`)

**Comment by carlhua** [comment]
@past2017 does this answer your question? I will close the issue if you have no further questions.

**Comment by past2017** [comment]
got it,thank you
