### ISSUE TITLE
Allow prepublishing of a UNL with a future activation date

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3548]
Validator lists currently take immediate effect; that is, as soon as a list with a sequence number greater than the one presently configured is loaded becomes the authoritative list.

Ideally, a validator list should include a new field, tentatively named effective_date, which specifies when the list's validity period should begin.

Servers should be able to track multiple lists from a single source, each with a different sequence number. Then, as the server operates, the server should use the close time of the last validated ledger to decide whether a list with an effective_date should be activated.

The list format should be augmented to allow multiple lists, each with its own signature, to be contained within a single file.

If multiple lists with different sequence numbers but the same effective_date are retrieved, the server should silently choose the list with the highest sequence number.

If multiple lists with the same sequence number are retrieved but they have different effective_date values, the server should generate a diagnostic at ERROR level and use the list with the earliest effective date.

Exported from RIPD-1660

**Comment by carlhua** [comment]
@ximinez please feel free to update the issue description as needed.

**Comment by MarkusTeufelberger** [comment]
You might want to start looking into using x509 certificates as validator lists with some custom extension to encode the validators contained in that list if you need that many features...
