### ISSUE TITLE
max_transactions (i.e. mempool) should be a config option rather than hardcoded

### ISSUE THREAD

**Issue by RichardAH** [ripple/rippled#3556]
https://github.com/ripple/rippled/blob/7b048b423e8ae08a54018a89231d050b9f562855/src/ripple/overlay/impl/PeerImp.cpp#L1510-L1514

Not sure why this isn't a config option already?

**Comment by nbougalis** [comment]
It probably should be.

I think it'd be fine to have "hard" limits in the code, and allow server operators to adjust "soft" limits within hard limits. For example:

```
/* These may not belong here - having this logic in the config may make more sense */
constexpr int minJQTxCount = 100;
constexpr int maxJQTxCount = 1000;

auto int limit = std::clamp(/* value from config */, minJQTxCount, maxJQTxCount);

if (app_.getJobQueue().getJobCount(jtTRANSACTION) > limit)
```

**Comment by Ghorbanian** [comment]
I would like to work on this issue if no one else is actively working on it.

**Comment by carlhua** [comment]
@Ghorbanian go ahead! Thanks for volunteering!

**Comment by codetsunami** [comment]
> I would like to work on this issue if no one else is actively working on it.

Cool! Easy fix ... should be easy to get a PR accepted. Clamp on new config value as nik suggested.

**Comment by nbougalis** [comment]
I believe this has already been handled by @natenichols in #3562.
