### ISSUE TITLE
[Node dropped from validator list after set_domain and token update] (Version: [1.6.0])

### ISSUE THREAD

**Issue by PacoCotera** [ripple/rippled#3592]
## Issue Description
A properly working validation node is dropped off the validators list after setting the domain and updating the token, after restart it still conencts to the livenet, is in proposing status, connected to peers, but not shown on any validator list.

## Steps to Reproduce
Have an existing validating node, in proposing status and shown on validator lists at XRPL network explorer and validator registry at xrpcharts.

Use validator-keys set_domain, get a new token, update the rippled.cfg, update the TOML file, submit domain verification request, restart the node.

Domain is dropped off the validator list, even after receiving domain validation success.

## Expected Result
Working validator node shown along domain in validator list.

## Actual Result
Working validator node dropped off the validator list.

## Environment
Ubuntu 18.04, Rippled 1.6.0, same behavior un 1.5.0

**Comment by MarkusTeufelberger** [comment]
Could you explain which "list" you are looking at and where you submitted your "domain verification request"? Could be just a display issue at that list's operator...

**Comment by PacoCotera** [comment]
It happens on the two validator lists that I'm aware of:

1) https://xrpcharts.ripple.com/#/validators
2) https://livenet.xrpl.org/network/validators

And as per the instructions on: https://xrpl.org/run-rippled-as-a-validator.html#6-provide-domain-verification

here is the Google Form for the inclusion on ripple.com validator registry 

https://docs.google.com/forms/d/e/1FAIpQLScszfq7rRLAfArSZtvitCyl-VFA9cNcdnXLFjURsdCQ3gHW7w/viewform

**Comment by nbougalis** [comment]
This is a known issue with the manifest processing code. We've identified a fix and it will be deployed soon.

**Comment by intelliot** [comment]
@PacoCotera Could you try this again? We've deployed an update that should fix this issue.

**Comment by PacoCotera** [comment]
Hi,

It partially works.

The webpage for the validator now shows the domain name. But stats for the validations are not present neither on this page or on the validator list. 

https://xrpcharts.ripple.com/#/validators/nHUfExi5maUJk5os6aRsbMFv37PyycQ5sVf4AMqTnLJMGPEsyjQo

![image](https://user-images.githubusercontent.com/19177310/103935039-9a3a9800-50eb-11eb-97e9-2da2ccf79637.png)


Validator status is proposing:

![image](https://user-images.githubusercontent.com/19177310/103935136-bdfdde00-50eb-11eb-97aa-6c5b1f9ece79.png)

**Comment by intelliot** [comment]
@PacoCotera Is your validator still running? It normally takes about 1-2 days for historical data to start showing on the validator page.

**Comment by mayurbhandary** [comment]
@PacoCotera, could you please paste your latest manifest? You can find this by using the manifest command and entering your validator's public key as the parameter. Please try the following on your validator: 
```
curl --location --request POST 'localhost:5005' \
--header 'Content-Type: application/json' \
--data-raw '{
    "method": "manifest",
    "params": [{
        "public_key": "nHUfExi5maUJk5os6aRsbMFv37PyycQ5sVf4AMqTnLJMGPEsyjQo"
    }]
}'
```

You can replace 5005 with your rpc admin port (5005 is the default listed under port_rpc_admin_local in the config file). I have put your validator's public key in the `public_key` parameter.

**Comment by granuz88** [comment]
Hi all,

I have the same issue. When I set the domain name and changed the token on the rippled.cfg file, the validator disappeared from the public validator list.
Is still proposing ad It is online.
Domain: xrpvalidator.ftso.eu
Public Key: nHBdXSF6YHAHSZUk7rvox6jwbvvyqBnsWGcewBtq8x1XuH6KXKXr
If I check the TOML and the domain using the tools provided on xrpl.org, the results are fine and it is all "green".

I try to run this command:

```
curl --location --request POST 'localhost:5005' \
--header 'Content-Type: application/json' \
--data-raw '{
    "method": "manifest",
    "params": [{
        "public_key": "nHBdXSF6YHAHSZUk7rvox6jwbvvyqBnsWGcewBtq8x1XuH6KXKXr"
    }]
}'
```

And this is the output:

{"result":{"details":{"domain":"xrpvalidator.ftso.eu","ephemeral_key":"n9MfeCuZK2ra5eJtFDtuCTnvxfsi85k4J3GXJ1TvRVr2o4EQeHMF","master_key":"nHBdXSF6YHAHSZUk7rvox6jwbvvyqBnsWGcewBtq8x1XuH6KXKXr","seq":2},"manifest":"JAAAAAJxIe0kh8AnrrWSIR31ZHToQaraDB9PBijoBO6fEuxOfFUZuXMhA1KqzeMXFIgOfqY2d+J7qzq24oruATCkmopCUMGJOEBldkYwRAIgCwa3VLJb/Dzkb2vyX/Z+uTQJU3P+KdCjagwKSLEguj4CIF00+9ztyp3KgV7MQmAi+nogs4f8rPbcG3SQAktWmscodxR4cnB2YWxpZGF0b3IuZnRzby5ldXASQJ4IcwxDN69Q4mkjemSlFX+mrNhsITvmeTyEP4f5E6WcE1u/WlDNCdqs/RDTG98eqyJE6MGUB76Qnxqb8Zi71QU=","requested":"nHBdXSF6YHAHSZUk7rvox6jwbvvyqBnsWGcewBtq8x1XuH6KXKXr","status":"success"}}

Thank you!

**Comment by mayurbhandary** [comment]
Hi @granuz88  and @PacoCotera. It seems the issue is that the validator list sites [subscribe](https://xrpl.org/subscribe.html#validations-stream) to the 'manifests' stream from rippled, but the manifests on those streams do not include the domain. A PR has been created in the rippled repo to resolve this issue: https://github.com/ripple/rippled/pull/3722/files.

**Comment by intelliot** [comment]
This should now be fixed: https://livenet.xrpl.org/network/validators
