### ISSUE TITLE
Implement Ledger RPC via gRPC

### ISSUE THREAD

**Issue by cjcobb23** [ripple/rippled#3596]
The gRPC API is supposed to provide a minimal, yet useful subset of the JSON API. As of the time of writing, gRPC supports `fee`, `submit`, `account_info`, `tx` and `account_tx`. These methods cover many use cases. However, the gRPC API is missing `ledger`, which is one of the most used (and most useful) RPCs; it's absence is particularly cumbersome for anyone using the gRPC API.

Implementing `ledger` via gRPC is rather straightforward. All of the transaction types are represented in protobuf. This mainly requires defining the ledger header via protobuf messages, writing the new gRPC handler, and calling it from `GRPCServer`. Take care to abstract common logic into helper functions and not duplicate code between the gRPC and JSON handlers for `ledger`.

**Comment by cjcobb23** [comment]
There is a version of this implemented as part of the reporting PR: https://github.com/ripple/rippled/pull/3609/files#diff-a14f409d58f17d81bc625cf5ba02a1c6
The response is binary only though

**Comment by scottschurr** [comment]
My understanding is that we're moving away from gRPC in rippled.  Should we close this issue?

**Comment by yxxyun** [comment]
> My understanding is that we're **moving away from gRPC** in rippled. Should we close this issue?

why?

**Comment by cjcobb23** [comment]
I don't think this should be closed right now. We have not yet decided the fate of gRPC in rippled. gRPC needs to stay in rippled at the moment because reporting mode uses certain gRPC methods to extract data. Also, the gRPC handlers may be moved (instead of deleted) as part of the RPC decoupling effort, in which case we would want the ledger command. And lastly, the ledger command was actually partially implemented as part of the reporting mode project. It wouldn't be too hard to flesh out the full functionality.

I think this issue should stay open, though I would encourage anyone who wishes to work on it to first reach out to the team.

**Comment by cjcobb23** [comment]
I think this issue should be closed now. The binary version of the ledger RPC used by reporting mode and clio will stay in rippled for some time, but I do not think we should flesh it out fully to be compliant with the JSON API.
