### ISSUE TITLE
Rename currency field to something more generic.

### ISSUE THREAD

**Issue by gmosx** [ripple/rippled#36]
Please consider renaming the field 'currency' within a transaction message

      'Amount' : { 
         'currency' : 'USD',
         'value' : '1',
         'issuer' : 'r3kmLJN5D28dHuH8vZNUZpMC43pEHpaocV'
      }

to something more generic, like *resource*, object, etc. AFAIU ripple could support non-currency *resources*/assets/instruments/whatever.

**Comment by rec** [comment]
We won't be fixing this, it's too ensconced...
