### ISSUE TITLE
rippled.cfg [amendments] stanza does not behave as documented (Version: 1.6.0)

### ISSUE THREAD

**Issue by intelliot** [ripple/rippled#3605]
## Issue Description

In the config file `rippled.cfg` the `[amendments]` stanza does not behave as documented.

The [documentation](https://xrpl.org/amendments.html#configuring-amendment-voting) says: "Use the [amendments] stanza to list amendments you want to vote for."

But the code says: "Use the [amendments] stanza to set the amendments that are considered to be already enabled."

From `./src/ripple/app/misc/impl/AmendmentTable.cpp`:

```
    for (auto const& a : parseSection(enabled))
    {
        if (auto s = add(a.first, sl))
        {
            JLOG(j_.debug()) << "Amendment " << a.first << " is enabled.";

            if (!a.second.empty())
                s->name = a.second;

            s->supported = true;
            s->enabled = true;
        }
    }
```

It seems like putting an amendment in the [amendments] stanza might actually prevent your server from voting for it (because your server will think that it is already enabled).

Or is there something that checks that the "enabled" amendments are not in conflict with the amendments that the ledger says are enabled?

In my opinion, the documentation describes the intended/expected behavior. The current behavior (if it's what I think it is) is a bug and should be fixed.

## Steps to Reproduce

Add/use the [amendments] stanza in rippled.cfg

## Expected Result

Per the docs, the server should vote in favor of the amendments listed

## Actual Result

Based on a reading of the code, it appears that the server will assume that the amendments listed are already enabled

## Environment

Any version of rippled including 1.6.0 (latest stable) and 1.7.0-b1

**Comment by ximinez** [comment]
The `[amendments]` stanza was effectively rendered obsolete by https://github.com/ripple/rippled/pull/3617, which was included in 1.7.0-b9 (https://github.com/ripple/rippled/pull/3708), so that makes this issue irrelevant.
