### ISSUE TITLE
Move manifest API call to the public API

### ISSUE THREAD

**Issue by tlongwell-ripple** [ripple/rippled#3611]
## Summary
Move the Manifest call (https://xrpl.org/manifest.html) from the admin API to the public API

## Motivation
This endpoint is used by the XRPL Explorer application. By moving the Manifest endpoint to the public API, it will be easier and safer to run the explorer since it will not require admin API access to a rippled node.

**Comment by intelliot** [comment]
Done in rippled 1.7.0-b2 https://github.com/ripple/rippled/pull/3612
