### ISSUE TITLE
[Title with short description] (Version: [rippled version])

### ISSUE THREAD

**Issue by fredbuluku** [ripple/rippled#3622]
## Issue Description
try to support people from African countries they are lacking facilities to support their efforts to be effective.Also security system maybe a challenge try to simplify things to the users to fix the security and the problems that are affecting them.

Thanks.

**Comment by nbougalis** [comment]
@fredbuluku: thanks for your message.

>try to support people from African countries they are lacking facilities to support their efforts to be effective.

I'm sure I speak on behalf of _everyone_ in the ecosystem when I say that you should outline any ideas you have that can help make the XRP Ledger a better tool to promote financial inclusion and make the world's financial system more accessible to everyone.

However, as important as this conversation is, I don't know that the issue tracker for `rippled` is the right place for this conversation.

May I recommend posting more about this on xrpchat.com to help kickstart a discussion?
