### ISSUE TITLE
Compression handshake is not handled correctly (Version: 1.7.0-b2)

### ISSUE THREAD

**Issue by gregtatcam** [ripple/rippled#3624]
## Issue Description
If an outbound node has compression enabled and an inbound node does not have compression enabled then the inbound node enabled link compression. 

## Steps to Reproduce
Run two nodes. Set compression to enabled in one node's configuration and disabled in another node's configuration.
[compression]
0|1 

## Expected Result
Both nodes should flag the link compression disabled.

## Actual Result
If the outbound node has the compression enabled and the inbound node has the compression disabled then the inbound node is forced into setting the compression flag as enabled. The outbound node consequently drops the connection in this case because the outbound node expects the uncompressed data but the inbound node sends compressed data due to incorrectly set flag.

## Environment
Ubuntu 20.04 with Boost 1.70
Release 1.7.0-b2

## Supporting Files
compressionEnabled_ flag should include additional condition `app_.config().COMPRESSION` in https://github.com/ripple/rippled/blob/develop/src/ripple/overlay/impl/PeerImp.cpp#L94 the same as in 
https://github.com/ripple/rippled/blob/develop/src/ripple/overlay/impl/PeerImp.h#L644

**Comment by mDuo13** [comment]
Done in 1.7.0-b9 #3708
