### ISSUE TITLE
trust line QualityIn in uncontroled (Version: 1.6.0)

### ISSUE THREAD

**Issue by maybeTomorrow** [ripple/rippled#3625]
## Summary
i suggest to remove this function

## Motivation
for example ,i want to pay 200 USD to address B,but B set QualityIn=0.5,then i actually pay 400USD to B

**Comment by MarkusTeufelberger** [comment]
This is intended behavior, how else do you suggest to deal with the problem that some issuances in the same denomination might be worth less to you than others?

**Comment by maybeTomorrow** [comment]
worth is same to one issuer，i think QualityIn should be use in diffrent issuer,(rippling)

**Comment by MarkusTeufelberger** [comment]
No, for example 1 BTC issued by MtGox are worth only 0.02 BTC to me, regardless of the existence of other issuers.

**Comment by mDuo13** [comment]
You can only end up sending 400 USD to B if your `SendMax` allows it. This is expected behavior, and you should set `SendMax` accordingly.

**Comment by maybeTomorrow** [comment]
for example 1 BTC issued by MtGox ,1 BTC can exchange 10 apple in MtGox's store,what ever a or b got 1 BTC
