### ISSUE TITLE
Shutdown and confusing errors when switching shard settings from NuDB to RocksDB

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3635]
I changed my shard store settings to switch to RocksDB, hoping this would stop the LoadMonitor warnings I was getting.
```
[shard_db]
type=NuDB
path=/another/devel/rippled/db/shards/
max_size_gb=4
```

After:
```
[shard_db]
type=RocksDB
path=/another/devel/rippled/db/shards/
max_size_gb=4
```

(The only thing I changed was the type field.)

After making this change, I tried to start rippled from the commandline. It launched several children, but ultimately all the processes ended and I was left without a rippled process running. The console included the following message, which (strangely) I haven't been able to find in the debug.log. I've uploaded an excerpt from my debug.log approximately covering this time. The abrupt ending after the log_level response is accurate to where it was when I experienced the problem: [debug_copy.log](https://github.com/ripple/rippled/files/5384932/debug_copy.log)

```
ShardStore:ERR shard 504 error: Unable to open/create RocksDB: Invalid argument: 
/another/devel/rippled/db/shards/504: does not exist (create_if_missing is false)
```

Meanwhile, in the folder from that message, I found a series of "LOG" files such as the one attached: [LOG.log](https://github.com/ripple/rippled/files/5384937/LOG.log)

I was able to get rippled to start by changing the path in the [shard_db] config to a new path. Basically, I think what was happening was it was looking at the shards I had (possibly incompletely) downloaded with NuDB and was trying to open them with RocksDB, which caused all rippled threads to shut down.

I think the server should output something clearer to the debug.log, possibly alerting the user to the log files in the shard store folders. Maybe there are some other sensible changes to make so that RocksDB and NuDB shards can live side-by-side, or maybe we should just be clear about documenting that if you change DB types in your config, you should change the path or delete the existing shards.

Exported from RIPD-1651

**Comment by mDuo13** [comment]
Now that the shard store no longer supports RocksDB, this is no longer relevant. Closing.
(I was the reporter of the original issue.)
