### ISSUE TITLE
source build got a large exec file(Version: 1.6)

### ISSUE THREAD

**Issue by maybeTomorrow** [ripple/rippled#3651]
when i build from source,i got a 800+MB exec file,but i see it's only 44mb by install from yum(centos)

**Comment by maybeTomorrow** [comment]
by yum ,ldd rippled 
	linux-vdso.so.1 =>  (0x00007ffe735c7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f912979c000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f9129594000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f912937e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f912917a000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9128e78000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9128c62000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9128894000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f91299b8000)


build self,
        linux-vdso.so.1 =>  (0x00007fff1e933000)
	libprotobuf.so.23 => not found
	libboost_coroutine.so.1.70.0 => not found
	libboost_filesystem.so.1.70.0 => not found
	libboost_program_options.so.1.70.0 => not found
	libboost_regex.so.1.70.0 => not found
	libboost_thread.so.1.70.0 => not found
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f3261183000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f3260f7b000)
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => not found
	libz.so.1 => /lib64/libz.so.1 (0x00007f3260d65000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f3260a5e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f326075c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f3260546000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f326032a000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f325ff5c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3263d96000)

**Comment by MarkusTeufelberger** [comment]
Maybe you did a debug build?

**Comment by maybeTomorrow** [comment]
i commond cmake -DCMAKE_BUILD_TYPE= Release ..

**Comment by nbougalis** [comment]
I believe the default is to make a **static** build, which would explain this.

**Comment by nbougalis** [comment]
@maybeTomorrow: have you been able to produce a smaller binary file? If so, could we close this issue?
