### ISSUE TITLE
`std::shared_mutex` may be buggy on ubuntu 18.04 and earlier

### ISSUE THREAD

**Issue by seelabs** [ripple/rippled#3663]
## Issue Description
According to this thread, there's a bug in glibc that can cause threads using std::shared_mutex to stall. (ref: https://www.reddit.com/r/cpp/comments/jsynzn/stdshared_mutex_was_broken_in_glibc230_distros/). The referenced bug in glibc is here: https://sourceware.org/bugzilla/show_bug.cgi?id=23861). This effects ubuntu 18.04, but not 20.04. We do make use of these locks in rippled (tho not extensively). We might want to look at replacing those locks with boost equivalents (according to that thead they are not, but we should confirm).

**Comment by HowardHinnant** [comment]
I've confirmed that `boost::shared_mutex` does not have this bug.  PR to switch to `boost::shared_mutex` is imminent.
