### ISSUE TITLE
how can i pause rippled when no transaction in(Version: 1.6)

### ISSUE THREAD

**Issue by maybeTomorrow** [ripple/rippled#3681]
The block height is growing too fast, but there is no transaction submission

**Comment by mDuo13** [comment]
I don't understand the question. If the question is how to stop the server when you're not actively using it, you can use `systemd` on supported distributions:

```
sudo systemctl stop rippled.service
```

(The `.service` part is optional; if you leave it off, systemd will _probably_ still figure out which thing you're talking about.)

To start the server again later when you want to use it again:

```
sudo systemctl start rippled.service
```

After this command, you'll have to wait for the server to sync back up (typically 5–15 minutes from a cold start).

**Comment by maybeTomorrow** [comment]
i hope  auto start service when transaction  submit

**Comment by maybeTomorrow** [comment]
i mean such as ethereum  miner.stop()

**Comment by nbougalis** [comment]
There's no mechanism in the code to achieve that: note that the XRPL does not use mining, and so resource usage should be minimal.

Please note that unless you are an exchange or other business that has specific requirements, you don't necessarily even need to run a server. You can rely on publicly accessible endpoints, like [**xrpl.ws**](https://xrpl.ws/) which is a great high-availability service that is available gratis.

**Comment by nbougalis** [comment]
@maybeTomorrow: can we close this issue?
