### ISSUE TITLE
Question: ModifiedNode -- why no Offer modifications?

### ISSUE THREAD

**Issue by ottcsconsult** [ripple/rippled#3688]
Sorry, this doesn't quite fit into the Bug Report or Feature Request categories.

Please entertain my issue and consider this scenario:

1. Account A places an offer: Buy 10 USD for 15 XRP.
2. The offer isn't immediately matched, so it becomes a ledger object.
3. Account B places an offer that is matched with Account A's offer. Account B buys 7.5 XRP for 5 USD.
4. Account A's offer is still a ledger object, now asking to buy 5 USD for 7.5 XRP.
5. Account C takes the remaining 7.5 XRP for 5 USD. The offer is now cancelled and no longer a ledger object.

My understanding is that step 2 creates on offer on the ledger and step 5 deletes the offer. Steps 3/4 modify the offer, but based on my understanding of the XRP ledger, this is not reflected in the transaction meta. There is no ModifiedNode for LedgerEntryType "Offer". AccountRoot gets modified when an offer is taken partially, but if there are multiple partial takes, then, it appears impossible (?) to figure out which offer was partially taken.

Questions:
(1) Why no ModifiedNode for offers?
(2) How can partial fills of offers be tracked based on ledger transactions?

**Comment by MarkusTeufelberger** [comment]
Do you have an example transaction for 3 or 4 (ideally on mainnet)?

**Comment by ottcsconsult** [comment]
I'm sorry. I think I misread the ledger information. I tested again and I now do see ModifiedNode entries with LedgerEntryType = "Offer". Sorry about the false alert.

**Comment by ximinez** [comment]
No problem. Glad you were able to resolve your issue!
