### ISSUE TITLE
tfClearNoRipple  does'nt work (Version: 1.6.0)

### ISSUE THREAD

**Issue by maybeTomorrow** [ripple/rippled#3715]
tx_json: 
   { Account: 'rf5Rdie79SdpRgF4gQv5ayatoqYufrVrSb',
     Fee: '0',
     Flags: 262144,
     LastLedgerSequence: 1239744,
     LimitAmount: 
      { currency: 'EKB',
        issuer: 'rLCparvg3CQJCrwYYRfEqmuBScoqLkBSt8',
        value: '1000000000' },
     Sequence: 1237799,
     SigningPubKey: '0242BBAF0D805001F7D330ADCE8040F927C76BA3A0A7036881474A30182FDC9853',
     TransactionType: 'TrustSet',
     TxnSignature: '304402206528F289A3C3F3AC03B7B9A24F2D54BF27A6F98F5AA9EEDDD38556B7E2A16AF5022050018A04AAE884B539041502302E4BC6B5B8CE14EFC310142DB7B28A36501A1B',
     hash: 'DD07C4BD1A307E2642CFCADC3F2624B329F8E2A01C38B24A1D221A5DD3545BA1' } }

truestline rf5Rdie79SdpRgF4gQv5ayatoqYufrVrSb [ { specification: 
     { limit: '1000000000',
       currency: 'EKB',
       counterparty: 'rLCparvg3CQJCrwYYRfEqmuBScoqLkBSt8' },
    counterparty: { limit: '0', ripplingDisabled: true },
    state: { balance: '0' } } ]

ripplingDisabled still show true

**Comment by maybeTomorrow** [comment]
some one help

**Comment by maybeTomorrow** [comment]
{ type: 'trustline',
  address: 'rhEjhs4Xq1VjCJM6THkWuYdeDZdt1pHvQ2',
  sequence: 7,
  id: '5107A2877136BC8478EFA5A237685D64D2B8EDAD901C85415EAD87FBD116681E',
  specification: 
   { limit: '1000000000',
     currency: 'NEC',
     counterparty: 'rhWmiZUid9489WVLBYyrje1FmpMkR5VuPk',
     ripplingDisabled: false },
  outcome: 
   { result: 'tesSUCCESS',
     timestamp: '2020-12-29T03:46:00.000Z',
     fee: '0.000012',
     balanceChanges: { rhEjhs4Xq1VjCJM6THkWuYdeDZdt1pHvQ2: [Array] },
     orderbookChanges: {},
     ledgerVersion: 6,
     indexInLedger: 0 } }

truestline rhEjhs4Xq1VjCJM6THkWuYdeDZdt1pHvQ2 [ { specification: 
     { limit: '999999',
       currency: 'CMC',
       counterparty: 'rhWmiZUid9489WVLBYyrje1FmpMkR5VuPk' },
    counterparty: { limit: '0', ripplingDisabled: true },
    state: { balance: '0' } },
  { specification: 
     { limit: '1000000000',
       currency: 'NEC',
       counterparty: 'rhWmiZUid9489WVLBYyrje1FmpMkR5VuPk' },
    counterparty: { limit: '0', ripplingDisabled: true },
    state: { balance: '0' } } ]

**Comment by nbougalis** [comment]
Hi @maybeTomorrow. I'm a bit confused at what you're asking. I can't see the accounts you specify either on the mainnet or the testnet. Can you show the transaction you're attempting to execute (on the testnet or the mainnet) please? If you cannot, maybe you could show the state of trust line _before_ and _after_ the execution of the transaction.

**Comment by nbougalis** [comment]
Hi @maybeTomorrow. Just pinging you about this issue.

**Comment by maybeTomorrow** [comment]
it's a private network,i resolved
