### ISSUE TITLE
One of the IP in S1 cluster is not working

### ISSUE THREAD

**Issue by anhcao142** [ripple/rippled#3748]
## Issue Description
Get this error: `connect ETIMEDOUT 52.43.100.200:51234` when using s1 cluster node `https://s1.ripple.com:51234/`. This happens quite a lot so can you take a look.

## Steps to Reproduce
You can try ping the IP:
```bash
curl -L -X POST '52.43.100.200:51234/' \
-H 'Content-Type: application/json' \
--data-raw '{
    "method": "ping",
    "params": [
        {
        }
    ]
}'
```

**Comment by cjcobb23** [comment]
Where did you get the ip `52.43.100.200` from?

**Comment by anhcao142** [comment]
Hi, this is the reproduce code. I believe that the error is thrown by `jayson`

```javascript
const jayson = require('jayson');
const Promise = require('bluebird');

async function getLedger(ledgerIndex) {
  const rpc = Promise.promisifyAll(jayson.client.https('https://s1.ripple.com:51234/'))
  const params = [{ ledger_index: ledgerIndex }];
  return (await rpc.requestAsync('ledger', params)).result;
}

getLedger('validated').catch(console.err);

// Log
// Error: connect ETIMEDOUT 52.43.100.200:51234
```

**Comment by nbougalis** [comment]
Appreciate the report; while this is not the correct place to report issues with the cluster of servers operated by Ripple, I will pass this on to the team that maintains/operates the cluster and the DNS zone files.

**Comment by anhcao142** [comment]
Hi, I have switched to the `https://xrpl.ws` node, so far I haven't encountered this error anymore. I will close this now since I can no longer report the error if it happens again.
