### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by tuloski** [ripple/rippled#3783]
I'm trying to update manually on ubuntu to 1.7 and there is a problem with GPG verification.
This happens:

An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repos.ripple.com/repos/rippled-deb xenial InRelease: The following signatures were invalid: KEYEXPIRED 1613256551  KEYEXPIRED 1613256551  KEYEXPIRED 1613256551
W: Failed to fetch https://repos.ripple.com/repos/rippled-deb/dists/xenial/InRelease  The following signatures were invalid: KEYEXPIRED 1613256551  KEYEXPIRED 1613256551  KEYEXPIRED 1613256551

**Comment by carlhua** [comment]
Hi @tuloski , we have extended our GPG Key, can you try following the instructions here to see if this fixes your issue (under Upgrading section).

https://xrpl.org/blog/2021/rippled-1.7.0.html

**Comment by tuloski** [comment]
That worked. Thanks.
