### ISSUE TITLE
Include new validation fields in subscription stream

### ISSUE THREAD

**Issue by wilsonianb** [ripple/rippled#3797]
## Summary
Include recently added validation fields in validations subscription stream messages:
- version
- cookie
- validated hash

## Motivation

>This information is useful for server operators, for developing who are putting together dashboards, and the community at large.

https://github.com/ripple/rippled/pull/3291#issue-385416706

## Solution

Add fields to [`pubValidation`](https://github.com/ripple/rippled/blob/9d89d4c1885e13e3c0aa7cdb4a389c6fbfd3790a/src/ripple/app/misc/NetworkOPs.cpp#L2081)

**Comment by nbougalis** [comment]
Yeah, those should have been added already. If anyone wants to tackle this, they're welcome to.
