### ISSUE TITLE
gpg: no valid OpenPGP data found

### ISSUE THREAD

**Issue by debragail** [ripple/rippled#3798]
## Issue Description
wget -q -O - "https://repos.ripple.com/repos/api/gpg/key/public" | \
    sudo apt-key add -

gpg: no valid OpenPGP data found.

## Steps to Reproduce
stuck at wget and apt-key add step of installing rippled

## Expected Result
GPG Key should be added

## Actual Result
gpg error

## Environment
Digital Ocean Droplet
16 GB Memory / 8 Intel vCPUs / 320 GB Disk / SFO3 - Ubuntu 20.04 (LTS) x64

**Comment by nbougalis** [comment]
I _just_ checked and the data I received seems reasonable. Please make sure you're typing everything on a single line:

```
wget -q -O - "https://repos.ripple.com/repos/api/gpg/key/public" | sudo apt-key add -
```

**Comment by nbougalis** [comment]
Is this still an issue @debragail, or can we close this issue?

**Comment by debragail** [comment]
@nbougalis I paused the project but if it occurs again i will reference this issue
