### ISSUE TITLE
validator server certificate expired (TESTNET) (Version: 1.7.0-1)

### ISSUE THREAD

**Issue by bert2002** [ripple/rippled#3836]
## Issue Description
Validator server certificate expired

## Logs

```
2021-May-03 10:22:25.375750503 UTC ValidatorSite:WRN Outbound SSL connection to vl.altnet.rippletest.net fails certificate verification
2021-May-03 10:22:25.375917766 UTC ValidatorSite:WRN Problem retrieving from https://vl.altnet.rippletest.net 65.9.109.56:443 337047686:certificate verify failed
2021-May-03 10:22:25.898967700 UTC NetworkOPs:WRN Node count (0) has fallen below required minimum (1).
```
Hi,
it seems the validator certificate expired on testnet and cannot sync with the network anymore. 

Thanks,
bert

**Comment by intelliot** [comment]
This has now been fixed. We missed this endpoint when updating the SSL cert last week. We reimported the cert, and it's now serving.

@bert2002 thank you for reporting this issue.
