### ISSUE TITLE
Can't install rippled since boost via Bintray is unavailable - 403: Forbidden (Version: 1.7.0)

### ISSUE THREAD

**Issue by alexsmith84** [ripple/rippled#3852]
## Issue Description
Can't install rippled due to failing step in the installation process.
Following the [installation instructions](https://xrpl.org/build-run-rippled-ubuntu.html) for rippled, step 5.1. Installing boost fails with a 403: Forbidden error.

## Steps to Reproduce
Attempt to install rippled via the instructions listed on the xrpl.org website linked above.

## Expected Result
Being able to install rippled on Ubuntu.

## Actual Result
Can't install rippled on Ubuntu.

## Environment
Ubuntu 20.04.2 LTS

## Supporting Files
n/a

**Comment by alloynetworks** [comment]
https://lists.boost.org/Archives/boost//2021/04/251468.php
Boost download locations seem to have changed since bintray is offline from May 1.
Thanks for noticing, will update docs to reflect this.

**Comment by legleux** [comment]
Fixed in https://github.com/ripple/xrpl-dev-portal/pull/1084
