### ISSUE TITLE
Issue an asset

### ISSUE THREAD

**Issue by will-yijinin** [ripple/rippled#3871]
## Summary

https://developers.ripple.com/issued-currencies.html

This link has word explanations but no code example. I tried to follow the instructions to issue an asset to no avail. Below are my code:
```
    // Submit a transaction to set the DefaultRipple flag on the account
    // https://xrpl.org/accountset.html
    const txnObj = {
        "TransactionType": "AccountSet",
        "Account": from,
        "Fee": "15",
        "Flags": 0,
        "SetFlag": 8,
        "Sequence": sequence,
    };
    const setFlagBool = await signAndSend(txnObj);
    
    // Choose a three-character code for your asset

    // Set up a trust link between two accounts
    // https://xrpl.org/trustset.html
    const trustTxnObj = {
        "TransactionType": "TrustSet",
        "Account": to,
        "Fee": "12",
        "Flags": 262144,
        "LimitAmount": {
          "currency": "TST",
          "issuer": from,
          "value": "10000"
        },
        "Sequence": sequence
    };
    const setTrustLinkBool = await signAndSend(trustTxnObj);

    // To issue your asset to people just use a Payment transaction
    const assetTxnObj = {
        TransactionType: 'Payment',
        Account: from,
        Destination: to,
        DestinationTag: tag ? Number(tag) : 0,
        Amount: {
            "currency" : "TST",
            "value" : "1",
            "issuer" : from
        },
        Fee: fee,
        Sequence: sequence,
        SigningPubKey: publicKey,
    };
    const issueAssetBool = await signAndSend(assetTxnObj);
```
The first two transactions returned "RippledError: invalidTransaction". The third just hang. What is the correct way?

## Motivation

So developers can easily test this feature.

**Comment by MarkusTeufelberger** [comment]
This seems to be JavaScript using (maybe?) ripple-lib and seems to miss quite a few steps (like setting up your key pair).

Probably this should be raised in https://github.com/ripple/xrpl-dev-portal - it doesn't seem to concern `rippled` and also there's no API of `rippled` used directly in the code given, only abstractions.

**Comment by mDuo13** [comment]
I think you're looking for this tutorial:

https://xrpl.org/issue-a-fungible-token.html

If not, feel free to reopen.
