### ISSUE TITLE
Unity files keep getting rebuilt (Version: rippled develop branch checkout)

### ISSUE THREAD

**Issue by guidovranken** [ripple/rippled#3885]
## Issue Description

All the `unity_*_cxx.cxx.o` keep getting built anew after they've been built already.

The reason for this is that in the build step for `soci`, the `include/soci/unsigned-types.h` file is patched. This leads the build script to believe that a dependency (`soci`, in particular `include/soci/unsigned-types.h`) is newer than the target (`unity_*_cxx.cxx.o`) and a rebuild is in order.

## Environment
Ubuntu x64

## Supporting Files

To resolve this:

```patch
--- a/Builds/CMake/soci_patch.cmake
+++ b/Builds/CMake/soci_patch.cmake
@@ -1,6 +1,7 @@
 # This patches unsigned-types.h in the soci official sources
 # so as to remove type range check exceptions that cause
 # us trouble when using boost::optional to select int values
+if(NOT EXISTS "include/soci/unsigned-types.h.orig")
 file (STRINGS include/soci/unsigned-types.h sourcecode)
 foreach (line_ ${sourcecode})
   if (line_ MATCHES "^[ \\t]+throw[ ]+soci_error[ ]*\\([ ]*\"Value outside of allowed.+$")
@@ -10,6 +11,7 @@ foreach (line_ ${sourcecode})
 endforeach ()
 file (RENAME include/soci/unsigned-types.h include/soci/unsigned-types.h.orig)
 file (RENAME include/soci/unsigned-types.h.patched include/soci/unsigned-types.h)
+endif()
 # also fix Boost.cmake so that it just returns when we override the Boost_FOUND var
 file (APPEND cmake/dependencies/Boost.cmake.patched "if (Boost_FOUND)\n")
 file (APPEND cmake/dependencies/Boost.cmake.patched "  return ()\n")
```

I can put up a PR if you prefer that.

**Comment by ximinez** [comment]
I for one would love it if you would open a PR for this fix. I do ask that you indent the lines that are now inside the `if/endif` block.
