### ISSUE TITLE
Question: what programming language will be used for xrpl smart contracts?

### ISSUE THREAD

**Issue by firefly3582** [ripple/rippled#3913]
What programming language will be used for smart contracts in XRP-L? 
I've heard Hooks will be used to facilitate smart contract capabilities in XRP-L but some are saying another language will be used.

```
DISCLAIMER, I know this is not the appropriate repo to ask questions but:

" We've Sunset
Ripplex.io

Thank you for visiting ripplex.io!
As of July 31, 2021, this website is no
longer being supported ."
-Ripplex.io website
```

**Comment by nbougalis** [comment]
My understanding is that Hooks uses [WebAssembly](https://en.m.wikipedia.org/wiki/WebAssembly) and there are various front-ends to that.

I believe that currently the [C](https://en.wikipedia.org/wiki/C_(programming_language)) front-end of choice and the existing code and documentation uses that, but other languages could theoretically also become available.

At any rate, this is a question best suited for the XRPL Labs team, which is developing hooks. I don't know if they have a forum or other similar medium to engage with them; perhaps @WietseWind or @RichardAH can chime in.

**Comment by firefly3582** [comment]
@RichardAH 

Thanks a lot, Im a newbie to C but is this how data is stored in a Hook?
```C
struct {
  char* account_id; // key
  long account_balance; // value
} accounts[] = {
  {"rAAA", 842},
  {"rZZZ", 4023}
};
```

**Comment by RichardAH** [comment]
> @RichardAH
> 
> Thanks a lot, Im a newbie to C but is this how data is stored in a Hook?
> 
> ```c
> struct {
>   char* account_id; // key
>   long account_balance; // value
> } accounts[] = {
>   {"rAAA", 842},
>   {"rZZZ", 4023}
> };
> ```

On the XRP Ledger Accounts are identified by a 20 byte ID. You know them as _r-addresses_ but these are actually base58check encoded `AccountID`s. (See: https://en.bitcoin.it/wiki/Base58Check_encoding, https://xrpl.org/accounts.html)

You would rarely use it in a production hook but there is a utility HookAPI for decoding r-addresses to a 20 byte `AccountID` see: https://xrpl-hooks.readme.io/reference/util_accid

To answer your question you could do something like this. This is not optimised, but does demonstrate how you might do it.
```C
// first get the Account ID you're interested in, for example you might get the otxn account
uint8_t account_field[20];
int64_t account_field_len = 
    otxn_field(account_field, 20, sfAccount);

// next turn the 20 byte Account ID into a 32 byte key for the state lookup
uint8_t key[32];
for (int i = 0; GUARD(32), i < 32; ++i)
    key[i] = (i < 20 ? account_field[i] : 0);

// finally get the value for this key, if it exists
uint8_t raw_value[4];
if (state(raw_value, 4, key, 32) == 4)
{ 
    // key successfully read, but it needs to be intrepreted as an integer to work with
    //(there's a concise helper macro for this btw **)
    uint32_t value = (((uint32_t)value[0]) << 24U) + (((uint32_t)value[1]) << 16U) + (((uint32_t)value[2]) << 8U) + ((uint32_t)value[3]);
    // do something with value here
}
else
{
    // k-v doesn't exist
}
```

To write a value to state it's the same process except use `state_set`: https://xrpl-hooks.readme.io/reference/state_set (and turn your int back into bytes before you call it.)

Hooks are very low level, designed for efficiency over ease-of-programming. Strongly suggest you first learn C and then work your way through the example Hooks. The simpler ones are easier to read e.g. carbon: https://github.com/XRPL-Labs/xrpld-hooks/blob/dfb6cd22b576287e260108bb35e06d7179811728/hook-api-examples/carbon/carbon.c

** Macro mentioned in the code is here: https://github.com/XRPL-Labs/xrpld-hooks/blob/dfb6cd22b576287e260108bb35e06d7179811728/hook-api-examples/hookmacro.h#L193

**Comment by firefly3582** [comment]
![Cdevs](https://user-images.githubusercontent.com/87929946/131216487-c5483261-9ed7-4cb7-a11e-5aa32cf26e12.PNG)
me trying to speedrun C at 4 am  ^

Anyways, ill try my best to learn some C, C seems low level at itself but Hooks seem way low level for the sake of efficiency for the nodes to compute, which is great.

**Comment by firefly3582** [comment]
![fuckinghooks](https://user-images.githubusercontent.com/87929946/131242224-206f4cb3-224d-4aee-8912-63fd641bb726.PNG)

Hello @RichardAH,
Based on the documentation, it seems like a Hook must be attached to an account *(example: rAlice's Hook, rInstituion's Hook)*.


Can a Hook act as a DeFi hub to facilitate lending and borrowing activities to the free market and can a Hook act as a private DeFi hub where a certain quota must be met in an account *(example: balance must be >1000 XRP & not in a blacklist)* to participate in?

**Comment by RichardAH** [comment]
> Can a Hook act as a DeFi hub to facilitate lending and borrowing activities to the free market and can a Hook act as a private DeFi hub where a certain quota must be met in an account _(example: balance must be >1000 XRP & not in a blacklist)_ to participate in?

You would first install a Hook on a dedicated "defi hub" XRPL account and then "blackhole" the account. This means key-based access is provably disabled for the account. Thereafter only the installed Hook can make changes to and/or send transactions from the account, and only accordng to that Hook's own internal logic. More info about blackholing here: https://xrpl.org/accounts.html#special-addresses

Hooks can reject incoming transactions according to their internal logic. It is possible to access most on-ledger objects from a Hook. It would be possible to fetch the originating transaction's `Account ID` (i.e. the sender of a transaction) and in turn lookup the `AccountRoot` to find the balance on that sending account. From there you can apply whatever rejection logic is appropriate.

As for blacklisting addresses, there is already an example hook that does this: https://github.com/XRPL-Labs/xrpld-hooks/tree/hooks-ssvm/hook-api-examples/firewall

**Comment by firefly3582** [comment]
Hey @RichardAH, I've been learning C for a while and analyzed some Hooks code from the [github](https://github.com/XRPL-Labs/xrpld-hooks/blob/hooks-ssvm/hook-api-examples);

Could you please tell me what these code snippets are? (from [Carbon](https://github.com/XRPL-Labs/xrpld-hooks/blob/hooks-ssvm/hook-api-examples/carbon/carbon.c)):


1: What's a TRACESTR?
```c
    TRACESTR("Carbon: started");
```

2: What's a otxn_field, SBUF, sfAccount
```c
    uint8_t account_field[20];
    int32_t account_field_len = otxn_field(SBUF(account_field), sfAccount);
    TRACEVAR(account_field_len);
```

3: What's the cbak for? I don't fully understand it from the documentation.
```c
int64_t cbak(int64_t reserved)
{
    return 0;
}

```
I'm sorry for bugging you, hope that a new version of the documentation explains these sort of stuff, thank you.

**Comment by RichardAH** [comment]
> Hey @RichardAH, I've been learning C for a while and analyzed some Hooks code from the [github](https://github.com/XRPL-Labs/xrpld-hooks/blob/hooks-ssvm/hook-api-examples);
> 
> Could you please tell me what these code snippets are? (from [Carbon](https://github.com/XRPL-Labs/xrpld-hooks/blob/hooks-ssvm/hook-api-examples/carbon/carbon.c)):
> 
> 1: What's a TRACESTR?
A helper macro which calls the trace API with a string you specify. Trace APIs are used for debugging hooks.
https://xrpl-hooks.readme.io/reference/trace
https://github.com/XRPL-Labs/xrpld-hooks/blob/dfb6cd22b576287e260108bb35e06d7179811728/hook-api-examples/hookmacro.h#L98


> 2: What's a otxn_field, SBUF, sfAccount
SBUF is a macro that takes an array `a` and expresses it as `a`, `sizeof(a)`. Used to condense otherwise verbose API calls. https://github.com/XRPL-Labs/xrpld-hooks/blob/dfb6cd22b576287e260108bb35e06d7179811728/hook-api-examples/hookmacro.h#L16

`sfAccount` is a serialized field identifier used by the XRP ledger.
https://xrpl-hooks.readme.io/reference/otxn_field
https://xrpl.org/serialization.html

 
> 3: What's the cbak for? I don't fully understand it from the documentation.
`cbak()` is called when a transaction your Hook previously emitted is finally accepted into a ledger or reaches the point where it can never be accepted into a ledger. If your hook doesn't emit any transactions this may be an empty function (or in future: not present.)



> I'm sorry for bugging you, hope that a new version of the documentation explains these sort of stuff, thank you.
I will add a section for the hook macros even though they aren't strictly part of Hooks
