### ISSUE TITLE
s2.ripple.com returns internal error 73 "Containing SHAMap node not found" when fetching transaction that was recently sent

### ISSUE THREAD

**Issue by CherryDT** [ripple/rippled#3982]
## Issue Description
Starting yesterday, we suddenly have an issue every time we send a transaction via the `wss://s2.ripple.com` server. The transaction is sent, but when we poll `getTransaction` to see when it was validated, we get an error 73 returned. Previously, we only initially received `PendingLedgerVersionError` which was expected. We aren't sure what this error is supposed to mean. This happens for every transaction.

I googled the error message `"Containing SHAMap node not found"` but I got only one result, which was the source code where the message is defined...

## Steps to Reproduce
Using `s2.ripple.com`, send any transaction, then attempt to fetch its data again.

## Expected Result
TX data returned or `PendingLedgerVersionError` .

## Actual Result
Internal error returned:
```
[RippledError(Containing SHAMap node not found, {
  error: 'internal',
  error_code: 73,
  error_message: 'Containing SHAMap node not found',
  id: 4700,
  request: {
    binary: false,
    command: 'tx',
    id: 4700,
    transaction: '<tx ID here>'
  },
  status: 'error',
  type: 'response',
  warnings: [
    {
      id: 1004,
      message: 'This is a reporting server.  The default behavior of a reporting server is to only return validated data. If you are looking for not yet validated data, include "ledger_index : current" in your request, which will cause this server to forward the request to a p2p node. If the forward is successful the response will include "forwarded" : "true"'
    }
  ]
})]
```

## Environment
Not sure what your server uses.

## Supporting Files
I guess you can find the logs on your server.

**Comment by cjcobb23** [comment]
Can you paste the transaction hash for which you see this error?

**Comment by CherryDT** [comment]
For example `40768E0C5654D219E84405375753EB833B8EDA951193D6E51FA067CEA8A41E8D`

**Comment by cjcobb23** [comment]
Sorry, infrastructure issue, should be fixed now.

**Comment by cjcobb23** [comment]
Thank you for bringing this to our attention, and do let us know if it happens again.

**Comment by CherryDT** [comment]
Thank you!
