### ISSUE TITLE
Orders failing to match - Negative spread & orders filling out of order

### ISSUE THREAD

**Issue by Cadey** [ripple/rippled#3985]
## Issue Description
Our token is xKangaMK1 and currently people are unable to buy on the dex either with market orders or limit orders.

You can place limit orders for higher amounts than the sell orders causing a negative spread.

These buy orders (which can be any amount higher than the sell orders) can be filled buy selling into them.

## Steps to Reproduce
Place an order (now 17 Nov 18:50 UTC) on our order book

https://sologenic.org/trade?network=mainnet&market=784B616E67614D4B310000000000000000000000%2BrPwdrA6YFGR6k5rPyT6QPx7MrQAavUtyz5%2FXRP

Try to do a market buy and then do a limit buy for more than the lowest sell orders

## Expected Result
The market order should buy at the lowest sell
The limit order should auto fill buying tokens from the lowest sell order up

## Actual Result
The market order fails
The limit order is placed as a buy order on the "buy" side of the order book

## Environment
This is happening on the live Dex

## Supporting Files

![image (2)](https://user-images.githubusercontent.com/8178177/142263973-2f1767f7-1dab-4e1d-85ef-95e33fcbede6.png)
![image (1)](https://user-images.githubusercontent.com/8178177/142264002-a5cfe932-49e6-4502-9407-41a87db25e59.png)

**Comment by mtrippled** [comment]
This problem should be fixed soon by th amendment described here: https://xrpscan.com/amendment/B6B3EEDC0267AB50491FDC450A398AF30DBCD977CECED8BEF2499CAB5DAC19E2

**Comment by Cadey** [comment]
Hi,

How long will that take to be propagated to the dex??

**Comment by scottschurr** [comment]
@Cadey, as it says on the linked web page, assuming the amendment continues to see support from validators, the change will be enabled at:

Nov 18, 2021, 05:16:31 PM UTC

I see no reason for the amendment to lose support at this point in time.
