### ISSUE TITLE
Ask About Online Delete (InsufficientNetworkMode) (Version: 1.7.3)

### ISSUE THREAD

**Issue by junha-ahn** [ripple/rippled#3990]
I have a problem with `InsufficientNetworkMode` two days ago.

So I researched about it.

I guess, the problem was the "online delete"

My Ec2 is `4 core (r5.large), 32 RAM, 360G data disk (SSD)`

![image](https://user-images.githubusercontent.com/41976906/142656532-0b77b13a-0c7a-4fbf-9d3c-dcc786a29b6c.png)
![image](https://user-images.githubusercontent.com/41976906/142656576-f6187d82-86df-4bfe-9fa9-eff4b5238d03.png)

- That time "load average: 7.58 6.82 6.72" 

this is my config file:
```
[node_size]
small

[node_db]
type=RocksDB
path=/data/rippled/data/rocksdb
open_files=512
filter_bits=12
cache_mb=512
file_size_mb=64
file_size_mult=2
online_delete=25000
advisory_delete=0

[ledger_history]
20000

[fetch_depth]
256
```

The problem is just so many `online deletion`
- This causes a lot of CPU use and DISK IO.

# 1. So, Do you think the cause of my problem is "Online-Option"?

I read a Document about [online deletion](https://xrpl.org/online-deletion.html), 

Is it supposed to run for 2-3 hours? 
- If you look at my setup file and log above:
- the usage increased for at least 2 hours.
- The reason why I am asking is that I want to make sure that the cause of my problem is "online-deletion"

![image](https://user-images.githubusercontent.com/41976906/142657324-8d7e0ed4-aaca-4a86-8f7f-f251e469a628.png)

Because If you look at this photo 
- It occurred once a day. (Probably for 2-3 hours)
- `XRP ledger` generated(blocktime) per 3~5 second, so `24 hours / 3 second = 28800`  
- And my current config is `online_delete=25000`, so Maybe once a day.
- So the cause of my problem is "online-deletion" 

# 2. How does It work? "online_delete" with "ledger_history" config

![image](https://user-images.githubusercontent.com/41976906/142658282-243e6296-ac4a-4518-9ec1-2cc3971d5833.png)
> https://xrpl.org/online-deletion.html

I read some docs, but I don't understand

```
online_delete = 1000
ledger_history = none
```
- `LastLedger:2000`, If there are 0 ~ 2,000 stored ledgers, delete the old ones. (delete 0 ~ 1000 ledger)
- " After running deletion, the server keeps at least 50,000 ledger versions (about two days' worth)" [from](https://xrpl.org/online-deletion.html)

```
online_delete = 1000
ledger_history = 256
```
- `LastLedger:2256`, If there are 0 ~ 2,256 stored ledgers, delete the old ones. (delete 1256 ~ 2256)

Is it right?

# 3. Is the best option?

My Ec2 is `4 core (r5.large), 32 RAM, 360G data disk (SSD)`
- only for `rippled`

so I will change it this way:

```
[node_size]
medium

[node_db]
type=NuDB
path=/var/lib/rippled/db/nudb
online_delete=350000 
advisory_delete=0

[ledger_history]
none

[fetch_depth]
256
```

### 4. But even if you change the setting, doesn't disk I/O eventually explode? (It just doesn't happen often)

If the `rippled` start "online-deletion", It will cause a lot of CPU use and DISK IO. 
- So same problem (`InsufficientNetworkMode`) 
- Am I right? How can I avoid this issue

Thank you for your help.

**Comment by amrendraw3** [comment]
I am also facing the `InsufficientNetworkMode` problem since the past upgrade. The reason is still unknown. I tried multiple solutions available on the internet and even created a new instance for this but the issue is still there.

I am running an instance of 32GB RAM and 300 GB SSD config. 

The rippled server_state stays on `connected` and sometimes it went to `proposing` but again it is in a `connected` state for more than 20 hours.

The instance was working fine 3 days ago, and I upgraded the `rippled` server yesterday only.

**Comment by ximinez** [comment]
The `online_delete` process is very disk intensive. Additionally, the mainnet has seen an explosion in activity recently, which is putting strain on many nodes. Improvements are being worked on, several of which should be released soon in version 1.8.0.

In the meantime, there are a few things you can try.
1. Change your `node_size` to `huge` if you have at least 32Gb of RAM. This will keep more information in memory for longer, which should decrease other disk activity, which should give `online_delete` less competition.
2. If your use case supports it, decrease your `online_delete` value. This will cause the rotation to run more frequently, but with less work to do each time. This will allow the rotation to finish more quickly, which reduces the chances of losing sync. If the node does lose sync, it will have a smaller ledger gap, and should be able to recover more quickly.
3. Increase your disk IOPS. The faster the disk, the more quickly the rotation process can complete, and the less likely the node is to lose sync.

**Comment by junha-ahn** [comment]
Ok. I will decrease my `online_delete` value for the short term running, but I want to save more ledger at least 7 days 
- 1 day = probably 25000 ledgers, So I want to save 125000 ledgers 

How can I do? online_delete often and save a lot

Is It possible? 

```
node_size = huge
online_delete = 25000
ledger_history = 100000
```

so `online_deletion` will be run for every 25,000 ledgers. and save with least 125,000 ledger (~ 150,000)

**Comment by ximinez** [comment]
The way `online_delete` works right now, you can't really save 125,000 ledgers while deleting 25,000 at a time.

> 2. How does It work? "online_delete" with "ledger_history" config

To summarize, `ledger_history` tells the server how the target minimum number of ledgers to have available, while `online_delete` tells the server how long to wait before deleting old ledgers.

An example to illustrate. Say `ledger_history` is 100 and `online_delete` is 200, and you're starting up a new server with no history databases. Here are the basic steps.
1. Two "buckets" are created to hold ledgers: "A" and "B".
2. Ledgers are downloaded into "B". Rippled tries to backfill 100 ledgers.
3. Once "B" has at least 200 ledgers, the rotation process runs. "A" is deleted. A new bucket "C" is created. The current ledger is copied from "B" to "C" as a baseline. "B" is effectively read-only.
4. Now all new ledger data is saved to "C".
5. Once "C" has at least 200 ledgers, the rotation process runs again. "B" is deleted, "D" is created, the ledger is copied from "C" to "D", and "C" is read-only.
6. It continues this way indefinitely.

**Comment by junha-ahn** [comment]
Hm... So If I want to save 125,000 ledgers with `online_delete`... I have to increase IOPS and `huge node_size` 

and I will wait for v1.8.0 

Thank you for your help.

**Comment by ximinez** [comment]
You're welcome!
