### ISSUE TITLE
GatewayBalances

### ISSUE THREAD

**Issue by wojake** [ripple/rippled#4046]
```
{'account': 'rXXXX', 'ledger_current_index': XXXXX, 'validated': False}
```
When an account has not issued their currency, this is given to an API request ^, there is no indicator that tells if an issuer/address has not issued a currency before.

Rather then giving no value at all, what if we create a new variable (bool) that indicates if an address has issued a currency before.
API: https://github.com/ripple/rippled/blob/develop/src/ripple/rpc/handlers/GatewayBalances.cpp

**Comment by MarkusTeufelberger** [comment]
There's not much that takes former state into account - to answer "has this account issued some currency in the past" this would require combing through all history until the funding of this account (and with deletable accounts that's not even enough) - so this would be an extremely extremely expensive operation. What's your use case for this?

**Comment by wojake** [comment]
>What's your use case for this?

I'm sure most users (99.9%) won't be encountering this issue but I am picking random trustlines and there might be a very small possibility that the trustline has 0 issued supply which would make it impossible for me to issue Offers on the dex.
context: https://github.com/wojake/XRP-transaction-burier

It's complicated (proven by you) and there's a very small chance that users want this, so I'll close the issue for now.
