### ISSUE TITLE
Testnet time/ledger bug

### ISSUE THREAD

**Issue by wojake** [ripple/rippled#4049]
## Test network time/ledger bug?
When I tried to issue an Escrow transaction on the testnet, it has failed multiple times, here are the fields that I used:
```
finish-after = current-ledger (provided by ripple's node) + 1000 ledgers
cancel-after = finish-after + 10 to 100 ledgers <- random int
```
### On-chain data:
- Account: [Wallet](https://test.bithomp.com/explorer/rs5C34igcZ4N45nucYnqkg58MDCpF7BgNQ)
- Failed Escrow transaction using current-ledger: [Failed tx](https://test.bithomp.com/explorer/D4086C5213329A54B7534403B6D4698E553FBE71E303BB6367A8872BD392A3E9)
- Successful Escrow transaction: [Successful Tx](https://test.bithomp.com/explorer/72440252EB372D0E0201F73D7D1800C5F6617ED3B66AF554D54F87C1BA46C5B0
)

Now, what did I do to issue a successful escrow transaction?
I had to multiply the current-ledger provided by the testnet node by **_x29.5_**! (in a round figure), the code:
```py
    finish_after=round(get_latest_validated_ledger_sequence(client)*29.5)
    cancel_after=round(get_latest_validated_ledger_sequence(client)*29.5) + (random_ledger + random.randint(10, 100))
```
If we look at the [_failed_](###on-chain-data) escrow transaction's raw data fields, it is shown that I used the current ledger:
```
    "CancelAfter": 23919671,
    "FinishAfter": 23919516,
    "ledger_index": 23918524,
```
Execute after (UTC):2000-10-03 20:18:36  &  Cancel after (UTC):2000-10-03 20:21:11
I'm not entering random ledgers here, this data was provided by a node and is the current ledger

But if we look at the [_successful_](###on-chain-data) transaction's raw data:
```
    "CancelAfter": 705598374,
    "FinishAfter": 705598228,
    "ledger_index": 23918593,
```
a whole 29.5x from the current ledger just to get a successful escrow transaction that will finish by mid 2022!

## Cause of all of this?
Now, I'm assuming it is a time + ledger related problem since Ripple's testnet has been [wiped/reset](https://xrpl.org/blog/2019/testnet-reset.html#xrp-testnet-has-been-reset) before, I don't know if my messy code did all of this but the data provided by the testnet itself is pretty damning.

That's all from me.

**Comment by wojake** [comment]
Yup, the date (based on the ledger) is not the same as the ledger:
```
    "date": 693914670, <--
    "hash": "D4086C5213329A54B7534403B6D4698E553FBE71E303BB6367A8872BD392A3E9",
    "inLedger": 23918524, <--
    "ledger_index": 23918524, <--
```

**Comment by wojake** [comment]
Well, the deleteAfter/cancelAfter field was supposed to be field in Ripple EPOCH time, my bad.

**Comment by intelliot** [comment]
Correct; for future readers, note the warning:

> Warning:
> If you use a UNIX time in the FinishAfter field without converting to the equivalent Ripple time first, that sets the unlock time to an extra 30 years in the future!

https://xrpl.org/send-a-time-held-escrow.html
