### ISSUE TITLE
issuing `rippled stop` results in a restart (Version: 1.8.0+)

### ISSUE THREAD

**Issue by crypticrabbit** [ripple/rippled#4052]
## Issue Description
Issuing `rippled stop` results in rippled restarting itself, not stopping. As an example, I called `rippled stop` when I wanted to upgrade from 1.8.0 to 1.8.2, and rippled just restarted itself into 1.8.2 without me having to issue `systemctl start rippled`.

The log files look exactly as I would expect if I had issued `systemctl stop rippled` followed by `systemctl start rippled` (in other words, I could see that rippled was binding to ports, listing supported amendments, etc., just like it would with a 'normal' startup).

Calling `systemctl stop rippled` stops rippled.

## Steps to Reproduce
I can't test/reproduce this behavior, since it happened on production servers. Time permitting, I'm planning to spin up a test server to see if I can reproduce. I've seen this happen using the command line, so I'm not sure if the issue is consistent with websocket or RPCs.

1. Issue `rippled stop` from the command line on a running rippled instance
2. rippled restarts instead of stops

## Expected Result
Stop command should stop the server. While this seems quite minor, unexpected behavior is problematic in some cases - for example, UNL validator operators might desire maximum efficiency when updating rippled or making config changes, so their downtime does not exceed the space between flag ledgers, thereby resulting in them being added to the negative UNL.

## Actual Result
rippled restarts rather than stops

## Environment
I don't know how long this has been an issue - I recall it happening with versions before 1.8.0, though I dismissed it as irrelevant.

The servers I observed this behavior on are bare metal and run Rocky Linux 8.

I was running 1.8.0, which I installed from the 'unstable' repo, and I went to upgrade to 1.8.2, also on 'unstable'.

## Supporting Files
If I can reproduce this on a test machine, I can add log files, if needed.

**Comment by legleux** [comment]
I couldn't replicate this on Ubuntu 20.04 going from 1.8.1 to 1.8.2. I'll try some other things.
I don't _think_ this is the issue bc I haven't seen it restart in this case but I have noticed if rippled doesn't stop within systemd's timeout, the unit enters the "failed" state

**Comment by legleux** [comment]
Any more info? I still can't replicate this. Are you _positive_ you were running 1.8.0 (rc2?)
>  I called rippled stop when I wanted to upgrade from 1.8.0 to 1.8.2, and rippled just restarted itself into 1.8.2

On Rocky Linux 8.4, while running 1.8.0-rc2, I tried to do exactly what (I think) you might have done, I called `yum upgrade rippled` , _then_ `rippled stop`. Rippled stopped and didn't restart. Rippled stopped quickly before systemd killed it so I couldn't test if what my last post described might elicit your observed behavior.
Can you check the systemd log `sudo journalctl -u rippled` and see if rippled was SIGKILLed by systemd which may restart it as you observed (as it should.)

**Comment by crypticrabbit** [comment]
I've tried to replicate this on other servers, without success. Further investigation of one rippled instance that was showing the behavior produced the following system messages:
```
Jan 14 12:23:41 lco-xrpl-hub2 rippled[3843816]: terminate called after throwing an instance of 'soci::sqlite3_soci_error'                                                                                         
Jan 14 12:23:41 lco-xrpl-hub2 rippled[3843816]:  what():  sqlite3_statement_backend::loadOne: attempt to write a readonly database while executing "DELETE FROM ValidatorManifests".                              
Jan 14 12:23:41 lco-xrpl-hub2 systemd[1]: Started Process Core Dump (PID 3843893/UID 0).
Jan 14 12:23:41 lco-xrpl-hub2 systemd-coredump[3843894]: Resource limits disable core dumping for process 3843816 (rippled).                                                                                      
Jan 14 12:23:41 lco-xrpl-hub2 systemd-coredump[3843894]: Process 3843816 (rippled) of user 1001 dumped core.                                                                                                      
Jan 14 12:23:41 lco-xrpl-hub2 systemd[1]: systemd-coredump@15-3843893-0.service: Succeeded.
Jan 14 12:23:42 lco-xrpl-hub2 systemd[1]: rippled.service: Main process exited, code=dumped, status=6/ABRT                                                                                                        
Jan 14 12:23:42 lco-xrpl-hub2 systemd[1]: rippled.service: Failed with result 'core-dump'.
Jan 14 12:23:42 lco-xrpl-hub2 systemd[1]: rippled.service: Service RestartSec=100ms expired, scheduling restart.                                                                                                  
Jan 14 12:23:42 lco-xrpl-hub2 systemd[1]: rippled.service: Scheduled restart job, restart counter is at 9.                                                                                                        
Jan 14 12:23:42 lco-xrpl-hub2 systemd[1]: Stopped Ripple Daemon.
Jan 14 12:23:42 lco-xrpl-hub2 systemd[1]: Started Ripple Daemon.
```

Further investigation showed that, likely due to restoring from a backup, my wallet.db was owned by root, not rippled. Changing the permissions resulted in the `rippled stop` call working as expected.
