### ISSUE TITLE
Rippled command line (Markers & Limits)

### ISSUE THREAD

**Issue by arminas5** [ripple/rippled#4054]
Sorry that I'm writing here, but I can't find information how to use Markers and Limits with rippled command line methods like account_lines. It would be great to get this answer and please add this to your documentation.

Rippled version 1.8.1

**Comment by ximinez** [comment]
For anything not available in the existing command line parameters, you can use the `json` command to specify all the query parameters: https://xrpl.org/json.html
For example:
```
$ rippled json account_lines '{"account": "rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq", "marker": "AC11308DC744AB21D6203CCD284F2D48503E9B7EA58D3534A7282DD826ADA945,8" }'

{
   "result" : {
      "account" : "rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq",
      "ledger_current_index" : 68816122,
      "limit" : 200,
      "lines" : [
[...]
      ],
      "marker" : "38FA4AF0D44E58CC139940E45E9B43BBC40F98977943E49ACCDFDF35CCE3E9B9,16",
      "status" : "success",
      "validated" : false
   }
}
```

**Comment by ximinez** [comment]
Since I think you got the answer you needed, I'm closing this issue, but feel free to reopen it, or create a new one, if you have further questions.
