### ISSUE TITLE
ValidatorList:DBG 0 of 0 listed validators eligible for inclusion (Version: 1.8.4)

### ISSUE THREAD

**Issue by Rutrus** [ripple/rippled#4091]
## Issue Description

- Rippled is not syncing since 1.8.1 (previous installed version)
- Default validators are not eligible for inclusion

## Steps to Reproduce

We use the default validators [from the example](https://github.com/ripple/rippled/blob/develop/cfg/validators-example.txt) and checked manually.

## Expected Result

Work normally

## Actual Result

- Our ledger is some days without sync.
- Can not sync.

## Environment

- Docker redhat/ubi8-init
- v1.8.4 Installed from RPM repos. Ports exposed.

## Supporting Files

```
2022-Feb-01 15:53:08.689374863 UTC Application:FTL Result: {}
...
2022-Feb-01 15:53:08.658874684 UTC LedgerMaster:DBG No validated ledger
2022-Feb-01 15:53:08.658866609 UTC ValidatorList:WRN New quorum of 18446744073709551615 exceeds the number of trusted validators (0)
2022-Feb-01 15:53:08.658842513 UTC ValidatorList:DBG 0 of 0 listed validators eligible for inclusion in the trusted set
2022-Feb-01 15:53:08.624412521 UTC ValidatorSite:DBG Loaded 2 sites
```

## Edit
I will add some older messages, that occurred repeatedly when I lost sync:
```
2022-Jan-18 22:39:49.406233183 UTC LedgerHistory:ERR MISMATCH on prior ledger
2022-Jan-18 22:39:49.396875409 UTC LedgerHistory:ERR MISMATCH: seq=69104332 validated:85E9AABA7E56F40F5B83594E2C7F434878209C0199AA7EFC3E010255D80D13BC then:40BF7ECF4A91B01D83F2E1B43AF668A615C159BF6261E3531E929B7BA3ED921D
```

**Comment by ximinez** [comment]
Can you please post the contents of your `rippled.cfg` and `validators.txt` files (be very careful to remove any secrets before posting), and the output of the `server_info` command. e.g. From the command line, `rippled server_info`.

**Comment by Rutrus** [comment]
Copied [validators-example.txt](https://github.com/ripple/rippled/blob/develop/cfg/validators-example.txt)

I checked `server_info` with a colleague and seems right. I added "Edit" part. Does it means something to you? I think is the root of the problem. There is no too much info in logs.

**Comment by Rutrus** [comment]
We improve the instance type and for some reason is now working:
```
instance_type = "r6i.2xlarge"
ebs_size = "840"
ebs_type = "gp3"
ebs_iops = "10000"
```

Also I read a comment:
>  rippled does not run well on EBS. Machines with ephemeral storage do better. The i3 machines work well, such as i3.2xlarge
