### ISSUE TITLE
Support the escrow feature for issued tokens

### ISSUE THREAD

**Issue by wojake** [ripple/rippled#4106]
Currently, rippled only supports the escrow feature for XRP. This is much appreciated by the ecosystem but the XRP Ledger will benefit tremendously from an escrow feature for issued tokens as there are multiple use cases and benefits of supporting them at a protocol-layer, there are also much more use cases for it when the [Hooks amendment](https://hooks-testnet.xrpl-labs.com/) is rolled out. It is possible to implement an escrow feature on a Hook but implementing an escrow feature at a protocol-layer allows us to set a standard and it is much more reliable & secure. It also saves the XRPL's validator's resources as they wouldn't be needing to compute spaghetti code from Hooks that want implement an escrow feature for tokens *<- if hooks are implemented*
> Issued tokens = currencies, tokens, NFTs, IOUs

As expected, the XRP Ledger has increased in terms of usage and development which excludes the utility of XRP alone, multiple tokens and currencies (soon NFTs) has been issued on the mainnet behind projects, stablecoin issuance, tools and Ripple has also been advocating to support CBDCs on the XRPL for quite some time. To increase the use case and the reliability of issued tokens on the XRPL, it's best to introduce the native escrow feature for issued tokens. 

Benefits:
- Users may simply call a function on the XRPL to escrow tokens, they wouldn't need to use Hooks to escrow their tokens
- It is much more secure and reliable as the escrow feature will be situated at a protocol-layer, developers all around the globe could work on it to improve the feature
- It sets a protocol wide standard (similar to XLS20, no smart contracts) which would greatly reduce the attack surface and allow the ecosystem to be interoperable 

I'm involving Hooks into the proposal as Hooks can support an escrow feature for issued tokens. If NFTs are being introduced at a protocol-layer, I think this feature should be introduced in the same manner as funds are involved.

**Comment by KarmaCoverage** [comment]
Hey wojake, How did this come out?
