### ISSUE TITLE
[about partial payments flags] (Version: [1.7.0])

### ISSUE THREAD

**Issue by DreamHackchosenone** [ripple/rippled#4118]
## Steps to Reproduce
I found partial payments **flags** is **131072** on this page
[https://xrpl.org/payment.html#payment-flags](url)
but i got a transaction detail **flags** is **2147614720** like this one 
[https://xrpscan.com/tx/6B426FBB5FF430888FC17C9D3CD0ADCD9E4AC3EB2E2F5F21FB1FB762435DF684](url)
why this transaction flags is not 131072
## Expected Result
flags is 131072

## Actual Result
flags is 2147614720

**Comment by wojake** [comment]
This transaction includes 2 flags, which are:
- tfPartialPayment
- tfFullyCanonicalSig

If you added both of their flag's decimal value together, you get **2147614720**. Which means your transaction was a Partial Payment transaction with the FullyCanonicalSig flag enabled as well, nothing went wrong.

If you want any transactions explained to you and broken down into pieces, I recommend using xrpl.org's explorer and directing yourself to the `Detailed` section. In this case, it's: [Your Tx](https://mainnet.xrpl.org/transactions/6B426FBB5FF430888FC17C9D3CD0ADCD9E4AC3EB2E2F5F21FB1FB762435DF684/detailed).

**Comment by DreamHackchosenone** [comment]
> This transaction includes 2 flags, which are:
> 
> * tfPartialPayment
> * tfFullyCanonicalSig
> 
> If you added both of their flag's decimal value together, you get **2147614720**. Which means your transaction was a Partial Payment transaction with the FullyCanonicalSig flag enabled as well, nothing went wrong.
> 
> If you want any transactions explained to you and broken down into pieces, I recommend using xrpl.org's explorer and directing yourself to the `Detailed` section. In this case, it's: [Your Tx](https://mainnet.xrpl.org/transactions/6B426FBB5FF430888FC17C9D3CD0ADCD9E4AC3EB2E2F5F21FB1FB762435DF684/detailed).

tfFullyCanonicalSig flag is 2147483648, tfPartialPayment flag is 131072, so this transaction flag is 2147483648 + 131072 = 2147614720
thanks! got it!

**Comment by MarkusTeufelberger** [comment]
https://en.wikipedia.org/wiki/Bit_field for more information on that topic.

**Comment by wojake** [comment]
Thanks @MarkusTeufelberger, I'm not familiar with bit fields but how does rippled know the transaction has 2 flags by the decimal value? 
```
flag1 + flag2 = tx's flags
```
What's the logic behind this?

**Comment by MarkusTeufelberger** [comment]
`rippled` doesn't care about the decimal representation and works in binary, like probably most (all?) other programs out there. Maybe https://en.wikipedia.org/wiki/Bit_array is clearer? In general in my CS studies this was considered basic knowledge, I'm unsure what your background is so I'm not sure where to start explaining this to you.
