### ISSUE TITLE
[Issued Currency used 16 instead of 15 decimals in delivered amount] (Version: [1.8.5])

### ISSUE THREAD

**Issue by justTil** [ripple/rippled#4126]
## Issue Description

The payment transaction _"F2B6B2D0163E87B5775D87F9E34E0AA98B534C478903BAF663D381656F1743D9"_ has an Amount Object, where the value field contains a number that has more than 15 decimals, it uses 16. However from the [Token Precision](https://xrpl.org/currency-formats.html#token-amounts) documentation we now that Tokens maintain 15 decimal digits of precision.
## Steps to Reproduce

We are parsing the tokens to a format that fit's into our software, however every software that works with the token values and it's precision of 15 digits, will crash or throw an error, if the software does not truncat the amount to 15 decimals, or stops.
## Expected Result

We would expect the value field to have a max. precision of 15 digits, or less.
## Actual Result

The Actual result is a value field that contains this value: "0.0777992157839049", a value field with 16 precision digits.
## Environment

Visual Studio IDE, using the public servers https://s2.ripple.com:51234/ and https://xrplcluster.com/ for data.

**Comment by MarkusTeufelberger** [comment]
I only see 15 digits and 2 leading zeroes in this transaction amount? I would anyways recommend to deserialize this from the binary format or use a library if you have issues.

**Comment by MarkusTeufelberger** [comment]
Why? The number is precise to 15 digits, e.g. `0.0001` would be only precise to a single digit, not 4.

**Comment by justTil** [comment]
The value is precise to 16 digits, but that should be impossible. Yes the digit can be less than 15, but you shouldn't be able to send/receive amounts with a precision of 16. 

After the decimal point, there should only be 15 digit allowed, not more. Less sure, but the value above specifies a value with the precision of 16 digits.

**Comment by MarkusTeufelberger** [comment]
That's not what precision is. Maybe this article can help you clear up your confusion? https://en.wikipedia.org/wiki/Significant_figures

**Comment by justTil** [comment]
Thank you @MarkusTeufelberger , that actually helped clear things up^^

**Comment by mDuo13** [comment]
Sounds like this issue is resolved, then.
