### ISSUE TITLE
Missing MemoType and MemoFormat in JSON response

### ISSUE THREAD

**Issue by lathanbritz** [ripple/rippled#4128]
## Issue Description
Missing the MemoType and MemoFormat when listening to ledger close using the xrpl-client lib but payload will be the same with xrpl.js

## Steps to Reproduce
Create a offercreate transaction include the MemoData, MemoFormat and MemoType as per spec at https://xrpl.org/transaction-common-fields.html#memos-field

Now consume that offer and look at the JSON result of that transaction.

## Expected Result
MemoData, MemoFormat and MemoType should all be present in the Memos field.

## Actual Result
only MemoData was returned

## Environment
xrpl-client 

## Supporting Files
<img width="1184" alt="Screen Shot 2022-03-30 at 23 00 52" src="https://user-images.githubusercontent.com/508629/160961873-7311b10e-6fd8-4737-b80d-00e74f25ec34.png">
<img width="1322" alt="Screen Shot 2022-03-30 at 22 59 22" src="https://user-images.githubusercontent.com/508629/160961877-6739b2bb-fcb1-4a76-ac81-d47f453e9a67.png">
<img width="1342" alt="Screen Shot 2022-03-30 at 22 58 04" src="https://user-images.githubusercontent.com/508629/160961880-0a8dedd7-83e0-4606-8874-71147fd4ec2d.png">

here is the offer create transaction
https://testnet.xrpl.org/transactions/9856E15441A4E3F7C67CB091C99AB817AAA03FF1025BF3F8D7F56F180C915249/detailed

here is the second offer create transaction that partially consumed the above.
https://testnet.xrpl.org/transactions/86A1F521E02CAFDB4D012D93017B8530E077D7DF4B455B0F013BCA21A638F7D5/detailed

**Comment by WietseWind** [comment]
Hey @lathanbritz,

Thanks for reporting this!

I'm not entirely sure I understand, but I think what it comes down to is:

- Subscriptions don't return the full memo object when checking the tx data in a ledger close event
- Manual `tx` fetch does

Am I correct?

**Comment by lathanbritz** [comment]
Correct @WietseWind the "xrpl-client" is used, but the issue is the JSON objet that rippled returns, its missing all the fields in the MEMOS response attached to the offerCreate response.

Here is how I attach to ledger close and pass all tx on and find the one that I need, the one that consumed the previous offerCreate.

That transaction payload (JSON) that is present there is incomplete.

<img width="532" alt="Screen Shot 2022-03-31 at 10 04 25" src="https://user-images.githubusercontent.com/508629/161062124-f6788a01-ef21-4c4f-a059-6d0fc3fc0fa3.png">


apologies should have been more clear.

**Comment by lathanbritz** [comment]
Figured this out.

Issue is the me looking at the wrong transaction for the memo. The consuming offer, I fired through the sologenic interface, that writes its own Memo into that new transaction.

I need to be digging out the transaction HASH of the previous transaction and pulling the memo off there. This was simply me getting lost walking through the transactions.
