### ISSUE TITLE
ripple_path_find ignores multiple available trustlines (Version: 1.8.5)

### ISSUE THREAD

**Issue by ajochems** [ripple/rippled#4141]
## Issue Description
Executing the ripple_path_find command from an account with multiple trustlines with funds and sufficient liquidity on the DEX are ignored when returning the path find result. I am sending CSC from issuer rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr to a destination account trying to use either CSC, XRP, Gatehub BTC, Bitstamp USD or SOLO. Only CSC direct, XRP and Bitstamp USD are returned while auto bridging should have returned SOLO -> XRP - CSC and Gatehub BTC -> XRP -> CSC as well. 

## Steps to Reproduce
`
{
    "command": "account_lines",
    "account": "rnhxcjE1PPCMdiHY9MvAZ13cQnrQh7yCsC"
}
`

`
{
  "result": {
    "account": "rnhxcjE1PPCMdiHY9MvAZ13cQnrQh7yCsC",
    "ledger_current_index": 70834069,
    "lines": [{
      "account": "rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr",
      "balance": "31051.88866666667",
      "currency": "CSC",
      "limit": "65000000000",
      "limit_peer": "0",
      "no_ripple": true,
      "no_ripple_peer": false,
      "quality_in": 0,
      "quality_out": 0
    }, {
      "account": "rchGBxcD1A1C2tdxF6papQYZ8kjRKMYcL",
      "balance": "0.001073627553938689",
      "currency": "BTC",
      "limit": "1000000000",
      "limit_peer": "0",
      "no_ripple": true,
      "no_ripple_peer": false,
      "quality_in": 0,
      "quality_out": 0
    }, {
      "account": "rsoLo2S1kiGeCcn6hCUXVrCpGMWLrRrLZz",
      "balance": "10.82438568152359",
      "currency": "534F4C4F00000000000000000000000000000000",
      "limit": "1000000000",
      "limit_peer": "0",
      "no_ripple": true,
      "no_ripple_peer": false,
      "quality_in": 0,
      "quality_out": 0
    }, {
      "account": "rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B",
      "balance": "30.94023904401504",
      "currency": "USD",
      "limit": "999999999",
      "limit_peer": "0",
      "no_ripple": true,
      "no_ripple_peer": false,
      "quality_in": 0,
      "quality_out": 0
    }],
    "validated": false
  },
  "status": "success",
  "type": "response"
}
`

`
{
    "command": "ripple_path_find",
    "source_account": "rnhxcjE1PPCMdiHY9MvAZ13cQnrQh7yCsC",
    "destination_account": "rCSCdExHGgZVA1GvKHp2PFYeosHDCoezP",
    "destination_amount": {
      "value": "50",
      "currency": "CSC",
      "issuer": "rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr"
    }
  }
`

  {
    "result": {
      "alternatives": [{
        "paths_canonical": [],
        "paths_computed": [
          [{
            "currency": "CSC",
            "issuer": "rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr",
            "type": 48
          }]
        ],
        "source_amount": "99144"
      }, {
        "paths_canonical": [],
        "paths_computed": [],
        "source_amount": {
          "currency": "CSC",
          "issuer": "rnhxcjE1PPCMdiHY9MvAZ13cQnrQh7yCsC",
          "value": "50"
        }
      }, {
        "paths_canonical": [],
        "paths_computed": [
          [{
            "account": "rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B",
            "type": 1
          }, {
            "currency": "CSC",
            "issuer": "rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr",
            "type": 48
          }]
        ],
        "source_amount": {
          "currency": "USD",
          "issuer": "rnhxcjE1PPCMdiHY9MvAZ13cQnrQh7yCsC",
          "value": "0.479958"
        }
      }],
      "destination_account": "rCSCdExHGgZVA1GvKHp2PFYeosHDCoezP",
      "destination_amount": {
        "currency": "CSC",
        "issuer": "rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr",
        "value": "50"
      },
      "destination_currencies": ["CSC", "XRP"],
      "full_reply": true,
      "source_account": "rnhxcjE1PPCMdiHY9MvAZ13cQnrQh7yCsC",
      "status": "success"
    },
    "status": "success",
    "type": "response"
  }

## Expected Result
An alternatives list that includes all available trustlines with sufficient funds to fulfill the required destination_amount

Is any additional configuration required on rippled to make the autobridging work?

**Comment by ximinez** [comment]
Because the `ripple_path_find` command is synchronous and needs to return in a reasonable amount of time, it is very limited as to how "deep" it will go to look for paths. If you want a longer path, try the asynchronous `path_find` - note that it only works on websocket connections. https://xrpl.org/path_find.html

In general, though, path finding is a "best effort" process, and makes no guarantees that it will find the best possible path, or that it will find all possible paths.

**Comment by ajochems** [comment]
The path_find command over a websocket gives the same results as the ripple_path_find method. Analyzing the outputs it seems as if it only tries direct exchange options and not trying to autobridge through XRP at all? Do i need to configure something to have path_find to autobridge using XRP?

**Comment by ajochems** [comment]
Hi, thank you very much for that elaborate answer, changing the path_search params in the rippled.cfg indeed does the trick! I think the path finding documentation should include that explanation and config as well.
