### ISSUE TITLE
Brief loss of synchronization results in pain to clients

### ISSUE THREAD

**Issue by JoelKatz** [ripple/rippled#48]
Currently, if the server has even the briefest lost of synchronization with the network (uncertainty over precisely what the most current ledger is in the internal transaction processing and validation engine) the client reports itself offline until full synchronization of the validation process is restored.

Much of this logic was developed before the validation gate logic and is wrong under the new transaction and ledger security model. The server is in synch if it has a recent fully validated ledger. If the server has lost synch, it's back in synch when it fully validates another ledger that is very recent (or becomes convinced there has been no new ledger since the last one it fully validated).

That is, synchronization as far as clients are concerned, should be based on holding full copies of recent fully validated ledgers, not the status of the consensus process.

**Comment by vinniefalco** [comment]
Is thsi still a problem?
