### ISSUE TITLE
M-of-N

### ISSUE THREAD

**Issue by JoelKatz** [ripple/rippled#49]
If we decide to go with an M-of-N scheme implemented directly as transactions, we need the following:

- [ ] Flag to disable the use of the master key to sign transactions for an account
- [ ] Transaction to enable and disable the "disable master key" flag
- [ ] Transaction to modify the quorum and access list for an account
- [ ] Transaction to propose a transaction for an M-of-N account
- [ ] Transaction to add/remove an M-of-N account to/from your owner directory (optional)
- [ ] Transaction to vote yes or no on a proposed transaction (or change your vote)
- [ ] Logic to execute a proposed transaction and create the correct txn/metadata structures.

Note that this is server support only, not client support.

**Comment by rec** [comment]
Probably we can close this, but wanted to bring this to your attention!

**Comment by scottschurr** [comment]
I believe we're tracking m-of-n progress through JIRA now.  I'm closing this so we're not tracking it in two places.  Thanks for calling it to my attention.
