### ISSUE TITLE
Node Scrubbing

### ISSUE THREAD

**Issue by JoelKatz** [ripple/rippled#52]
Some people run the server on nodes with terabytes of storage and are happy to keep tons of history. However, there are also people who are on VPS's or other systems where storage is at a premium.

Currently, we have no way to purge history other than deleting all your databases and refetching what you want. This works very well for validators, but it's awful for servers that handle clients.

As our transaction volume grows, this is going to be more and more of an issue.

We need to do "node scrubbing". Essentially, this means finding nodes that do not need to be kept given the server's data retention policy and removing them. This is complicated by two factors. First, nodes are not indexed except by hash. Second, a node that's not used has nothing happen to it, there's nothing to tell us it has fallen out of the ledger. Worse, it may be out of the ledger and then back in and thus need to be retained.

The fix is a bit painful. If a server has a configured retention time or number of ledgers, we need to identify nodes that need to be retained versus those that don't and remove the ones that don't. I propose this method:

1) Figure out a ledger such that this and all prior ledgers do not need to be retained according to the server's retention policy. Store that ledger's sequence number. Remove all ledgers prior to that from our local tracking of ledgers we have and ensure we don't add them back.

2) Walk all ledgers after the ledger identified in step 1 starting with the current ledger and ending with the ledger after the ledger we found in step 1. This means all transaction and metadata nodes, account state nodes, ledger headers, and so on.

3) For all nodes found during the walk and not in a local "suppression" cache, bump the node sequence in the node database to the ledger index in which the node was found (if it's less than that) and add the node index to the suppression cache (so we don't read it again).

4) Traverse the main node database. Remove all nodes whose node sequence is less than the sequence of the retention ledger selected in step 1. (LevelDB has some tricks to make this efficient.)

Note that this process should be done slowly at low priority.

**Comment by vinniefalco** [comment]
This is implemented in "online-delete".
