### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by kravets** [ripple/rippled#96]
### TCP Ports have only 2^16 possible values
1. https://github.com/kravets/NewCoin/blob/develop/src/cpp/ripple/ripple.proto#L190
2. https://github.com/kravets/NewCoin/blob/develop/src/cpp/ripple/ripple.proto#L68

Both lines specify that TCP port number is to be encoded using uint32 whereas uint16 should be used instead (also there should only be a single place instead of two where this is spec'd)
### IPv6 _MUST_ be Supported

Instead of allocating 32 bits to IPv4 address here
https://github.com/kravets/NewCoin/blob/develop/src/cpp/ripple/ripple.proto#L189
one can allocated uint128 to handle _either_ IPv4 or IPv6 addresses where the most significan 96 bits of an address being zero would mean this endpoint is an IPv4 endpoint.

See http://www.tcpipguide.com/free/t_IPv6IPv4AddressEmbedding.htm#Figure_99 for details.

Alternatively allowing _either_ IPv4 or IPv6 address (or both) for an endpoint would allow endpoints more flexibility in deciding to be visible on one, the other or both.
### Discussion

It is critical to get these in _before_ the code base is open sourced, changes at such low level of the protocol will be a **BIG DEAL** later.

For comparison: Bitcoin supports not only IPv6, but also Tor and may even support I2P, "shipping" w/o IPv6 is very very uncool.

**Comment by vinniefalco** [comment]
This is something to consider in the long term but for now I'm closing it.
